pipeline {
   agent any
   stages {
      stage('Install') {
         steps {
            sshagent(['ssh-root-user-with-default-key']) {
                withCredentials([usernamePassword(credentialsId:'admin-latlon-repo', passwordVariable: 'Password', usernameVariable: 'Username')]) {
                    sh label: 'Download from Nexus', script: '''
                        ssh root@xplanbox2019.lat-lon.de "
                        curl -L -o xplan-docker-volumes.zip -u $Username:$Password -X GET 'https://repo.lat-lon.de/service/rest/v1/search/assets/download?sort=version&repository=xplanbox-snapshots&maven.groupId=de.latlon.product.xplanbox&maven.artifactId=xplan-docker-volumes&maven.extension=zip'
                        "
                        '''
                }
                sh label: 'Upload Docker Images', script: '''
                    docker save -o xplan-validator-web-docker.tar xplanbox/xplan-validator-web-docker:latest
                    docker save -o xplan-manager-web-docker.tar xplanbox/xplan-manager-web-docker:latest
                    docker save -o xplan-db-docker.tar xplanbox/xplan-db-docker:latest
                    docker save -o xplan-services-docker.tar xplanbox/xplan-services-docker:latest
                    docker save -o xplan-db-inspireplu-docker.tar xplanbox/xplan-db-inspireplu-docker:latest
                    docker save -o xplan-services-inspireplu-docker.tar xplanbox/xplan-services-inspireplu-docker:latest
                    scp xplan-validator-web-docker.tar root@xplanbox2019.lat-lon.de:
                    scp xplan-manager-web-docker.tar root@xplanbox2019.lat-lon.de:
                    scp xplan-db-docker.tar root@xplanbox2019.lat-lon.de:
                    scp xplan-services-docker.tar root@xplanbox2019.lat-lon.de:
                    scp xplan-db-inspireplu-docker.tar root@xplanbox2019.lat-lon.de:
                    scp xplan-services-inspireplu-docker.tar root@xplanbox2019.lat-lon.de:
                    ssh root@xplanbox2019.lat-lon.de "
                    docker load --input xplan-validator-web-docker.tar
                    docker load --input xplan-manager-web-docker.tar
                    docker load --input xplan-db-docker.tar
                    docker load --input xplan-services-docker.tar
                    docker load --input xplan-db-inspireplu-docker.tar
                    docker load --input xplan-services-inspireplu-docker.tar
                    "
                    '''
                sh label: 'Install', script: '''
                    ssh root@xplanbox2019.lat-lon.de "
                    export XPLANBOX_HOME=/root
                    export XPLANBOX_VOLUMES=/root
                    cd xplanbox-infrastructure/
                    docker-compose down --rmi local
                    scripts/setupVolumes.sh xplanbox2019.lat-lon.de /root/xplan-docker-volumes.zip
                    docker-compose up -d
                    sleep 120s
                    docker-compose restart
                    "
                    '''
            }
         }
      }
   }
}
