[Überschrift]
== Überblick


Die xPlanBox dient der Abbildung der Bauleit- und der
Landschaftsplanung. Die xPlanBox basiert auf den Standards des
http://www.opengeospatial.org[Open Geospatial Consortium], der
http://inspire.ec.europa.eu[INSPIRE Richtlinie] und insbesondere dem
Standard http://www.xplanung.de[XPlanung] zur Abbildung des deutschen
Planungsrechts durch ein GML Anwendungsschema.

Zur Implementierung der Komponenten der xPlanBox wurde die Open Source
Software http://www.deegree.org[deegree] eingesetzt, das ein
Projekt der OSGeo Foundation ist. Die xPlanBox besteht aus den
folgenden Komponenten:

__________________________________________________________________________________
* XPlanManager: Web-Oberfläche für das Datenmanagement
* XPlanValidator: Web-Oberfläche für den Validator
* XPlanWMS: Standard-Karten-Dienst für die Auskunft
* XPlanWFS: Standard-Daten-Dienst für die Auskunft (originale
Datenstruktur)
* XPlanSynWFS: Standard-Daten-Dienst für die Auskunft (vereinfachte
Datenstruktur)
__________________________________________________________________________________

Die Komponenten der xPlanBox werden in dieser Benutzerdokumentation im
Einzelnen erläutert.
