\i fix/xplan2/create.sql
\i fix/xplan3/create.sql
\i fix/xplan40/create.sql
\i fix/xplan41/create.sql
\i fix/xplan41nsm/create.sql
\i fix/xplan50/create.sql
\i fix/xplan51/create.sql
\i fix/xplansyn/create.sql
\i pre/xplan2/create.sql
\i pre/xplan3/create.sql
\i pre/xplan40/create.sql
\i pre/xplan41/create.sql
\i pre/xplan50/create.sql
\i pre/xplan51/create.sql
\i pre/xplan41nsm/create.sql
\i pre/xplansyn/create.sql
\i archive/xplan2/create.sql
\i archive/xplan3/create.sql
\i archive/xplan40/create.sql
\i archive/xplan41/create.sql
\i archive/xplan41nsm/create.sql
\i archive/xplan50/create.sql
\i archive/xplan51/create.sql
\i archive/xplansyn/create.sql
\i xplanmgr/create.sql