include:
  - project: 'grit/cicd-templates'
    ref: main
    file: '/gitlab/maven-3.9.yml'

variables:
  DEBUG:
    description: "Enable debugging"
    options:
      - "TRUE"
      - "FALSE"
    value: "FALSE"

image: grit/build-container:temurin-jdk11-maven-3-9

stages:
  - prepare
  - build

debug:
  stage: prepare
  script:
    - pwd
    - ls
    - set
    - mvn help:effective-settings
  rules:
    - if: $DEBUG == "TRUE"

maven-build-deploy:
  stage: build
  script:
    - echo "Starting build and deploy ..."
    - mvn $MAVEN_CLI_OPTS -Dmaven.install.skip=true -PskipAll deploy

