[Weiterführende Informationen zur semantischen Validierung]
=== Weiterführende Informationen zur semantischen Validierung


Bei der Ausgabe des Ergebnisses der semantischen Validerung kann eine
Referenz auf eine externe Resource gesetzt werden, die weiterführenden
Informationen bereitstellt. Die Referenzen können in der Datei
_managerConfiguration.properties_ im Verzeichnis
_~/.deegree/manager-configuration/_ konfiguriert werden.

----
linkSemanticConformity_XPLAN_2=
linkSemanticConformity_XPLAN_3=
linkSemanticConformity_XPLAN_40=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_4.pdf
linkSemanticConformity_XPLAN_41=http://localhost:8080/external/documentation/Konformitaetsbedingungen-XPlanGML_4_1.pdf
----



NOTE: Es müssen ggf. Zeilenumbrüche entfernt werden.


Für jede XPlan-GML-Version kann hier die Referenz auf eine externe
Resource konfiguriert werden. Ist für eine Version keine Resource
vorhanden, kann der Eintrag vollständig entfernt oder der Wert zu dem
Schlüssel leer gelassen werdem (wie im Beispiel für XPLAN_2 und
XPLAN_3). Es wird dann kein Hinweis im Validierungs-Report ausgegeben.




NOTE: Es wird empfohlen die Dokumente über die Komponente XPlanResources
bereit zu stellen, um die Unabhängigkeit zu externen Resourcen
sicherzustellen.

