[Konfiguration der Datenbank]
=== Konfiguration der Datenbank


Wie in Abschitt _Systemüberblick_ beschrieben, ist mindestens die
Installation von PostgreSQL 8.4 mit der Erweiterung PostGIS 1.5.4
erforderlich.

Für die Konfiguration der Datenbank-Anbindung muss die
__xplan-manager-cli__-Datei entpackt sein. Dabei spielt das Verzeichnis
in dem die Datei entpackt wurde keine Rolle. Ist diese entpackt, kann
die Datenbankerzeugung mittels des XPlanmangerCLIs durchgeführt werden.
Informationen zu den Befehlen und der Erzeugung der Datenbank finden
sich im Abschnitt XPlanManagerCLI im XPlanBenutzerhandbuch. Die
erforderlichen Informationen sind im Abschnitt _Alternativer
Betriebsmodus_ beschrieben.

Mit dem XPlanManagerCLI werden auch die Verbindungsdetails im XPlanMangerWorkspace anhand der übergebenden Parameter gesetzt, so dass der XPlanManager nach Ausführung ohne manuelle Anpassungen auf die Datenbank zugreifen kann.
Dagegen müssen die Datenbank Verbindung in den XPlanDiensten manuell angepasst werden. Betroffen sind folgende Dateien:

 * _.deegree/xplansyn-wms-workspace/jdbc/xplan.xml_
 * _.deegree/xplan-wms-workspace/jdbc/xplan.xml_
 * _.deegree/xplan-wfs-workspace/jdbc/xplan.xml_

Dabei kann auf zwei verschiedene Arten vorgegangen werden:

 * Die __xplan.xml__-Datei aus dem XPlanManger Workspace _.deegree/xplan-manager-workspace/jdbc/_ wird kopiert und die bereits vorhandene Konfiguration damit überschrieben.
 * Alternativ ist auch eine direkte Anpassung in der bereits vorhandenen __xplan.xml__-Datei möglich.

In den __xplan.xml__-Datei werden die ConnectionsPools für den Zugriff auf die Datenbank konfiguriert . Diese beinhalten neben den Verbindungsdetails wie die Url, den Nutzernamen und das Passwort weitere Details, die ggf. bei einer Installation zu berücksichtigen sind. Darunter:

* initialSize: Die Anzahl der initialen Verbindungen, die beim Start geöffnet werden.
* maxActive: Die maximale Anzahl von offenen Verbindungen die von Pool zeitgleich verwendet werden können.
* maxIdle: Die maximale Anzahl der  Verbindungen, die sich ungenutzt im Pool befinden können.

Da die Anzahl der zugelassenen Verbindungen des Datenbankservers begrenzt sein kann, ist es abhängig von der Installation der xPlanBox, der Anzahl der Nutzer und gegebenenfalls weiterer Faktoren sinnvoll, die vordefinierten Werte an die Installationsumgebung anzupassen.