[Anwendung installieren]
=== Anwendung installieren

[[konfiguration]]
==== Konfiguration

Die im Verzeichnis _config_ enthaltenen __zip__-Archive müssen in das
Verzeichnis _.deegree_ im Home-Verzeichnis des Nutzers kopiert und
entpackt werden:

_____________________________________________________________________________________________
* _xplan-wfs-workspace_
* _xplansyn-wfs-workspace_
* _xplansyn-wms-workspace_
* _xplan-manager-workspace_
* _xplan-manager-config_ (Name des Verzeichnis nach dem Entpacken:
__manager-configuration__)
_____________________________________________________________________________________________

NOTE: Alle Workspaces müssen in dem selben Verzeichnis liegen.

[[web-anwendungen]]
==== Web-Anwendungen

Um das korrekte Zusammenarbeiten der verschiedenen im Abschnitt
Systemarchitektur und Schnittstellen <architecture> beschriebenen
Komponenten zu gewährleisten, wird eine Trennung der Dienste und
Anwendungskomponenten empfohlen. Zwingend erforderlich ist dies beim
Einsatz von GDAL (s. <<[[installation-gdal]]>>).

Die folgenden WAR-Archive aus dem Ordner _web_ müssen in das Verzeichnis
der Tomcat-Installation (__Dienste-Tomcat__, z.B. Port: 8080) kopiert
werden:

____________________
* _xplan-wms.war_
* _xplan-wfs.war_
* _xplansyn-wfs.war_
____________________

Die WAR-Archive der Anwendungskomponenten werden über eine
weitere Tomcat-Installation (_Anwendungs-Tomcat_, z.B. Port: 8081)
bereitgestellt:

______________________
* _xplanmanager.war_
* _xplanvalidator.war_
* _xplan-root.war_
______________________

NOTE: Da die Komponente XPlanResources eine Einstiegsseite bereit stellt, bietet es sich an, diese als ROOT-Webapp des Anwendungs-Tomcat zu installieren. Das war-Archiv muss dafür im Verzeichnis ROOT entpackt werden.

[[kommandozeilen-anwendungen]]
==== Kommandozeilen-Anwendungen

Die Kommandozeilenkomponenten aus dem Ordner _cli_ können an beliebiger
Stelle entpackt werden. Im jeweiligen _bin_ Verzeichnis der beiden
Kommandozeilenwerkzeuge findet sich das entsprechende Ausführungsskript
_XPlanManager_ bzw. _XPlanValidator_.

[[dokumentation]]
==== Dokumentation

Im Verzeichnis _doc_ findet sich eine gezippte Version der
Dokumentation. Dieses Archiv enthält die Benutzerdokumentation zu den
Komponenten in den Formaten HTML und PDF.

[[installation-über-ein-install-skript]]
==== Installation über ein Install-Skript

Das Ablegen bzw. der Austausch der Web-Archive sowie das Ablegen bzw.
die Aktualisierung der betroffenen Konfigurationsdateien in den
Workspaces kann auf Linux-Umgebungen auch über das angehängte 
Installations-Skript (s. <<Installations-Skript, Anhang>>) ausgeführt werden:

----
sh ${WORK_DIR}/install.sh
----

Installationswerkzeuge und -skripte werden ohne Gewähr bereitgestellt.
Für professionelle Unterstützung wenden Sie sich bitte an die
http://www.lat-lon.de[lat/lon GmbH].