[Logging]
=== Logging


Die Anwendungen XPlanManager Web, XPlanManager CLI, XPlanValidator Web
und XPlanValidator CLI schreiben Log-Ausgaben standardmäßig nach
Standard-Out. Für die Web-Anwendungen ist dies die Logging-Datei des
Java Applikationsserver (Tomcat: catalina.out) und bei den
CLI-Anwendungen die Konsole. Zusätzlich wird das Logging für alle
Anwendungen in eine separate Datei geschrieben:

[width="88%",cols="35%,65%",options="header",]
|============================================================
|Anwendung |Log-Datei
|XPlanManager Web |$\{xplan.logdir}/xplan-manager-web.log
|XPlanManager CLI |./xplan-manager-cli.log
|XPlanValidator Web |$\{xplan.logdir}/xplan-validator-web.log
|XPlanValidator CLI |./xplan-validator-cli.log
|============================================================

Während die log-Dateien des CLIs immer in dem Verzeichnis abgelegt
werden in dem das Kommandozeilen ausgeführt wurde, ist das Verzeichnis
in den Web-Anwendungen mit der Variable $\{xplan.logdir} zu
konfigurieren. Dies ist bereits in Abschnitt <<Konfiguration der
Applikationsserver>> beschrieben. Ist die
Variable nicht korrekt konfiguriert, kommt es zu einer Fehlermeldung
beim Starten der Anwendung (java.io.FileNotFoundException:
/xplan-manager-web.log (Keine Berechtigung)).
