# https://github.com/prometheus/jmx_exporter#configuration
---   
whitelistObjectNames:
- "Catalina:type=Manager,*"
- "java.lang:type=Memory"
- "java.lang:type=Threadin"
- "java.lang:type=GarbageCollector,name=*"
- "java.lang:type=OperatingSystem"
lowercaseOutputLabelNames: true
lowercaseOutputName: true
rules:
- pattern: ".*"
