[[konfiguration-der-datenbank]]
=== Konfiguration der Datenbank

Das Anlegen der Datenbank XPlanDB kann entweder über das XPlanManagerCLI oder manuell mit einem beliebigen Datenbankwerkzeug wie z. B. https://www.pgadmin.org[pgAdmin] erfolgen. Beide Varianten sind in den folgenden Abschnitten beschrieben.

==== Initiales Aufsetzen der Datenbank über das XPlanManagerCLI

Für die Konfiguration der Datenbank-Anbindung muss die
Datei __xplan-manager-cli__ entpackt sein. Dabei spielt das Verzeichnis, in dem die Datei entpackt wurde, keine Rolle. Ist diese entpackt, kann die Datenbankerzeugung mittels des XPlanManagerCLI durchgeführt werden:

----
XPlanManager -createdb 'xplanbox' jdbc:postgresql://localhost:5432 -u postgres -p postgres
----

NOTE: Informationen zu den Befehlen und der Erzeugung der Datenbank finden sich im Abschnitt XPlanManagerCLI im XPlanBenutzerhandbuch.

Mit dem XPlanManagerCLI werden auch die Werte für die Datenbankverbindung im XPlanManagerWorkspace anhand der übergebenden Parameter gesetzt, so dass der XPlanManager nach Ausführung ohne manuelle Anpassungen auf die Datenbank zugreifen kann.
Die Datenbankverbindungen in den XPlanDiensten müssen jedoch manuell angepasst werden. Betroffen sind folgende Dateien:

* _.deegree/xplan-manager-workspace/jdbc/xplan.xml_
* _.deegree/xplan-wfs-workspace/jdbc/xplan.xml_
* _.deegree/xplansyn-wfs-workspace/jdbc/xplan.xml_
* _.deegree/xplansyn-wms-workspace/jdbc/xplan.xml_

Dabei kann auf zwei verschiedene Arten vorgegangen werden:

 * Die Datei __xplan.xml__ aus dem XPlanManger-Workspace _.deegree/xplan-manager-workspace/jdbc/_ wird kopiert und die bereits vorhandene Konfiguration damit überschrieben.
 * Alternativ ist auch eine direkte Anpassung in den bereits vorhandenen Dateien __xplan.xml__ möglich.

==== Manuelles Aufsetzen der Datenbank

Alternativ zum Aufsetzen über das XPlanManagerCLI kann die Datenbank auch manuell ausgeführt werden. Dafür müssen die folgenden Schritte ausgeführt werden:

 . Anlegen einer neuen Datenbank.
 . Installation der PostGIS-Erweiterung für die neue Datenbank.
 . Das SQL-Create-Skript _create.sql_ aus dem Verzeichnis _xplan-manager-workspace/sql_ in der neu angelegten Datenbank ausführen.
 . Anpassen der Datenbank-Verbindungen in den XPlanDiensten und im XPlanManagerWorkspace:
 .. _.deegree/xplan-manager-workspace/jdbc/xplan.xml_
 .. _.deegree/xplan-wfs-workspace/jdbc/xplan.xml_
 .. _.deegree/xplansyn-wfs-workspace/jdbc/xplan.xml_
 .. _.deegree/xplansyn-wms-workspace/jdbc/xplan.xml_

[[aufsetzen-plu-db-schema]]
==== Manuelles Aufsetzen der Datenbank für die Bereitstellung von INSPIRE PLU

Für die Bereitstellung von Plänen, die vom XPlanManager verwaltet werden, als INSPIRE PLU konforme Datensätze ist eine weitere Datenbank erforderlich. Diese kann aktuell nur manuell aufgesetzt werden!

Es müssen die folgenden Schritte ausgeführt werden:

 . Anlegen einer neuen Datenbank.
 . Installation der PostGIS-Erweiterung für die neue Datenbank.
 . Die folgenden SQL-Create-Skripte aus dem Verzeichnis _xplan-manager-workspace/sql/inspireplu_ in der neu angelegten Datenbank ausführen (in dieser Reihenfolge):
 .. _04_create_inspireplu_schema.sql_
 .. _05_create_inspireplu_view.sql_
 . Anpassen der Datenbank-Verbindungen in den XPlanDiensten und im XPlanManagerWorkspace:
 .. _.deegree/xplan-inspireplu-workspace/jdbc/inspireplu.xml_
 .. _.deegree/xplan-manager-workspace/jdbc/inspireplu.xml_

==== Weiterführende Informationen zur Konfiguration des Datenbankzugriffs

In den Dateien __xplan.xml__ werden die ConnectionsPools für den Zugriff auf die Datenbank konfiguriert. Diese beinhalten neben den Verbindungsdetails wie die URL, den Nutzernamen und das Passwort weitere Details, die ggf. bei einer Installation zu berücksichtigen sind. Darunter:

* `initialSize`: Die Anzahl der initialen Verbindungen, die beim Start geöffnet werden.
* `maxTotal`: Die maximale Anzahl von offenen Verbindungen, die von Pool zeitgleich verwendet werden können.
* `maxIdle`: Die maximale Anzahl der Verbindungen, die sich ungenutzt im Pool befinden können.

Da die Anzahl der zugelassenen Verbindungen des Datenbankservers begrenzt sein kann, ist es abhängig von der Installation der xPlanBox, der Anzahl der Nutzer und gegebenenfalls weiterer Faktoren sinnvoll, die vordefinierten Werte an die Installationsumgebung anzupassen.

Alternativ zur Konfiguration von ConnectionsPools für den Zugriff auf die Datenbank kann auch eine JNDI DataSource konfiguriert werden. Details hierzu befinden sich im Handbuch von https://download.deegree.org/documentation/current/html/#anchor-configuration-jdbc[deegree webservices].
