[[konfiguration-der-datenbank]]
=== Konfiguration der Datenbank

Das Anlegen der Datenbank XPlanDB kann mit einem beliebigen Datenbankwerkzeug, wie z. B. dem Kommandozeilentool `psql` oder https://www.pgadmin.org[pgAdmin] erfolgen.

Für die Erstellung der XPlanDB müssen die folgenden Schritte ausgeführt werden:

 . Anlegen einer neuen Datenbank.
 . Installation der PostGIS-Erweiterung für die neue Datenbank.
 . Das SQL-Skript _create.sql_ aus dem Verzeichnis _xplan-manager-workspace/sql_ in der neu angelegten Datenbank ausführen.
 . Anpassen der Datenbank-Verbindungen in den XPlanDiensten und im XPlanManagerWorkspace:
 .. _<DEEGREE_WORKSPACE_ROOT>/xplan-manager-workspace/jdbc/xplan.xml_
 .. _<DEEGREE_WORKSPACE_ROOT>/xplan-wfs-workspace/jdbc/xplan.xml_
 .. _<DEEGREE_WORKSPACE_ROOT>/xplansyn-wfs-workspace/jdbc/xplan.xml_
 .. _<DEEGREE_WORKSPACE_ROOT>/xplansyn-wms-workspace/jdbc/xplan.xml_
. Anpassen der Datenbank-Verbindungen im XPlanValidatorWMS, wenn die persistente Datenhaltung verwendet wird (siehe <<konfiguration-xplanvalidatorwms>>)
.. _<DEEGREE_WORKSPACE_ROOT>/xplan-validator-wms-sql-workspace/jdbc/xplan.xml_

[[aufsetzen-plu-db-schema]]
==== Manuelles Aufsetzen der Datenbank für die Bereitstellung von INSPIRE PLU

Für die Bereitstellung von Plänen, die vom XPlanManager verwaltet werden, als INSPIRE PLU konforme Datensätze ist eine weitere Datenbank erforderlich. Diese kann aktuell nur manuell aufgesetzt werden!

Es müssen die folgenden Schritte ausgeführt werden:

 . Anlegen einer neuen Datenbank.
 . Installation der PostGIS-Erweiterung für die neue Datenbank.
 . Die folgenden SQL-Skripte aus dem Verzeichnis _xplan-manager-workspace/sql/inspireplu_ in der neu angelegten Datenbank ausführen (in der genannten Reihenfolge):
 .. _04_create_inspireplu_schema.sql_
 .. _05_create_inspireplu_view.sql_
 . Anpassen der Datenbank-Verbindungen in den XPlanDiensten und im XPlanManagerWorkspace:
 .. _<DEEGREE_WORKSPACE_ROOT>/xplan-inspireplu-workspace/jdbc/inspireplu.xml_
 .. _<DEEGREE_WORKSPACE_ROOT>/xplan-manager-workspace/jdbc/inspireplu.xml_

==== Weiterführende Informationen zur Konfiguration des Datenbankzugriffs

In den Dateien __xplan.xml__ werden die ConnectionsPools für den Zugriff auf die Datenbank konfiguriert. Diese beinhalten neben den Verbindungsdetails wie die URL, den Nutzernamen und das Passwort weitere Details, die ggf. bei einer Installation zu berücksichtigen sind. Darunter:

* `initialSize`: Die Anzahl der initialen Verbindungen, die beim Start geöffnet werden.
* `maxTotal`: Die maximale Anzahl von offenen Verbindungen, die von Pool zeitgleich verwendet werden können.
* `maxIdle`: Die maximale Anzahl der Verbindungen, die sich ungenutzt im Pool befinden können.

Da die Anzahl der zugelassenen Verbindungen des Datenbankservers begrenzt sein kann, ist es abhängig von der Installation der xPlanBox, der Anzahl der Nutzer und gegebenenfalls weiterer Faktoren sinnvoll, die vordefinierten Werte an die Installationsumgebung anzupassen.

Alternativ zur Konfiguration von ConnectionsPools für den Zugriff auf die Datenbank kann auch eine JNDI DataSource konfiguriert werden. Details hierzu befinden sich im Handbuch von https://download.deegree.org/documentation/current/html/#anchor-configuration-jdbc[deegree webservices].