[[konfiguration-der-datenbank]]
=== Erstellen der Datenbank XPlanDB

Das Erstellen der Datenbank XPlanDB kann mit einem beliebigen Datenbankwerkzeug, wie z. B. dem Kommandozeilentool `psql` oder https://www.pgadmin.org[pgAdmin] erfolgen.

Für die Erstellung der XPlanDB müssen die folgenden Schritte ausgeführt werden:

- Verbindung zum PostgreSQL-Server als Super User (Rolle _postgres_) herstellen
- Anlegen der Datenbank und Datenbankbenutzer mit:
[source,sql]
----
CREATE USER "$DB_INIT_USER" PASSWORD '$DB_INIT_PASSWORD';
CREATE USER "$DB_USER" PASSWORD '$DB_PASSWORD';
CREATE DATABASE "$DB_NAME" OWNER '$DB_INIT_USER';
GRANT ALL PRIVILEGES ON DATABASE "$DB_NAME" TO "$DB_INIT_USER";
GRANT CONNECT ON DATABASE "$DB_NAME" TO "$DB_USER";
----
- Installation der PostGIS-Erweiterung für die neu erstellte Datenbank.
 .. Dazu als Super User (_postgres_) mit der neuen Database `$DB_NAME` verbinden und folgendes SQL-Statement ausführen:
[source,sql]
----
CREATE EXTENSION IF NOT EXISTS postgis;
----
- Das SQL-Skript _create.sql_ aus dem Verzeichnis _xplan-manager-workspace/sql_ in der neu angelegten Datenbank in der Rolle `$DB_INIT_USER` ausführen.
- Anpassen der Datenbank-Verbindungen in den XPlanDiensten und im XPlanManagerWorkspace unter Verwendung der Rolle `$DB_USER`:
 .. _<DEEGREE_WORKSPACE_ROOT>/xplan-manager-workspace/jdbc/xplan.xml_
 .. _<DEEGREE_WORKSPACE_ROOT>/xplan-services-wfs-workspace/jdbc/xplan.xml_
 .. _<DEEGREE_WORKSPACE_ROOT>/xplan-services-wfs-syn-workspace/jdbc/xplan.xml_
 .. _<DEEGREE_WORKSPACE_ROOT>/xplan-services-wms-workspace/jdbc/xplan.xml_
. Anpassen der Datenbank-Verbindungen im XPlanValidatorWMS, wenn die persistente Datenhaltung verwendet wird (siehe <<konfiguration-xplanvalidatorwms>>)
.. _<DEEGREE_WORKSPACE_ROOT>/xplan-webservices-validator-wms-sql-workspace/jdbc/xplan.xml_

NOTE: Weitere Informationen zu der Erstellung der XPlanDB im Anhang <<appendix_xplandb_skript>>.

[[aufsetzen-plu-db-schema]]
==== Erstellen der Datenbank für INSPIRE PLU

Für die Bereitstellung von Plänen, die vom XPlanManager verwaltet werden, als INSPIRE PLU konforme Datensätze ist ein weiteres Datenbankschema erforderlich.

Es müssen die folgenden Schritte ausgeführt werden:

 . Die folgenden SQL-Skripte aus dem Verzeichnis _xplan-manager-workspace/sql/inspireplu_ in der neu angelegten Datenbank ausführen (in der genannten Reihenfolge):
 .. _01_create_inspireplu_schema.sql_
 .. _02_create_inspireplu_view.sql_
 . Anpassen der Datenbank-Verbindungen in den XPlanDiensten und im XPlanManagerWorkspace:
 .. _<DEEGREE_WORKSPACE_ROOT>/xplan-webservices-inspireplu-workspace/jdbc/inspireplu.xml_
 .. _<DEEGREE_WORKSPACE_ROOT>/xplan-manager-workspace/jdbc/inspireplu.xml_

==== Weiterführende Informationen zur Konfiguration des Datenbankzugriffs

In den Dateien __xplan.xml__ werden die ConnectionsPools für den Zugriff auf die Datenbank konfiguriert. Diese beinhalten neben den Verbindungsdetails wie die URL, den Nutzernamen und das Passwort weitere Details, die ggf. bei einer Installation zu berücksichtigen sind. Darunter:

* `initialSize`: Die Anzahl der initialen Verbindungen, die beim Start geöffnet werden.
* `maxTotal`: Die maximale Anzahl von offenen Verbindungen, die von Pool zeitgleich verwendet werden können.
* `maxIdle`: Die maximale Anzahl der Verbindungen, die sich ungenutzt im Pool befinden können.

Da die Anzahl der zugelassenen Verbindungen des Datenbankservers begrenzt sein kann, ist es abhängig von der Installation der xPlanBox, der Anzahl der Nutzer und gegebenenfalls weiterer Faktoren sinnvoll, die vordefinierten Werte an die Installationsumgebung anzupassen.

Alternativ zur Konfiguration von ConnectionsPools für den Zugriff auf die Datenbank kann auch eine JNDI DataSource konfiguriert werden. Details hierzu befinden sich im Handbuch von https://download.deegree.org/documentation/current/html/#anchor-configuration-jdbc[deegree webservices].