[[installation-gdal]]
=== Installation und Konfiguration von GDAL

Die xPlanBox unterstützt die Darstellung von Rasterdaten über die GDAL-Bibliothek.
Die GDAL-Unterstützung ist optional, die Konfiguration im XPlanManagerWeb und XPlanManagerAPI ist im Abschnitt <<konfiguration-gdal>> beschrieben.

Es muss die GDAL-Bibliothek und die dazugehörige JNI-Schnittstelle installiert werden.

IMPORTANT: Der Zugriff auf die GDAL-Bibliothek erfolgt über die Schnittstelle Java Native Interface (JNI). Je JVM kann die GDAL-Bibliothek nur einmal geladen werden. Deswegen muss jede Webapp der xPlanBox, die GDAL verwendet (`xplan-wms` und `xplan-manager-web`), in einer separaten Tomcat-Instanz installiert werden.

[[installation-gdal-linux]]
==== Linux

Damit GDAL über die JNI-Schnittstelle unter Linux angesprochen werden kann, muss die
Umgebungsvariable zur GDAL-Bibliothek gesetzt werden, z. B.:

----
export LD_LIBRARY_PATH=/usr/lib/jni/
----

IMPORTANT: Die Umgebungsvariable `LD_LIBRARY_PATH` muss auf das Verzeichnis
zeigen, in dem sich die Datei _libgdaljni.so_ befindet.

[[installation-gdal-windows]]
==== Windows

Die GDAL-Bibliothek für Windows kann bei https://www.gisinternals.com/[GISInternals]
heruntergeladen werden. Die Architektur der GDAL-Bibliothek (32bit
oder 64bit) muss der Architektur von Java und dem Betriebssystem
http://windows.microsoft.com/de-de/windows/32-bit-and-64-bit-windows[Windows]
entsprechen. Als Download-Format sollten die kompilierten Binaries in
einem einzelnen ZIP-Archiv gewählt werden.

NOTE: Die MSVC-Version mit der GDAL kompiliert wurde, setzt die jeweilige
Version des Microsoft C/C++ Runtime Library (CRT) voraus. Ab der Version
MSVC 11.0 (1700) werden Windows XP and Windows Server 2003 nicht mehr
unterstützt. Die Version des Microsoft C/C++ Runtime Library (CRT) kann über die Windows Systemsteuerung angezeigt werden.

Das ZIP-Archiv kann an einem beliebigen Ort entpackt werden.

Unter
_Systemsteuerung->System und Sicherheit->System->Erweiterte Systemeinstellungen->Erweitert->Umgebungsvariablen_
müssen folgende Einstellungen vorgenommen werden:

* Setzen der Umgebungsvariable `JAVA_HOME` mit der Pfadangabe zum Installationsverzeichnis des JDK, z. B.: `C:\Program Files\Java\jdk-11.0.11`
* Setzen der Umgebungsvariable `GDAL_DATA` mit der Pfadangabe zum Verzeichnis in dem die Datei _gcs.csv_ enthalten ist, z. B.: `C:\Program Files (x86)\gdal\bin\gdal-data`
* Zur Umgebungsvariable _PATH_ müssen zwei Pfade hinzugefügt werden (Annahme: Entpacktes ZIP-Archiv von GISInternals wurde genutzt):
`<GDAL-INSTALLATIONSORDNER>\bin;<GDAL-INSTALLATIONSORDNER>\bin\gdal\java`
