[[anwendung-installieren]]
=== Anwendungskomponenten installieren

Speichern Sie die Distributionsdatei in einem lokalen Verzeichnis und entpacken Sie die ZIP-Datei. Prüfen Sie die Vollständigkeit der Distributionsdatei anhand der Auflistung der im Kapitel <<installationskomponenten>>.

[[konfiguration]]
==== Konfigurationsdateien der Anwendungskomponenten

Die ZIP-Archive mit den deegree Workspaces (s. <<installationskomponenten>>) müssen in das Verzeichnis _<DEEGREE_WORKSPACE_ROOT>_ (s. <<vorbereitung-der-installation>>) entpackt werden:

* _xplan-manager-workspace.zip_
* _xplan-services-wfs-workspace.zip_
* _xplan-services-wfs-syn-workspace.zip_
* _xplan-services-wms-workspace.zip_
* _xplan-validator-workspace.zip_ (nur erforderlich in Kombination mit dem _xplan-webservices-validator-wms-sql-workspace.zip_)
* _xplan-webservices-validator-wms-memory-workspace.zip_ *oder* _xplan-webservices-validator-wms-sql-workspace.zip_ (siehe <<konfiguration-xplanvalidatorwms>>)
* _xplan-webservices-inspireplu-workspace.zip_ (optional)

Die ZIP-Archive mit den Konfigurationen für die XPlanManager und XPlanValidator (s. <<installationskomponenten>>) müssen in das Verzeichnis _<XPLANBOX_CONFIG>_ (s. <<vorbereitung-der-installation>>) entpackt werden:

* _xplan-manager-config-default.zip_
* _xplan-validator-config.zip_ (nur erforderlich, wenn ausschließlich der XPlanValidator installiert werden soll)
* _xplan-dokumente-config.zip_ (optional)

[[web-anwendungen]]
==== Web-Anwendungen

Um den Betrieb der verschiedenen im Abschnitt
<<systemarchitektur-und-schnittstellen, Systemarchitektur und Schnittstellen>> beschriebenen
Komponenten zu gewährleisten, wird eine Trennung der Dienste,
Anwendungskomponenten und der REST-API empfohlen. Zwingend erforderlich ist die Trennung beim
Einsatz von GDAL (s. <<installation-gdal>>). Dann müssen die Web-Anwendungen getrennt voneinander
betrieben werden. Im Folgenden ist beschrieben, wie eine Installation der Komponenten auf drei Tomcat-Instanzen erfolgen kann. Werden drei Tomcat-Instanzen auf einem Server betrieben, dann sollte der Server die im Kapitel <<empfohlene-systemkonfiguration>> beschriebenen Anforderungen erfüllen.

Die folgenden WAR-Archive (s. <<installationskomponenten>>) müssen in das Verzeichnis _<CATALINA_HOME>/webapps_ der Tomcat-Instanz _Dienste-Tomcat_ (z. B. auf Port: 8080) kopiert werden:

* _xplan-services-wfs.war_ (XPlanWFS)
* _xplan-services-wfs-syn.war_ (XPlanSynWFS)
* _xplan-services-wms.war_ (XPlanWMS und XPlanWerkWMS)
* _xplan-webservices-inspireplu.war_ (XPlanInspirePluWMS und XPlanInspirePluWFS) (optional)
* _xplan-webservices-validator-wms.war_ (XPlanValidatorWMS)

Die WAR-Archive der Anwendungskomponenten XPlanManagerWeb und XPlanValidatorWeb werden über eine weitere Tomcat-Instanz _Anwendungs-Tomcat_ (z. B. auf Port: 8081) bereitgestellt:

* _xplan-manager-web.war_ (XPlanManagerWeb)
* _xplan-validator-web.war_ (XPlanValidatorWeb)
* _xplan-webpages-default.war_ (XPlanRessourcen)

Die WAR-Archive der REST-API werden über eine weitere Tomcat-Instanz _API-Tomcat_ (z. B. auf Port: 8082) bereitgestellt:

* _xplan-manager-api.war_ (XPlanManagerAPI)
* _xplan-validator-api.war_ (XPlanValidatorAPI)

TIP: Da die Komponente XPlanRessourcen eine Einstiegsseite bereitstellt, bietet es sich an, diese als ROOT-Webapp der Instanz _Anwendungs-Tomcat_ zu installieren. Das WAR-Archiv _xplan-webpages-default.war_ muss dafür im Verzeichnis _ROOT_ entpackt werden.

[[installation-webapp-properties]]
==== Verknüpfung von Webapp und Workspace

Für die Tomcat-Instanz _Dienste-Tomcat_ muss eine _webapp.properties_ Datei angelegt werden.
Diese enthält die Verknüpfung zwischen der Webapp und dem Workspace.

.Beispiel für _webapps.properties_ für den _Dienste-Tomcat_:
[source,properties]
----
/xplan-services-wms=xplan-services-wms-workspace
/xplan-services-wfs-syn=xplan-services-wfs-syn-workspace
/xplan-services-wfs=xplan-services-wfs-workspace
/xplan-webservices-validator-wms=xplan-webservices-validator-wms-memory-workspace <1>
/xplan-webservices-inspireplu=xplan-webservices-inspireplu-workspace
----
<1> dieser Workspace wird als Vorgabewert konfiguriert, alternativ kann der _xplan-webservices-validator-wms-sql-workspace_ verwendet werden (weitere Informationen zur Konfiguration des XPlanValidatorWMS sind im Kapitel <<konfiguration-xplanvalidatorwms>> zu finden).

[[kommandozeilen-anwendungen]]
==== Kommandozeilen-Anwendungen

Die Kommandozeilenkomponenten (s. <<installationskomponenten>>) können an beliebiger Stelle entpackt werden. Im jeweiligen _bin/_ Verzeichnis des Kommandozeilenwerkzeugs befindet sich das Ausführungsskript.

TIP: Um die Kommandozeilenwerkzeuge von einem beliebigen Ort aufrufen zu können, empfiehlt es sich, die Pfade in die `PATH` Variable mit aufzunehmen.

IMPORTANT: Je nach Kommandozeilenwerkzeug müssen über Umgebungsvariablen wie z. B. `DEEGREE_WORKSPACE_ROOT` der Pfad zum deegree Workspace und mit `LD_LIBRARY_PATH` der Pfad zum Installationsverzeichnis von GDAL gesetzt werden (siehe auch <<installation-gdal>>).

Folgende Kommandos sind Teil der XPlanCLI Tools:

* Kommando `validate`: _xpb validate_ - Beschreibung der Funktionalität im Kapitel "XPlanCLI Tools" des XPlanBenutzerhandbuchs.
** Subkommando `db`: _xpb validate db_ - ermöglicht die **semantische** Validierung von bereits in die <<XPlanDB>> importierten Plänen. Der Aufruf des Kommandos mit `help` liefert Hinweise zur Verwendung.
* Kommando `manage`: _xpb manage_ - Beschreibung der Funktionalität im Kapitel "XPlanCLI Tools" des XPlanBenutzerhandbuchs.
** Subkommando `create-metadata`: _xpb manage create-metadata_ - Erzeugt Dienst-Metadaten für den <<xplanwms, XPlanWerkWMS>>.
* Kommando `admin`: _xpb admin_ - mit folgenden Subkommandos, die für die <<aktualisierung,Aktualisierung>> des Datenbestands in der <<xplandb>> verwendet werden können.
** Subkommando `district-update`:  _xpb admin district-update_ - ermöglicht die Aktualisierung der in der Datenbank gespeicherten Ortsteilnamen. Der Aufruf des Tools mit `help` liefert Hinweise zur Verwendung.
** Subkommando `resynthesize`: _xpb admin resynthesize_ - ermöglicht die Aktualisierung der im XPlanSyn-Schema gespeicherten Daten. Der Aufruf des Tools mit `help` liefert Hinweise zur Verwendung.
** Subkommando `sortdate-update`: _xpb admin sortDateUpdate_ - ermöglicht die Aktualisierung der in der Datenbank gespeicherten Sortierfelder und die Sortierung der Rasterdaten in der Themes Konfiguration, sofern deegree für die Bereitstellung der Rasterdaten verwendet wird. Der Aufruf des Tools mit `help` liefert Hinweise zur Verwendung.
** Subkommando `evaluation-db-update`: _xpb admin evaluation-db-update_ - das Kommando erzeugt ein weiteres Datenbankschema für die Auswertung und kann die Daten aus dem XPlanSyn-Schema der XPlanDB mit dem des Auswerteschemas synchronisieren. Das Auswerteschema unterscheidet sich zum XPlanSyn-Schema dadurch, dass die GML-Geometrien (wie z.B. Kreisbögen) aus dem XPlanGML zusätzlich zu den https://www.ogc.org/standards/sfa[Simple Features Geometrien] abgelegt sind.

[[xplanevaluationschema]]
===== Konfiguration für das Auswerteschema

Das Anlegen des zusätzlichen Datenbankschemas ist optional. Für den Betrieb der xPlanBox ist dieses nicht erforderlich.
Das Datenbankschema für die Auswertung muss durch Ausführen der SQL-Skripte aus dem Verzeichnis _scripts/_ angelegt werden. Folgende Reihenfolge muss beibehalten werden:

. _00_create_schema.sql_
. _01_create_function.sql_
. _02_create_tables.sql_
. _03_create_trigger-function.sql_
. _04_create_trigger.sql_
. _05_grant_user.sql_ (zuvor muss die Variable `$DB_USER` im Skript durch den Namen des Datenbanknutzers ausgetauscht werden, mit dem der XPlanManager und die XPlanDienste auf die XPlanDB zugreifen (s. Abschnitt <<konfiguration-der-datenbank>>).

Die Skripte erstellen eine Kopie der drei XPlanSyn-Schemas in den Schemas _xplanevaluationxplansynpre_, _xplanevaluationxplansyn_ und _xplanevaluationxplansynarchive_ sowie eine Log-Tabelle _xplanevaluation.planTableLog_.

Die Log-Tabelle wird beim Importieren, Editieren und Löschen von Plänen über den XPlanManager mit einer Historie der ausgeführten Operationen auf die einzelnen Pläne gefüllt und dient als Basis für die regelmäßige Synchronisierung des Auswerteschemas mit dem XPlanSyn-Schema.

===== Synchronisation des Auswerteschemas

Das Kommando unterstützt zwei Modi, die über die Option `-t` aufgerufen werden können:

* Option *ALL* zur Überführung aller Pläne aus dem XPlanSyn-Schema der xPlanBox in das Auswerteschema.
* Option *SYNC* um die Synchronisierung der seit der letzten Ausführung des Werkzeuges geänderten Pläne aus dem XPlanSyn-Schema in das Auswerteschema durchzuführen.

Es erfolgt zunächst einmalig die Ausführung mit der Option *ALL* und anschließend regelmäßig (z.B. mit Hilfe eines Cron-Jobs) mit der Option *SYNC* um einen tagesaktuellen Stand im Auswerteschema zu erreichen.
Die zweimalige Ausführung mit der Option *ALL* führt zu einem Fehler bei der Ausführung, wenn bereits Daten synchronisiert wurden.

Die einzelnen Parameter des Werkzeuges können durch folgenden Aufruf abgerufen werden:

-------
xpb admin evaluation-db-update help
-------

Beispiel für den Aufruf mit den Parametern `-h` für den Hostnamen des PostgreSQL-Servers, `-p` den Port, `-d` der Datenbank, `-u` dem Benutzer, `-P` dem Passwort, `-t` der Angabe zur Synchronisierung:

-------
xpb admin evaluation-db-update -h localhost -p 5432 -d xplanbox -u postgres -P postgres -t ALL
-------

[[dokumentation]]
==== Dokumentation

Das XPlanBenutzerhandbuch und XPlanBetriebshandbuch (s. <<installationskomponenten>>) zu den verschiedenen Komponenten der xPlanBox liegt in den Formaten HTML und PDF vor.
