[[anwendung-installieren]]
=== Anwendung installieren

[[konfiguration]]
==== Konfiguration

Die ZIP-Archive mit den Konfigurationen (s. <<installationskomponenten>>) müssen in das
Verzeichnis _.deegree_ im Home-Verzeichnis (s. <<vorbereitung-der-installation>>) des Nutzers kopiert und entpackt werden:

* _xplan-wfs-workspace_
* _xplansyn-wfs-workspace_
* _xplansyn-wms-workspace_
* _xplan-inspireplu-workspace_ (XPlanInspirePluWMS und XPlanInspirePluWFS)
* _xplan-validator-wms-workspace_
* _xplan-manager-workspace_
* _xplan-manager-config_
* _xplan-validator-config_ (nur erforderlich, wenn ausschließlich der XPlanValidator installiert werden soll)

NOTE: Die Konfigurationen müssen alle unterhalb des selben Basis-Verzeichnisses liegen.

[[web-anwendungen]]
==== Web-Anwendungen

Um den Betrieb der verschiedenen im Abschnitt
<<systemarchitektur-und-schnittstellen, Systemarchitektur und Schnittstellen>> beschriebenen
Komponenten zu gewährleisten, wird eine Trennung der Dienste,
Anwendungskomponenten und der REST-API empfohlen. Zwingend erforderlich ist die Trennung beim
Einsatz von GDAL (s. <<installation-gdal>>). Dann müssen die Web-Anwendungen getrennt voneinander
betrieben werden. Im Folgenden ist beschrieben, wie eine Installation der Komponenten auf drei Tomcat-Instanzen erfolgen kann. Werden drei Tomcat-Instanzen auf einem Server betrieben, dann sollte der Server die im Kapitel <<empfohlene-systemkonfiguration>> beschriebenen Anforderungen erfüllen.

Die folgenden WAR-Archive (s. <<installationskomponenten>>) müssen in das Verzeichnis `webapps`
der Tomcat-Instanz (_Dienste-Tomcat_, z. B. Port: 8080) kopiert
werden:

* _xplan-wms.war_ (XPlanWMS und XPlanWerkWMS)
* _xplan-wfs.war_ (XPlanWFS)
* _xplansyn-wfs.war_ (XPlanSynWFS)
* _xplan-inspireplu.war_ (XPlanInspirePluWMS und XPlanInspirePluWFS)
* _xplan-validator-wms.war_ (XPlanValidatorWMS)

Die WAR-Archive der Anwendungskomponenten XPlanManagerWeb und XPlanValidatorWeb werden über eine
weitere Tomcat-Instanz (_Anwendungs-Tomcat_, z. B. Port: 8081)
bereitgestellt:

* _xplan-manager-web.war_ (XPlanManagerWeb)
* _xplan-validator-web.war_ (XPlanValidatorWeb)
* _xplan-root.war_ (XPlanRessourcen)

Die WAR-Archive der REST-API werden über eine weitere Tomcat-Instanz (_API-Tomcat_, z. B. Port: 8082)
bereitgestellt:

* _xplan-api-manager.war_ (XPlanManagerAPI)
* _xplan-api-validator.war_ (XPlanValidatorAPI)


NOTE: Da die Komponente XPlanRessourcen eine Einstiegsseite bereitstellt, bietet es sich an, diese als ROOT-Webapp des Anwendungs-Tomcat zu installieren. Das WAR-Archiv _xplan-root.war_ muss dafür im Verzeichnis _ROOT_ entpackt werden.

[[kommandozeilen-anwendungen]]
==== Kommandozeilen-Anwendungen

Die Kommandozeilenkomponenten (s. <<installationskomponenten>>) können an beliebiger Stelle entpackt werden. _xplan-update-database_ wird nur für eine Aktualisierung der xPlanBox benötigt (weitere Informationen befinden sich im Abschnitt <<aktualisierung>>). Im jeweiligen _bin_ Verzeichnis der beiden Kommandozeilenwerkzeuge findet sich das entsprechende Ausführungsskript:

* _XPlanManager_ (XPlanManagerCLI)
* _XPlanValidator_ (XPlanValidatorCLI)

[[dokumentation]]
==== Dokumentation

Das XPlanBenutzerhandbuch (s. <<installationskomponenten>>) zu den verschiedenen Komponenten liegt in den Formaten HTML und PDF vor.

[[installation-über-ein-install-skript]]
==== Installation über ein Install-Skript

Das Ablegen der Web-Archive sowie der Konfigurationsdateien kann auf Linux-Umgebungen auch über das angehängte
Installations-Skript (s. <<Installations-Skript, Anhang>>) ausgeführt werden:

----
sh ${WORK_DIR}/install.sh
----

NOTE: Das Installationsskript wird ohne Gewähr bereitgestellt! Dieses Skript kann als Vorlage für eine Installationsroutine verwendet werden. Für professionelle Unterstützung wenden Sie sich bitte an die https://www.lat-lon.de[lat/lon GmbH].