[[konfiguration-der-applikationsserver]]
=== Konfiguration der Applikationsserver

Wie im Abschnitt <<anwendung-installieren>> beschrieben,
werden für den Betrieb aller Komponenten der xPlanBox getrennte Tomcat-Instanzen empfohlen,
der _Anwendungs-Tomcat_, _Dienste-Tomcat_ und _API-Tomcat_. Im Folgenden wird die
Konfiguration der drei Tomcat-Instanzen beschrieben.

[[anwendungs-tomcat]]
==== Anwendungs-Tomcat

Im _Anwendungs-Tomcat_ muss folgende Konfiguration vorgenommen werden:

. Für den XPlanManagerWeb muss die Variable _XPLANBOX_CONFIG_ als Java Property gesetzt werden. Das mit Hilfe dieser Variable referenzierte Verzeichnis muss die Konfiguration des XPlanManagerWeb und XPlanValidatorWeb enthalten, mit den Dateien _managerConfiguration.properties_,
_managerWebConfiguration.properties_ und _validatorConfiguration.properties_. Wurde der Anleitung in Abschnitt <<anwendung-installieren>> gefolgt, befindet sich das Verzeichnis mit dem Namen _xplan-manager-config_ im Verzeichnis _.deegree_ im Home-Verzeichnis des Nutzers. Wird ausschließlich der XPlanValidatorWeb installiert, heißt das Verzeichnis _xplan-validator-config_.
. Die Bibliothek JTS muss über die Variable `jts.overlay=ng` konfiguriert werden.
. Die Bibliothek deegree muss über die Variable `javax.xml.transform.TransformerFactory=net.sf.saxon.TransformerFactoryImpl` konfiguriert werden.

IMPORTANT: Wurden die Workspaces nicht im Verzeichnis _.deegree_ des Home-Verzeichnis abgelegt, ist das Setzen der Umgebungsvariable _DEEGREE_WORKSPACE_ROOT_ zusätzlich erforderlich.

TIP: Es wird empfohlen die Zeitzone im _Anwendungs-Tomcat_ auf "Europe/Berlin" zu konfigurieren, wenn dies nicht bereits auf Ebene des Betriebssystems gesetzt ist. Andernfalls kann es beim Editieren eines Plans veränderten Datumsangaben (z. B. Herstellungsdatum) kommen. Für die Konfiguration im Tomcat muss folgende Option zusätzlich in den `CATALINA_OPTS` ergänzt werden: `-Duser.timezone=Europe/Berlin`.

[[anwendungs-tomcat-linux]]
===== Linux

Unter Linux muss im Verzeichnis _<CATALINA_HOME>/bin_ der Instanz _Anwendungs-Tomcat_ ggfs. eine neue Datei mit dem Namen _setenv.sh_ angelegt werden.

In dieser Datei wird die Variable `CATALINA_OPTS` wie folgt erweitert:

----
export CATALINA_OPTS='-DXPLANBOX_CONFIG=/home/xplanbox/.deegree/xplan-manager-config -DDEEGREE_WORKSPACE_ROOT=/pfad/zu/den/workspaces -Djts.overlay=ng -Djavax.xml.transform.TransformerFactory=net.sf.saxon.TransformerFactoryImpl -Duser.timezone=Europe/Berlin'
----

Falls bereits ein Export von `CATALINA_OPTS` in dieser Datei vorhanden ist, muss die Variable `CATALINA_OPTS` erweitert werden.

[[anwendungs-tomcat-windows]]
===== Windows

Unter Windows muss im Verzeichnis _<CATALINA_HOME>/bin_ der Instanz _Anwendungs-Tomcat_ ggfs. eine neue Datei mit dem Namen _setenv.bat_ angelegt werden.

In dieser Datei wird die Variable `CATALINA_OPTS` wie folgt erweitert:

----
export CATALINA_OPTS='-DXPLANBOX_CONFIG=C:\.deegree\xplan-manager-config -DDEEGREE_WORKSPACE_ROOT=C:\pfad\zu\den\workspaces -Djts.overlay=ng -Djavax.xml.transform.TransformerFactory=net.sf.saxon.TransformerFactoryImpl -Duser.timezone=Europe/Berlin'
----

Falls bereits ein Export von `CATALINA_OPTS` in dieser Datei vorhanden ist, muss die Variable  `CATALINA_OPTS` erweitert werden.

IMPORTANT: Der _Anwendungs-Tomcat_ muss mindestens über 4GB Arbeitsspeicher verfügen, dies kann durch Setzen der Umgebungsvariable: `export JAVA_OPTS='-Xmx4096m'` erfolgen.

[[dienste-tomcat]]
==== Dienste-Tomcat

Falls der XPlanManager nach jedem Einfügen und Löschen eines Plan den
XPlanWMS und XPlanWerkWMS aktualisieren soll, muss ein Tomcat-Nutzer angelegt werden.
Ansonsten ist ein manueller Workspace-Reload nötig, um die neu
importieren bzw. gelöschten Rasterpläne im XPlanWMS darzustellen bzw. zu
entfernen.

Dafür müssen in der Datei _<CATALINA_HOME>/conf/tomcat-users.xml_ der Instanz _Dienste-Tomcat_ folgende
Zeilen hinzugefügt werden:

----
<role rolename="deegree"/>
<user username="<NUTZERNAME>" password="<PASSWORT>" roles="deegree"/>
----
Weitere Informationen zur https://tomcat.apache.org/tomcat-9.0-doc/realm-howto.html[Konfiguration von Benutzern] ist in der Dokumentation von Apache Tomcat zu finden.

NOTE: Der Nutzername und das Passwort müssen in die
_managerConfiguration.properties_ eingetragen werden (s. Kapitel
<<automatischer-workspace-reload>>.

Für den _Dienste-Tomcat_ muss auch die Variable `CATALINA_OPTS` wie folgt erweitert werden:

----
export CATALINA_OPTS='-DDEEGREE_WORKSPACE_ROOT=/pfad/zu/den/workspaces -Djavax.xml.transform.TransformerFactory=net.sf.saxon.TransformerFactoryImpl'
----

CAUTION: Der _Dienste-Tomcat_ muss ebenfalls mindestens über 4GB Arbeitsspeicher verfügen,
dies kann durch Setzen der Umgebungsvariable: `export JAVA_OPTS='-Xmx4096m'` erfolgen.

[[api-tomcat]]
==== API-Tomcat

Für den _API-Tomcat_ muss auch die Variable `CATALINA_OPTS` wie auch für den <<dienste-tomcat,_Dienste-Tomcat_>> wie folgt erweitert werden:

----
export CATALINA_OPTS='-DXPLANBOX_CONFIG=/home/xplanbox/.deegree/xplan-manager-config -DDEEGREE_WORKSPACE_ROOT=/pfad/zu/den/workspaces -Djts.overlay=ng -Djavax.xml.transform.TransformerFactory=net.sf.saxon.TransformerFactoryImpl -Duser.timezone=Europe/Berlin'
----

CAUTION: Der _API-Tomcat_ muss ebenfalls mindestens über 4GB Arbeitsspeicher verfügen,
dies kann durch Setzen der Umgebungsvariable: `export JAVA_OPTS='-Xmx4096m'` erfolgen.

==== Absicherung des Tomcat und der Webanwendungen

Wenn die xPlanBox in einer produktiven Umgebung betrieben wird, sollte der Apache Tomcat abgesichert werden. Dazu sind die allgemeinen Empfehlungen aus der https://tomcat.apache.org/tomcat-9.0-doc/security-howto.html[Dokumentation von Apache Tomcat zum Thema Sicherheit] zu beachten.

Zusätzlich sollte die xPlanBox wie folgt konfiguriert sein:

. die deegree webservice console für die Dienste _xplan-wms_, _xplan-wfs_, _xplansyn-wfs_ und _xplan-inspireplu_ im _Dienste-Tomcat_ ist durch ein Kennwort geschützt (Datei _console.pw_ im deegree Workspace).
. die deegree REST-Schnittstelle ist durch Benutzername und Kennwort abgesichert (Datei _web.xml_ und _tomcat-users.xml_ im Tomcat-Konfigurationsverzeichnis, siehe Kapitel <<dienste-tomcat>>).
. der Zugriff auf die deegree webservice console ist auf IP-Adressbereiche bzw. Domänen eingeschränkt (Datei _context.xml_ innerhalb der Webanwendungen).
. die Tomcat-Instanzen werden hinter einem Proxy (z. B. Apache httpd) betrieben (Datei _server.xml_ im Tomcat-Konfigurationsverzeichnis).
. der Zugriff auf den XPlanManagerWeb ist durch Benutzername und Kennwort abgesichert (siehe Kapitel <<security>>).
