\i fix/xplan2/drop.sql
\i fix/xplan3/drop.sql
\i fix/xplan40/drop.sql
\i fix/xplan41/drop.sql
\i fix/xplan41nsm/drop.sql
\i fix/xplan50/drop.sql
\i fix/xplan51/drop.sql
\i fix/xplansyn/drop.sql
\i pre/xplan2/drop.sql
\i pre/xplan3/drop.sql
\i pre/xplan40/drop.sql
\i pre/xplan41/drop.sql
\i pre/xplan41nsm/drop.sql
\i pre/xplan50/drop.sql
\i pre/xplan51/drop.sql
\i pre/xplansyn/drop.sql
\i archive/xplan2/drop.sql
\i archive/xplan3/drop.sql
\i archive/xplan40/drop.sql
\i archive/xplan41/drop.sql
\i archive/xplan41nsm/drop.sql
\i archive/xplan50/drop.sql
\i archive/xplan51/drop.sql
\i archive/xplansyn/drop.sql
\i xplanmgr/drop.sql