[XPlanValidator Web]
=== XPlanValidatorWeb

Die Komponente XPlanValidatorWeb ist eine Web-Oberfläche, welche dem
Fachadministrator der xPlanBox ermöglicht, XPlanGML Instanzdokumente zu
validieren. Der XPlanValidatorWeb ist auf dem Kommandozeilenwerkzeug
aufgebaut.

[[benutzungsanleitung]]
==== Benutzungsanleitung

Die Webanwendung XPlanValidatorWeb dient der Validierung von XPlanGML und
ist unter:

----
http://<host>:<port>/xplanvalidator/
----

verfügbar.

[[hinzufuegen]]
===== Hinzufügen

Das XPlanArchiv kann über den Button _Durchsuchen_ ausgewählt und über
die Auswahl _Hochladen und Validierungsoption einstellen_ zur
Web-Anwendung hinzugefügt werden.

Der Benutzer erhält einen Hinweis, dass der Plan in die Web-Anwendung
geladen wurde.

===== Bezeichnung der Validierung

Für jede Validierung kann eine Bezeichnung vergeben werden, sodass der
Durchlauf zu einem späterem Zeitpunkt eindeutig zugeordnet werden kann.

[[validierungsart]]
===== Validierungsart

Die folgenden Validierungsarten können über ein Menü ausgewählt
werden:
  * Syntaktische Validierung
  * Geometrische Validierung
  * Semantische Validierung

Die Auswahl ist obligatorisch.

[[validierungsoption]]
===== Validierungsoption

Die folgenden Validierungsoptionen können über den Button _weitere
Validierungsoptionen_ ausgewählt werden:
  * falsche Laufrichtung von Polygonen ignorieren
  * Selbstüberschneidungen ignorieren
  * Toleranz für Stützpunktabstände in m
  * Sonstige Planwerke ignorieren
  * Präsentationsobjekte ignorieren

Die Änderungen können über den Button _Speichern_ für den aktuellen
Validierungsdurchlauf gespeichert werden. Die Auswahl ist optional.

[[validierung]]
===== Validierung

Die Validierung kann über den Button _Validierung starten_ gestartet
werden.

[[validierungsergebnis]]
==== Validierungsergebnis

Das Ergebnis der Validierung kann im Anschluss als HTML, PDF und XML
Report herunter geladen werden. Je nachdem ob ein Geometriefehler
enthalten ist, können die Geometriefehler als Shapefile und als Grafik
gespeichert werden.

Alle Ergebnisdateien werden in einem Zip Archiv gespeichert. Der
Dateiname enthält die Bezeichnung der Validierung.
