[XPlanValidator Web]
=== XPlanValidatorWeb

Die Komponente XPlanValidatorWeb ist eine Web-Oberfläche, welche dem
Fachadministrator der xPlanBox ermöglicht, XPlanGML Instanzdokumente zu
validieren. Der XPlanValidatorWeb ist auf dem Kommandozeilenwerkzeug
XPlanValidatorCLI aufgebaut.

[[benutzungsanleitung]]
==== Benutzungsanleitung

Die Web-Anwendung XPlanValidatorWeb dient der Validierung von XPlanGML und
ist unter:

----
http://<host>:<port>/xplanvalidator/
----

verfügbar.

[[hinzufuegen]]
===== XPlanArchiv Hinzufügen

Ein im lokalen Dateisystem vorliegendes XPlanArchiv kann über den Button _Durchsuchen_ ausgewählt und über
die Auswahl _Hochladen und Validierungsoption einstellen_ auf den Server
hochgeladen werden.

Nachdem die Datei erfolgreich übertragen wurde, erhält der Benutzer einen Hinweis, dass das XPlanArchiv in die Web-Anwendung
geladen wurde.

===== Bezeichnung der Validierung

Für jede Validierung kann eine Bezeichnung vergeben werden, sodass der
Durchlauf zu einem späterem Zeitpunkt eindeutig zugeordnet werden kann.

[[validierungsart]]
===== Validierungstyp

Die folgenden Validierungstypen können über eine Auswahlliste ausgewählt
werden:

  * Semantische Validierung
  * Geometrische Validierung
  * Syntaktische Validierung

Die Auswahl ist obligatorisch. Wenn die semantische Validierung ausgewählt wird, werden die geometrische und
syntaktische Validierung zusätzlich ausgeführt. Wird die geometrische Validierung ausgewählt, dann wird
zusätzlich auch die syntaktische Validierung ausgeführt.

[[validierungsoption]]
===== Validierungsoption

Die folgenden Validierungsoptionen können über den Button _weitere
Validierungsoptionen_ ausgewählt werden:

  * Selbstüberschneidungen ignorieren
  * falsche Laufrichtung von Polygonen ignorieren
  * Toleranz für Stützpunktabstände in Metern
  * Sonstige Planobjekte ignorieren
  * Präsentationsobjekte ignorieren

Die Änderungen können über den Button _Speichern_ für den aktuellen
Validierungsdurchlauf gespeichert werden. Die Auswahl ist optional.

[[validierung]]
===== Validierung

Die Validierung kann über den Button _Validierung starten_ gestartet
werden.

[[validierungsergebnis]]
==== Validierungsergebnis

Das Ergebnis der Validierung kann im Anschluss als HTML, PDF und XML
Report herunter geladen werden. Je nachdem ob ein Geometriefehler
enthalten ist, können die Geometriefehler als Shapefile und als Grafik
gespeichert werden.

Alle Ergebnisdateien werden in einem Zip Archiv gespeichert. Der
Dateiname enthält die Bezeichnung der Validierung.
