[XPlanManagerWeb]
=== XPlanManagerWeb

Die Komponente XPlanManagerWeb ist eine Web-Oberfläche, die dem
Fachadministrator der xPlanBox ermöglicht, die Datenhaltung zu
kontrollieren. Die Web-Oberfläche ist auf dem Kommandozeilenwerkzeug
aufgebaut. Der XPlanManagerWeb ist in der Lage, XPlanGML
Instanzdokumente in die Datenhaltung zu Laden, zu Löschen sowie
importiere Pläne in einer Liste anzuzeigen.

[[benutzungsanleitung]]
==== Benutzungsanleitung

Die Webanwendung XPlanManagerWeb dient der Verwaltung von XPlanGML
konformen Plänen und ist unter:

----
http://<host>:<port>/xplanmanager/
----

verfügbar.

[[hilfe]]
===== Hilfe

Die Hilfe mit den Angaben zu den möglichen Funktionen lässt sich durch
Betätigen des Buttons _Hilfe_ ausgeben.

[[hinzufuegen]]
===== Hinzufügen

Vor dem Importieren eines XPlanGML Instanzdokumentes in die Datenbasis,
muss dieser über die Web-Oberfläche hochgeladen werden. Hierfür kann der Plan
über den Button _Durchsuchen_ ausgewählt und durch einen Klick auf
_Import_ hochgeladen werden. Der Benutzer wird
über das erfolgreiche bzw. fehlerhafte Hinzufügen des Plans in Form
eines PopUps informiert.

Nachdem der Plan hochgeladen wurde, kann dieser
validiert bzw. entfernt werden. Erst nachdem der Plan erfolgreich
validiert wurde, kann der Plan in die Datenbasis importiert werden.
Andernfalls ist der Button _Import_ deaktiviert.

[[import]]
===== Import

Nachdem der Plan erfolgreich validiert wurde, kann der Plan durch einen
Klick auf den Button _Import_ in die Datenbasis importiert werden. Der
Benutzer wird über den erfolgreichen bzw. fehlerhaften Import des Plans
in Form eines PopUps informiert.

[[auflistung]]
===== Auflistung

Standardmäßig werden alle importierten Pläne in einer Liste angezeigt.
Diese Liste kann nach dem __Namen__, der __ID__, dem __Plantyp__, der
__sonstige Planart__, dem __Rechtsstand__, dem
__Veröffentlichungsdatum__, dem _Importdatum_ oder nach dem _Planstatus_
auf- oder absteigend sortiert werden.

[[kartenvorschau]]
===== Kartenvorschau

Durch den Klick auf den Button _Kartenvorschau_ öffnet sich ein neues
Fenster, indem der XPlan visualisiert wird. Im Hintergrund befindet sich
eine OpenStreetMap Karte. Durch den Klick auf _Schließen_ wird die
Kartenvorschau wieder geschlossen.

[[herunterladen]]
===== Herunterladen

Die importierten Pläne können vom Benutzer durch den Klick auf den
Button _Herunterladen_ wieder heruntergeladen werden.

[[loeschen]]
==== Löschen

Je nach Benutzerrechten können die importierten Pläne durch den Klick
auf den Button _Löschen_ aus der Datenbasis gelöscht werden. Hat ein
Benutzer keine Rechte, so wird der Button grau dargestellt.

[[editieren]]
===== Editieren

Abhängig von den Benutzerrechten können Pläne editiert werden. Fehlen dem Benutzer
die entsprechenden Rechte ist die Funktion deaktiviert und der Button __Editieren__ wird grau dargestellt. Das Editieren ist beschränkt auf BPläne in der XPlanGML Version
3.0 und 4.1. Die Editieransicht öffnet sich durch den Klick auf den
Button __Editieren__. Die Ansicht ist in verschiedene Bereiche
aufgeteilt, die insgesamt die Bearbeitung folgender Elemente zulässt:

*Basisdaten*

________________________
* name
* beschreibung
* technHerstellDatum
* untergangsDatum
* planArt
* sonstPlanArt
* verfahren
* rechtsstand
* rechtsverordnungsDatum
________________________

Das Editieren des Rechtsstands kann dazu führen, dass eine
Zustandsänderung des Plans eintritt Damit verbunden ist das Verschieben
der Vektor- und Rasterdaten in die entsprechende Datenhaltung. Übergänge
sind beliebig zwischen den drei Zuständen 'Festgestellt', 'In
Aufstellung' und 'Archiviert' möglich. Eine Zustandsänderung von
'Festgestellt' nach 'In Aufstellung' tritt beispielsweise beim Ändern
des Rechtsstands von 'InkraftGetreten' nach 'Untergegangen' ein.

Achtung: Beim Import kann der Nutzer den Zustand eines Planes über eine
Auswahlliste mit den Optionen 'Festgestellt, ’In Aufstellung' und
'Archiviert' ändern. Abhängig von dem im Plan gesetzten Rechtsstand wird
eine Vorauswahl getroffen, die der Nutzer aber überschreiben kann. Beim
Öffnen der Editieransicht wird der Rechtsstand aus dem Plan
berücksichtigt, der vom Nutzer ausgewählte Zustand bleibt dagegen
unberücksichtigt. Somit entspricht die Auswahl des Rechtsstands nicht
dem Zustand des Plans, falls dieser beim Import manipuliert wurde. Beim
Abspeichern eines Editiervorgangs ist hier somit Vorsicht geboten, da so
unbeabsichtigt eine Zustandsänderung vorgenommen werden kann.

*Gültigkeitszeitraum*

___________________________________________________________________________________________________________________________________________________________________________
* Der Zeitraum in dem ein Plan gültig ist. Für dieses Feld gibt es keine
Entsprechung im XPlanGML. Die Einschränkung, wie sie beim Import
erfolgt ist, wird überschrieben.
___________________________________________________________________________________________________________________________________________________________________________

*Änderungen*

___________________
* aendert
* wurdeGeaendertVon
___________________

*Texte*

_______
* texte
_______

*Referenzen*

______________________
* refBegruendung
* refRechtsplan
* refGruenordnungsplan
______________________

*Rasterbasis*

_____________
* rasterbasis
_____________

*Änderungen von Rasterplänen*

_________________
* rasterAenderung
_________________

Werden Referenzen entfernt oder verändert, so werden die nicht mehr
referenzierten Dateien aus der Datenhaltung entfernt. In den Bereichen
'Rasterbasis' und 'Änderungen von Rasterplänen' kann lediglich ein
Austausch bereits referenzierter Dateien erfolgen. Änderungen führen zu
einer Aktualisierung der XPlanWMS-Konfiguration. Klickt der Nutzer auf
__Speichern__, wird zunächst eine Validierung der Rasterdaten
vorgenommen. Bei invaliden Dateien bekommt der Nutzer eine
Entscheidungsoption wie mit diesen Daten umgegangen werden soll.
Anschließend erfolgt die Aktualisierung der Daten.


NOTE: Die Editierfunktion steht nur für BPläne in der XPlanGML Version 3.0 und
4.1 zur Verfügung.

