ALTER TABLE xplansyn.xplan_fp_wasserwirtschaft ADD xplan_startbedingung TEXT;
ALTER TABLE xplansynpre.xplan_fp_wasserwirtschaft ADD xplan_startbedingung TEXT;
ALTER TABLE xplansynarchive.xplan_fp_wasserwirtschaft ADD xplan_startbedingung TEXT;
ALTER TABLE xplansyn.xplan_fp_wasserwirtschaft ADD xplan_endebedingung TEXT;
ALTER TABLE xplansynpre.xplan_fp_wasserwirtschaft ADD xplan_endebedingung TEXT;
ALTER TABLE xplansynarchive.xplan_fp_wasserwirtschaft ADD xplan_endebedingung TEXT;

ALTER TABLE xplansyn.xplan_bp_gemeinschaftsanlagenzuordnung ADD xplan_gehoertzubereich TEXT;
ALTER TABLE xplansynpre.xplan_bp_gemeinschaftsanlagenzuordnung ADD xplan_gehoertzubereich TEXT;
ALTER TABLE xplansynarchive.xplan_bp_gemeinschaftsanlagenzuordnung ADD xplan_gehoertzubereich TEXT;
