=== XPlanWMS/ XPlanWFS/ XPlanSynWFS

[[manuelle-anpassung-der-bbox_cache.properties]]
==== Manuelle Anpassung der bbox_cache.properties

Damit eine Abfrage von Vektor- bzw. Rasterdaten über den XPlanWMS, XPlanWFS und XPlanSynWFS erfolgen kann, muss eine BoundingBox definiert werden, in der alle räumlichen Daten liegen, die sich in dem System befinden.
Diese BoundingBox wird in der Datei bbox_cache.properties in dem Verzeichnis _.deegree/<XPlan-Dienst-Workspace>/datasources/feature_ konfiguriert. Dabei muss für jeden FeatureType der EPSG-Code und die BoundingBox, die alle räumlichen Daten des Systems umfasst, gesetzt werden.

Falls die bbox_cache.properties Datei nicht korrekt konfiguriert wurde, ist die in den Capabilities-Dokumenten angegebene BoundingBox gegebenenfalls falsch. Dies kann unter anderem dazu führen, dass die Daten durch Clients nicht angezeigt werden.

Beispiel: Auschnitt aus der bbox_cache.properties Datei

----
....
{http\://www.deegree.org/xplanung/1/0}FP_Strassenverkehr=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}BP_EinfahrtPunkt=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}BP_SchutzPflegeEntwicklungsMassnahme=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}FP_Plan=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}XP_Grenze=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}FP_Luftverkehr=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}BP_UeberbaubareGrundstuecksFlaeche=epsg\:4326,8.0,53.0,9.0,54.0
....
----