=== Verfahrensdatenbank


Die Verfahrensdatenbank kann in der Datei
_managerWebConfiguration.properties_ im Verzeichnis
_~/.deegree/manager-configuration/_ aktiviert oder deaktiviert werden: :

----
activateInternalIdDialog=[true|false]
----

Die Anfrage der Verfahrensdatenbank kann an den Aufbau der Datenbank
angepasst werden. Dies erfolgt in der Datei
__managerConfiguration.properties__:

----
workspaceName=xplan-manager-workspace
jdbcConnectionId=vfdb
internalIdLabel=verfahrensid
internalNameLabel=verfahrensname
selectMatchingIdsSql=SELECT verfahrensid, verfahrensname FROM planverfahren WHERE lower(verfahrensname) LIKE lower(?) ORDER BY verfahrensname ASC
selectAllIdsSql=SELECT verfahrensid, verfahrensname FROM planverfahren ORDER BY verfahrensname ASC
----

Über die Schlüssel _workspaceName_ und _jdbcConnectionId_ wird der
Workspace und die Id der Datei in der die Datenbank-Verbindung angepasst
werden kann angegeben. Die Standardwerte können in den meisten Fällen
übernommen werden.

Die Schlüssel _internalIdLabel_ und _internalNameLabel_ geben die
Spalten an unter denen die Verfahrensid und der Verfahrensname
adressiert werden. Diese müssen zwingend über die Schlüssel
_selectMatchingIdsSql_ und _selectAllIdsSql_ konfigurierten
SQL-Statments selektiert werden. Das SQL-Statment _selectMatchingIdsSql_
erlaubt die Anfrage der Verfahren, die dem Plan über den Plan-Namen
zugeordnet sind. Der Plan-Name wird an der Stelle des `?' eingesetzt.
Das SQL-Statement _selectAllIdsSql_ ermöglicht dagegen die Anfrage aller
Verfahren.

[NOTE]
====

Anforderungen an die Konfiguration im Überblick:

* _selectMatchingIdsSql_ und _selectAllIdsSql_ müssen die mit
_internalIdLabel_ und _internalNameLabel_ angegeben Spalten
selektierten.
* _selectMatchingIdsSql_ muss exakt einen Platzhalten `?' für den
Plan-Namen beinhalten.
* _selectAllIdsSql_ darf keinen Platzhalter beinhalten.

====

Die Datenbank-Anbindung kann in der Datei _vfdb.xml_ im XPlanManager
Workspace konfiguriert werden (der Name des workspaces und die ID der
Konfigurationsdatei können wie zuvor beschrieben geändert werden):

----
<Property name="driverClassName" value="org.postgresql.Driver"/>
<Property name="url" value="jdbc:postgresql://<host>:<port>/<dbname>"/>
<Property name="username" value="postgres"/>
<Property name="password" value="postgres"/>
<Property name="maxActive" value="10"/>
----
