=== XPlanWMS/ XPlanWFS/ XPlanSynWFS


[[manuelle-anpassung-der-bbox_cache.properties]]
==== Manuelle Anpassung der bbox_cache.properties


F체r die Darstellung von Vektorlayer bzw. Rasterlayer ist ein r채umlich korrekter Kartenausschnitt notwendig, der durch eine BoundingBox definiert wird. Diese BoundingBox wird automatisch durch das einf체gen von Vekror bzw. Rasterdateien oder durch die GetCapabilities-Anfrage jedes Featuretypes als bbox_cache.properties generiert. Die Konfigurationsdatei ist in _.deegree/<Xplan-Workspace>/datasources/feature_ zufinden.

Da es oft durch z.B. das Fehlen des CRS in den Daten zu fehlerhaften Eintr채gen kommt, muss die bbox_cache.properties in den Workspaces der Dienste manuell so angepasst werden, dass in dieser immer die richtige BoundingBox enthalten ist. 

Auschnitt aus der bbox_cache.properties Datei

----
....
{http\://www.deegree.org/xplanung/1/0}FP_Strassenverkehr=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}BP_EinfahrtPunkt=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}BP_SchutzPflegeEntwicklungsMassnahme=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}FP_Plan=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}XP_Grenze=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}FP_Luftverkehr=epsg\:4326,8.0,53.0,9.0,54.0
{http\://www.deegree.org/xplanung/1/0}BP_UeberbaubareGrundstuecksFlaeche=epsg\:4326,8.0,53.0,9.0,54.0
....
----



