== Konfiguration der Datenbank


Wie in Abschitt _Systemüberblick_ beschrieben, ist mindestens die
Installation von PostgreSQL 8.4 mit der Erweiterung PostGIS 1.5.4
erforderlich.

Für die Konfiguration der Datenbank-Anbindung muss die
__xplan-manager-cli__-Datei entpackt sein. Dabei spielt das Verzeichnis
in dem die Datei entpackt wurde keine Rolle. Ist diese entpackt, kann
die Datenbankerzeugung mittels des XPlanmanger-CLIs durchgeführt werden.
Informationen zu den Befehlen und der Erzeugung der Datenbank finden
sich im Abschnitt XPlanManager CLI in der Benutzerdokumentation. Die
erforderlichen Informationen sind in Abschnitt _Alternativer
Betriebsmodus_ beschrieben.

Datenbank Verbindung in xplansyn-wms-workspace manuell anpassen: Nach
der Erzeugung der Datenbank in PostgreSQL muss die __xplan.xml__-Datei
im XPlanmanger Workspace _.deegree/xplan-manager-workspace/jdbc/_
kopiert und in das Verzeichnis _.deegree/xplansyn-wms-workspace/jdbc/_
eingefügt werden. Dabei wird die bereits vorhandene Konfiguration
ausgetauscht. Alternativ ist auch eine direkte Anpassung in der bereits
vorhandenen __xplan.xml__-Datei im _xplansyn-wms-workspace_ möglich.
