[[kartenvorschau-validator]]
=== Kartenvorschau im XPlanValidatorWeb

Die nachfolgende Konfiguration muss in der Datei _<XPLANBOX_CONFIG>/validatorConfiguration.properties_ angepasst werden.

Um die Kartenvorschau im XPlanValidatorWeb zu aktivieren, muss die URL des XPlanValidatorWMS konfiguriert werden:

----
validatorWmsEndpoint=http://<host>:<port>>/xplan-validator-wms/services/wms
----

Um die Hintergrundkarte der Kartenvorschau anzupassen, ist die Anpassung einer Datei im _xplan-validator-web.war_ erforderlich.

Der Inhalt der anzupassende Datei link:./downloads/services-internet.template.json[services-internet.template.json] ist im Folgenden dargestellt:

----
include::../../downloads/services-internet.template.json[]
----

Um die Hintergrundkarte anzupassen, müssen folgende Schritte ausgeführt werden:

. Ablegen der Datei unter _masterportal/template/services-internet.template.json_ im Dateisystem (Pfad und Dateiname müssen beibehalten werden).
. Anpassen der URL des WMS-Dienstes (Property `url`) und des Layers (Property `layers`)
. Austausch der Datei im _xplan-validator-web.war_, z.B. durch Ausführen des folgenden Kommandos:

----
jar uf xplan-validator-web.war masterportal/template/services-internet.template.json
----

NOTE: Die Zeilen mit den Angaben für `${SERVICESCONFIG}`, `id` und `name` dürfen nicht angepasst werden!
