[[kartenvorschau-validator]]
=== Kartenvorschau im XPlanValidatorWeb

Die nachfolgende Konfiguration muss in der Datei _<XPLANBOX_CONFIG>/validatorConfiguration.properties_ angepasst werden.

Um die Kartenvorschau im XPlanValidatorWeb zu aktivieren, muss die URL des XPlanValidatorWMS konfiguriert werden:

----
validatorWmsEndpoint=http://<host>:<port>>/xplan-webservices-validator-wms/services/wms
----

Um die Hintergrundkarte der Kartenvorschau anzupassen, ist die Anpassung einer Datei im _xplan-validator-web.war_ erforderlich.

Der Inhalt der anzupassende Datei link:./downloads/services-internet.template.json[services-internet.template.json] ist im Folgenden dargestellt:

----
include::../../downloads/services-internet.template.json[]
----

Um die Hintergrundkarte anzupassen, müssen folgende Schritte ausgeführt werden:

. Ablegen der Datei unter _masterportal/template/services-internet.template.json_ im Dateisystem (Pfad und Dateiname müssen beibehalten werden).
. Anpassen der URL des WMS-Dienstes (Property `url`) und des Layers (Property `layers`)
. Austausch der Datei im _xplan-validator-web.war_, z.B. durch Ausführen des folgenden Kommandos:

----
jar uf xplan-validator-web.war masterportal/template/services-internet.template.json
----

NOTE: Die Zeilen mit den Angaben für `${SERVICESCONFIG}`, `id` und `name` dürfen nicht angepasst werden!

[[konfiguration-xplanvalidatorwms]]
==== Konfiguration des XPlanValidatorWMS

Im XPlanValidatorWMS werden die im XPlanValidator hochgeladenen XPlanGML-Dateien visualisiert und können u.a. über die Kartenvorschau im XPlanValidatorWeb angezeigt werden. Der XPlanValidatorWMS unterstützt für die temporäre Datenhaltung zwei Konfigurationen.

Mit der Workspace-Konfiguration _xplan-webservices-validator-wms-memory-workspace_ wird der XPlanValidatorWMS so konfiguriert, dass die Daten ausschliesslich im Arbeitsspeicher vorgehalten werden.

Mit dem _xplan-webservices-validator-wms-sql-workspace_ kann stattdessen die XPlanDB als Datenhaltung für den XPlanValidatorWMS konfiguriert werden. Dabei muss ein separates Schema für den XPlanValidatorWMS in der XPlanDB angelegt werden (weitere Informationen zur Einrichtung der XPlanDB im Kapitel <<konfiguration-der-datenbank>>). Wenn diese Workspace-Konfiguration gewählt wird, muss zusätzlich auch der _xplan-validator-workspace.zip_ im Verzeichnis _<DEEGREE_WORKSPACE_ROOT>_ abgelegt werden.

Die Aktivierung der gewünschten Workspace-Konfiguration erfolgt über die Datei _<DEEGREE_WORKSPACE_ROOT>/webapps.properties_ (siehe <<installation-webapp-properties>>).

.Beispiel für den Eintrag in der _webapps.properties_ mit der Auswahl der XPlanDB als Datenhaltung für den XPlanValidatorWMS:
[source,properties]
----
/xplan-webservices-validator-wms=xplan-webservices-validator-wms-sql-workspace
----

[IMPORTANT]
====
Um die Kartenvorschau zu aktivieren, muss zusätzlich die Umgebungsvariable `spring_profiles_active` für XPlanValidatorWeb, XPlanValidatorAPI und XPlanValidatorWMS wie folgt gesetzt werden:

* Für die Speicherung der Daten im Arbeitsspeicher: `spring_profiles_active=validatorwmsmemory`
* Für die Speicherung der Daten in der XPlanDB: `spring_profiles_active=validatorwmssql`
====

[[konfiguration-xplanvalidatorwms-scheduler]]
==== Konfiguration des Löschens von Daten aus dem XPlanValidatorWMS

Standardmäßig werden Pläne fünf Minuten nach der Validierung wieder aus dem XPlanValidatorWMS entfernt und sind in der Kartenvorschau nicht mehr sichtbar.
Der Zeitraum, in dem validierte Pläne für die Kartenvorschau vorgehalten werden, kann angepasst werden. Die Konfiguration unterscheidet sich je nachdem ob die Daten im Arbeitsspeicher oder in der XPlanDB abgelegt werden. Im folgenden Beispiel wird der Zeitraum, in der die Daten über den XPlanValidatorWMS sichtbar sind, auf 15 Minuten erhöht:

* Bei Speicherung der Daten im Arbeitsspeicher: Setzen der Umgebungsvariable `DELETE_AFTER_MINUTES=15` für den XPlanValidatorWMS.
* Bei Speicherung der Daten in der XPlanDB: Setzen der Umgebungsvariable `DELETE_AFTER_MINUTES=15` für XPlanValidatorWeb *und* XPlanValidatorAPI.