[[semantische-validierungsregeln-validiator]]
=== Semantische Validierungsregeln

Die als XQuery-Dateien vorliegenden semantischen Validierungsregeln können in einem externen Verzeichnis abgelegt und durch entsprechende Konfiguration im XPlanManager und XPlanValidator verwendet werden, wenn z. B. die semantischen Validierungsregeln angepasst, erweitert oder durch eine aktuellere Version ersetzt werden sollen.
Um statt der mit dem xPlanBox ausgelieferten Regeln externen Regeln zu verwenden, muss dieses Verzeichnis konfiguriert werden.
Der Pfad zu den semantischen Regeln muss in der Datei _<XPLANBOX_CONFIG>/validatorConfiguration.properties_ wie folgt konfiguriert werden:

----
validationRulesDirectory=/home/xplanbox/semantischeRegeln/1.0/
----

NOTE: Diese Konfiguration wirkt sich auf die Komponenten XPlanManagerAPI, XPlanManagerWeb und XPlanManagerCLI sowie XPlanValidatorAPI, XPlanValidatorWeb und XPlanValidatorCLI aus.

NOTE: Ist der Pfad nicht konfiguriert, werden die internen Validierungsregeln für die genannten Komponenten verwendet.

IMPORTANT: Das Basisverzeichnis _rules/_ darf nur Unterverzeichnisse enthalten, die der Namenskonvention _xplangml<VERSION>_ entsprechen, wobei der Bezeichner _<VERSION>_ eine Versionsnummer ohne Trennzeichen enthält z. B. _54_ für XPlanGML-Version 5.4. Des Weiteren dürfen nur Unterverzeichnisse mit Validierungsregeln vorkommen, deren XPlanGML-Version von der xPlanBox unterstützt wird.

Wenn innerhalb des Validierungsberichts die Version und die Quelle der semantischen Validierungsregeln angezeigt werden sollen, dann muss im Verzeichnis aus _validationRulesDirectory_ eine Textdatei mit dem Dateinamen _version.properties_ und folgendem Inhalt angelegt werden:

[[semantische-validierungsregeln-beispiel-versionproperties]]
.Beispiel für version.properties:
[source,properties]
----
version=1.1.4 <1>
source=https://gitlab.opencode.de/xleitstelle/xplanung/validierungsregeln/standard/-/tree/v1.1.4 <2>
----
<1> Angabe zur Version der Validierungsregeln (optional)
<2> Angabe zur Quelle der Validierungsregeln (optional)

[[weiterfuehrende-informationen-zur-semantischen-validierung]]
==== Weiterführende Informationen zur semantischen Validierung

Die Regeln für die semantische Validierung von XPlanGML-Dokumenten sind als XQuery-Abfragen implementiert und entsprechend der Nummer der Regel aus den Konformitätsbedingungen benannt.

===== Referenzen auf externe Ressourcen

Bei der Ausgabe des Ergebnisses der semantischen Validierung kann eine
Referenz auf eine externe Ressource gesetzt werden, die weiterführenden
Informationen bereitstellt. Die Referenzen können in der Datei
_<XPLANBOX_CONFIG>/managerConfiguration.properties_ konfiguriert werden.

----
linkSemanticConformity_XPLAN_40=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_4_0.pdf
linkSemanticConformity_XPLAN_41=http://localhost:8080/external/documentation/Konformitaetsbedingungen-XPlanGML_4_1.pdf
linkSemanticConformity_XPLAN_50=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_5_0.pdf
linkSemanticConformity_XPLAN_51=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_5_1.pdf
linkSemanticConformity_XPLAN_52=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_5_2.pdf
linkSemanticConformity_XPLAN_53=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_5_3.pdf
linkSemanticConformity_XPLAN_54=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_5_4.pdf
linkSemanticConformity_XPLAN_60=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_6_0.pdf
----

IMPORTANT: Es müssen ggf. Zeilenumbrüche entfernt werden.

Für jede XPlanGML-Version kann hier die Referenz auf eine externe
Ressource konfiguriert werden. Ist für eine Version keine Ressource
vorhanden, kann der Eintrag vollständig entfernt oder der Wert zu dem
Schlüssel leer gelassen werden. Es wird dann kein Hinweis im Validierungsbericht ausgegeben.

TIP: Es wird empfohlen die Dokumente mit den Konformitätsbedingungen über die Komponente XPlanRessourcen bereitzustellen, um die Unabhängigkeit von externen Ressourcen
sicherzustellen.

===== Schnittstelle zu XQuery-Statements

Der Rückgabewert der XQuery-Statements wird vom XPlanValidator ausgewertet und im Validierungsbericht ausgegeben. Dabei kann der XPlanValidator zwischen Fehlern und Warnungen unterscheiden. Neben der GML-ID des betroffenen Elements kann optional noch eine Meldung mit ausgelesen werden.

Damit der XPlanValidator den Rückgabewert verarbeiten kann, muss dieser wie folgt strukturiert sein:

`GML_ID`
oder
`[GML_ID, 'W', 'NACHRICHT']`

==== Validierungsprofile

Zusätzlich zu den aus den Konformitätsbedingungen abgeleiteten Validierungsregeln können ergänzende Prüfungen als XQuery-Abfragen definiert und über ein Profil in den XPlanValidator eingebunden werden. Dazu sind folgende Schritte erforderlich:

* Anlegen einer Konfigurationsdatei im YAML-Dateiformat im Verzeichnis _<XPLANBOX_CONFIG>/profiles_ (verpflichtend)
* Die YAML-Datei kann die Konfiguration für ein oder mehrere Profile beinhalten, der Dateiname ist frei wählbar, die Dateiendung muss _.yaml_ oder _.yml_ sein. (verpflichtend)
* Ein Profil wird durch folgende Eigenschaften beschrieben:
** *id*: Ein eindeutiger Bezeichner für das Profil. (verpflichtend)
** *name*: Der Name des Profils, dieser wird im XPlanValidatorWeb und XPlanManagerWeb angezeigt. (verpflichtend)
** *description*: Beschreibung des Profils, wird als Tooltip im XPlanValidatorWeb und XPlanManagerWeb angezeigt. (verpflichtend)

.Beispiel für profile.yaml:
[source,yaml]
----
- id: nrw [1]
  name: Pflichtenheft NRW
  description: Vorgaben aus Musterpflichtenheft zur Erstellung XPlanung-konformer Bebauungspläne in NRW
----

NOTE: Alternativ zur Konfiguration von Profilen im Dateisystem unter _<XPLANBOX_CONFIG>/profiles_ können Profile auch im Classpath der Anwendung bzw. der API abgelegt werden. Dabei gelten die zuvor genannten Anforderungen. Weiterhin muss die Konfigurationsdatei im YAML-Dateiformat dem Namen _profiles-<bez>.yaml_ oder _profiles-<bez>.yml_ entsprechen. Als <bez> sollte zur eindeutigen Zuordnung ein eindeutiger Bezeichner verwendet werden. Z.B. _profiles-nds.yaml_. Weiterhin muss eine Datei mit dem Namen _xqueryregeln-<id>>.txt_ auf der obersten Ebene abgelegt werden. Diese Datei muss alle XQuery Regeln als Pfade auflisten, außerdem die version.properties und rules.properties.

.Beispiel für _xqueryregeln-<id>>.txt_
----
/nrw/rules.properties
/nrw/version.properties
/nrw/xplangml54/bp/01_gemeinde.xq
/nrw/xplangml54/bp/02_plangeber.xq
/nrw/xplangml60/bp/01_gemeinde.xq
/nrw/xplangml60/bp/02_plangeber.xq
----

Die XQuery-Regeln für ein Profil müssen in dem Verzeichnis _<XPLANBOX_CONFIG>/profiles/id_ mit der id aus der Profil-Konfiguration [1] liegen. Die Verzeichnisstruktur unterhalb dieses Verzeichnisses muss folgende Vorgaben erfüllen:
** Die Dateien mit den XQuery-Regeln müssen je XPlanGML-Version in getrennten Verzeichnissen abgelegt werden. Der Verzeichnisname setzt sich zusammen aus _xplangml<XPLANGML-VERSION>_, z. B. _xplangml54_, _xplangml60_.
** Es dürfen nur Unterverzeichnisse mit Validierungsregeln vorkommen, deren XPlanGML-Version von der xPlanBox unterstützt wird.
** Jede XQuery-Regel muss in einer Datei mit dem Namen _<DATEINAME>.xq_ abgelegt sein.
** Es wird nur XQuery 3.0 oder 3.1 verwendet.
** Im Verzeichnis muss eine Datei mit dem Namen _rules.properties_ liegen. (optional)
** Die Beschreibung der Regeln in der Properties-Datei muss folgende Vorgaben erfüllen:
** Ein Eintrag besteht aus einem Namen und einem Wert, wobei der Name sich aus dem Dateinamen und der XPlanGML-Version zusammensetzt. Der Wert legt die Beschreibung fest. Das Name/Wert-Paar `<DATEINAME>_<VERSION>=<Beschreibung>` besteht aus:
*** `DATEINAME`: Name der Datei ohne die Dateiendung _.xq_
*** `VERSION`: XPlanGML-Version der Regel, z.B. XPLAN_50, XPLAN_51
*** `Beschreibung`: Beschreibung der Regel

[[semantische-validierungsregeln-beispiel-rulesproperties]]
.Beispiel für rules.properties:
[source,properties]
----
ruleA_XPLAN_54=Das Attribut A darf nicht unbelegt sein.
ruleB_XPLAN_54=Das Attribut B darf nicht unbelegt sein, wenn f\u00FCr das Attribut A der Wert 1000 angegeben ist.
rule1_XPLAN_60=Das Attribut 1 darf nicht unbelegt sein.
rule2_XPLAN_60=Das Attribut 2 darf nicht unbelegt sein.
----

.Beispiel für die Verzeichnisstruktur des Profils mit der id 'nrw':
----
nrw
├── rules.properties        # <1>
├── version.properties      # <2>
├── xplangml54              # <3>
│   ├── ruleA.xq
│   └── ruleB.xq
└── xplangml60              # <4>
    ├── rule1.xq
    └── rule2.xq
----
<1> Datei mit der Beschreibung der Regeln, siehe <<semantische-validierungsregeln-beispiel-rulesproperties>>
<2> Datei mit den Informationen zur Quelle und Version der Regeln, siehe <<semantische-validierungsregeln-beispiel-versionproperties>>
<3> Verzeichnis mit Validierungsregeln für die XPlanGML-Version 5.4
<4> Verzeichnis mit Validierungsregeln für die XPlanGML-Version 6.0
