[[aktualisierung]]
== Aktualisierung

Bei einer Aktualisierung der xPlanBox müssen folgende Schritte durchgeführt werden:

Datenunabhängige Aktualisierungsschritte:

* Stoppen aller Tomcat-Instanzen
* <<austausch-der-web-archive, Austausch der Web-Archive in den Tomcat-Instanzen>>
* <<austausch-der-commandline-tools, Austausch der Kommandozeilenwerkzeuge>>

Aktualisierungsschritte, die die Datenhaltung betreffen:

* <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces, Aktualisierung der betroffenen Konfigurationsdateien in den Workspaces>>
* <<aktualisierung-der-schemas, Aktualisierung des Datenbankschemas>>
* <<aktualisierung-der-daten, Aktualisierung der Daten>>

Nachdem alle Aktualisierungsschritte erfolgreich durchgeführt worden, wird die Aktualisierung mit dem

* <<neustart-tomcat, Starten aller Tomcat-Instanzen>>

abgeschlossen. Im <<appendix_checklists,Anhang sind Checklisten>> hinterlegt, die bei der Aktualisierung helfen, die erforderlichen Schritte vollständig auszuführen.

[[austausch-der-web-archive]]
=== Austausch der Web-Archive

Es müssen die bereitgestellten WAR-Dateien in das Verzeichnis _webapps/_
der jeweiligen Tomcat-Instanz kopiert werden.

Als Platzhalter werden im Folgenden __<WORK_DIR>__ als Download-Verzeichnis mit der entpackten Distributionsdatei und __<CATALINA_HOME>__ mit dem Installationsverzeichnis des Tomcat-Servers verwendet.

----
# Anwendungs-Tomcat
cp ${WORK_DIR}/web/xplan-manager-web.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-validator-web.war <CATALINA_HOME>/webapps/
# API-Tomcat
cp ${WORK_DIR}/web/xplan-manager-api.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-validator-api.war <CATALINA_HOME>/webapps/
# Dienste-Tomcat
cp ${WORK_DIR}/web/xplan-services-wfs-syn.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-services-wfs.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-services-wms.war <CATALINA_HOME>/webapps/
----

NOTE: Falls die Hintergrundkarte der Kartenvorschau im XPlanValidatorWeb angepasst wurde, müssen die Änderungen in der Datei _services-internet.template.json_ manuell in die neue Webapp _xplan-validator-web_ übertragen werden (s. <<kartenvorschau-validator>>).

[[neustart-tomcat]]
=== Neustart der Tomcat-Server

Es müssen alle Tomcat-Instanzen neu gestartet werden. Der Neustart muss nach der Aktualisierung der Workspaces erfolgen (s. <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces>>).

[[austausch-der-commandline-tools]]
=== Austausch der Kommandozeilenwerkzeuge

Die ZIP-Archive mit den <<kommandozeilen-anwendungen,Kommandozeilenwerkzeugen>> müssen entpackt werden:

----
unzip ${WORK_DIR}/bin/xplan-cli-tools.zip
unzip ${WORK_DIR}/bin/xplan-transform-cli.zip
----

=== Übersicht über die Datenhaltung betreffende Änderungen

Folgende Tabelle listet auf, bei welchen xPlanBox Versionen die Datenhaltung betreffende Änderungen vorgenommen wurden.

In der Tabelle sind nur Versionen aufgelistet, die auch Änderungen an der Datenhaltung enthalten. Anhand der Übersicht lässt sich ableiten, welche Schritte bei einer Aktualisierung ausgeführt werden müssen. Die Schritt-für-Schritt-Anleitung zur Aktualisierung der jeweiligen Versionen sind in den nachfolgenden Kapiteln enthalten.

Die Aktualisierungswerkzeuge und -skripte werden nur für die genannten Versionen zusammen mit der aktuellen Liefereinheit bereitgestellt. Bei Fragen zur Aktualisierung von früheren Versionen (6.0 und älter), wenden Sie sich bitte an die https://www.lat-lon.de[lat/lon GmbH].

.Überblick über die Datenhaltung betreffenden Änderungen (ab Version 6.0)
[cols="3*^", options="header,footer"]
|===
| xPlanBox Version | Änderungen an den Workspaces/ der Konfiguration? | Änderungen am Datenbankschema?
| 6.0              | ja (<<aktualisierung-version-6.0, Details>>)  | ja (<<aktualisierung-version-6.0, Details>>)
| 6.0.1              | ja (<<aktualisierung-version-6.0.1, Details>>)  | ja (<<aktualisierung-version-6.0.1, Details>>)
| 7.0             | ja (<<aktualisierung-version-7.0, Details>>)  | ja (<<aktualisierung-version-7.0, Details>>)
| 7.0.1             | ja (<<aktualisierung-version-7.0.1, Details>>)  | nein
| 7.0.2             | ja (<<aktualisierung-version-7.0.2, Details>>)  | nein
| 7.1             | ja (<<aktualisierung-version-7.1, Details>>)  | ja (<<aktualisierung-version-7.1, Details>>)
| 7.1.1             | nein | nein
| 7.1.2             | ja (<<aktualisierung-version-7.1.2, Details>>) | nein
|Durchzuführende Aktualisierungen | <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces>> | <<aktualisierung-der-schemas>> und <<aktualisierung-der-daten>>
|===

[[aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces]]
=== Aktualisierung der betroffenen Konfigurationsdateien in den Workspaces

Bei der Aktualisierung der Workspaces ist zwischen einer vollständigen und teilweisen Aktualisierung zu unterscheiden. Bei der im Abschnitt <<vollstaendige-aktualisierung>> beschriebenen vollständigen Aktualisierung werden z. B. Rasterdaten aus Plänen, die bereits importiert wurden, verworfen. Sollen vorhandene Daten beibehalten werden, ist das im Abschnitt <<teilweise-aktualisierung>> beschriebene Vorgehen durchzuführen.

IMPORTANT: Das HTML-Template für die XPlanWMS GFI Ausgabe muss, wie in <<konfiguration-xplanwms-gfi>> beschrieben, angepasst werden.

IMPORTANT: Alle Konfigurationsänderungen in den Verzeichnissen _xplan-manager-config/_ und _xplan-validator-config/_  müssen manuell übertragen werden.

[[vollstaendige-aktualisierung]]
==== Vollständige Aktualisierung der Workspaces

Es müssen die bereitgestellten Konfigurationsdateien in das Verzeichnis _<DEEGREE_WORKSPACE_ROOT>_ kopiert werden.
Diese ersetzen die bereits vorhandenen:

----
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-manager-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-services-wfs-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-services-wfs-syn-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-services-wms-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-webservices-inspireplu-workspace.zip
cd ${XPLANBOX_CONFIG} && unzip -o ${WORK_DIR}/conf/xplan-manager-config-default.zip
cd ${XPLANBOX_CONFIG} && unzip -o ${WORK_DIR}/conf/xplan-validator-config.zip
----

[[teilweise-aktualisierung]]
==== Teilweise Aktualisierung der Workspaces

Es müssen die bereitgestellten Konfigurationsdateien mit Ausnahme des _xplan-services-wms-workspace_ in das Verzeichnis
_<DEEGREE_WORKSPACE_ROOT>_ kopiert werden. Diese ersetzen die bereits vorhanden:

----
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-manager-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-services-wfs-workspace-.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-services-wfs-syn-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-webservices-inspireplu-workspace.zip
cd ${XPLANBOX_CONFIG} && unzip -o ${WORK_DIR}/conf/xplan-manager-config-default.zip
cd ${XPLANBOX_CONFIG} && unzip -o ${WORK_DIR}/conf/xplan-validator-config.zip
----

Folgende Verzeichnisse des neuen _xplan-services-wms-workspace_ müssen in die bestehende Installation integriert werden:

* _appschemas/_
* _datasources/feature/_
* _layers/_
* _services/_
* _styles/_
* _themes/_

IMPORTANT: Im Verzeichnis _themes/_ nicht die Dateien, die auf _raster.xml_ enden, ersetzen!

[[aktualisierung-der-schemas]]
=== Aktualisierung der Datenbank XPlanDB

IMPORTANT: Die folgenden Schritte müssen nur ausgeführt werden, wenn die bereits in das System importierten Daten beibehalten werden sollen. Wenn dies nicht notwendig ist, kann die Datenbank XPlanDB neu aufgesetzt werden (siehe Kapitel <<konfiguration-der-datenbank>>).

Die SQL-Skripte für die Datenbankschemas jeder Version befinden sich im
_xplan-manager-workspace_ im Verzeichnis _sql/_. Für jedes Datenbankschema gibt es dort einen eigenen Unterordner. Neu hinzugekommene Datenbankschemas können zu der
Datenbank hinzugefügt werden und stehen danach für die Anwendung
bereit. Bei Änderungen an einem Datenbankschema müssen diese durch ein
SQL-Skript durchgeführt werden. Für die Aktualisierungen der XPlanDB liegen die entsprechenden Skripte im Verzeichnis _update/_.

Führen Sie die zu der Version passenden SQL-Skripte aus dem entsprechenden Unterordner aus:

- von 6.0 auf 6.0.1 aus dem Verzeichnis _from_6.0_to_6.0.1/_
- von 6.0.1 auf 7.0 aus dem Verzeichnis _from_6.0.1_to_7.0/_
- von 7.0 auf 7.1 aus dem Verzeichnis _from_7.0_to_7.1/_

IMPORTANT: Erstellen Sie vor der Aktualisierung ein Backup der Datenbank! Und achten Sie bei der Ausführung der SQL-Skripte darauf, dass diese vollständig ausgeführt werden! Nutzen Sie für die Ausführung der SQL-Skripte das `psql`-Tool z.B. mit dem Aufruf `psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE -f $PATH_TO_SCRIPTS/UPDATE_SCRIPT.sql`.

NOTE: Bei der Aktualisierung der XPlanDB kann es bei Ausführung der SQL-Skripte zu folgender Fehlermeldungen kommen: _ERROR:  relation "databasechangeloglock" already exists_ kommen. Diese Fehlermeldung kann ignoriert werden.

NOTE: Manuelle Änderungen an den Datenbank-Schemata können die fehlerfreie und vollständige Ausführung der SQL-Skripte verhindern. Wenn Sie Änderungen an den Datenbank-Schemata vorgenommen haben, müssen diese vor Ausführung der SQL-Skripte zurückgesetzt werden.

[[aktualisierung-der-daten]]
=== Aktualisierung der Daten

IMPORTANT: Die folgenden Schritte müssen nur ausgeführt werden, wenn die bereits in die XPlanDB importierten Daten beibehalten werden sollen. Wenn dies nicht notwendig ist, kann die Datenbank XPlanDB neu aufgesetzt werden (siehe Kapitel <<konfiguration-der-datenbank>>).

Zur Aktualisierung der Daten stehen Kommandozeilenwerkzeuge im XPlanUpdateDataCLI zur Verfügung. Nach einer Aktualisierung der xPlanBox muss folgendes Tool ausgeführt werden:

. _reSynthesizer_

Weitere Informationen zu den Tools stehen im Kapitel <<kommandozeilen-anwendungen>>.

[[aktualisierung-version-6.0]]
=== Aktualisierung auf die Version 6.0 der xPlanBox

Mit der Version 6.0 der xPlanBox wird die Version XPlanGML 6.0 unterstützt. Neben der Aktualisierung auf deegree webservices Version 3.5 sind einige Erweiterungen und Verbesserungen an den Komponenten der xPlanBox vorgenommen worden. Ab Version 6.0 ist mindestens PostgreSQL Version 12 mit der PostGIS-Erweiterung 3.1 erforderlich.

IMPORTANT: Mit der Version 6.0 der xPlanBox wird XPlanGML 3 nicht mehr unterstützt! Vor der Aktualisierung müssen alle Pläne in der Version XPlanGML 3 heruntergeladen und gelöscht werden. Heruntergeladene Pläne müssen manuell in eine höhere Version überführt und nach der Aktualisierung wieder über den XPlanManager importiert werden.

Für die Aktualisierung auf die Version 6.0 sind folgende Schritte auszuführen:

* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
** Anpassung der Konfigurationsdateien _xplan.xml_, _vfdb.xml_ und _inspireplu.xml_ im Unterverzeichnis _jdbc/_ für alle deegree Workspaces mit folgenden Änderungen:
*** den Wert für die Eigenschaft `driverClassName` von `org.apache.commons.dbcp.BasicDataSource` auf `org.apache.commons.dbcp2.BasicDataSource` ändern.
*** die Eigenschaft `maxActive` umbenennen in `maxTotal`
*** die Eigenschaft `maxWait` umbenennen in `maxWaitMillis`
*** die Eigenschaft `removeAbandoned` ersetzen entweder durch `removeAbandonedOnBorrow` (empfohlen) oder `removeAbandonedOnMaintenance` (weitere Informationen unter https://commons.apache.org/proper/commons-dbcp/configuration.html[Apache DBCP Konfigurationsoptionen])
* Aktualisierung der Datenbank:
** Ausführen des Skripts _migrate.sql_ im Verzeichnis _sql/update/from_5.0.2_to_6.0_ im Modul _xplan-manager-workspace_
** Ausführen des Skripts _databasechangelog_v60.sql_ im Verzeichnis _sql/changelog_ im Modul _xplan-manager-workspace_
** Ausführen des Kommandozeilenwerkzeugs __reSynthesizer__ aus XPlanUpdateDataCLI zur Aktualisierung der in der XPlanSyn-Datenhaltung gespeicherten Daten ist erforderlich. Der Aufruf des Tools mit `--help` liefert Hinweise zur Verwendung.
** Installation des Kommandozeilenwerkzeugs <<xplanclitools,XPlanCLI>> und dem <<xplanevaluationschema,Auswerteschemas>> (optional)

[[aktualisierung-version-6.0.1]]
=== Aktualisierung auf die Version 6.0.1 der xPlanBox

Mit der Version 6.0.1 der xPlanBox ist unter anderem die Umsetzung der Bugfix Version XPlanGML 6.0.2 erfolgt. Von den Änderungen betroffen sind alle Komponenten der xPlanBox.

Für die Aktualisierung auf die Version 6.0.1 sind folgende Schritte auszuführen:

* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
* Aktualisierung der Datenbank:
** Ausführen des Skripts _migrate.sql_ im Verzeichnis _sql/update/from_6.0_to_6.0.1_ im Modul _xplan-manager-workspace_
** Ausführen des Kommandozeilenwerkzeugs __reSynthesizer__ aus XPlanUpdateDataCLI zur Aktualisierung der in der XPlanSyn-Datenhaltung gespeicherten Daten ist erforderlich. Der Aufruf des Tools mit `--help` liefert Hinweise zur Verwendung.

[[aktualisierung-version-6.0.2]]
=== Aktualisierung auf die Version 6.0.2

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der Webapps:
** _xplan-validator-api.war_
** _xplan-manager-api.war_
** _xplan-validator-web.war_
** _xplan-manager-web.war_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

[[aktualisierung-version-6.0.3]]
=== Aktualisierung auf die Version 6.0.3

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der Webapps:
** _xplan-validator-api.war_
** _xplan-manager-api.war_
** _xplan-validator-web.war_
** _xplan-manager-web.war_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

[[aktualisierung-version-7.0]]
=== Aktualisierung auf die Version 7.0 der xPlanBox

Mit der Version 7.0 der xPlanBox erfolgte eine Anpassung der Werkseinstellungen für das Logging. Für die Anwendungen XPlanManagerWeb, XPlanManagerAPI, XPlanValidatorWeb und XPlanValidatorAPI sowie alle XPlanDienste werden keine Log-Dateien mehr geschrieben. Alle Log-Ausgaben werden nur noch in die Standardausgabe (stdout) geschrieben. Um das Logging so anzupassen, dass die Log-Ausgaben zusätzlich auch in Log-Dateien geschrieben werden, müssen Anpassungen an der Konfiguration vorgenommen werden. Beispiele dafür sind im Kapitel <<logging>> zu finden.

Für die Aktualisierung auf die Version 7.0 sind folgende Schritte auszuführen:

* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
** Es wird empfohlen zur Absicherung der REST-Schnittstellen der XPlanDienste von der Authentifizierung über einen Tomcat-Nutzer auf API-Key umzustellen. Details dazu finden sich im Abschnitt <<dienste-tomcat>>. Soll weiterhin die Absicherung über einen konfigurierten Tomcat-Nutzer erfolgen, muss in der Datei _<DEEGREE_WORKSPACE_ROOT>/config.apikey_ ein `*` eingetragen werden, um die Absicherung zu deaktivieren.
** Im _xplan-manager-workspace_ muss eine neue Konfigurationsdatei für einen `JpaConnectionProvider` im Unterverzeichnis _jdbc/_ angelegt werden. Die Datei muss mit der bereits vorhandenen Konfigurationsdatei für den `DataSourceConnectionProvider` über die Ressourcen-ID verknüpft werden. Vorlagen befinden sich in dem bereitgestellten Workspace _xplan-manager-workspace_.
* Aktualisierung der Datenbank:
** Ausführen des Skripts _migrate.sql_ im Verzeichnis _sql/update/from_6.0.1_to_7.0_ im Modul _xplan-manager-workspace_
*** vor Ausführung des Skripts muss die Variable `${xplan.srid}` mit dem verwendeten CRS ausgetauscht werden. Die Datei _migrate_25832.sql_ beinhaltet bereits die Ersetzung durch den CRS Code `25832` und kann ohne Änderungen ausgeführt werden.
* Ausführen der Kommandozeilenwerkzeuge __artefactsTableUpdate__ und __reSynthesizer__ aus XPlanUpdateDataCLI zur Aktualisierung der XPlanDB ist erforderlich. Der Aufruf der Tools mit `--help` liefert Hinweise zu deren Verwendung.

IMPORTANT: Mit der Version 7.0 der xPlanBox ist die Kartenvorschau im XPlanValidator nicht mehr standardmäßig aktiviert. Hinweise zur Konfiguration der Kartenvorschau sind im Abschnitt <<kartenvorschau-validator>> beschrieben.

[[aktualisierung-version-7.0.1]]
=== Aktualisierung auf die Version 7.0.1

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der Webapps:
** _xplan-validator-api.war_
** _xplan-manager-api.war_
** _xplan-validator-web.war_
** _xplan-manager-web.war_
* Aktualisierung des Workspace und der Konfigurationen (s. <<teilweise-aktualisierung>>) für:
** _xplan-services-wms-workspace_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

[[aktualisierung-version-7.0.2]]
=== Aktualisierung auf die Version 7.0.2

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der Webapps:
** _xplan-validator-api.war_
** _xplan-manager-api.war_
** _xplan-validator-web.war_
** _xplan-manager-web.war_
* Austausch der ZIP-Datei mit dem XPlanUpdateDataCLI und Ausführung des Kommandozeilenwerkzeugs __artefactsTableUpdate__ zur Aktualisierung der XPlanDB, wenn dieses bei der Installation der Version 7.0 oder 7.0.1 nicht erfolgreich ausgeführt werden konnte.

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

[[aktualisierung-version-7.1]]
=== Aktualisierung auf die Version 7.1 der xPlanBox

Für die Aktualisierung auf die Version 7.1 sind folgende Schritte auszuführen:

* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
* Aktualisierung der Datenbank:
** Ausführen des Skripts _migrate.sql_ im Verzeichnis _sql/update/from_7.0_to_7.1_ im Modul _xplan-manager-workspace_

[[aktualisierung-version-7.1.1]]
=== Aktualisierung auf die Version 7.1.1

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der Webapps:
** _xplan-api-validator.war_
** _xplan-api-manager.war_
** _xplan-validator-web.war_
** _xplan-manager-web.war_
** _xplan-api-dokumente.war_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

[[aktualisierung-version-7.1.2]]
=== Aktualisierung auf die Version 7.1.2

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der Webapps:
** _xplan-wms.war_
** _xplan-api-manager.war_
** _xplan-manager-web.war_
* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
** _xplansyn-wms-workspace.zip_
** _xplan-inspireplu-workspace.zip_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

NOTE: Um das Löschen von Rasterdaten unter dem Betriebssystem Windows sicher zu stellen, muss der Workspace-Reload, wie im Kapitel <<automatischer-workspace-reload>> beschrieben, konfiguriert sein.

=== Troubleshooting

Bei unerwartetem Verhalten der xPlanBox nach einer Aktualisierung können folgende Aktionen helfen:

* Ausführen des Kommandozeilenwerkzeugs __reSynthesizer__ aus XPlanUpdateDataCLI zur Aktualisierung der in der XPlanSyn-Datenhaltung gespeicherten Daten.
* Löschen des Verzeichnisses _<CATALINA_HOME>/work/_ des Tomcat-Servers. Der Tomcat-Server muss zuvor gestoppt und anschließend neu gestartet werden.
* Reload der Workspaces der XPlanDienste.
* Löschen des Browser-Caches.