[[aktualisierung]]
== Aktualisierung

Bei einer Aktualisierung der xPlanBox müssen folgende Schritte durchgeführt werden:

Datenunabhängige Aktualisierungsschritte:

* Stoppen aller Tomcat-Instanzen
* <<austausch-der-web-archive, Austausch der Web-Archive in den Tomcat-Instanzen>>
* <<austausch-der-commandline-tools, Austausch der Commandline-Tools>>

Aktualisierungsschritte, die die Datenhaltung betreffen:

* <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces, Aktualisierung der betroffenen Konfigurationsdateien in den Workspaces>>
* <<aktualisierung-der-schemas, Aktualisierung des Datenbankschemas>>
* <<aktualisierung-der-daten, Aktualisierung der Daten>>

Nachdem alle Aktualisierungsschritte erfolgreich durchgeführt worden, wird die Aktualisierung mit dem

* <<neustart-tomcat, Starten aller Tomcat-Instanzen>>

abgeschlossen.

[[austausch-der-web-archive]]
=== Austausch der Web-Archive

Es müssen die bereitgestellten WAR-Dateien in das Verzeichnis _webapps/_
der jeweiligen Tomcat-Instanz kopiert werden:

----
cp ${WORK_DIR}/web/xplan-manager-web.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-validator-web.war <CATALINA_HOME>/webapps/

cp ${WORK_DIR}/web/xplan-api-manager.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-api-validator.war <CATALINA_HOME>/webapps/

cp ${WORK_DIR}/web/xplansyn-wfs.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-wfs.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-wms.war <CATALINA_HOME>/webapps/
----

NOTE: Falls die Hintergrundkarte der Kartenvorschau im XPlanValidatorWeb angepasst wurde, müssen die Änderungen in der Datei _services-internet.template.json_ manuell in die neue Webapp _xplan-validator-web_ übertragen werden (s. <<kartenvorschau-validator>>).

[[neustart-tomcat]]
=== Neustart der Tomcat-Server

Es müssen alle Tomcat-Instanzen neu gestartet werden. Der Neustart muss nach der Aktualisierung der Workspaces erfolgen (s. <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces>>).

[[austausch-der-commandline-tools]]
=== Austausch der Commandline-Tools

Die ZIP-Archive mit den Kommandozeilen-Tools müssen entpackt werden:

----
unzip ${WORK_DIR}/cli/xplan-manager-cli-${VERSION}.zip 
unzip ${WORK_DIR}/cli/xplan-validator-cli-${VERSION}.zip 
unzip ${WORK_DIR}/cli/xplan-transform-cli-${VERSION}.zip
unzip ${WORK_DIR}/cli/xplan-update-data-cli-${VERSION}.zip
unzip ${WORK_DIR}/cli/xplan-validatedb-cli-${VERSION}.zip
unzip ${WORK_DIR}/cli/xplan-evaluation-schema-synchronize-cli--${VERSION}.zip
----

=== Übersicht über die Datenhaltung betreffende Änderungen

Folgende Tabelle listet auf, bei welchen xPlanBox Versionen die Datenhaltung betreffende Änderungen vorgenommen wurden.

In der Tabelle sind nur Versionen aufgelistet, die auch Änderungen an der Datenhaltung enthalten. Anhand der Übersicht lässt sich ableiten, welche Schritte bei einer Aktualisierung ausgeführt werden müssen. Die Schritt-für-Schritt-Anleitung zur Aktualisierung der jeweiligen Versionen sind in den nachfolgenden Kapiteln enthalten.

Die Aktualisierungswerkzeuge und -skripte werden nur für die genannten Versionen zusammen mit der aktuellen Liefereinheit bereitgestellt. Bei Fragen zur Aktualisierung von früheren Versionen (5.0 und älter), wenden Sie sich bitte an die https://www.lat-lon.de[lat/lon GmbH].

.Überblick über die Datenhaltung betreffenden Änderungen (ab Version 5.0)
[cols="3*^", options="header,footer"]
|===
| xPlanBox Version | Änderungen an den Workspaces/ der Konfiguration? | Änderungen am Datenbankschema?
| 5.0              | ja (<<aktualisierung-auf-die-version-5.0, Details>>)  | ja (<<aktualisierung-auf-die-version-5.0, Details>>)
| 6.0              | ja (<<aktualisierung-auf-xplanbox-version-6.0, Details>>)  | ja (<<aktualisierung-auf-xplanbox-version-6.0, Details>>)
|Durchzuführende Aktualisierungen | <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces>> | <<aktualisierung-der-schemas>> und <<aktualisierung-der-daten>>
|===

[[aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces]]
=== Aktualisierung der betroffenen Konfigurationsdateien in den Workspaces

Bei der Aktualisierung der Workspaces ist zwischen einer vollständigen und teilweisen Aktualisierung zu unterscheiden. Bei der im Abschnitt <<vollstaendige-aktualisierung>> beschriebenen vollständigen Aktualisierung werden z. B. Rasterdaten aus Plänen, die bereits importiert wurden, verworfen. Sollen vorhandene Daten beibehalten werden, ist das im Abschnitt <<teilweise-aktualisierung>> beschriebene Vorgehen durchzuführen.

IMPORTANT: Das HTML-Template für die XPlanWMS GFI Ausgabe muss, wie in <<konfiguration_xplanwms>> beschrieben, angepasst werden.

IMPORTANT: Alle Konfigurationsänderungen in _xplan-manager-config.properties_ und _xplan-validator-config.properties_  müssen manuell übertragen werden.

[[vollstaendige-aktualisierung]]
==== Vollständige Aktualisierung der Workspaces

Es müssen die bereitgestellten Konfigurationsdateien in das Verzeichnis _<DEEGREE_DIR>_, z. B. _.deegree/_ kopiert werden.
Diese ersetzen die bereits vorhandenen:

----
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-manager-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-wfs-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplansyn-wfs-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplansyn-wms-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-inspireplu-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-manager-config-${VERSION}-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-validator-config-${VERSION}.zip
----

[[teilweise-aktualisierung]]
==== Teilweise Aktualisierung der Workspaces

Es müssen die bereit gestellten Konfigurationsdateien mit Ausnahme des _xplansyn-wms-workspace_ in das Verzeichnis
_<DEEGREE_DIR>_, z. B. _.deegree/_ kopiert werden. Diese ersetzen die bereits vorhanden:

----
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-manager-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-wfs-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplansyn-wfs-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-inspireplu-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-manager-config-${VERSION}-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-validator-config-${VERSION}.zip
----

Folgende Ordner des neuen _xplansyn-wms-workspace_ müssen in die bestehende Installation integriert werden:

* _appschemas/_
* _datasources/feature/_
* _layers/_
* _services/_
* _styles/_
* _themes/_

CAUTION: Im Ordner _themes/_ nicht die Dateien, die auf _raster.xml_ enden, ersetzen!


[[aktualisierung-der-schemas]]
=== Aktualisierung der Datenbank XPlanDB

IMPORTANT: Die folgenden Schritte müssen nur ausgeführt werden, wenn die bereits in das System importierten Daten beibehalten werden sollen. Für den Fall, dass dies nicht notwendig ist, kann die Datenbank XPlanDB neu aufgesetzt werden. Mehr Details hierzu finden Sie im Kapitel <<konfiguration-der-datenbank>>.

Die SQL-Skripte für die Datenbankschemas jeder Version befinden sich im
_xplan-manager-workspace_ im Ordner _sql/_. Für jedes Datenbankschema gibt es dort
einen eigenen Unterordner. Neu hinzugekommene Datenbankschemas können zu der
Datenbank hinzugefügt werden und stehen danach für die Anwendung
bereit. Bei Änderungen an einem Datenbankschema müssen diese durch ein
SQL-Skript durchgeführt werden. Für die Aktualisierungen der XPlanDB liegen die entsprechenden Skripte im Verzeichnis _update/_.

Führen Sie die zu der Version passenden SQL-Skripte aus dem entsprechenden Unterordner aus:

- von 5.0 auf 5.0.2 aus dem Ordner _from_5.0_to_5.0.2/_
- von 5.0.2 auf 6.0 aus dem Ordner _from_5.0.2_to_6.0/_

NOTE: Bei der Aktualisierung der XPlanDB kann es bei Ausführung der SQL zu folgender Fehlermeldungen kommen: _ERROR:  relation "databasechangeloglock" already exists_ kommen. Diese Fehlermeldung kann ignoriert werden.

[[aktualisierung-der-daten]]
=== Aktualisierung der Daten

IMPORTANT: Die folgenden Schritte müssen nur ausgeführt werden, wenn die bereits in das System importierten Daten beibehalten werden sollen. Für den Fall, dass dies nicht notwendig ist, kann die Datenbank XPlanDB neu aufgesetzt werden. Dieser Schritt sollte bereits während der Anwendung des Kapitels <<aktualisierung-der-schemas>> durchgeführt worden sein.

Zur Aktualisierung der Daten stehen Kommandozeilenwerkzeuge im Modul _xplan-update-data-cli_ zur Verfügung:
- _bereichUpdate_
- _destrictUpdate_
- _reSynthesizer_

Weitere Informationen stehen im Kapitel <<kommandozeilen-anwendungen>>.

[[aktualisierung-auf-die-version-5.0]]
=== Aktualisierung auf die Version 5.0

Mit der Version 5.0 der xPlanBox kann die xPlanBox ausschließlich unter Java 11 mit Tomcat 9 betrieben werden, außerdem wird die Version XPlanGML 5.4 unterstützt. Weiterhin sind einige Erweiterungen und Verbesserungen am XPlanValidator, XPlanManagerWeb und den XPlanDiensten vorgenommen worden. Zwei Kommandozeilenwerkzeuge (XPlanAuswerteschemaCLI und XPlanValidateDB) sind neu hinzugekommen.

Für die Aktualisierung auf die Version 5.0 sind folgende Schritte auszuführen:

* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
* Aktualisierung der Datenbank:
** Ausführen der Skripte für die Erstellung der Datenhaltung für 5.4 aus dem Modul _xplan-manager-workspace_:
*** _fix/xplan54/create.sql_
*** _pre/xplan54/create.sql_
*** _archive/xplan54/create.sql_
** Ausführen der Skripte im Verzeichnis _from_4.2_to_5.0_ im Modul _xplan-update-data-cli_ in der vorgegebenen Reihenfolge
** Ausführen des Kommandozeilenwerkzeugs __reSynthesizer__ im Modul _xplan-update-data-cli_ zur Aktualisierung der in der XPlanSyn-Datenhaltung gespeicherten Daten. Der Aufruf des Tools mit `--help` liefert Hinweise zur Verwendung.
** Installation bzw. Inbetriebnahme des neuen Kommandozeilenwerkzeugs <<xplanevaluationschemasynchronize-cli, XPlanAuswerteschemaCLI>> (wenn benötigt)

IMPORTANT:  Java 1.8 wird nicht mehr unterstützt.

IMPORTANT: Die SQL-Skripte für die Aktualisierung der XPlanDB auf die Version 5.0 werden ab xPlanBox Version 6.0 nicht mehr ausgeliefert. Bei Fragen zur Aktualisierung von früheren Versionen (5.0 und älter), wenden Sie sich bitte an die https://www.lat-lon.de[lat/lon GmbH].

[[aktualisierung-auf-die-version-5.0.1]]
=== Aktualisierung auf die Version 5.0.1

Für eine Installation der Bugfix-Version ist ein Austausch der beiden Webapps erforderlich:

* _xplan-api-manager.war_
* _xplan-api-validator.war_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden. Anpassungen an den Konfigurationsdateien sind ebenfalls nicht erforderlich.

[[aktualisierung-auf-die-version-5.0.2]]
=== Aktualisierung auf die Version 5.0.2

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der beiden Webapps:
** _xplan-api-manager.war_
** _xplan-manager-web.war_
* Ausführen des Skripts _01_addBereichTable.sql_ im Verzeichnis _sql/update/from_5.0_to_5.0.2_ im Modul _xplan-manager-workspace_
* Ausführen des Kommandozeilenwerkzeugs _databaseUpdate_ (für Version 5.0.2) im Modul _xplan-update-data-cli_ zur Aktualisierung der XPlanSyn-Datenhaltung, z.B. mit `./databaseUpdate -c <XPLANBOX_CONFIG>/`

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

[[aktualisierung-auf-die-version-5.0.3]]
=== Aktualisierung auf die Version 5.0.3

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Setzen der Variable `jts.overlay=ng` im _Anwendungs-Tomcat_ und _API-Tomcat_, siehe auch Kapitel <<anwendungs-tomcat>>.
* Austausch der Webapps:
** _xplan-api-validator.war_
** _xplan-api-manager.war_
** _xplan-validator-web.war_
** _xplan-manager-web.war_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

[[aktualisierung-auf-xplanbox-version-6.0]]
=== Aktualisierung auf die Version 6.0 der xPlanBox

Mit der Version 6.0 der xPlanBox wird die Version XPlanGML 6.0 unterstützt. Neben der Aktualisierung auf deegree webservices Version 3.5 sind einige Erweiterungen und Verbesserungen an den Komponenten der xPlanBox vorgenommen worden. Ab Version 6.0 ist mindestens PostgreSQL Version 12 mit der PostGIS-Erweiterung 3.1 erforderlich.

IMPORTANT: Mit der Version 6.0 der xPlanBox wird XPlanGML 3 nicht mehr unterstützt! Vor der Aktualisierung müssen alle Pläne in der Version XPlanGML 3 heruntergeladen und gelöscht werden. Heruntergeladene Pläne müssen manuell in eine höhere Version überführt und nach der Aktualisierung wieder über den XPlanManager importiert werden.

Für die Aktualisierung auf die Version 6.0 sind folgende Schritte auszuführen:

* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
** Anpassung der Konfigurationsdateien _xplan.xml_, _vfdb.xml_ und _inspireplu.xml_ im Unterverzeichnis _jdbc/_ für alle deegree Workspaces mit folgenden Änderungen:
*** den Wert für die Eigenschaft `driverClassName` von `org.apache.commons.dbcp.BasicDataSource` auf `org.apache.commons.dbcp2.BasicDataSource` ändern.
*** die Eigenschaft `maxActive` umbenennen in `maxTotal`
*** die Eigenschaft `maxWait` umbenennen in `maxWaitMillis`
*** die Eigenschaft `removeAbandoned` ersetzen entweder durch `removeAbandonedOnBorrow` (empfohlen) oder `removeAbandonedOnMaintenance` (weitere Informationen unter https://commons.apache.org/proper/commons-dbcp/configuration.html[Apache DBCP Konfigurationsoptionen])
* Aktualisierung der Datenbank:
** Ausführen des Skripts _migrate.sql_ im Verzeichnis _sql/update/from_5.0.2_to_6.0_ im Modul _xplan-manager-workspace_
** Ausführen des Skripts _databasechangelog_v60.sql_ im Verzeichnis _sql/changelog_ im Modul _xplan-manager-workspace_
** Ausführen des Kommandozeilenwerkzeugs __reSynthesizer__ im Modul _xplan-update-data-cli_ zur Aktualisierung der in der XPlanSyn-Datenhaltung gespeicherten Daten ist erforderlich. Der Aufruf des Tools mit `--help` liefert Hinweise zur Verwendung.
** Installation bzw. Inbetriebnahme des neuen Kommandozeilenwerkzeugs <<xplanevaluationschemasynchronize-cli, XPlanAuswerteschemaCLI>> (wenn benötigt)

=== Troubleshooting

Bei unerwartetem Verhalten der xPlanBox nach der Aktualisierung können folgende Punkte helfen:

* Löschen des Verzeichnisses _<CATALINA_HOME>/work/_ der Tomcat-Server. Der Tomcat-Server muss zuvor gestoppt und anschließend neu gestartet werden.
* Reload der Workspaces der XPlanDienste.
* Löschen des Browser-Caches.
