[[aktualisierung]]
== Aktualisierung

Bei einer Aktualisierung der xPlanBox müssen folgende Schritte durchgeführt werden:

Datenunabhängige Aktualisierungsschritte:

* Stoppen aller Tomcat-Instanzen
* <<austausch-der-web-archive, Austausch der Web-Archive in den Tomcat-Instanzen>>
* <<austausch-der-commandline-tools, Austausch der Kommandozeilenwerkzeuge>>

Aktualisierungsschritte, die die Datenhaltung betreffen:

* <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces, Aktualisierung der betroffenen Konfigurationsdateien in den Workspaces>>
* <<aktualisierung-der-schemas, Aktualisierung des Datenbankschemas>>
* <<aktualisierung-der-daten, Aktualisierung der Daten>>

Nachdem alle Aktualisierungsschritte erfolgreich durchgeführt worden, wird die Aktualisierung mit dem

* <<neustart-tomcat, Starten aller Tomcat-Instanzen>>

abgeschlossen. Im <<appendix_checklists,Anhang sind Checklisten>> hinterlegt, die bei der Aktualisierung helfen, die erforderlichen Schritte vollständig auszuführen.

[[austausch-der-web-archive]]
=== Austausch der Web-Archive

Es müssen die bereitgestellten WAR-Dateien in das Verzeichnis _webapps/_
der jeweiligen Tomcat-Instanz kopiert werden.

Als Platzhalter werden im Folgenden __<WORK_DIR>__ als Download-Verzeichnis mit der entpackten Distributionsdatei und __<CATALINA_HOME>__ mit dem Installationsverzeichnis des Tomcat-Servers verwendet.

----
# Anwendungs-Tomcat
cp ${WORK_DIR}/web/xplan-manager-web.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-validator-web.war <CATALINA_HOME>/webapps/
# API-Tomcat
cp ${WORK_DIR}/web/xplan-manager-api.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-validator-api.war <CATALINA_HOME>/webapps/
# Dienste-Tomcat
cp ${WORK_DIR}/web/xplan-services-wfs-syn.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-services-wfs.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-services-wms.war <CATALINA_HOME>/webapps/
----

NOTE: Falls die Hintergrundkarte der Kartenvorschau im XPlanValidatorWeb angepasst wurde, müssen die Änderungen in der Datei _services-internet.template.json_ manuell in die neue Webapp _xplan-validator-web_ übertragen werden (s. <<kartenvorschau-validator>>).

[[neustart-tomcat]]
=== Neustart der Tomcat-Server

Es müssen alle Tomcat-Instanzen neu gestartet werden. Der Neustart muss nach der Aktualisierung der Workspaces erfolgen (s. <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces>>).

[[austausch-der-commandline-tools]]
=== Austausch der Kommandozeilenwerkzeuge

Die ZIP-Archive mit den <<kommandozeilen-anwendungen,Kommandozeilenwerkzeugen>> müssen entpackt werden:

----
unzip ${WORK_DIR}/bin/xplan-cli-tools.zip
unzip ${WORK_DIR}/bin/xplan-transform-cli.zip
----

=== Übersicht über die Datenhaltung betreffende Änderungen

Folgende Tabelle listet auf, bei welchen xPlanBox Versionen die Datenhaltung betreffende Änderungen vorgenommen wurden.

In der Tabelle sind nur Versionen aufgelistet, die auch Änderungen an der Datenhaltung enthalten. Anhand der Übersicht lässt sich ableiten, welche Schritte bei einer Aktualisierung ausgeführt werden müssen. Die Schritt-für-Schritt-Anleitung zur Aktualisierung der jeweiligen Versionen sind in den nachfolgenden Kapiteln enthalten.

Die Aktualisierungswerkzeuge und -skripte werden nur für die genannten Versionen zusammen mit der aktuellen Liefereinheit bereitgestellt. Bei Fragen zur Aktualisierung von früheren Versionen (7.0 und älter), wenden Sie sich bitte an die https://www.lat-lon.de[lat/lon GmbH].

.Überblick über die Datenhaltung betreffenden Änderungen (ab Version 6.0)
[cols="3*^", options="header,footer"]
|===
| xPlanBox Version | Änderungen an den Workspaces/ der Konfiguration? | Änderungen am Datenbankschema?
| 7.1   (<<aktualisierung-version-7.1, Details>>)       | ja   | ja
| 7.1.1 (<<aktualisierung-version-7.1.1, Details>>)     | nein | nein
| 7.1.2 (<<aktualisierung-version-7.1.2, Details>>)     | ja   | nein
| 7.1.3 (<<aktualisierung-version-7.1.3, Details>>)     | ja   | nein
| 7.2   (<<aktualisierung-version-7.2, Details>>)       | ja   | ja
| 7.2.1 (<<aktualisierung-version-7.2.1, Details>>)     | nein | nein
|Durchzuführende Aktualisierungen | <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces>> | <<aktualisierung-der-schemas>> und <<aktualisierung-der-daten>>
|===

[[aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces]]
=== Aktualisierung der betroffenen Konfigurationsdateien in den Workspaces

Bei der Aktualisierung der Workspaces ist zwischen einer vollständigen und teilweisen Aktualisierung zu unterscheiden. Bei der im Abschnitt <<vollstaendige-aktualisierung>> beschriebenen vollständigen Aktualisierung werden z. B. Rasterdaten aus Plänen, die bereits importiert wurden, verworfen. Sollen vorhandene Daten beibehalten werden, ist das im Abschnitt <<teilweise-aktualisierung>> beschriebene Vorgehen durchzuführen.

IMPORTANT: Das HTML-Template für die XPlanWMS GFI Ausgabe muss, wie in <<konfiguration-xplanwms-gfi>> beschrieben, angepasst werden.

IMPORTANT: Alle Konfigurationsänderungen in den Verzeichnissen _xplan-manager-config/_ und _xplan-validator-config/_  müssen manuell übertragen werden.

[[vollstaendige-aktualisierung]]
==== Vollständige Aktualisierung der Workspaces

Es müssen die bereitgestellten Konfigurationsdateien in das Verzeichnis _<DEEGREE_WORKSPACE_ROOT>_ kopiert werden.
Diese ersetzen die bereits vorhandenen:

----
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-manager-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-services-wfs-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-services-wfs-syn-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-services-wms-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-webservices-inspireplu-workspace.zip
cd ${XPLANBOX_CONFIG} && unzip -o ${WORK_DIR}/conf/xplan-manager-config-default.zip
cd ${XPLANBOX_CONFIG} && unzip -o ${WORK_DIR}/conf/xplan-validator-config.zip
----

[[teilweise-aktualisierung]]
==== Teilweise Aktualisierung der Workspaces

Es müssen die bereitgestellten Konfigurationsdateien mit Ausnahme des _xplan-services-wms-workspace_ in das Verzeichnis
_<DEEGREE_WORKSPACE_ROOT>_ kopiert werden. Diese ersetzen die bereits vorhanden:

----
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-manager-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-services-wfs-workspace-.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-services-wfs-syn-workspace.zip
cd ${DEEGREE_WORKSPACE_ROOT} && unzip -o ${WORK_DIR}/conf/xplan-webservices-inspireplu-workspace.zip
cd ${XPLANBOX_CONFIG} && unzip -o ${WORK_DIR}/conf/xplan-manager-config-default.zip
cd ${XPLANBOX_CONFIG} && unzip -o ${WORK_DIR}/conf/xplan-validator-config.zip
----

Folgende Verzeichnisse des neuen _xplan-services-wms-workspace_ müssen in die bestehende Installation integriert werden:

* _appschemas/_
* _datasources/feature/_
* _layers/_
* _services/_
* _styles/_
* _themes/_

IMPORTANT: Im Verzeichnis _themes/_ nicht die Dateien, die auf _raster.xml_ enden, ersetzen!

[[aktualisierung-der-schemas]]
=== Aktualisierung der Datenbank XPlanDB

IMPORTANT: Die folgenden Schritte müssen nur ausgeführt werden, wenn die bereits in das System importierten Daten beibehalten werden sollen. Wenn dies nicht notwendig ist, kann die Datenbank XPlanDB neu aufgesetzt werden (siehe Kapitel <<konfiguration-der-datenbank>>).

Die SQL-Skripte für die Datenbankschemas jeder Version befinden sich im
_xplan-manager-workspace_ im Verzeichnis _sql/_. Für jedes Datenbankschema gibt es dort einen eigenen Unterordner. Neu hinzugekommene Datenbankschemas können zu der
Datenbank hinzugefügt werden und stehen danach für die Anwendung
bereit. Bei Änderungen an einem Datenbankschema müssen diese durch ein
SQL-Skript durchgeführt werden. Für die Aktualisierungen der XPlanDB liegen die entsprechenden Skripte im Verzeichnis _update/_.

Führen Sie die zu der Version passenden SQL-Skripte aus dem entsprechenden Unterordner aus:

- von 7.0 auf 7.1 aus dem Verzeichnis _from_7.0_to_7.1/_
- von 7.1 auf 7.2 aus dem Verzeichnis _from_7.1_to_7.2/_

IMPORTANT: Erstellen Sie vor der Aktualisierung ein Backup der Datenbank! Und achten Sie bei der Ausführung der SQL-Skripte darauf, dass diese vollständig ausgeführt werden! Nutzen Sie für die Ausführung der SQL-Skripte das `psql`-Tool z.B. mit dem Aufruf `psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE -f $PATH_TO_SCRIPTS/UPDATE_SCRIPT.sql`.

NOTE: Bei der Aktualisierung der XPlanDB kann es bei Ausführung der SQL-Skripte zu folgender Fehlermeldungen kommen: _ERROR:  relation "databasechangeloglock" already exists_ kommen. Diese Fehlermeldung kann ignoriert werden.

NOTE: Manuelle Änderungen an den Datenbank-Schemata können die fehlerfreie und vollständige Ausführung der SQL-Skripte verhindern. Wenn Sie Änderungen an den Datenbank-Schemata vorgenommen haben, müssen diese vor Ausführung der SQL-Skripte zurückgesetzt werden.

[[aktualisierung-der-daten]]
=== Aktualisierung der Daten

IMPORTANT: Die folgenden Schritte müssen nur ausgeführt werden, wenn die bereits in die XPlanDB importierten Daten beibehalten werden sollen. Wenn dies nicht notwendig ist, kann die Datenbank XPlanDB neu aufgesetzt werden (siehe Kapitel <<konfiguration-der-datenbank>>).

Zur Aktualisierung der Daten stehen Kommandozeilenwerkzeuge im XPlanUpdateDataCLI zur Verfügung. Nach einer Aktualisierung der xPlanBox muss folgendes Tool ausgeführt werden:

. _reSynthesizer_

Weitere Informationen zu den Tools stehen im Kapitel <<kommandozeilen-anwendungen>>.

[[aktualisierung-version-7.1]]
=== Aktualisierung auf die Version 7.1 der xPlanBox

Für die Aktualisierung auf die Version 7.1 sind folgende Schritte auszuführen:

* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
* Aktualisierung der Datenbank:
** Ausführen des Skripts _migrate.sql_ im Verzeichnis _sql/update/from_7.0_to_7.1_ im Modul _xplan-manager-workspace_

[[aktualisierung-version-7.1.1]]
=== Aktualisierung auf die Version 7.1.1

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der Webapps:
** _xplan-api-validator.war_
** _xplan-api-manager.war_
** _xplan-validator-web.war_
** _xplan-manager-web.war_
** _xplan-api-dokumente.war_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

[[aktualisierung-version-7.1.2]]
=== Aktualisierung auf die Version 7.1.2

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der Webapps:
** _xplan-wms.war_
** _xplan-api-manager.war_
** _xplan-manager-web.war_
* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
** _xplansyn-wms-workspace.zip_
** _xplan-inspireplu-workspace.zip_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

NOTE: Um das Löschen von Rasterdaten unter dem Betriebssystem Windows sicherzustellen, muss der Workspace-Reload, wie im Kapitel <<automatischer-workspace-reload>> beschrieben, konfiguriert sein.

[[aktualisierung-version-7.1.3]]
=== Aktualisierung auf die Version 7.1.3

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der Webapps:
** _xplan-wms.war_
** _xplan-api-manager.war_
** _xplan-manager-web.war_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

NOTE: Um das Löschen von Rasterdaten unter dem Betriebssystem Windows sicherzustellen, muss der Workspace-Reload, wie im Kapitel <<automatischer-workspace-reload>> beschrieben, konfiguriert sein.

[[aktualisierung-version-7.2]]
=== Aktualisierung auf die Version 7.2 der xPlanBox

Für die Aktualisierung auf die Version 7.2 sind folgende Schritte auszuführen:

* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
** _xplan-inspireplu-workspace.zip_ - muss vollständig ausgetauscht werden!
* Aktualisierung der Datenbank:
** Ersetzen der Variable _${xplan.db.user}_ durch den Benutzernamen des `$DB_USER` (_XPLAN_DB_USER_) in allen Zeilen des Skript _migrate.sql_ im Verzeichnis _sql/update/from_7.1_to_7.2_ im Modul _xplan-manager-workspace_
** Ausführen des Skripts _migrate.sql_ im Verzeichnis _sql/update/from_7.1_to_7.2_ im Modul _xplan-manager-workspace_
* Umbenennung der Datei _<XPLANBOX_CONFIG>/dokumentenApiConfiguration.properties_  nach _<XPLANBOX_CONFIG>/dokumenteApiConfiguration.properties_ zur Konfiguration der <<konfiguration-document-api>>.
* Umstellung der Konfiguration der XPlanDokumenteAPI
** Die Referenz auf den _xplan-manager-workspace_ kann entfernt werden
** Konfiguration der Datenbankverbindung wie in <<konfiguration-document-api>> beschrieben

NOTE: Die Webanwendungen mit den REST-APIs sowie die der XPlanDienste und deren Workspace-Konfigurationen wurden umbenannt. Die neuen Dateinamen sind im Kapitel <<installationskomponenten>> aufgeführt.

NOTE: Durch die Änderungen im GML-Applikationsschema von INSPIRE PLU müssen alle Daten neu transformiert werden. Die Änderungen vom 07.02.2024 in der Version 4.0.1 im XML-Schema https://inspire.ec.europa.eu/schemas/plu/4.0/PlannedLandUse.xsd sind nicht abwärtskompatibel! Weitere Informationen dazu sind unter https://github.com/INSPIRE-MIF/application-schemas/releases/tag/2024.1 und im Amendment 1089/2010 zu finden.

[[aktualisierung-version-7.2.1]]
=== Aktualisierung auf die Version 7.2.1

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der Webapps:
** _xplan-manager-api.war_
** _xplan-manager-web.war_
** _xplan-services-wfs.war_
** _xplan-services-wfs-syn.war_
** _xplan-services-wms.war_
** _xplan-validator-web.war_
** _xplan-webservices-inspireplu.war_
** _xplan-webservices-validator-wms.war_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

=== Troubleshooting

Bei unerwartetem Verhalten der xPlanBox nach einer Aktualisierung können folgende Aktionen helfen:

* Ausführen des Kommandozeilenwerkzeugs __reSynthesizer__ aus XPlanUpdateDataCLI zur Aktualisierung der in der XPlanSyn-Datenhaltung gespeicherten Daten.
* Löschen des Verzeichnisses _<CATALINA_HOME>/work/_ des Tomcat-Servers. Der Tomcat-Server muss zuvor gestoppt und anschließend neu gestartet werden.
* Reload der Workspaces der XPlanDienste.
* Löschen des Browser-Caches.