[[aktualisierung]]
== Aktualisierung

Bei einer Aktualisierung der xPlanBox müssen folgende Schritte durchgeführt werden:

Datenunabhängige Aktualisierungsschritte:

* Stoppen aller Tomcat-Instanzen
* <<austausch-der-web-archive, Austausch der Web-Archive (.war) in den Tomcat-Instanzen>>
* <<austausch-der-commandline-tools, Austausch der Commandline-Tools>>

Aktualisierungsschritte, die die Datenhaltung betreffen:

* <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces, Aktualisierung der betroffenen Konfigurationsdateien in den Workspaces>>
* <<aktualisierung-der-schemas, Aktualisierung des Datenbankschemas>>
* <<aktualisierung-der-daten, Aktualisierung der Daten>>

Nachdem alle Aktualisierungsschritte erfolgreich durchgeführt worden, wird die Aktualisierung mit dem

* <<neustart-tomcat, Starten aller Tomcat-Instanzen>>

abgeschlossen.

[[austausch-der-web-archive]]
=== Austausch der Web-Archive

Es müssen die bereitgestellten WAR-Dateien in das Verzeichnis _webapps/_
der jeweiligen Tomcat-Instanz kopiert werden:

----
cp ${WORK_DIR}/web/xplan-manager-web.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-validator-web.war <CATALINA_HOME>/webapps/

cp ${WORK_DIR}/web/xplan-api-manager.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-api-validator.war <CATALINA_HOME>/webapps/

cp ${WORK_DIR}/web/xplansyn-wfs.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-wfs.war <CATALINA_HOME>/webapps/
cp ${WORK_DIR}/web/xplan-wms.war <CATALINA_HOME>/webapps/
----

NOTE: Falls die Hintergrundkarte der Kartenvorschau im XPlanValidatorWeb angepasst wurde, müssen die Änderungen in der Datei _services-internet.template.json_ manuell in die neue Webapp _xplan-validator-web_ übertragen werden (s. <<kartenvorschau-validator>>).

[[neustart-tomcat]]
=== Neustart der Tomcat-Server

Es müssen alle Tomcat-Instanzen neu gestartet werden. Der Neustart muss nach der Aktualisierung der Workspaces erfolgen (s. <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces>>).

[[austausch-der-commandline-tools]]
=== Austausch der Commandline-Tools

Es müssen die bereit gestellten ZIP-Archive für die Kommandozeilen-Tools
entpackt werden:

----
unzip ${WORK_DIR}/cli/xplan-manager-cli-${VERSION}.zip 
unzip ${WORK_DIR}/cli/xplan-validator-cli-${VERSION}.zip 
----

=== Übersicht über die Datenhaltung betreffende Änderungen

Folgende Tabelle listet auf, bei welchen xPlanBox Versionen die Datenhaltung betreffende Änderungen vorgenommen wurden.

In der Tabelle sind nur Versionen aufgelistet, die auch Änderungen an der Datenhaltung enthalten. Anhand der Übersicht lässt sich ableiten, welche Schritte bei einer Aktualisierung ausgeführt werden müssen. Die Schritt-für-Schritt-Anleitung zur Aktualisierung der jeweiligen Versionen sind in den nachfolgenden Kapiteln enthalten.

Die Aktualisierungswerkzeuge und -skripte werden nur für die genannten Versionen zusammen mit der aktuellen Liefereinheit bereitgestellt. Bei  Fragen zur Aktualisierung von früheren Versionen (5.0 und älter), wenden Sie sich bitte an die https://www.lat-lon.de[lat/lon GmbH].

.Überblick über die Datenhaltung betreffenden Änderungen (ab Version 5.0)
[cols="3*^", options="header,footer"]
|===
| xPlanBox Version | Änderungen an den Workspaces/ der Konfiguration? | Änderungen am Datenbankschema?
| 5.0              | ja (<<aktualisierung-auf-die-version-5.0, Details>>)  | ja (<<aktualisierung-auf-die-version-5.0, Details>>)
| 6.0              | ja (<<aktualisierung-auf-xplanbox-version-6.0, Details>>)  | ja (<<aktualisierung-auf-xplanbox-version-6.0, Details>>)
|Durchzuführende Aktualisierungen | <<aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces>> | <<aktualisierung-der-schemas>> und <<aktualisierung-der-daten>>
|===

[[aktualisierung-der-betroffenen-konfigurationsdateien-in-den-workspaces]]
=== Aktualisierung der betroffenen Konfigurationsdateien in den Workspaces

Bei der Aktualisierung der Workspaces ist zwischen einer vollständigen und teilweisen Aktualisierung zu unterscheiden. Bei der im Abschnitt <<vollstaendige-aktualisierung>> beschriebenen vollständigen Aktualisierung werden z. B. Rasterdaten aus Plänen, die bereits importiert wurden, verworfen. Sollen vorhandene Daten beibehalten werden, ist das im Abschnitt <<teilweise-aktualisierung>> beschriebene Vorgehen durchzuführen.

IMPORTANT: Das HTML-Template für die XPlanWMS GFI Ausgabe muss, wie in <<konfiguration_xplanwms>> beschrieben, angepasst werden.

IMPORTANT: Alle Konfigurationsänderungen in _xplan-manager-config.properties_ und _xplan-validator-config.properties_  müssen manuell übertragen werden.

[[vollstaendige-aktualisierung]]
==== Vollständige Aktualisierung des Workspaces

Es müssen die bereitgestellten Konfigurationsdateien in das Verzeichnis _<DEEGREE_DIR>_, z. B. _.deegree/_ kopiert werden.
Diese ersetzen die bereits vorhandenen:

----
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-manager-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-wfs-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplansyn-wfs-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplansyn-wms-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-inspireplu-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-manager-config-${VERSION}-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-validator-config-${VERSION}.zip
----

[[teilweise-aktualisierung]]
==== Teilweise Aktualisierung des Workspaces

Es müssen die bereit gestellten Konfigurationsdateien mit Ausnahme des _xplansyn-wms-workspace_ in das Verzeichnis
_<DEEGREE_DIR>_, z. B. _.deegree/_ kopiert werden. Diese ersetzen die bereits vorhanden:

----
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-manager-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-wfs-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplansyn-wfs-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-workspaces-${VERSION}-xplan-inspireplu-workspace-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-manager-config-${VERSION}-${ENV}.zip
cd ${DEEGREE_DIR} && unzip -o ${WORK_DIR}/config/xplan-validator-config-${VERSION}.zip
----

Folgende Ordner des neuen _xplansyn-wms-workspace_ müssen in die bestehende Installation integriert werden:

* _appschemas/_
* _datasources/feature/_
* _layers/_
* _services/_
* _styles/_
* _themes/_

CAUTION: Im Ordner _themes/_ nicht die Dateien, die auf _raster.xml_ enden, ersetzen!


[[aktualisierung-der-schemas]]
=== Aktualisierung des Datenbankschemas

IMPORTANT: Die folgenden Schritte müssen nur ausgeführt werden, wenn die bereits in das System importierten Daten beibehalten werden sollen.
Für den Fall, dass dies nicht notwendig ist, muss lediglich die Datenbank neu aufgesetzt werden. Mehr Details hierzu finden Sie im Kapitel <<konfiguration-der-datenbank>>.

Die Datenbankschemas jeder Version befinden sich im
_xplan-manager-workspace_ im Ordner _sql/_ und für jedes Schema gibt es dort
einen eigenen Unterordner. Neu hinzugekommene Schemas können direkt auf
der Datenbank ausgeführt werden und stehen danach für die Anwendung
bereit. Bei Änderungen in einem Schema müssen diese durch in ein
Update-Skript überführt und damit an der Datenbank durchgeführt werden.
Für einige Aktualisierungen sind Aktualisierungsskripte im Modul
_xplan-update-data-cli_ verfügbar.

TIP: Es gibt sowohl SQL-Update-Skripte als auch Liquibase-Skripte, die mit
der Software https://www.liquibase.org/[Liquibase] ausgeführt werden
können. Falls beide Skript-Typen vorhanden sind, kann der Nutzer wählen,
ob das Update per SQL oder Liquibase durchgeführt werden soll.

NOTE: Werden mehrere Aktualisierungschritte mit Liquibase ausgeführt, kann es zu folgender Fehlermeldungen: _ERROR:  relation "databasechangeloglock" already exists_ kommen. Diese Fehlermeldung kann ignoriert werden.

[[aktualisierung-der-daten]]
=== Aktualisierung der Daten

IMPORTANT: Die folgenden Schritte müssen nur ausgeführt werden, wenn die bereits in das System importierten Daten beibehalten werden sollen. Für den Fall, dass dies nicht notwendig ist, muss lediglich die Datenbank neu aufgesetzt werden. Dieser Schritt sollte bereits während der Anwendung des Kapitels <<aktualisierung-der-schemas>> durchgeführt worden sein.

[[aktualisierung-auf-die-version-5.0]]
=== Aktualisierung auf die Version 5.0

Mit der Version 5.0 der xPlanBox kann die xPlanBox ausschließlich unter Java 11 mit Tomcat 9 betrieben werden, außerdem wird die Version XPlanGML 5.4 unterstützt. Weiterhin sind einige Erweiterungen und Verbesserungen am XPlanValidator, XPlanManagerWeb und den XPlanDiensten vorgenommen worden. Zwei Kommandozeilenwerkzeuge (XPlanAuswerteschemaCLI und XPlanValdiateDB) sind neu hinzugekommen.

Für die Aktualisierung auf die Version 5.0 sind folgende Schritte auszuführen:

* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
* Aktualisierung der Datenbank:
** Ausführen der Skripte für die Erstellung der Datenhaltung für 5.4 aus dem Modul _xplan-manager-workspace_:
*** _fix/xplan54/create.sql_
*** _pre/xplan54/create.sql_
*** _archive/xplan54/create.sql_
** Ausführen der Skripte im Verzeichnis _from_4.2_to_5.0_ im Modul _xplan-update-data-cli_ in der vorgegebenen Reihenfolge
** Ausführen des Kommandozeilenwerkzeugs __reSynthesizer__ im Modul _xplan-update-data-cli_ zur Aktualisierung der in der XPlanSyn-Datenhaltung gespeicherten Daten. Der Aufruf des Tools mit `--help` liefert Hinweise zur Verwendung.
** Installation bzw. Inbetriebnahme des neuen Kommandozeilenwerkzeugs <<xplanevaluationschemasynchronize-cli, XPlanAuswerteschemaCLI>> (wenn benötigt)

IMPORTANT:  Java 1.8 wird nicht mehr unterstützt.

[[aktualisierung-auf-die-version-5.0.1]]
=== Aktualisierung auf die Version 5.0.1

Für eine Installation der Bugfix-Version ist ein Austausch der beiden Webapps erforderlich:

* _xplan-api-manager.war_
* _xplan-api-validator.war_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden. Anpassungen an den Konfigurationsdateien sind ebenfalls nicht erforderlich.

[[aktualisierung-auf-die-version-5.0.2]]
=== Aktualisierung auf die Version 5.0.2

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Austausch der beiden Webapps:
** _xplan-api-manager.war_
** _xplan-manager-web.war_
* Ausführen der Skripte im Verzeichnis _from_5.0_to_5.0.2_ im Modul _xplan-update-data-cli_ in der vorgegebenen Reihenfolge
* Ausführen des Kommandozeilenwerkzeugs __databaseUpdate__ (für Version 5.0.2) im Modul _xplan-update-data-cli_ zur Aktualisierung der XPlanSyn-Datenhaltung, z.B. mit `./databaseUpdate -c <XPLANBOX_CONFIG>/`

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

[[aktualisierung-auf-die-version-5.0.3]]
=== Aktualisierung auf die Version 5.0.3

Für eine Installation der Bugfix-Version müssen folgende Schritte ausgeführt werden:

* Setzen der Variable `jts.overlay=ng` im _Anwendungs-Tomcat_ und _API-Tomcat_, siehe auch Kapitel <<anwendungs-tomcat>>.
* Austausch der Webapps:
** _xplan-api-validator.war_
** _xplan-api-manager.war_
** _xplan-validator-web.war_
** _xplan-manager-web.war_

TIP: Alle anderen Komponenten sind unverändert und müssen nicht aktualisiert werden.

[[aktualisierung-auf-xplanbox-version-6.0]]
=== Aktualisierung auf die Version 6.0 der xPlanBox

Mit der Version 6.0 der xPlanBox wird die Version XPlanGML 6.0 unterstützt. Neben der Aktualisierung auf deegree webservices Version 3.5 sind einige Erweiterungen und Verbesserungen an den Komponenten der xPlanBox vorgenommen worden.

Für die Aktualisierung auf die Version 6.0 sind folgende Schritte auszuführen:

* Aktualisierung der Workspaces und Konfigurationen (s. <<teilweise-aktualisierung>>)
** Anpassung der Konfigurationsdateien _xplan.xml_, _vfdb.xml_ und _inspireplu.xml_ im Unterverzeichnis _jdbc/_ für alle deegree Workspaces mit folgenden Änderungen:
*** den Wert für die Eigenschaft `driverClassName` von `org.apache.commons.dbcp.BasicDataSource` auf `org.apache.commons.dbcp2.BasicDataSource` ändern.
*** die Eigenschaft `maxActive` umbenennen in `maxTotal`
*** die Eigenschaft `maxWait` umbenennen in `maxWaitMillis`
*** die Eigenschaft `removeAbandoned` ersetzen entweder durch `removeAbandonedOnBorrow` (empfohlen) oder `removeAbandonedOnMaintenance` (weitere Informationen unter https://commons.apache.org/proper/commons-dbcp/configuration.html[Apache DBCP Konfigurationsoptionen])
* Aktualisierung der Datenbank:
** Ausführen der Skripte für die Erstellung der Datenhaltung für 6.0 aus dem Modul _xplan-manager-workspace_:
*** _fix/xplan60/create.sql_
*** _pre/xplan60/create.sql_
*** _archive/xplan60/create.sql_
** Ausführen der Skripte im Verzeichnis _from_5.0_to_6.0_ im Modul _xplan-update-data-cli_ in der vorgegebenen Reihenfolge
** Ausführen des Kommandozeilenwerkzeugs __reSynthesizer__ im Modul _xplan-update-data-cli_ zur Aktualisierung der in der XPlanSyn-Datenhaltung gespeicherten Daten. Der Aufruf des Tools mit `--help` liefert Hinweise zur Verwendung.
** Installation bzw. Inbetriebnahme des neuen Kommandozeilenwerkzeugs <<xplanevaluationschemasynchronize-cli, XPlanAuswerteschemaCLI>> (wenn benötigt)

IMPORTANT:  XPlanGML 3 wird nicht mehr unterstützt.

=== Troubleshooting

Bei unerwartetem Verhalten der xPlanBox nach der Aktualisierung können folgende Punkte helfen:

* Löschen des Verzeichnisses _<CATALINA_HOME>/work/_ des Tomcat-Servers. Der Tomcat-Server muss zuvor gestoppt und anschließend neu gestartet werden.
* Löschen des Browser-Caches.