[[konfiguration-der-applikationsserver]]
=== Konfiguration der Applikationsserver

Wie im Abschnitt <<anwendung-installieren>> beschrieben,
werden für den Betrieb aller Komponenten der xPlanBox zwei Tomcat-Instanzen empfohlen,
der _Dienste-Tomcat_ sowie __Anwendungs-Tomcat__. Im Folgenden wird die
Konfiguration beider Tomcat-Instanzen beschrieben.

[[anwendungs-tomcat]]
==== Anwendungs-Tomcat

Im Anwendungs-Tomcat muss folgende Konfigurationen vorgenommen werden:

Für den XPlanManagerWeb muss die Variable _XPLANBOX_CONFIG_ als Java
Property gesetzt werden. Das mit Hilfe dieser Variable referenzierte
Verzeichnis muss die Konfiguration des XPlanManagerWeb und XPlanValidatorWeb enthalten (es
handelt sich um die Dateien managerConfiguration.properties,
managerWebConfiguration.properties und validatorConfiguration.properties).
Wurde der Anleitung in Abschnitt <<anwendung-installieren>> gefolgt, befindet sich das
Verzeichnis mit dem Namen _xplan-manager-config_ im Verzeichnis
_.deegree_ im Home-Verzeichnis des Nutzers. Wird ausschließlich der XPlanValidatorWeb installiert,
heißt das Verzeichnis _xplan-validator-config_.

[[anwendungs-tomcat-linux]]
===== Linux

Für die Konfiguration der oben genannten Punkte muss zunächst im
Verzeichnis _<tomcat-root>/bin_ eine neue Datei mit dem Namen
_setenv.sh_ angelegt werden.

In dieser Datei erfolgt das Setzen der Variable _XPLANBOX_CONFIG_ durch das Hinzufügen von:

----
export JAVA_OPTS=’-DXPLANBOX_CONFIG=/home/xplanbox/.deegree/manager-configuration’
----

Falls es bereits einen Export von JAVA_OPTS in dieser Datei gibt, muss die Variable *-DXPLANBOX_CONFIG=/home/xplanbox/.deegree/manager-configuration* in die bestehenden JAVA_OPTS integriert werden.

[[anwendungs-tomcat-windows]]
===== Windows

Für das Setzen der Variable _XPLANBOX_CONFIG_ sowie muss zunächst eine neue Datei mit dem Namen _setenv.bat_
im Verzeichnis _<tomcat-root>/bin_ angelegt werden. Dort wird die Variable wie folgt hinzugefügt:

----
export JAVA_OPTS=’-DXPLANBOX_CONFIG=C:\.deegree\manager-configuration’
----

Falls es bereits einen Export von JAVA_OPTS in dieser Datei gibt, muss die Variable *-DXPLANBOX_CONFIG=C:\.deegree\manager-configuration* in die bestehenden JAVA_OPTS integriert werden.

NOTE: Der Anwendungs-Tomcat muss mindestens über 4GB Arbeitsspeicher verfügen,
dies kann durch setzen der Umgebungsvariable: _export JAVA_OPTS=’-Xmx4096m’_ erfolgen.

[[dienste-tomcat]]
==== Dienste-Tomcat

Falls der XPlanManager nach jedem Einfügen und Löschen eines Plan den
XPlanWMS und XPlanWerkWMS aktualisieren soll, muss ein Tomcat-Nutzer angelegt werden.
Ansonsten ist ein manueller Workspace-Reload nötig, um die neu
importieren bzw. gelöschten Rasterpläne im XPlanWMS darzustellen bzw. zu
entfernen.

Dafür müssen in der Datei _<tomcat-root>/conf/tomcat-users.xml_ folgende
Zeilen hinzugefügt werden:

----
<role rolename="deegree"/>
<user username="<NUTZERNAME>" password="<PASSWORT>" roles="deegree"/>
----
Weitere Informationen zur https://tomcat.apache.org/tomcat-8.5-doc/realm-howto.html[Konfiguration von Benutzern] ist in der Dokumentation von Apache Tomcat zu finden.

NOTE: Der Nutzername und das Passwort müssen in die
managerConfiguration.properties eingetragen werden (s. Kapitel
<<automatischer-workspace-reload>>.

NOTE: Der Dienste-Tomcat muss ebenfalls mindestens über 4GB Arbeitsspeicher verfügen,
dies kann durch setzen der Umgebungsvariable: _exportJAVA_OPTS=’-Xmx4096m’_ erfolgen.

==== Absicherung des Tomcat und der Webanwendungen

Wenn die xPlanBox in einer produktiven Umgebung betrieben wird, sollte der Apache Tomcat abgesichert werden. Dazu sind die
allgemeinen Empfehlungen aus der https://tomcat.apache.org/tomcat-8.5-doc/security-howto.html[Dokumentation von Apache Tomcat zum Thema Sicherheit] zu beachten.

Zusätzlich sollte die xPlanBox wie folgt konfiguriert sein:

. die deegree webservice console für die drei Dienste-Konfigurationen _xplan-wms_, _xplan_wfs_ und _xplansyn-wfs_ im _Dienste-Tomcat_ ist durch ein Kennwort geschützt (Datei _console.pw_ im deegree Workspace).
. die deegree REST-Schnittstelle ist durch Benutzername und Kennwort abgesichert (Datei _web.xml_ und _tomcat-users.xml_ im Tomcat-Konfigurationsverzeichnis, siehe Kapitel <<dienste-tomcat>>).
. der Zugriff auf die deegree webservice console ist auf IP-Adressbereiche bzw. Domänen eingeschränkt (Datei _context.xml_ innerhalb der Webanwendungen).
. beide Tomcat-Instanzen werden hinter einem Proxy (z. B. Apache httpd) betrieben (Datei _server.xml_ im Tomcat-Konfigurationsverzeichnis).
. der Zugriff auf den XPlanManagerWeb ist durch Benutzername und Kennwort abgesichert (siehe Kapitel <<security>>).
