[[konfiguration-der-applikationsserver]]
=== Konfiguration der Applikationsserver

Wie im Abschnitt <<anwendung-installieren>> beschrieben,
werden zum Betreiben aller Komponenten zwei Tomcat-Instanzen empfohlen,
der _Dienste-Tomcat_ sowie __Anwendungs-Tomcat__. Im Folgenden wird die
Konfiguration beider Tomcats beschrieben.

[[anwendungs-tomcat]]
==== Anwendungs-Tomcat

Im Anwendungs-Tomcat müssen folgende Konfigurationen vorgenommen werden:

.  Für den XPlanManagerWeb muss die Variable _XPLANBOX_CONFIG_ als Java
Property gesetzt werden. Das mit Hilfe dieser Variable referenzierte
Verzeichnis muss die Konfiguration des XPlanManagerWeb enthalten (es
handelt sich um die Dateien managerConfiguration.properties und
managerWebConfiguration.properties). Wurde der Anleitung in Abschnitt
<<anwendung-installieren>> gefolgt, befindet sich das
Verzeichnis mit dem Namen _manager-configuration_ im Verzeichnis
_.deegree_ im Home-Verzeichnis des Nutzers.
.  Um das Logging der Anwendungen XPlanManagerWeb und XPlanValidatorWeb in ein gesondertes Verzeichnis zu aktivieren (s. Details im
Abschnitt <<Logging>> muss die Variable
_xplan.logdir_ als Java Property gesetzt werden. In dem so
konfigurierten Verzeichnis werden die log-Dateien der beiden Anwendungen
abgelegt.

[[anwendungs-tomcat-linux]]
===== Linux

Für die Konfiguration der oben genannten Punkte muss zunächst im
Verzeichnis _<tomcat-root>/bin_ eine neue Datei mit dem Namen
_setenv.sh_ angelegt werden.

In dieser Datei erfolgt das Setzen der Variable
_XPLANBOX_CONFIG_ sowie _xplan.logdir_ durch das Hinzufügen von:

----
export JAVA_OPTS=’-DXPLANBOX_CONFIG=/home/xplanbox/.deegree/manager-configuration -Dxplan.logdir=/home/xplanbox/logs’
----

Falls es bereits einen Export von JAVA_OPTS in dieser Datei gibt, müssen *-DXPLANBOX_CONFIG=/home/xplanbox/.deegree/manager-configuration* und *-Dxplan.logdir=/home/xplanbox/logs* in die bestehenden JAVA_OPTS integriert werden.

[[anwendungs-tomcat-windows]]
===== Windows

Für das Setzen der Variable _XPLANBOX_CONFIG_ sowie
_xplan.logdir_ muss zunächst eine neue Datei mit dem Namen _setenv.bat_
im Verzeichnis _<tomcat-root>/bin_ angelegt werden. Dort werden die
Variablen wie folgt hinzugefügt:

----
export JAVA_OPTS=’-DXPLANBOX_CONFIG=C:\.deegree\manager-configuration -Dxplan.logdir=C:\logs’
----

Falls es bereits einen Export von JAVA_OPTS in dieser Datei gibt, müssen *-DXPLANBOX_CONFIG=C:\.deegree\manager-configuration* und *-Dxplan.logdir=C:\logs* in die bestehenden JAVA_OPTS integriert werden.

NOTE: Der Anwendungs-Tomcat muss mindestens über 4GB Arbeitsspeicher verfügen,
dies kann durch setzen der Umgebungsvariable: _exportJAVA_OPTS=’-Xmx4096m’_ erfolgen.

[[dienste-tomcat]]
==== Dienste-Tomcat

Falls der XPlanManager nach jedem Einfügen und Löschen eines Plan den
XPlanWMS und XPlanWerkWMS aktualisieren soll, muss ein Tomcat-Nutzer angelegt werden.
Ansonsten ist ein manueller Workspace-Reload nötig, um die neu
importieren bzw. gelöschten Rasterpläne im XPlanWMS darzustellen bzw. zu
entfernen.

Dafür müssen in der Datei _<tomcat-root>/conf/tomcat-users.xml_ folgende
Zeilen hinzugefügt werden:

----
<role rolename="deegree"/>
<user username="<NUTZERNAME>" password="<PASSWORT>" roles="deegree"/>
----

NOTE: Der Nutzername und das Passwort müssen in die
managerConfiguration.properties eingetragen werden (s. Kapitel
<<automatischer-workspace-reload>>.

NOTE: Der Dienste-Tomcat muss ebenfalls mindestens über 4GB Arbeitsspeicher verfügen,
dies kann durch setzen der Umgebungsvariable: _exportJAVA_OPTS=’-Xmx4096m’_ erfolgen.
