[[logging]]
=== Logging

Die Anwendungen XPlanManagerWeb, XPlanManagerCLI, XPlanValidatorWeb
und XPlanValidatorCLI und alle XPlanDienste schreiben Log-Ausgaben standardmäßig nach
Standard-Out. Für die Web-Anwendungen und die Webservices ist dies die Logging-Datei des
Java Applikationsserver (Tomcat: catalina.out) und bei den CLI-Anwendungen die Konsole.
Nach Standard-Out werden nur Warnungen und Fehler geschrieben.

Zusätzlich wird ein erweitertes Log für alle Anwendungen und Dienste in eine entsprechend der
Anwendung, bzw. des Dienstes (z.B. xplan-wms.log) benannten Datei in das Log-Verzeichnis des
Tomcats ($\{catalina.base}/logs/xplan-manager-web.log) geschrieben.

[width="88%",cols="35%,65%",options="header",]
|============================================================
|Anwendung |Log-Datei
|XPlanManagerWeb |$\{catalina.base}/logs/xplan-manager-web.log
|XPlanManagerCLI |./xplan-manager-cli.log
|XPlanValidatorWeb |$\{catalina.base}/logs/xplan-validator-web.log
|XPlanValidatorCLI |./xplan-validator-cli.log
|XPlanWMS |$\{catalina.base}/logs/xplan-wms.log
|XPlanWFS |$\{catalina.base}/logs/xplan-wfs.log
|XPlanWSynFS |$\{catalina.base}/logs/xplansyn-wfs.log
|============================================================
