[[sortierung-der-daten-in-dervisualisierung]]
=== Sortierung der Daten in der Visualisierung

Für die Sortierung von Plandaten im XPlanWMS nach einem Datumsfeld stehen
alle Datumsfelder zur Verfügung. Welches Feld für die Sortierung
verwendet wird, kann in der Datei _<XPLANBOX_CONFIG>/managerConfiguration.properties_ konfiguriert werden.

----
wmsSortDate_BP_Plan_XPLAN_3=BP_Plan,inkrafttretensDatum
wmsSortDate_BP_Plan_XPLAN_40=BP_Plan,inkrafttretensDatum
wmsSortDate_BP_Plan_XPLAN_41=BP_Plan,inkrafttretensDatum
wmsSortDate_BP_Plan_XPLAN_50=BP_Plan,inkrafttretensDatum
wmsSortDate_BP_Plan_XPLAN_51=BP_Plan,inkrafttretensDatum
wmsSortDate_BP_Plan_XPLAN_52=BP_Plan,inkrafttretensDatum
wmsSortDate_FP_Plan_XPLAN_3=FP_Plan,wirksamkeitsDatum
wmsSortDate_FP_Plan_XPLAN_40=FP_Plan,wirksamkeitsDatum
wmsSortDate_FP_Plan_XPLAN_41=FP_Plan,wirksamkeitsDatum
wmsSortDate_FP_Plan_XPLAN_50=FP_Plan,wirksamkeitsDatum
wmsSortDate_FP_Plan_XPLAN_51=FP_Plan,wirksamkeitsDatum
wmsSortDate_FP_Plan_XPLAN_52=FP_Plan,wirksamkeitsDatum
wmsSortDate_RP_Plan_XPLAN_3=RP_Plan,datumDesInkrafttretens
wmsSortDate_RP_Plan_XPLAN_40=RP_Plan,datumDesInkrafttretens
wmsSortDate_RP_Plan_XPLAN_41=RP_Plan,datumDesInkrafttretens
wmsSortDate_RP_Plan_XPLAN_50=RP_Plan,datumDesInkrafttretens
wmsSortDate_RP_Plan_XPLAN_51=RP_Plan,datumDesInkrafttretens
wmsSortDate_RP_Plan_XPLAN_52=RP_Plan,datumDesInkrafttretens
wmsSortDate_LP_Plan_XPLAN_3=
wmsSortDate_LP_Plan_XPLAN_40=LP_Plan,inkrafttretenDatum
wmsSortDate_LP_Plan_XPLAN_41=LP_Plan,inkrafttretenDatum
wmsSortDate_LP_Plan_XPLAN_50=LP_Plan,inkrafttretenDatum
wmsSortDate_LP_Plan_XPLAN_51=LP_Plan,inkrafttretenDatum
wmsSortDate_SO_Plan_XPLAN_50=SO_Plan,inkrafttretenDatum
wmsSortDate_SO_Plan_XPLAN_51=SO_Plan,inkrafttretenDatum
wmsSortDate_SO_Plan_XPLAN_52=SO_Plan,inkrafttretenDatum
----

NOTE: Es müssen ggf. Zeilenumbrüche entfernt werden.

Die Angabe eines Sortierfeldes kann für jeden Plan-Type und Plan-Version
differenziert erfolgen und kann am Aufbau des Schlüsselnamens erkannt
werden.

----
wmsSortDate_<TYP>_<VERSION>
----

Der Wert gibt immer den Namen des FeatureTypes sowie den Namen der
Eigenschaft durch ein Komma separiert an.

----
<FEATURETYPE>,<PROPERTYNAME>
----

Wird kein Wert angegeben, oder fehlt ein Eintrag vollständig, kann für
die Version/den Typ keine Zuordnung gefunden werden. Das Datumsfeld
bleibt leer. Eine Änderung dieser Konfiguration während des laufenden
Betriebs führt zu unterschiedlichen Grundlagen der Sortierung, über die
Option _-updatewmssortdate_ des XPlanManagerCLIs kann die Änderung aber
für bereits importierte Daten nachgezogen werden. Dies ist im
entsprechenden Kapitel des XPlanBenutzerhandbuchs beschrieben.
