[[weiterfuehrende-informationen-zur-semantischen-validierung]]
=== Weiterführende Informationen zur semantischen Validierung

==== Validierungsregeln

Die Regeln für die semantische Validierung von XPlanGML-Dokumenten sind als XQuery Abfragen implementiert.
Die Dateien mit den XQuery Abfragen sind im XPlanValidatorCLI und dem XPlanValidatorWeb enthalten und entsprechend
der Nummer der Regel aus den Konformitätsbedingungen benannt.

==== Referenzen auf externe Ressourcen

Bei der Ausgabe des Ergebnisses der semantischen Validerung kann eine
Referenz auf eine externe Ressource gesetzt werden, die weiterführenden
Informationen bereitstellt. Die Referenzen können in der Datei
_<XPLANBOX_CONFIG>/managerConfiguration.properties_ konfiguriert werden.

----
linkSemanticConformity_XPLAN_2=
linkSemanticConformity_XPLAN_3=
linkSemanticConformity_XPLAN_40=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_4.pdf
linkSemanticConformity_XPLAN_41=http://localhost:8080/external/documentation/Konformitaetsbedingungen-XPlanGML_4_1.pdf
linkSemanticConformity_XPLAN_50=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_5.pdf
linkSemanticConformity_XPLAN_51=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_5_1.pdf
linkSemanticConformity_XPLAN_52=http://localhost:8080/external/documentation/Konformitaetsbedingungen_XPlanGML_5_2.pdf
----

NOTE: Es müssen ggf. Zeilenumbrüche entfernt werden.

Für jede XPlanGML-Version kann hier die Referenz auf eine externe
Resource konfiguriert werden. Ist für eine Version keine Resource
vorhanden, kann der Eintrag vollständig entfernt oder der Wert zu dem
Schlüssel leer gelassen werdem (wie im Beispiel für XPLAN_2 und
XPLAN_3). Es wird dann kein Hinweis im Validierungsbericht ausgegeben.

NOTE: Es wird empfohlen die Dokumente über die Komponente XPlanRessourcen
bereit zu stellen, um die Unabhängigkeit zu externen Resourcen
sicherzustellen.

