[[migration-der-anwendung-beispiele]]
=== Migration der Anwendung (Beispiele)

Bei einem Hostumzug, bei dem sich der Hostname des Servers ändert, muss
die URL in mehreren Konfigurationen angepasst werden, damit die
Funktionalität der Anwendungen gewährleistet ist. Dabei müssen folgende
Anpassungen erfolgen:

[[fuer-den-xplanmanager]]
==== Für den XPlanManager:

________________________________________________________________________________________________________________________
* _managerWebConfiguration.properties_ (im Verzeichnis
_.deegree/manager-configuration_ im Home-Verzeichnis des Nutzers)
* _managerConfiguration.properties_ (im Verzeichnis
_.deegree/manager-configuration_ im Home-Verzeichnis des Nutzers)
________________________________________________________________________________________________________________________

*Anpassungen in der Datei managerWebConfiguration.properties:*

In dieser Datei müssen Anpassungen an der URL erfolgen, damit die
Kartenvorschau im XPlanManager funktioniert. Dazu muss der Wert des
Schlüssels _wmsUrl_ angepasst werden.

----
wmsUrl=http://<host>:<port>/xplan-wms/services
----

Für mehr Details siehe Kapitel <<kartenvorschau>>

*Anpassungen in der Datei managerConfiguration.properties:*

Für einen Workspace-Reload, muss der XPlanManager den deegree-Dienst
erreichen können. Es muss daher der Wert des Schlüssels
_workspaceReloadUrls_ angepasst werden

----
#workspace reloader configuration
workspaceReloadUrls=http://<host>:<port>/<service>/
workspaceReloadUser=<user>
workspaceReloadPassword=<passwort>
----

NOTE: Werden der deegree-Dienst und der XPlanManager auf dem selben Server
betrieben, so können die Dienste über den Hostnamen _localhost_
kommunizieren.

Für mehr Details siehe Kapitel <<automatischer-workspace-reload>>

[[fuer-den-xplanwms]]
==== Für den XPlanWMS:

__________________________________________________________________________________
* _html.gfi_ (im Verzeichnis _.deegree/xplansyn-wms-workspace_ unter
__services__)
__________________________________________________________________________________

*Anpassungen in der Datei html.gfi:*

Damit die Links auf Dokumente in der GetFeatureInfo Ausgabe
funktionsfähig ist, muss eine Anpassung der URL in der Datei _html.gfi_
erfolgen.

----
<?template makeitalink>
<tr>
  <td <?odd:maybegray>><?name:map propname></td>
  <td <?odd:maybegray>><?link:http://<host>:<port>/<service>:Dokument herunterladen></td>
</tr>
----
