[[logging]]
== Logging

Die Anwendungen XPlanManagerWeb, XPlanManagerApi, XPlanValidatorWeb und XPlanValidatorApi, sowie alle XPlanDienste und das Kommandozeilenwerkzeug schreiben Log-Ausgaben standardmäßig nach
Standard-Out. Für die Web-Anwendungen und die Webservices ist dies die Logging-Datei des
Java Applikationsserver (Apache Tomcat: _catalina.out_) und beim Kommandozeilenwerkzeug die Konsole.
Nach Standard-Out werden Informationen, Warnungen und Fehler geschrieben.

=== Protokolldateien der Komponenten

Zusätzlich wird eine Log-Datei für das Kommandozeilenwerkzeug in einer entsprechend benannten Datei im Log-Verzeichnis des Tomcat-Servers _logs/xplan-cli.log_ geschrieben.
In die Log-Dateien werden Informationen, Warnungen und Fehler geschrieben.

NOTE: Ab der xPlanBox Version 7.0 ist die Ausgabe in Log-Dateien deaktiviert. Für die Konfiguration kann das Beispiel für die Ausgabe über einen `RollingFile`-Appender im folgenden Kapitel <<logging-konfiguration>> verwendet werden.

=== Protokollebenen

In den Anwendungen werden für die Nachrichten verschiedenen Protokollebenen (Log-Level) verwendet. Diese haben folgende Bedeutung:

- FATAL: Schwerwiegender Fehler, die einen Betrieb der Software verhindern und Aktionen des Administrators erfordern (Vorgabeeinstellung: ist aktiviert)
- ERROR: Programmfehler, die einen Betrieb der Software einschränken und Aktionen des Administrators erfordern (Vorgabeeinstellung: ist aktiviert)
- WARN: Warnungen, die den Betrieb der Software nicht einschränken, aber auf Konfigurationsprobleme, -fehler o.ä. hinweisen, die von Administrator behoben werden sollten (Vorgabeeinstellung: ist aktiviert)
- INFO: Informationen, die wichtige Programmschritte dokumentieren und vom Administrator und Entwickler zur Kontrolle ausgewertet werden können (Vorgabeeinstellung: nur in den Log-Dateien aktiviert)
- DEBUG: Detaillierte Informationen zum Programmablauf, die vom Entwickler zur Fehler- und Laufzeitanalyse ausgewertet werden können (Vorgabeeinstellung: deaktiviert, wird bei Bedarf und nur temporär aktiviert)
- TRACE: noch detailliertere Informationen zum Programmablauf (Vorgabeeinstellung: deaktiviert, wird bei Bedarf und nur temporär aktiviert, erzeugt viele Nachrichten)

[[logging-konfiguration]]
=== Konfiguration

Die Konfiguration des verwendeten Apache Log4j-Frameworks erfolgt über die Konfigurationsdatei `log4j2.yaml`. Diese Datei ist in allen Komponenten enthalten und liegt in den Webapps im Verzeichnis `WEB-INF/classes` und beim Kommandozeilenwerkzeug im Verzeichnis `etc/`.

Der Aufbau einer Log4j-Konfigurationsdatei ist in mehrere Abschnitte aufgeteilt.
Die verschiedenen Protokollausgabekanäle werden im Abschnitt `Appenders` definiert:

[source,yaml]
----
  Appenders:
    Console: <1>
      name: STDOUT
      target: SYSTEM_OUT <2>
      PatternLayout:
        Pattern: "%d %p %C{1.} [%t] %m%n" <3>
    RollingFile: <4>
      name: RollingFile_Appender
      fileName: ${log.path}/${log.file} <5>
      filePattern: ${log.path}/${log.file}.%d{yyyy-MM-dd-hh-mm} <6>
      PatternLayout:
        pattern: "%d %p %C{1.} [%t] %m%n" <3>
      Policies: <7>
        SizeBasedTriggeringPolicy: <8>
          size: 100 MB
      DefaultRollOverStrategy: <9>
        max: 5
----
<1> Definiert den Ausgabekanal `STDOUT` der auf die Konsole verweist
<2> Konsolenausgabe erfolgt nach Standard-Out `SYSTEM_OUT` (oder `SYSTEM_ERR`)
<3> Definiert das Format für eine Nachricht
<4> Definiert den Ausgabekanal `RollingFile_Appender` der auf eine Protokolldatei verweist
<5> Definiert den Dateipfad und -namen der Protokolldatei
<6> Definiert den Dateipfad und -namen der archivierten Protokolldateien
<7> Definiert die Eigenschaften wann eine Protokolldatei automatisch archiviert wird
<8> Auslöser bei einer Überschreitung der Protokolldatei von 100 MB
<9> Begrenzung der Anzahl der Protokolldateien auf max. 5 Dateien.

Im Abschnitt `Loggers` werden die einzelnen `Logger` konfiguriert:

[source,yaml]
----
  Loggers:
    Root: <1>
      level: info
      AppenderRef:
        - ref: STDOUT <2>
          level: error
        - ref: RollingFile_Appender <3>
          level: info
    Logger:
      - name: org.deegree <4>
        level: info
      - name: de.latlon.xplan
        level: info
----
<1> Konfiguriert den Logger `Root` auf Log-Level `info` und schreibt in die beiden Ausgabekanäle `STDOUT` und `RollingFile_Appender`
<2> Der Ausgabekanal `STDOUT` gibt nur Fehler aus (Log-Level `error` und `fatal`)
<3> Der Ausgabekanal `RollingFile_Appender` gibt Informationen, Warnung und Fehler aus (Log-Level `info`, `warn`, `error` und `fatal` )
<4> Für die Logger `org.deegree` und `de.latlon.xplan` ist ebenfalls ein Log-Level `info` gesetzt. Der Wert für den Log-Level kann `trace`, `debug`, `info`, `warn`, `error`, `fatal` oder `off` sein. Zwischen Klein- und Grossschreibung wird nicht unterschieden.

Im Abschnitt `Properties` können zusätzliche Eigenschaften definiert werden, die in der Konfigurationsdatei verwendet werden können:

[source,yaml]
----
  Properties:
    Property:
      - name: log.file <1>
        value: xplan-validator-cli.log
      - name: log.path <2>
        value: ${sys:basedir:-.}/logs
----
<1> Definiert die Variable `log.file` mit dem Wert `xplan-validator-cli.log`
<2> Definiert die Variable `log.path` mit dem Wert `${sys:basedir:-.}/logs`, dabei wird die Systemvariable `basedir` ausgewertet und dem Verzeichnisnamen `logs` vorangestellt. Ist die Systemvariable nicht gesetzt `:-`, wird der Vorgabewert `.` (Basisverzeichnis des Prozesses) verwendet und dem Verzeichnisnamen `logs` vorangestellt.

Weitere Informationen zur Konfiguration von Log4j sind auf den Seiten des Projekts unter https://logging.apache.org/log4j/2.x/manual/configuration.html zu finden.

==== Setzen der Log4j-Konfiguration

Beim Betrieb der xPlanBox-Komponenten in einem Apache Tomcat muss die Systemvariable `log4j2.configurationFile` gesetzt werden. Die Einstellung wird am besten zu den `CATALINA_OPTS` hinzugefügt:

[source,bash]
----
CATALINA_OPTS=-Dlog4j2.configurationFile=classpath:/log4j2.yaml
----

Weitere Informationen zur Konfiguration von Log4j in einem Servlet-Container sind unter https://logging.apache.org/log4j/2.x/manual/webapp.html zu finden.