[[praeambel]]
== Präambel

Dieses Dokument ist das offizielle Betriebshandbuch zur Installation der
Software xPlanBox. Die in diesem Dokument genannten Soft- und
Hardwarebezeichnungen sind in den meisten Fällen auch eingetragene
Warenzeichen und unterliegen als solche den gesetzlichen Bestimmungen.

Die in diesem Werk enthaltenen Angaben, Daten, Ergebnisse usw. wurden
von den Autoren nach bestem Wissen erstellt und mit Sorgfalt überprüft.
Dennoch sind inhaltliche Fehler nicht völlig auszuschließen. Daher
erfolgen alle Angaben ohne jegliche Verpflichtung oder Garantie. Die
Autoren übernehmen aus diesem Grund auch keinerlei Verantwortung oder
Haftung für Fehler und deren Folgen. Hinweise auf eventuelle Irrtümer
werden gerne entgegengenommen.

Dieses Dokument ist mit AsciiDoc gesetzt. Es ist als
Quellcode erhältlich und kann als HTML und PDF angeschaut bzw.
bereitgestellt werden. Die Bereitstellung des AsciiDoc Quellcode erfolgt über die https://gitlab.opencode.de/diplanung/ozgxplanung[OpenCoDE-Plattform].

[[autoren]]
=== Autoren

Danilo Bretschneider, Jens Fitzke, Torsten Friebe, Dirk Stenger,
Sebastian Goerke, Lyn Elisa Goltz, Carmen Tawalika, Jeronimo Wanhoff,
Lena Rippolz, Julian Zilz.

Copyright (C) 2010 - 2023, lat/lon GmbH, Bonn.

[[lizenz]]
=== Lizenz

Die Komponenten der xPlanBox sind urheberrechtlich geschützt und werden unter der https://www.gnu.org/licenses/agpl-3.0.en.html[GNU Affero General Public License, Version 3 oder jeder späteren Version] veröffentlicht. +
Die xPlanBox basiert auf dem https://www.deegree.org[OSGeo-Projekt deegree], welches Bestandteil der xPlanBox ist. Der Quellcode von deegree ist urheberrechtlich geschützt und wird unter der http://www.gnu.org/licenses/lgpl-2.1.html[GNU Lesser General Public License (LGPL), version 2.1] veröffentlicht. Bitte beachten Sie auch die Lizenzen der verwendeten Bibliotheken im <<appendix_license,Anhang>>.

Copyright (C) 2010 - 2023, lat/lon GmbH, Bonn.

[[softwareüberlassung]]
==== Softwareüberlassung

Die Überlassung der in Binärcode übersetzten Programme (Binärprogramme) der
xPlanBox sowie Skripte, Konfigurationsdateien und Dokumentation erfolgt als Distributionsdatei durch https://www.lat-lon.de[lat/lon] und stehen auf der https://gitlab.opencode.de/diplanung/ozgxplanung[OpenCoDE-Plattform] zum Download zur Verfügung.

[[gewährleistung]]
==== Gewährleistung

Für die Komponenten der xPlanBox gelten die Haftungs- und Gewährleistungsausschlüsse wie in der AGPL benannt. Für deegree gelten die Haftungs- und Gewährleistungsausschlüsse wie in der LGPL benannt.

Die Firma https://www.lat-lon.de[lat/lon] übernimmt keine Gewähr zur Freiheit der Software xPlanBox
bezüglich von Funktions- oder Sachmängeln.

[[nutzungsbedingungen]]
==== Nutzungsbedingungen

Die Nutzungsbedingungen ergeben sich aus der https://www.gnu.org/licenses/agpl-3.0.en.html[GNU Affero General Public License, Version 3 oder jeder späteren Version].

[[lizenz-des-dokuments]]
=== Lizenz des Dokuments

Es wird die Erlaubnis gewährt, dieses Dokument zu kopieren, zu verteilen
und/oder zu modifizieren, unter den Bestimmungen der GNU Free
Documentation License, Version 1.3 oder jeder späteren Version,
veröffentlicht von der Free Software Foundation; mit den unveränderlichen
Abschnitten Präambel und Autoren, ohne vordere Umschlagtexte und ohne hintere Umschlagtexte.
Die Lizenz wird unter http://www.gnu.org/licenses/fdl-1.3
bereitgestellt.
