[[systemueberblick]]
== Systemüberblick

In diesem Betriebshandbuch befinden sich Informationen zu
Systemvoraussetzungen, Schnittstellen und Installation für den Betrieb
der xPlanBox. Die Web-Anwendungen basieren auf den Komponenten des
OSGeo-Projekts http://www.deegree.org/[deegree]. Als zugrunde liegende
Basistechnologien werden Java, Apache Tomcat und PostgreSQL mit PostGIS
verwendet.

Zur erfolgreichen Installation der Software-Komponenten müssen die in
diesem Kapitel beschriebenen Voraussetzungen erfüllt werden.

[[systemvoraussetzungen]]
=== Systemvoraussetzungen

[[server]]
==== Server

[[minimale-systemvoraussetzung]]
===== Minimale Systemvoraussetzung

* CPU: 8 CPUs bzw. 8 Kernen (64 Bit) mit minimal 2,5-GHz-Prozessorgeschwindigkeit
* Arbeitsspeicher: 16 GB RAM
* Netzwerkadapter: Gigabit-Ethernet-Adapter (10/100/1000baseT PHY/MAC)
* Festplattensystem: Journaling-Dateisystem (Kapazität nach Bedarf,
Minimum 500 GB)

CAUTION: Die Anwendung xPlanBox benötigt min. 800 MB Festplattenspeicherplatz.
Wachsende Daten über die Laufzeit sind die Datenhaltung für die Pläne
inkl. der Anhänge und die Systemlogdateien. Zur Kapazitätsplanung kann folgende Abschätzung gegeben werden: Der Festplattenspeicherplatz für die Daten ist erforderlich auf dem Server mit der <<XPlanDB>> und der Tomcat-Instanz mit dem <<XPlanManager>>. Folgende Formel kann bei der   Kapazitätsplanung zur Hilfe gezogen werden: _Größe eines XPlanArchivs (inkl. der Anhänge) * Anzahl der XPlanArchive * 2_. Wenn also zum Beispiel 100 Pläne mit einer durchschnittlichen Größe von 50 MB inkl. der Anhänge importiert werden sollen, dann sind ca. 10 GB Festplattenspeicherplatz je Server notwendig.

[[empfohlene-systemkonfiguration]]
===== Empfohlene Systemkonfiguration

* CPU: 16 CPUs bzw. 16 Kernen (64 Bit) mit 3,2-GHz-Prozessorgeschwindigkeit
* Arbeitsspeicher: 32 GB RAM
* Netzwerkadapter: Gigabit-Ethernet-Adapter (10/100/1000baseT PHY/MAC)
* Festplattensystem: RAID-10 (Kapazität nach Bedarf, Minimum 500 GB)
optional mit SSD

IMPORTANT: Hohe Datentransferraten sind bei Bereitstellung von großen
Datenbeständen sowohl von Raster- als auch Vektordaten
notwendig, u.a. um die Vorgaben der INSPIRE-Richtlinien zu erfüllen.

[[client]]
==== Client

* CPU: 2 CPU mit mindestens 2,0-GHz-Prozessor
* Arbeitsspeicher: 4 GB RAM

NOTE: Weitere Informationen zu den Systemvoraussetzungen bei den unterstützten
Browsern: Microsoft Edge (79.0+), Mozilla Firefox (80.0+), Google Chrome (85.0+)

[[betriebssystem]]
=== Betriebssystem

Als Betriebssystem kann ein beliebiges 64-bit Betriebssystem verwendet werden.

TIP: Empfohlen wird die Nutzung eines der folgenden Betriebssysteme: Debian 10 (Buster) oder Ubuntu 20.04 LTS (Focal Fossa).

TIP: Das Gebietsschema des Betriebssystems ("Locale") sollte auf deutsch
konfiguriert sein, da einzelne Fehlerbeschreibungen in dieser Sprache
ausgegeben werden (z. B. im Validierungsbericht). Unter Linux kann das
Gebietsschema beispielsweise in der Datei "/etc/default/locale"
angepasst werden.

[[jdk]]
=== Java SE
Als Java SE 11 wird sowohl
http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle JDK 11]
als auch OpenJDK 11 (https://adoptium.net/?variant=openjdk11&jvmVariant=hotspot[AdoptOpenJDK 11]
oder https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html[Amazon Corretto 11]) unterstützt.

TIP: Empfohlen wird OpenJDK 11.0.13+8.


[[java-applikationsserver]]
=== Java Applikationsserver

Als Applikationsserver wird Apache Tomcat empfohlen.
Das Installationsarchiv findet sich bei der https://tomcat.apache.org[Apache Foundation]. Diese Dokumentation bezieht sich grundsätzlich auf den Apache Tomcat.

Um eine spätere Trennung der Dienste (Web-Anwendungen) zu gewährleisten, wird die Konfiguration von mehreren Tomcat-Instanzen empfohlen (siehe Kapitel <<web-anwendungen>>).

TIP: Die minimale Anforderung an den Applikationsserver ist das Java EE 7 Web
Profil. Empfohlen wird Apache Tomcat Version 9.0.58.

[[datenbank]]
=== Datenbank

Als Datenbanksystem ist eine Installation von PostgreSQL 9.5+ mit der
Erweiterung PostGIS 2.4+ mindestens erforderlich.

TIP: Empfohlen wird PostgreSQL 11+ mit PostGIS 3.0+.

=== GDAL

Optional kann die Installation der https://gdal.org/[GDAL-Bibliothek] erforderlich sein. Liegen Teil-Vektorielle Pläne mit Rasterdaten in anderen Formaten als GeoTiff vor, die mit der xPlanBox verwaltet werden sollen, ist der Einsatz von GDAL erforderlich. Liegen die Rasterdaten dagegen nur im GeoTiff-Format vor, wird GDAL nicht benötigt.
Weitere Informationen zur Installation von GDAL befinden sich im Abschnitt <<installation-gdal>>.

IMPORTANT: Erforderlich ist GDAL 3.0.

=== HALE CLI

Optional kann die Installation von https://github.com/halestudio/hale-cli/[HALE CLI] erforderlich sein. HALE CLI wird benötigt, wenn die Bereitstellung von Plänen in XPlanGML, die im XPlanManager verwaltet werden, im INSPIRE Planned Land Use (PLU) Datenthema, genutzt werden soll. Weitere Informationen zur Installation befinden sich im Abschnitt <<installation-hale-cli>>.

IMPORTANT: Erforderlich ist HALE CLI 3.4.0+.
