[[systemueberblick]]
== Systemüberblick

In diesem Betriebshandbuch befinden sich Informationen zu
Systemvoraussetzungen, Schnittstellen und Installation für den Betrieb
der xPlanBox. Die Web-Anwendungen basieren auf den Komponenten des
Open-Source-Projekts http://www.deegree.org/[deegree]. Als zugrunde liegende
Basistechnologien werden Java, Apache Tomcat und PostgreSQL mit PostGIS
verwendet.

Zur erfolgreichen Installation der Software-Komponenten müssen die in
diesem Kapitel beschriebenen Voraussetzungen erfüllt werden.

[[betriebssystem]]
=== Betriebssystem

Als Betriebssystem kann ein beliebiges 64-bit Betriebssystem verwendet
werden, das Java SE 8
(http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle
JRE 1.8]) unterstützt.

NOTE: Empfohlen wird Oracle JDK 1.8_202+.

NOTE: Empfohlen wird die Nutzung eines der folgenden Betriebssysteme: Debian 10 (Buster),
Ubuntu 19.04 (Disco Dingo), SLES 12 SP5, CentOS 7.x, Windows Server 2012 R2.

NOTE: Das Gebietsschema des Betriebssystems ("Locale") sollte auf deutsch
konfiguriert sein, da einzelne Fehlerbeschreibungen in dieser Sprache
ausgegeben werden (z.B. im Validator-Report). Unter Linux kann das
Gebietsschema beispielsweise in der Datei "/etc/default/locale"
angepasst werden.

[[java-applikationsserver]]
=== Java Applikationsserver

Als Applikationsserver wird Apache Tomcat empfohlen.
Das Installationsarchiv findet sich bei der
http://tomcat.apache.org[Apache Foundation]. Diese Dokumentation bezieht
sich grundsätzlich auf den Apache Tomcat. Um eine spätere Trennung der
Dienste (Web-Anwendungen) zu gewährleisten, wird die Konfiguration von zwei
Tomcat-Instanzen empfohlen.

NOTE: Die minimale Anforderung an den Applikationsserver ist das Java EE 6 Web
Profil. Empfohlen wird Apache Tomcat Version 8.5.46+ oder 9.0.27+.

[[datenbank]]
=== Datenbank

Als Datenbanksystem ist eine Installation von PostgreSQL 9.4+ mit der
Erweiterung PostGIS 2.3+ mindestens erforderlich.

NOTE: Empfohlen wird PostgreSQL 11+ mit PostGIS 2.5+.

=== GDAL

Optional kann die Installation von GDAL erforderlich sein. Liegen Teil-Vektorielle Pläne mit Rasterdaten in anderen Formaten als GeoTiff vor, die mit der xPlanBox verwaltet werden sollen, ist der Einsatz von GDAL erforderlich. Liegen die Rasterdaten dagegen nur im GeoTiff-Format vor, wird GDAL nicht benötig.
Weitere Informationen zur Installation von GDAL befinden sich im Abschnitt <<installation-gdal>>.

=== HALE CLI

Optional kann die Installation von HALE CLI erforderlich sein. HALE CLI wird benötigt, wenn die Bereitstellung von Plänen in XPlanGML, die im XPlanManager verwaltet werden, im INSPIRE Planned Land Use (PLU) Datenthema, genutzt werden soll. Weitere Informationen zur Installation befinden sich im Abschnitt <<installation-hale-cli>>.


[[systemvoraussetzungen]]
=== Systemvoraussetzungen

[[server]]
==== Server

[[minimale-systemvoraussetzung]]
===== Minimale Systemvoraussetzung


* CPU: 8 CPUs bzw. 8 Kernen (64 Bit) mit minimal 2,5-GHz-Prozessorgeschwindigkeit
* Arbeitsspeicher: 16 GB RAM
* Netzwerkadapter: Gigabit-Ethernet-Adapter (10/100/1000baseT PHY/MAC)
* Festplattensystem: Journaling-Dateisystem (Kapazität nach Bedarf,
Minimum 500 GB)

NOTE: Die Anwendung xPlanBox benötigt min. 800 MB Festplattenspeicherplatz.
Wachsende Daten über die Laufzeit sind die Datenhaltung für die Pläne
inkl. der Anhänge und die Systemlogdateien. Zu der Kapazitätsnutzung der
xPlanBox können folgende Abschätzung gegeben werden: Größe eines
XPlanArchivs (inkl. der Anhänge) * Anzahl der XPlanArchive * 2. Wenn also
100 Pläne mit einer durchschnittlichen Größe von 10 MB inkl. der Anhänge
importiert werden sollen, dann sind ca. 2 GB Festplattenspeicherplatz
notwendig.

[[empfohlene-systemkonfiguration]]
===== Empfohlene Systemkonfiguration

* CPU: 16 CPUs bzw. 16 Kernen (64 Bit) mit 3,2-GHz-Prozessorgeschwindigkeit
* Arbeitsspeicher: 32 GB RAM
* Netzwerkadapter: Gigabit-Ethernet-Adapter (10/100/1000baseT PHY/MAC)
* Festplattensystem: RAID-10 (Kapazität nach Bedarf, Minimum 500 GB)
optional mit SSD

NOTE: Hohe Datentransferraten sind bei Bereitstellung von großen
Datenbeständen sowohl von Raster- als auch Vektordaten
notwendig, u.a. um die Vorgaben der INSPIRE-Richtlinien zu erfüllen.

[[client]]
==== Client

* CPU: 1 CPU mit mindestens 2,0-GHz-Prozessor
* Arbeitsspeicher: 4 GB RAM

NOTE: Weitere Informationen zu den Systemvoraussetzungen bei den unterstützten
Browsern: Microsoft Internet Explorer (10, 11), Mozilla Firefox: 36+,
Google Chrome: 40+
