[[systemueberblick]]
== Systemüberblick

In diesem Betriebshandbuch befinden sich Informationen zu
Systemvoraussetzungen, Schnittstellen und Installation für den Betrieb
der xPlanBox. Die Web-Anwendungen basieren auf den Komponenten des
OSGeo-Projekts https://www.deegree.org/[deegree]. Als zugrunde liegende
Basistechnologien werden Java, Apache Tomcat und PostgreSQL mit PostGIS
verwendet.

Zur erfolgreichen Installation der Software-Komponenten müssen die in
diesem Kapitel beschriebenen Voraussetzungen erfüllt werden.

[[systemvoraussetzungen]]
=== Systemvoraussetzungen

[[server]]
==== Server

[[minimale-systemvoraussetzung]]
===== Minimale Systemvoraussetzung

* CPU: 8 CPUs bzw. 8 Kernen (64 Bit) mit minimal 2,5-GHz-Prozessorgeschwindigkeit
* Arbeitsspeicher: 16 GB RAM
* Netzwerkadapter: Gigabit-Ethernet-Adapter (10/100/1000baseT PHY/MAC)
* Festplattensystem: Journaling-Dateisystem (Kapazität nach Bedarf,
Minimum 500 GB)

[[empfohlene-systemkonfiguration]]
===== Empfohlene Systemkonfiguration

* CPU: 16 CPUs bzw. 16 Kernen (64 Bit) mit 3,2-GHz-Prozessorgeschwindigkeit
* Arbeitsspeicher: 32 GB RAM
* Netzwerkadapter: Gigabit-Ethernet-Adapter (10/100/1000baseT PHY/MAC)
* Festplattensystem: RAID-10 (Kapazität nach Bedarf, Minimum 500 GB)
optional mit SSD

IMPORTANT: Hohe Datentransferraten sind bei Bereitstellung von großen
Datenbeständen sowohl von Raster- als auch Vektordaten
notwendig, u.a. um die Vorgaben der INSPIRE-Richtlinien zu erfüllen.

[[client]]
==== Client

* CPU: 2 CPU mit mindestens 2,0-GHz-Prozessor
* Arbeitsspeicher: 4 GB RAM

NOTE: Weitere Informationen zu den Systemvoraussetzungen bei den unterstützten
Browsern: Microsoft Edge (79.0+), Mozilla Firefox (80.0+), Google Chrome (85.0+)

[[betriebssystem]]
=== Betriebssystem

Als Betriebssystem kann ein beliebiges 64-bit Betriebssystem verwendet werden.

TIP: Empfohlen wird die Nutzung eines der folgenden Betriebssysteme: Debian 10 (Buster) oder Ubuntu 20.04 LTS (Focal Fossa).

TIP: Das Gebietsschema des Betriebssystems ("Locale") sollte auf deutsch
konfiguriert sein, da einzelne Fehlerbeschreibungen in dieser Sprache
ausgegeben werden (z. B. im Validierungsbericht). Unter Linux kann das
Gebietsschema beispielsweise in der Datei "/etc/default/locale"
angepasst werden.

[[jdk]]
=== Java SE
Als Java SE 11 wird sowohl
https://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle JDK 11]
als auch OpenJDK 11 (https://adoptium.net/?variant=openjdk11&jvmVariant=hotspot[AdoptOpenJDK 11]
oder https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html[Amazon Corretto 11]) unterstützt.

TIP: Empfohlen wird AdoptOpenJDK/Temurin 11.0+.


[[java-applikationsserver]]
=== Java Applikationsserver

Als Applikationsserver wird Apache Tomcat empfohlen.
Das Installationsarchiv findet sich bei der https://tomcat.apache.org[Apache Foundation]. Diese Dokumentation bezieht sich grundsätzlich auf den Apache Tomcat.

Um eine spätere Trennung der Dienste (Web-Anwendungen) zu gewährleisten, wird die Konfiguration von mehreren Tomcat-Instanzen empfohlen (siehe Kapitel <<web-anwendungen>>).

TIP: Die minimale Anforderung an den Applikationsserver ist das Java EE 7 Web
Profil. Empfohlen wird Apache Tomcat Version 9.0+.

[[datenbank]]
=== Datenbank

Als Datenbanksystem ist eine Installation von PostgreSQL 12+ mit der
Erweiterung PostGIS 3.1+ erforderlich.

TIP: Empfohlen wird PostgreSQL 14+ mit PostGIS 3.3+.

[[gdal]]
=== GDAL

Optional kann die https://gdal.org/[GDAL-Bibliothek] installiert werden. Wenn teilvektorielle Pläne mit Rasterdaten in anderen Formaten als GeoTiff vorliegen, die mit der xPlanBox verwaltet werden sollen, dann ist der Einsatz von GDAL erforderlich. Liegen die Rasterdaten dagegen nur im GeoTiff-Format vor, wird GDAL nicht benötigt.
Weitere Informationen zur Installation von GDAL befinden sich im Abschnitt <<installation-gdal>>.

IMPORTANT: Erforderlich ist GDAL 3.0+.

[[mapserver]]
=== MapServer

Optional kann https://mapserver.org[MapServer] installiert werden. Wenn für die Bereitstellung von Rasterdaten MapServer verwendet werden soll, dann muss die Software zusammen mit <<gdal, GDAL>> installiert werden. Weitere Informationen zur Installation befinden sich im Abschnitt <<installation-mapserver>>.

IMPORTANT: Erforderlich ist MapServer 8.0.0.

[[mapproxy]]
=== MapProxy

Optional kann https://mapproxy.org/[MapProxy] installiert werden. MapProxy kann als Proxy kaskadierend für den XPlanWMS mit Cache-Funktion verwendet werden, um den Zugriff auf Raster- und Vektorebenen des XPlanWMS zu beschleunigen. Der Zugriff auf MapProxy kann über die Standardschnittstellen WMS und WMTS erfolgen.

Weitere Informationen zur Installation befinden sich im Abschnitt <<installation-mapproxy>>.

IMPORTANT: Erforderlich ist MapProxy 1.16.0.

[[halecli]]
=== HALE CLI

Optional kann das https://github.com/halestudio/hale-cli/[HALE CLI] installiert werden. Wenn Daten der xPlanBox transformiert werden sollen, dann ist der Einsatz des HALE CLI erforderlich. Weitere Informationen zur Installation befinden sich im Abschnitt <<installation-hale-cli>>.

IMPORTANT: Erforderlich ist HALE CLI 3.4.0.