== Weiterführende Informationen

=== Einbindung in andere Software

Zur Betrachtung der über den XPlanManager importierten Planwerke bietet sich die Einbindung des <<xplanwms, XPlanWMS oder XPlanWerkWMS>> in einen geeigneten Client an. Da es sich bei beiden Diensten jeweils um einen standardkonformen WMS handelt, kann jeder Client verwendet werden, der diese Schnittstelle in den Versionen 1.1.1 und 1.3.0 unterstützt.
Der Zugriff auf die XPlanGML-Daten ist über den XPlanSynWFS oder die versionsspezifischen XPlanWFS-Dienste möglich.

NOTE: Als Desktop-Client wird https://qgis.org/[QGIS] empfohlen. Als WebGIS-Client wird das https://www.masterportal.org[Masterportal] empfohlen. Detaillierte Informationen zur Installation, Konfiguration und Benutzung finden sich in der Dokumentation der jeweiligen Software.

=== Zugriff auf Daten

Über die <<xplanmanager-api, REST-API des XPlanManager>> und den <<xplanwfs>> kann jedes importierte XPlanGML abgerufen werden. Je nach Version des XPlanGML-Instanzdokuments und Planstatus wird dieses aus der <<xplandb>> ausgelesen, wobei folgende Beispiele den Zugriff auf das XML-Dokument in der Tabelle `DATENBANK_SCHEMA.GML_OBJECTS.BINARY_OBJECT` verdeutlichen sollen: für einen rechtskräftigen Plan mit Planstatus "festgestellt" in der Version 5.1 erfolgt der Abruf aus `XPLAN51.GML_OBJECTS.BINARY_OBJECT` über den XPlanWFS Endpoint _wfs51_. Für einen in Aufstellung befindlichen Plan in der Version 5.3 der Abruf aus `XPLAN53PRE.GML_OBJECTS.BINARY_OBJECT` über den XPlanWFS Endpoint _wfs53pre_. Änderungen, die über den XPlanManager vorgenommen werden, werden in den Instanz-Dokumenten in der XPlanDB gespeichert. Wie die XPlanDB aufgebaut ist, ergibt sich aus der Einrichtung der Datenbank wie im Kapitel <<konfiguration-der-datenbank>> beschrieben.

=== Empfehlungen für die Bereitstellung von XPlanungsdaten

Die Leitstelle XPlanung/XBau hat einen https://www.xleitstelle.de/leitfaden[Leitfaden XPlanung] herausgegeben, der sich an die Träger von Planverfahrenen, Planer in der öffentlichen Verwaltung als auch in Planungs- und Ingenieurbüros wendet, die mit der konkreten technischen Umsetzung von XPlanung bzw. der Erstellung von Planwerken gemäß dem Standard XPlanung beauftragt sind. Der Leitfaden bietet Unterstützung in der effektiven Umsetzung von XPlanung und der standardkonformen Erstellung und Bereitstellung von XPlanungsdaten von hoher Qualität.

