== XPlanDB

[[datenzugriff-xplandb]]
=== Zugriff auf Daten der XPlanDB

Über die <<xplanmanager-api, REST-API des XPlanManager>> und den <<xplanwfs>> kann jedes importierte XPlanGML-Dokument abgerufen werden. Je nach Version des XPlanGML-Dokuments und Planstatus wird dieses aus der <<xplandb>> ausgelesen, wobei folgende Beispiele den Zugriff auf das XML-Dokument in der Tabelle `<DATENBANK_SCHEMA>.GML_OBJECTS.BINARY_OBJECT` verdeutlichen sollen:

- für einen rechtskräftigen Plan mit Planstatus "festgestellt" in der Version 5.1 erfolgt der Abruf aus `XPLAN51.GML_OBJECTS.BINARY_OBJECT` über den XPlanWFS Endpoint _wfs51_.
- für einen in Aufstellung befindlichen Plan in der Version 5.3 erfolgt der Abruf aus `XPLAN53PRE.GML_OBJECTS.BINARY_OBJECT` über den XPlanWFS Endpoint _wfs53pre_.

Änderungen, die über den XPlanManager vorgenommen werden, werden in der XPlanDB gespeichert. Die Datenbankschemata der XPlanDB sind im Anhang unter <<appendix_xplandb>> zu finden. Der Ablageort der Rasterdaten aus einem XPlanArchiv wird im Anhang unter <<appendix_xplanwms-workspace>> näher beschrieben.

==== Übersicht der Datenbankschemata

Die folgende Tabelle zeigt die in der XPlanDB enthaltenen Datenbankschemata und die auf diese Schema zugreifenden Komponenten am Beispiel der festgestellten.

[width="100%",cols="25%,50%,25%",options="header"]
|===
| Datenbankschema
| Komponente/Endpoint
| Mapping-Typ
| `xplan40`
| <<xplanwfs>>/_wfs40_
| BLOB
| `xplan41`
| <<xplanwfs>>/_wfs41_
| BLOB
| `xplan50`
| <<xplanwfs>>/_wfs50_
| BLOB
| `xplan51`
| <<xplanwfs>>/_wfs51_
| BLOB
| `xplan52`
| <<xplanwfs>>/_wfs52_
| BLOB
| `xplan53`
| <<xplanwfs>>/_wfs53_
| BLOB <<appendix_xplandb_xplan53,(Schema)>>
| `xplan54`
| <<xplanwfs>>/_wfs54_
| BLOB
| `xplan60`
| <<xplanwfs>>/_wfs60_
| BLOB
| `xplansyn`
| <<xplansynwfs>>/_xplansynwfs_, <<xplanwms>>/_wms_
| Relational <<appendix_xplandb_xplansyn,(Schema)>>
| `inspireplu`
| <<xplaninspirepluwfs>>/_downloadservice_, <<xplaninspirepluwms>>/_viewservice_
| Relational
| `xplanmgr`
| <<xplanmanager-web>>, <<xplanmanager-api>>, <<xplanmanager-cli>>, <<xplanwms, XPlanWerkWMS>>
| Relational <<appendix_xplandb_xplanmgr,(Schema)>>
|===

Für alle in Aufstellung befindlichen Pläne existiert zusätzlich ein Datenbankschema mit der Namenskonvention `xplan*pre` und den Endpoints <<xplanwfs>>/_wfs*pre_ sowie für die archivierten Pläne mit `xplan*archive` und den Endpoints <<xplanwfs>>/_wfs*archive_.

Die Datenbankstruktur für die Schemata `xplan*` wird im Anhang <<appendix_xplandb>> beschrieben.



