[[konfiguration-von-externen-codelisten]]
=== Konfiguration von externen Codelisten

Externe Codelisten können im Verzeichnis _<XPLANBOX_CONFIG>/synthesizer_ abgelegt werden. Dabei weist die Variable _<XPLANBOX_CONFIG>_ auf das Verzeichnis, in dem sich die Dateien _managerConfiguration.properties_ und _managerWebConfiguration.properties_ befindet (s. auch <<Anwendungs-Tomcat>>). Das Unterverzeichnis _<XPLANBOX_CONFIG>/synthesizer_ muss ggfs. angelegt werden.

Für die Zuordnung zu dem Property im vereinfachten XPlanSyn-Schema und dem komplexen XPlanGML-Schema, müssen Regeln konfiguriert werden.
Die Regeln müssen abhängig von der XPlanGML-Version in einer der folgenden Dateien angelegt werden (die Dateinamen dürfen dabei nicht verändert werden):

* xplan40.syn
* xplan41.syn
* xplan50.syn
* xplan51.syn
* xplan52.syn
* xplan53.syn
* xplan54.syn

Eine Zeile in diesen Dateien entspricht einer Regel.
Beispiele für eine Regel:

----
# Beispiel 1:
BP_BaugebietsTeilFlaeche/besondereArtDerBaulNutzung=xplanExternalCodeLookup(xpath('xplan:besondereArtDerBaulNutzung'), 'XP_BesondereArtDerBaulNutzung.xml')

# Beispiel 2:
BP_BaugebietsTeilFlaeche/besondereArtDerBaulNutzung=xplanExternalCodeLookup(xpath('xplan:besondereArtDerBaulNutzung'), 'XP_BesondereArtDerBaulNutzung.xml', 'XP_BesondereArtDerBaulNutzung')
----

Aufbau der Regel:

----
<XPATH_XPLANSYN>=xplanExternalCodeLookup(xpath('<PROPERTY_XPLAN_GML>'), '<CODELIST_DATEI>', '<CODELIST_NAME>')
----

Erläuterungen:

* <XPATH_XPLANSYN>: XPath-Ausdruck im XPlanSyn-Schema, für den der übersetze Code eingetragen werden soll.
* <PROPERTY_XPLAN_GML>: Property im XPlanGML-Schema.
* <CODELIST_DATEI>: Relativer Pfad zur Codelist-Datei.
* <CODELIST_NAME>: Optionale Angabe des Namens der Codeliste. Wird nur benötigt, wenn die mit <CODELIST_DATEI> angegebene Datei mehr als eine Codeliste enthält.

Änderungen an den Regel-Dateien sowie Codelist-Dateien werden erst nach einem Neustart des XPlanManagers wirksam.
Sie gelten für den Import von Plänen und werden auch beim Editieren verwenden.
Codes aus bereits importierten Plänen werden nicht neu übersetzt, für diese ist der Aufruf des <<kommandozeilen-anwendungen, Kommandozeilenwerkzeugs reSynthesizer>> erforderlich.

==== Übersetzung von Codelisten für komplexe Zweckbestimmungen

Ab der XPlanGML-Version 6.0 können Codelisten für komplexe Zweckbestimmungen verwendet werden. Dazu müssen diese Codelisten im Verzeichnis _XPLANBOX_CONFIG/synthesizer_ hinterlegt werden.

Für die XPlanGML-Version 6.0 muss ein Unterverzeichnis _xplangml60/_ (mit der gleichen Namenskonvention wie zur Benennung von Verzeichnissen für die <<semantische-validierungsregeln-validator, Validierungsregeln>>) angelegt werden. Hier können die Codelisten als GML 3.2 Dictionary abgelegt werden. Ausgewertet werden alle Dateien mit der Dateiendung _*.xml_ und _*.gml_. Die Struktur der Codeliste muss der einer Enumeration entsprechen (https://xleitstelle.de/downloads/xplanung/releases/XPlanung%20Version%206.0.2/Enumerationen_6_0_2.XML[Beispiel für eine Enumeration aus XPlanGML-Version 6.0]).
