[[konfiguration-daten-dienste-kopplung]]
=== Konfiguration der automatisierten Erstellung von Service-Metadatensätzen

Die xPlanBox bietet die Möglichkeit einen Service-Metadatensatz für einen Plan bzw. den dazugehörigen XPlanWerkWMS automatisiert zu erstellen. Voraussetzung dafür ist, dass für den Plan bereits ein Datensatz-Metadatensatz in einen Metadatenkatalog (CSW) vorhanden ist.
Um diese Funktion zu aktivieren, muss die Konfiguration in der Datei _<XPLANBOX_CONFIG>/managerConfiguration.properties_ angepasst werden. Im Folgenden der relevante Abschnitt:

---------
#Daten-Dienste-Kopplung
planWerkWmsBaseUrl=http://localhost:8083/xplan-planwerk-wms/
planWerkWmsGetMapLayers_BP_Plan=BP_Planvektor
planWerkWmsGetMapStyles_BP_Plan=
planWerkWmsGetMapLayers_FP_Plan=FP_Planvektor
planWerkWmsGetMapStyles_FP_Plan=
planWerkWmsGetMapLayers_RP_Plan=RP_Planvektor
planWerkWmsGetMapStyles_RP_Plan=
planWerkWmsGetMapLayers_LP_Plan=LP_Planvektor
planWerkWmsGetMapStyles_LP_Plan=
planWerkWmsGetMapLayers_SO_Plan=SO_Planvektor
planWerkWmsGetMapStyles_SO_Plan=
planWerkWmsGetMapWidth=750
planWerkWmsGetMapHeight=750
cswUrlProvidingDatasetMetadata=https://metaver.de/csw?SERVICE=CSW&REQUEST=GetCapabilities
#the directory must be existing and writeable
directoryToStoreMetadata=/tmp/
---------

Erläuterung der einzelnen Properties:

 * *planWerkWmsBaseUrl*: Die öffentliche Basis-URL des XPlanWerkWMS, z. B. http://xplanbox.lat-lon.de/xplan-services-wms/
 * *planWerkWmsGetMapLayers_BP_Plan* und *planWerkWmsGetMapStyles_BP_Plan*: Angabe der zu verwendenen Layer und Styles, die in der GetMap Anfrage (GraphicOverview) angegeben werden sollen
 * *planWerkWmsGetMapWidth* und *planWerkWmsGetMapHeight*: Angabe der zu verwendenden Höhe und Breite des Kartenbildes in Pixeln, die in der GetMap Anfrage (GraphicOverview) angegeben werden sollen
 * *cswUrlProvidingDatasetMetadata*: GetCapabilities URL des CSW, der Daten-Metadatensätze zu einem Plan bereitstellt
 * *directoryToStoreMetadata*: Verzeichnis in dem die erstellten Service-Metadatensätze abgelegt werden (das Verzeichnis muss beim Start des Tomcat-Servers, in dem sich die xplanwebapp-manager-web befindet, existieren). Unter Windows muss das Zeichen "\" als Pfad-Trennzeichen verwendet werden (z. B. "C:\tmp\").

Weiterhin muss im Verzeichnis <XPLANBOX_CONFIG>/metadata die Datei _service-iso-metadata-template.xml_ liegen (zum Zeitpunkt des Start des Tomcat-Servers in dem sich die xplanwebapp-manager-web befindet). Diese Datei dient als Template für die vom System zu erstellenden Service-Metadatensätze. Folgende Platzhalter werden bei der Erstellung des Service-Metadatensatz durch entsprechende Werte zur Laufzeit durch das System ausgetauscht und können im Template verwendet werden:

 * *METADATA_ID*: Generierte UUID als FileIdentifier für den generierten Metadatensatz
 * *CURRENT_DATE*: Aktuelles Datum
 * *CURRENT_DATE_TIME*: Aktuelles Datum und Uhrzeit
 * *TITLE*: Titel des WMS
 * *ABSTRACT*: Beschreibung des Plans
 * *PLANWERKWMS_OVERVIEW*: Generierte GetMap-URL des XPlanWerkWMS mit dem Geltungsbereich des Planwerks
 * *WEST_BOUND_LONG*, *EAST_BOUND_LONG*, *SOUTH_BOUND_LAT*, *NORTH_BOUND_LAT*: räumlicher Geltungsbereich des Plans
 * *DATA_METADATA_RESOURCEIDENTIFIER*: GetRecordById-URL zur Abfrage des Daten-Metadatensatz (generiert aus dem FileIdentifier des Daten-Metadatensatz)
 * *DATA_METADATA_FILEIDENTIFIER*: ResourceIdentifier aus dem Daten-Metadatensatz
 * *PLANWERKWMS_CAPABILITIES*: Generierte GetCapabilities-URL des XPlanWerkWMS

==== Abfrage der Datensatz-Metadaten

Die Abfrage des Daten-Metadatensatzes erfolgt mit Hilfe des Plannamens aus dem XPlanGML. Im Folgenden ist die CSW GetRecords-Anfrage dokumentiert, mit der die Metadaten abgerufen werden:

---------
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:apiso="http://www.opengis.net/cat/csw/apiso/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" service="CSW" version="2.0.2" maxRecords="1" startPosition="1" resultType="results" outputFormat="application/xml" outputSchema="http://www.isotc211.org/2005/gmd" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd">
  <csw:Query typeNames="gmd:MD_Metadata">
    <csw:ElementSetName typeNames="gmd:MD_Metadata">full</csw:ElementSetName>
    <csw:Constraint version="1.1.0">
      <ogc:Filter>
        <ogc:PropertyIsEqualTo>
          <ogc:PropertyName>apiso:AlternateTitle</ogc:PropertyName>
          <ogc:Literal>PLANNAME</ogc:Literal>
        </ogc:PropertyIsEqualTo>
      </ogc:Filter>
    </csw:Constraint>
  </csw:Query>
</csw:GetRecords>
---------

Werden mehrere Datensätze gefunden, wird nur einer verwendet (maxRecords="1" ). Es wird eine Warnung im Log ausgegeben.

==== Erzeugung der Service-Metadaten

Der Service-Metadatensatz wird beim Import eines Plans über den XPlanManager erzeugt und im Dateisystem abgelegt.
Ändert ein Benutzer den Plannamen oder die Beschreibung über die Änderungsfunktion des XPlanManager, dann wird ebenfalls ein neuer Service-Metadatensatz erstellt.

NOTE: Um die erstellten Service-Metadatensätze in einen Metadatenkatalog zu übernehmen, müssen diese entweder über die Harvest-Funktion des CSW oder über die CSW-Transaction Insert-Operation in den Metadatenkatalog übernommen werden. Die Funktion für die Übernahme der Service-Metadaten ist nicht Teil der xPlanBox und ist abhängig vom Funktionsumfang des Metadatenkatalogs.

