[[konfiguration-externe-refrenzen]]
=== Bereitstellung externer Referenzen

Um im XPlanManager den Austausch der relativen URLs in absolute URLs für den direkten Abruf der Rasterdaten und/oder Begleitdokumenten eines XPlanArchivs zu aktivieren, muss die Basis URL über eine Umgebungsvariablen gesetzt werden:

[source,properties]
----
XPLAN_DOCUMENT_URL_PUBLIC=http://example.org/xplan-api-dokumente/xdokumente/api/v1/dokument/{planId}/{fileName}
----

Die beiden Platzhalter `{planId}` und `{fileName}` werden beim Austausch der URL durch die ID des Planes und Name der Datei ersetzt. Als Basis URL kann, wie im Beispiel gezeigt, die der <<xplandokumenten-api>> oder bei Nutzung eines <<s3-storage>> auch die öffentliche URL des S3 Objektspeichers konfiguriert werden.

Es wird dann beim Import eines XPlanArchivs mit Rasterdaten und/oder Begleitdokumenten die vollständige URL in folgenden Komponenten ausgegeben:

 * XPlanWMS: GetFeatureInfo-Anfrage in allen unterstützen Formaten
 * XPlanWFS: GetFeature-Anfrage (insbs. GML Format)
 * XPlanSynWFS: GetFeature-Anfrage (insbs. GML Format)
 * XPlanManagerWeb/XPlanManagerAPI: heruntergeladenes XPlan GML
