[[konfiguration-gdal]]
=== GDAL

Die GDAL Unterst체tzung erfordert die Installation von GDAL, diese ist im
Abschnitt Installation <<installation-gdal>> beschrieben.

Um die GDAL Unterst체tzung zu aktivieren, muss die
GDAL-Hauptkonfiguration erzeugt werden. Dazu wird im Basisverzeichnis des
Workspaces _xplansyn-wms-workspace_ eine Datei mit dem Namen _gdal.xml_
und mit folgendem Inhalt abgelegt:

----
<GDALSettings xmlns="http://www.deegree.org/gdal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.deegree.org/gdal https://schemas.deegree.org/3.5/commons/gdal/gdal.xsd">
  <OpenDatasets>5</OpenDatasets>
</GDALSettings>
----

Damit beim Import von Rasterdaten eine GDAL Konfiguration erzeugt wird,
muss in der Datei _<XPLANBOX_CONFIG>/managerConfiguration.properties_ die folgende Option aktiviert sein:

----
# must be gdal, geotiff or mapserver, default is gdal
rasterConfigurationType=gdal
----

Ist die GDAL-Bibliothek nicht installiert, kann stattdessen der
Konfigurationstyp f체r das GeoTiff Format konfiguriert werden:

----
#must be gdal or geotiff, default is gdal
rasterConfigurationType=geotiff
----

Der _xplansyn-wms-workspace_ wird mit einer Dummy-Konfiguration eines GDAL-Rasterlayers ausgeliefert. Liegen zun채chst keine Daten vor, kann dieser aktiviert werden, um Fehler nach dem ersten Import eines Plans mit Rasterdaten zu vermeiden. Dazu muss in den Theme-Konfigurationen unter _themes_ in allen Dateien, die mit raster.xml enden, die folgende Zeile auskommentiert werden:
----
<Layer layerStore="dummyrasterlayer">dummyraster</Layer>
----