[[konfiguration-gdal]]
=== GDAL

Um im XPlanManger die GDAL-Unterst체tzung zu aktivieren, muss vorher die <<installation-gdal,Installation>> und <<konfiguration-gdal,Konfiguration>> von GDAL erfolgt sein.

Um die GDAL Unterst체tzung zu aktivieren, muss die
GDAL-Konfigurationsdatei erzeugt werden. Dazu wird Workspace-Verzeichnis _<DEEGREE_WORKSPACE_ROOT>/xplansyn-wms-workspace_ eine Datei mit dem Namen _gdal.xml_ und mit folgendem Inhalt abgelegt:

[source,xml]
----
<GDALSettings xmlns="http://www.deegree.org/gdal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.deegree.org/gdal https://schemas.deegree.org/core/3.5/commons/gdal/gdal.xsd">
  <OpenDatasets>5</OpenDatasets>
</GDALSettings>
----

Damit beim Import von Rasterdaten eine GDAL Konfiguration erzeugt wird,
muss in der Datei _<XPLANBOX_CONFIG>/managerConfiguration.properties_ die folgende Option aktiviert sein:

[source,properties]
----
# must be gdal, geotiff or mapserver, default is gdal
rasterConfigurationType=gdal
----

Ist die GDAL-Bibliothek nicht installiert, kann stattdessen der
Konfigurationstyp f체r das GeoTiff Format konfiguriert werden:

[source,properties]
----
# must be gdal, geotiff or mapserver, default is gdal
rasterConfigurationType=geotiff
----

Der _xplansyn-wms-workspace_ wird mit einer Dummy-Konfiguration eines GDAL-Rasterlayers ausgeliefert. Liegen zun채chst keine Daten vor, kann dieser aktiviert werden, um Fehler nach dem ersten Import eines Plans mit Rasterdaten zu vermeiden. Dazu muss in den Theme-Konfigurationen unter _themes_ in allen Dateien, die mit raster.xml enden, die folgende Zeile auskommentiert werden:
----
<Layer layerStore="dummyrasterlayer">dummyraster</Layer>
----