[[konfiguration-gdal]]
=== GDAL

Um im XPlanManger die GDAL-Unterstützung zu aktivieren, muss vorher die <<installation-gdal,Installation>> von GDAL erfolgt sein.

Um die GDAL-Unterstützung in deegree zu aktivieren, muss die
GDAL-Konfigurationsdatei erzeugt werden. Dazu muss im Workspace-Verzeichnis _<DEEGREE_WORKSPACE_ROOT>/xplan-services-wms-workspace_ eine Datei mit dem Namen _gdal.xml_ und mit folgendem Inhalt vorhanden sein:

[source,xml]
----
<GDALSettings xmlns="http://www.deegree.org/gdal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.deegree.org/gdal https://schemas.deegree.org/core/3.5/commons/gdal/gdal.xsd">
  <OpenDatasets>10</OpenDatasets>
  <GDALOption name="GDAL_CACHEMAX">1000</GDALOption>
</GDALSettings>
----

TIP: Im Workspace liegt eine Datei _gdal.ignore_ die in _gdal.xml_ umbenannt werden kann.

Damit beim Import von Rasterdaten eine GDAL-Konfiguration erzeugt wird,
muss zusätzlich in der Datei _<XPLANBOX_CONFIG>/managerConfiguration.properties_ die folgende Option aktiviert sein:

[source,properties]
----
# must be gdal, geotiff or mapserver, default is gdal
rasterConfigurationType=gdal
----

Der _xplan-services-wms-workspace_ wird mit einer Dummy-Konfiguration eines GDAL-Rasterlayers ausgeliefert. Liegen zunächst keine Daten vor, kann dieser aktiviert werden, um Fehler nach dem ersten Import eines Plans mit Rasterdaten zu vermeiden. Dazu muss in den Theme-Konfigurationen unter _themes_ in allen Dateien, die mit _raster.xml_ enden, die folgende Zeile auskommentiert werden:
[source,xml]
----
<Layer layerStore="dummyrasterlayer">dummyraster</Layer>
----

==== GDAL deaktiveren

Ist die GDAL-Bibliothek nicht installiert oder soll nicht verwendet werden, kann stattdessen der Konfigurationstyp für das GeoTIFF-Format gesetzt werden:

[source,properties]
----
# must be gdal, geotiff or mapserver, default is gdal
rasterConfigurationType=geotiff
----