[[kartenvorschau]]
=== Kartenvorschau

Die nachfolgenden Konfigurationen müssen in der Datei _<XPLANBOX_CONFIG>/managerWebConfiguration.properties_ angepasst werden.

[[kartenvorschau-xplanwms]]
==== XPlanWMS

Um den XPlanWMS im XPlanManagerWeb für die Kartenvorschau zu konfigurieren, muss der Wert des Schlüssels _wmsUrl_ angepasst werden.
Über die Schlüssel _vectorWmsName_ und _rasterWmsName_ können die in der Kartenvorschau dargestellte Namen für Vektor- und Rasterlayer konfiguriert werden:

_Beispiel der Konfiguration des XPlanWMS für die Kartenvorschau:_
----
wmsUrl=http://<host>:<port>/xplan-services-wms/services
vectorWmsName=xplan-services-wms: Vektorkarten
rasterWmsName=xplan-services-wms: Rasterkarten
wmsEndpoint=wms
wmsPreEndpoint=wmspre
wmsArchiveEndpoint=wmsarchive
----

Über die Schlüssel _wmsEndpoint_, _wmsPreEndpoint_ und
_wmsArchiveEndpoint_ wird angegeben welcher Endpunkt des XPlanWMS für die
Kartenvorschau verwendet wird, wenn ein Plan 'In Aufstellung',
'Festgestellt' oder 'Archiviert' ist. Die URL setzt sich bei Plänen mit dem Status
'Festgestellt' aus der _wmsUrl_ und dem Wert für _wmsEndpoint_ zusammen. Bei Plänen mit dem Status 'In Aufstellung' wird der Wert für _wmsPreEndpoint_ und bei Plänen mit dem Status 'Archiviert' der mit dem Wert _wmsArchiveEndpoint_ verwendet.

[[hintergrundkarte]]
==== Hintergrundkarte

Um die Hintergrundkarte zu konfigurieren, muss der Wert des Schlüssels
_basemapUrl_ angepasst werden. Über den Schlüssel _basemapName_ kann der
in der Kartenvorschau dargestellte Name konfiguriert werden:

----
basemapUrl=http://<host>:<port>/basemap/service
basemapName=Basiskarte
----

[[koordinatensystem]]
==== Koordinatensystem

Das Koordinatensystem, indem die Kartenvorschau angezeigt werden soll,
kann über den Schlüssel _mapCrs_ und dem dazugehörigen Wert konfiguriert
werden:

----
mapCrs=EPSG:25832
----

[[kartenausschnitt]]
==== Kartenausschnitt

----
mapExtent=464540.516097552,4294418.79680585,760676.555028607,9320086.20690937
----

[[ebenen]]
==== Ebenen

Die in der Kartenvorschau dargestellten Ebenen können ebenfalls über
Schlüssel-Wert-Paare konfiguriert werden. Für die Hintergrundkarte wird
der Schlüssel _basemapLayer_ benötigt:

----
basemapLayer=Basemap
----

Des Weiteren können die Layer für die Bebauungspläne, Flächennutzungspläne, Landschaftspläne, Raumordnungspläne und sonstige raumbezogene Planwerke (Vektor- und Rasterlayer) einzeln in einer kommaseparierten Liste konfiguriert werden.

Vektorlayer:

----
bpLayer=BP_Planvektor
fpLayer=FP_Planvektor
lpLayer=LP_Planvektor
rpLayer=RP_Planvektor
soLayer=SO_Planvektor
----

Rasterlayer:

----
bpRasterLayer=BP_Planraster
fpRasterLayer=FP_Planraster
lpRasterLayer=LP_Planraster
rpRasterLayer=RP_Planraster
soRasterLayer=SO_Planraster
----
