[[kategorien]]
=== Filterkategorien

Filterkategorien können genutzt werden, damit ein Benutzer im XPlanManagerWeb die Anzeige der Pläne nach Gemeinden filtern kann. Dabei werden je Plan die Informationen aus dem Element `XP_Gemeinde` ausgewertet.

Um den Filter nach Kategorien zu aktivieren, muss die Datei _<XPLANBOX_CONFIG>/managerWebConfiguration.properties_ entsprechend angepasst werden.

IMPORTANT: Die Filterung nach Filterkategorien ist veraltet und wird in zukünftigen Versionen der xPlanBox entfernt.

[[kategorien-filtern]]
==== Gemeinden

Der Filter je Gemeinde wird über das Element `categoryFilterValues` aktiviert. Die Liste
der Gemeindenamen muss als kommaseparierte Liste angegeben werden. Dabei muss folgende Syntax beachtet werden:

----
categoryFilterValues=Gemeinde1,Gemeinde2
----

Beispiel für die Anzeige der Hamburger Bezirke als Auswahlelemente für die "Gemeindeauswahl" im XPlanManagerWeb:

----
categoryFilterValues=Altona,Bergedorf,Eimsb\u00fcttel,Hamburg-Mitte,Hamburg-Nord,Harburg,Wandsbek
----

IMPORTANT: Umlaute müssen in Unicode für Java codiert werden. Und Sonderzeichen wie z. B. Zeilenumbrüche müssen entfernt werden.

[[kategorien-ortsteile]]
==== Ortsteile

Jeder Gemeinde können mehrere Ortsteile über das Element `categoriesToParts` in der Datei _<XPLANBOX_CONFIG>/managerConfiguration.properties_ zugeordnet werden.
Dabei ist folgende Syntax zu beachten:

----
categoriesToParts=Gemeinde1(Ortsteil1,Ortsteil2);Gemeinde2(Ortsteil3,Ortsteil4)
----

Beispiel für die Zuordnung der Stadtteile Hamburgs zu den Bezirken:

----
categoriesToParts=Altona(Altona-Altstadt,Altona-Nord);
                  Hamburg-Mitte(HafenCity,Hamburg-Altstadt,Neustadt,St.Georg,St.Pauli);
                  Hamburg-Nord(Alsterdorf,Barmbek-Nord,Barmbek-S\u00FCd)
----

IMPORTANT: Umlaute müssen in Unicode für Java codiert werden. Und Sonderzeichen wie z. B. Zeilenumbrüche müssen entfernt werden.

NOTE: Im XPlanGML können mehrere Elemente des Typs `xplan:XP_Gemeinde` angegeben werden (erfordert XPlanGML 4.0 oder aktueller). Aktuell wird bei mehreren Elementen nur das letzte Element ausgewertet! Beinhaltet dieses Element ein `xplan:ortsteilName` dann können hier mehrere Ortsteilnamen kommasepariert angegeben werden. Die Zuordnung zu der Gemeinde erfolgt dann anhand des ersten Ortsteilnamens.

Um den Zugriff auf Pläne im XPlanManagerWeb anhand der Filterkategorien einzuschränken, muss zusätzlich der XPlanManagerWeb für den Rollen-basierten Zugriff (siehe Kapitel <<ldap_security>>) abgesichert werden.