[[standard-crs]]
=== Standard-Koordinatenreferenzsystem

Die von der xPlanBox unterstützten Koordinatenreferenzsysteme können wie folgt konfiguriert werden.

[[crs-rasterdaten]]
==== Rasterdaten

Die nachfolgende Konfiguration muss in der Datei _<XPLANBOX_CONFIG>/managerConfiguration.properties_ angepasst werden.

Das Standard-Koordinatenreferenzsystem kann über den Schlüssel
_rasterConfigurationCrs_ konfiguriert werden:

[source,properties]
----
rasterConfigurationCrs=EPSG:25832
----

[[crs-featurestore]]
==== Ändern des Koordinatenreferenzsystems

Als Vorgabewert für das Standard-Koordinatenreferenzsystem wird EPSG:25832 in allen Konfigurationsdateien gesetzt. Wenn das Standard-Koordinatenreferenzsystem der Datenhaltung geändert werden soll, dann ist eine Anpassung der Konfiguration für <<crs-rasterdaten>> als auch eine Anpassung an den Konfigurationsdateien für die SQLFeatureStore und der XPlanDB erforderlich.

Um die Datenhaltung der XPlanDB z. B. auf EPSG:25833 umzustellen müssen in allen SQLFeatureStore-Dateien die Angabe des `StorageCRS` und der Angabe des PostGIS SRID wie folgt angepasst werden:

[source,xml]
----
 <StorageCRS srid="25833" dim="2D">EPSG:25833</StorageCRS>
----

Um die notwendigen Änderungen auch an der XPlanDB vorzunehmen, müssen für alle Geometrie-Spalten der XPlanDB das PostGIS SRID gesetzt werden.

Hier am Beispiel für das Schema `xplan60` für die Spalte `bbox` der Tabelle `feature_types`:
----
SELECT UpdateGeometrySRID('xplan60','feature_types','bbox',25833);
----

NOTE: Die vollständige Liste der Geometrie-Spalten der XPlanDB finden sie in den mitgelieferten Skripten zum Aufsetzen der XPlanDB, siehe Kapitel <<konfiguration-der-datenbank>>.