[[security]]
=== Absicherung des XPlanManagerWeb

Der Zugriff auf die Komponente XPlanManagerWeb kann mittels Spring Security über BASIC-Authentication abgesichert werden.

Dabei stehen drei verschiedene Konfigurationsvarianten zur Verfügung:

1. Datei-basierte Benutzerverwaltung (siehe <<simple_security>>)
2. Datenbank-basierte Benutzerverwaltung (siehe <<database_security>>)
3. Anbindung an ein LDAP bzw. Microsoft Active Directory (AD) Server (siehe <<ldap_security>>, diese Variante ist veraltet und wird in zukünftigen Versionen der xPlanBox entfernt)

[[enable_security]]
==== Absicherung aktivieren

Um die Absicherung des XPlanManagerWeb zu aktivieren, muss folgende Änderung in dem Deployment-Deskriptor _WEB-INF/web.xml_
der Webanwendung _xplan-manager-web.war_ vorgenommen werden.

Der Spring Security Servlet-Filter muss hinzugefügt werden:

[source,xml]
----
<filter>
  <filter-name>springSecurityFilterChain</filter-name>
  <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
</filter>
<filter-mapping>
  <filter-name>springSecurityFilterChain</filter-name>
  <url-pattern>/*</url-pattern>
</filter-mapping>
----

NOTE: Diese Konfiguration ist für alle drei Varianten erforderlich! Wenn der Servlet-Filter aktiviert ist, muss zusätzlich noch eine der drei Varianten konfiguriert werden. Wie die Absicherung deaktiviert werden kann, ist in <<disable_security>> beschrieben.

Weitere Informationen zur Absicherung mit Spring Security sind Online in der Referenzdokumentation von Spring Security zu finden:

* https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html5/#ns-getting-started[Servlet-Filter von Spring Security]
* https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html5/#jc-authentication[Authentifizierung mit Spring Security]

==== Rollenbasierter Zugriff

Hat sich ein Benutzer erfolgreich am XPlanManager angemeldet, dann wird über ein rollenbasiertes Berechtigungskonzept entschieden, welche Funktionen der Benutzer im XPlanManager ausführen darf.
Dabei werden folgende drei Rollen vom XPlanManager ausgewertet:

- _SUPERUSER_: Hat alle Berechtigungen (Schreib- und Leseberechtigung) für alle Pläne
- _EDITOR_: Hat alle Berechtigungen (Schreib- und Leseberechtigung) für die Pläne einer Organisationseinheit (z.B. einer Kommune oder eines Bezirks)
- _USER_: Hat nur Leseberechtigung für alle Pläne

Weitere Informationen zu den Rollen und Berechtigungen stehen im Kapitel <<rollenundgruppen>>.

[[simple_security]]
==== Einfache Absicherung mit Spring Security

Steht keine Datenbank oder ein LDAP mit Benutzerinformationen zur Verfügung, dann kann die Absicherung über einen UserService von Spring Security erfolgen,
dessen Konfiguration aus der Konfigurationsdatei _security-simple.xml_ ausgelesen wird.

Die Vorgabewerte für die beiden vorkonfigurierten Benutzer "admin" (Rolle _SUPERUSER_) und "guest" (Rolle _USER_) sind in der Konfigurationsdatei _WEB-INF/classes/security.properties_ gesetzt.

Um die Absicherung zu aktivieren ist neben der Konfiguration des Spring Security Servlet-Filter wie oben in <<enable_security>> beschrieben folgende
Anpassungen im Deployment-Deskriptor _WEB-INF/web.xml_ notwendig:

Austauschen der Konfiguration:

[source,xml]
----
<context-param>
  <param-name>contextConfigLocation</param-name>
  <param-value>de.latlon.xplan.manager.web.spring.config.ManagerWebSpringConfig</param-value>
</context-param>
----
durch:

[source,xml]
----
<context-param>
  <param-name>contextConfigLocation</param-name>
  <param-value>de.latlon.xplan.manager.web.spring.config.ManagerWebSpringConfigWithSimpleSecurity</param-value>
</context-param>
----

NOTE: Bei dieser Variante der Absicherung werden Gruppenhierarchien (siehe Kapitel <<gruppenhierarchien>>) nicht unterstützt.

[[database_security]]
==== Absicherung mit Datenbank

Wie bei der einfachen Absicherung wird als Datenquelle für die Benutzerinformationen ein UserService von Spring Security verwendet. Der Unterschied ist,
dass statt einer Datei eine Datenbank verwendet wird. Auch hier muss zuerst der Spring Security Servlet-Filter (siehe <<enable_security>>) und die Konfiguration (siehe <<simple_security>>) aktiviert werden.

In der Datei _security-simple.xml_ muss statt dem Datei-basierten der Datenbank-basierte UserService konfiguriert werden.

Austauschen der Konfiguration:

[source,xml]
----
<security:user-service>
        <security:user name="${simple.user.username}" password="${simple.user.password}" authorities="ROLE_XPLAN_SUPERUSER" />
        <security:user name="${simple.guest.username}" password="${simple.guest.password}" authorities="ROLE_XPLAN_USER" />
</security:user-service>
----
durch:

[source,xml]
----
<security:jdbc-user-service data-source-ref="dataSource"/>
----

NOTE: Die Datenbankverbindung mit dem Bezeichner _datasource_ muss zusätzlich in der Datei _security-simple.xml_ ergänzt werden. Weitere Informationen und Beispiele sind in
der Referenzdokumentation von Spring Security zu finden. Auch diese Variante unterstützt keine Gruppenhierarchien (siehe Kapitel <<gruppenhierarchien>>).

Die Konfiguration eines UserService mit allen Optionen ist auch in der Referenzdokumentation von Spring Security beschrieben:

* https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html5/#core-services-jdbc-user-service[Datenbank UserService]

[[ldap_security]]
==== Absicherung mit LDAP

Wenn zur Authentifizierung eines Benutzers ein LDAP bzw. Microsoft Active Directory (AD) Server verwendet werden soll,
dann muss wie oben in <<enable_security>> beschrieben zuerst der Spring Security Servlet-Filter aktiviert werden.
Neben den Informationen zur Authentifizierung können über LDAP auch Autorisierungsinformationen wie Rollen- und Gruppenzugehörigkeiten
abgerufen werden. Nur mit dieser Variante der Absicherung können Gruppenhierarchien (siehe Kapitel <<gruppenhierarchien>>) abgebildet werden.

Im Deployment-Deskriptor _WEB-INF/web.xml_ muss folgende Änderung vorgenommen werden:

Austauschen der Konfiguration:

[source,xml]
----
<context-param>
  <param-name>contextConfigLocation</param-name>
  <param-value>de.latlon.xplan.manager.web.spring.config.ManagerWebSpringConfig</param-value>
</context-param>
----
durch:

[source,xml]
----
<context-param>
  <param-name>contextConfigLocation</param-name>
  <param-value>de.latlon.xplan.manager.web.spring.config.ManagerWebSpringConfigWithAdLdapSecurity</param-value>
</context-param>
----

===== Verbindung zu LDAP Server konfigurieren

Die Verbindung zum LDAP bzw. AD Server kann in der Webapp des
XPlanManagers in der Datei _WEB-INF/classes/security.properties_
konfiguriert werden.

Beispiel für die Konfiguration:
----
ldap.server.domain=adserver.domain
ldap.server.url=ldap://adserver:389
ldap.server.searchUser=user
ldap.server.searchPassword=password
ldap.server.searchNode=OU=xplanisk,DC=adserver,DC=domain
----

In der Datei muss neben der Adresse und der Domain des AD ein (technischer) Nutzer konfiguriert werden, der lesenden
Zugriff auf das AD hat (__ldap.server.searchUser__ und __ldap.server.searchPassword__). Mit dem
Schlüssel _ldap.server.searchNode_ wird die Organisationseinheit mit `OU`,
und die Domänen Komponenten mit `DC` in kommaseparierter Form angegeben.

Weiterhin kann in dieser Datei die Konfiguration für das dynamische Auslesen der
Gruppenhierarchien erfolgen. Dies ist lediglich nötig, wenn dynamische
Gruppenhierarchien genutzt werden (siehe <<gruppenhierarchien>>).

Weitere Informationen zur LDAP/AD-Anbindung in der Referenzdokumentation von Spring Security im Kapitel:

* https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html5/#ldap[LDAP/AD-Anbindung]

[[rollenundgruppen]]
===== Rollen und Gruppen konfigurieren

Die Konfiguration der Superuser-, der Editor- und der Active Directory-Gruppen mit den dazugehörigen Organisationseinheiten (wie z. B. einer Kommune oder eines Bezirks),
auf die diese Gruppen zugreifen dürfen, erfolgt in der Datei _WEB-INF/classes/security-configuration.xml_.

Konfigurationsbeispiel:

[source,xml]
----
<util:list id="groupsSuper" value-type="java.lang.String">
  <beans:value>SUPER</beans:value>
</util:list>

<util:list id="groupsEditor" value-type="java.lang.String">
  <beans:value>EDITOR</beans:value>
</util:list>

<util:map id="groupsTodistricts" key-type="java.lang.String" value-type="java.util.List">
  <beans:entry key="ALTONA" value-ref="districtsAltona" />
  <beans:entry key="HARBURG" value-ref="districtsHarburg" />
  <beans:entry key="HAMBURGNORD" value-ref="districtsHamburgNord" />
</util:map>

<util:list id="districtsAltona" value-type="java.lang.String">
  <beans:value>Altona</beans:value>
</util:list>

<util:list id="districtsHarburg" value-type="java.lang.String">
  <beans:value>Harburg</beans:value>
</util:list>

<util:list id="districtsHamburgNord" value-type="java.lang.String">
  <beans:value>Hamburg-Nord</beans:value>
</util:list>

<beans:bean id="grantedAuthoritiesMapper"
            class="de.latlon.xplan.manager.web.spring.security.ActiveDirectoryGrantedAuthoritiesMapper">
  <beans:constructor-arg index="0">
    <beans:ref bean="groupsSuper" />
  </beans:constructor-arg>
  <beans:constructor-arg index="1">
    <beans:ref bean="groupsEditor" />
  </beans:constructor-arg>
  <beans:constructor-arg index="2">
    <beans:ref bean="groupsTodistricts" />
  </beans:constructor-arg>
  <beans:constructor-arg index="3">
    <beans:ref bean="roleHierarchy" />
  </beans:constructor-arg>
</beans:bean>
----

Details zur Konfiguration:

* Die Liste _groupsSuper_ (im Beispiel mit SUPER konfiguriert) stellt eine Liste
aller Superuser-Gruppen dar. Ein Nutzer, der einer Superuser-Gruppe
zugeordnet ist, hat keinerlei Beschränkungen bei der Nutzung des
XPlanManagerWeb.
* Die Liste _groupsEditor_ (im Beispiel mit EDITOR konfiguriert) stellt eine
Liste aller Editor-Gruppen dar. Wenn ein Nutzer einer Editor-Gruppe
zugeordnet ist, kann dieser alle Pläne aus Bezirken editieren, für die
der Nutzer Rechte hat (siehe nächste Zeile).
* Die Map _groupsTodistricts_ (im Beispiel mit ALTONA, HARBURG und
HAMBURGNORD konfiguriert) muss eine Active Directory-Gruppe als Key erhalten
und als Value eine Liste aller Bezirke, auf welche die Gruppe zugreifen
darf. Ein Nutzer, der einer oder mehrerer dieser Gruppen zugeordnet
ist, besitzt alle Rechte für die den Bezirken zugeordneten Plänen.
* Die Listen der Bezirke _groupsTodistricts_ (im Beispiel mit Altona,
Harburg und Hamburg-Nord konfiguriert) stellen eigene Spring-Beans dar und
werden von der zuvor beschriebenen Map referenziert.
* Der _grantedAuthoritiesMapper_ nutzt die zuvor konfigurierten Gruppen- und Rollenzuordnungen.
Diese Bean muss nicht manipuliert werden! Die Konfiguration sollte
lediglich modifiziert werden, wenn Gruppenhierarchien deaktiviert werden
sollen (dazu mehr im nächsten Abschnitt).

IMPORTANT: *Achtung* - In der obigen Beispielkonfiguration wird eine Gruppenhierarchie
genutzt. Der nächste Absatz muss zwingend beachtet werden.

[[gruppenhierarchien]]
===== Gruppenhierarchien

Es können Gruppenhierarchien konfiguriert werden, um hierarchische
Abhängigkeiten zwischen Gruppen abzubilden. So kann eine Gruppe
Mitglied einer anderen Gruppe sein und dabei die Eigenschaften der
übergeordneten Gruppe übernehmen.

Beispiel: Gruppe "Hamburg" ist Mitglied der Gruppe "Editor". Dadurch
hat die Gruppe "Hamburg" die Eigenschaften von "Hamburg" und
"Editor". Die Gruppe "Editor" hat dagegen lediglich die
Eigenschaften von "Editor".

Details zur Konfiguration:

* Das als viertes Konstruktorargument übergebene Argument der Bean
_grantedAuthoritiesMapper_ (siehe vorheriges Konfigurationsbeispiel)
muss der Gruppenhierarchie entsprechen. Dies kann wie im folgenden Beispiel 1 in
der Konfiguration direkt erfolgen (das Beispiel konfiguriert HARBURG als
Mitglied der Gruppe EDITOR) oder von der Anwendung aus dem
ActiveDirectory ausgelesen werden, wie im folgenden Beispiel 2 gezeigt.
* Sind keine Gruppenhierarchien vorhanden, muss das vierte
Konstruktorargument entfernt werden (dies sollte der einzige Fall sein,
in dem der _grantedAuthoritiesMapper_ manipuliert wird).
* Falls eine dynamische Rollenhierarchie wie in Beispiel 2 genutzt wird,
müssen in der Datei _WEB-INF/classes/security.properties_ zwingend der
searchUser, das searchPassword und der searchNode angegeben werden
(siehe weiter oben).

Beispiel 1 - Konfiguration einer statischen Rollenhierarchie:

[source,xml]
----
<beans:bean id="roleHierarchy" class="org.springframework.security.access.hierarchicalroles.RoleHierarchyImpl">
  <beans:property name="hierarchy">
   <beans:value>
     HARBURG > EDITOR
   </beans:value>
  </beans:property>
</beans:bean>
----

Beispiel 2 - Konfiguration einer dynamischen Rollenhierarchie:

[source,xml]
----
<beans:bean id="roleHierarchy" class="org.springframework.security.access.hierarchicalroles.RoleHierarchyImpl">
  <beans:property name="hierarchy">
    <beans:bean factory-bean="roleHierarchyScanner" factory-method="retrieveRoleHierarchy" />
  </beans:property>
</beans:bean>

<beans:bean id="roleHierarchyScanner"
            class="de.latlon.xplan.manager.web.spring.security.ActiveDirectoryRoleHierarchyScanner">
  <beans:constructor-arg index="0" value="${ldap.server.url}" />
  <beans:constructor-arg index="1" value="${ldap.server.domain}" />
  <beans:constructor-arg index="2" value="${ldap.server.searchUser}" />
  <beans:constructor-arg index="3" value="${ldap.server.searchPassword}" />
  <beans:constructor-arg index="4" value="${ldap.server.searchNode}" />
  <beans:constructor-arg index="5">
    <beans:ref bean="groupsSuper" />
  </beans:constructor-arg>
  <beans:constructor-arg index="6">
    <beans:ref bean="groupsEditor" />
  </beans:constructor-arg>
  <beans:constructor-arg index="7">
    <beans:ref bean="groupsTodistricts" />
  </beans:constructor-arg>
</beans:bean>
----

Weitere Informationen zur Konfiguration von Spring und Spring Security sind in der Online Dokumentation zu finden:

* https://docs.spring.io/spring-framework/docs/5.2.x/spring-framework-reference/core.html#spring-core[Allgemeine Informationen zur Konfiguration von Spring]
* https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html5/[Konfiguration von Spring Security]

NOTE: Sowohl die dynamische als auch die statische Gruppenhierarchie wird
während des Starts der Webapp einmalig ausgewertet. Wenn es zur Laufzeit
Änderungen an den Hierarchien gibt, muss die Webapp neu gestartet
werden, damit die Änderungen von der Software erkannt und ausgewertet werden können.

IMPORTANT: Die Absicherung mit  LDAP ist veraltet und wird in zukünftigen Versionen der xPlanBox entfernt.

[[disable_security]]
==== Absicherung deaktivieren

Um die Absicherung zu deaktivieren, muss der im Abschnitt <<enable_security>> genannte Servlet-Filter aus der Datei _web.xml_ entfernt und die Spring Konfiguration `de.latlon.xplan.manager.web.spring.config.ManagerWebSpringConfig` eingebunden werden.