[[konfiguration-mapserver]]
=== MapServer

Damit beim Import von Rasterdaten eine Konfiguration für den MapServer erzeugt wird,
muss in der Datei _<XPLANBOX_CONFIG>/managerConfiguration.properties_ die folgende Option aktiviert sein:

[source,properties]
----
# must be gdal, geotiff or mapserver, default is gdal
rasterConfigurationType=mapserver
----

==== S3 Storage

Optional kann als Ablageort von Rasterdaten die AWS S3 API zusammen mit MapServer verwendet werden.
Dazu müssen in der Konfiguration für MapServer und XPlanManager folgende Angaben über Umgebungsvariablen gesetzt werden:

[source,properties]
----
MAPSERVER_STORAGETYPE=s3 <1>
MAPSERVER_S3_ACCESS_KEY=XXXX <2>
MAPSERVER_S3_SECRET_ACCESS_KEY=XXXX <3>
MAPSERVER_S3_BUCKET_NAME=mybucket <4>
MAPSERVER_S3_REGION=eu-central-1 <5>
MAPSERVER_S3_ENDPOINT=https://bucket.domain.com <6>
----
<1> Für die Aktivierung der S3 API muss `s3` gesetzt werden
<2> Hier muss der AWS S3 Accesskey gesetzt werden
<3> Hier muss der AWS S3 Secretkey gesetzt werden
<4> Hier muss der Name des S3-Bucket gesetzt werden
<5> Hier muss die S3 Region gesetzt werden
<6> Hier muss die S3 Endpoint URL gesetzt werden (optional)

Weitere Information zur Konfiguration von MapServer für https://aws.amazon.com/de/s3/[AWS S3] im https://mapserver.org/mapfile/map.html[Mapfile] und zum GDAL Virtual File Systems[https://gdal.org/user/virtual_file_systems.html].

NOTE: Für die Aktivierung der S3 API für die Ablage von Rasterdaten muss zusätzlich auch die Umgebungsvariable `spring_profiles_active=s3` gesetzt werden.