[[migration-der-anwendung-beispiele]]
=== Migration der Anwendung (Beispiele)

Bei einem Hostumzug, bei dem sich der Hostname des Servers ändert, muss
die URL in mehreren Konfigurationen angepasst werden, damit die
Funktionalität der Anwendungen gewährleistet ist. Dabei müssen folgende
Anpassungen erfolgen:

[[fuer-den-xplanmanager]]
==== Für den XPlanManager:

* _<XPLANBOX_CONFIG>/managerWebConfiguration.properties_
* _<XPLANBOX_CONFIG>/managerConfiguration.properties_

*Anpassungen in der Datei managerWebConfiguration.properties:*

In dieser Datei müssen Anpassungen an der URL erfolgen, damit die
Kartenvorschau im XPlanManager funktioniert. Dazu muss der Wert des
Schlüssels _wmsUrl_ angepasst werden.

----
wmsUrl=http://<host>:<port>/xplan-wms/services
----

Für mehr Details siehe Kapitel <<kartenvorschau>>

*Anpassungen in der Datei managerConfiguration.properties:*

Für einen Workspace-Reload, muss der XPlanManager den deegree-Dienst
erreichen können. Es muss daher der Wert des Schlüssels
_workspaceReloadUrls_ angepasst werden

----
#workspace reloader configuration
workspaceReloadUrls=http://<host>:<port>/<service>/
workspaceReloadUser=<user>
workspaceReloadPassword=<passwort>
----

NOTE: Werden der deegree-Dienst und der XPlanManager auf dem selben Server
betrieben, so können die Dienste über den Hostnamen _localhost_
kommunizieren.

Für mehr Details siehe Kapitel <<automatischer-workspace-reload>>

[[fuer-den-xplanwms]]
==== Für den XPlanWMS:

* _html.gfi_ (im Verzeichnis _.deegree/xplansyn-wms-workspace/services_)

*Anpassungen in der Datei html.gfi:*

Damit die Links auf Dokumente in der GetFeatureInfo Ausgabe
funktionsfähig sind, muss eine Anpassung der URL in der Datei _html.gfi_
erfolgen. Die URL in dem zweiten Tabellenelement muss auf die öffentliche URL des XPlanWMS geändert werden, über die die
Anhänge aus dem XPlanArchiv über die Operation GetAttachment des XPlanWMS bereitstellt werden.

----
<?template makeitalink>
<tr>
  <td <?odd:maybegray>><?name:map propname></td>
  <td <?odd:maybegray>><a target="_blank" href="http://<host>:<port>/xplan-wms<?value>">Dokument herunterladen</a></td>
</tr>
----
