[[sortierung-der-daten-in-dervisualisierung]]
=== Sortierung der Daten in der Visualisierung

Für die Sortierung von Plandaten im XPlanWMS nach einem Datumsfeld stehen
alle Datumsfelder zur Verfügung. Welches Feld für die Sortierung
verwendet wird, kann in der Datei _<XPLANBOX_CONFIG>/managerConfiguration.properties_ konfiguriert werden.

Beispiel für eine Konfiguration mit unterschiedlichen Datumsfeldern je Planart:
----
wmsSortDate_BP_Plan_XPLAN_40=BP_Plan,inkrafttretensDatum
wmsSortDate_BP_Plan_XPLAN_41=BP_Plan,inkrafttretensDatum
wmsSortDate_BP_Plan_XPLAN_50=BP_Plan,inkrafttretensDatum
wmsSortDate_BP_Plan_XPLAN_51=BP_Plan,inkrafttretensDatum
wmsSortDate_BP_Plan_XPLAN_52=BP_Plan,inkrafttretensDatum
wmsSortDate_FP_Plan_XPLAN_40=FP_Plan,wirksamkeitsDatum
wmsSortDate_FP_Plan_XPLAN_41=FP_Plan,wirksamkeitsDatum
wmsSortDate_FP_Plan_XPLAN_50=FP_Plan,wirksamkeitsDatum
wmsSortDate_FP_Plan_XPLAN_51=FP_Plan,wirksamkeitsDatum
wmsSortDate_FP_Plan_XPLAN_52=FP_Plan,wirksamkeitsDatum
wmsSortDate_FP_Plan_XPLAN_53=FP_Plan,wirksamkeitsDatum
wmsSortDate_FP_Plan_XPLAN_54=FP_Plan,wirksamkeitsDatum
wmsSortDate_RP_Plan_XPLAN_40=RP_Plan,datumDesInkrafttretens
wmsSortDate_RP_Plan_XPLAN_41=RP_Plan,datumDesInkrafttretens
wmsSortDate_RP_Plan_XPLAN_50=RP_Plan,datumDesInkrafttretens
wmsSortDate_RP_Plan_XPLAN_51=RP_Plan,datumDesInkrafttretens
wmsSortDate_RP_Plan_XPLAN_52=RP_Plan,datumDesInkrafttretens
wmsSortDate_RP_Plan_XPLAN_53=RP_Plan,datumDesInkrafttretens
wmsSortDate_RP_Plan_XPLAN_54=RP_Plan,datumDesInkrafttretens
wmsSortDate_LP_Plan_XPLAN_40=LP_Plan,inkrafttretenDatum
wmsSortDate_LP_Plan_XPLAN_41=LP_Plan,inkrafttretenDatum
wmsSortDate_LP_Plan_XPLAN_50=LP_Plan,inkrafttretenDatum
wmsSortDate_LP_Plan_XPLAN_51=LP_Plan,inkrafttretenDatum
wmsSortDate_SO_Plan_XPLAN_50=SO_Plan,inkrafttretenDatum
wmsSortDate_SO_Plan_XPLAN_51=SO_Plan,inkrafttretenDatum
wmsSortDate_SO_Plan_XPLAN_52=SO_Plan,inkrafttretenDatum
wmsSortDate_SO_Plan_XPLAN_53=SO_Plan,inkrafttretenDatum
wmsSortDate_SO_Plan_XPLAN_54=SO_Plan,inkrafttretenDatum
----

IMPORTANT: Es müssen ggf. Zeilenumbrüche entfernt werden.

Die Angabe eines Sortierfeldes kann für jede Planart und XPlanGML-Version
differenziert erfolgen und kann am Aufbau des Schlüsselnamens erkannt
werden.

----
wmsSortDate_<PLANART>_PLAN_XPLAN_<VERSION>
----

Der Wert gibt immer den Namen des FeatureTypes sowie den Namen der
Eigenschaft durch ein Komma separiert an.

----
<FEATURETYPE>,<PROPERTYNAME>
----

Wird kein Wert angegeben, oder fehlt ein Eintrag vollständig, kann für
die Version/den Typ keine Zuordnung gefunden werden. Das Datumsfeld
bleibt leer.

IMPORTANT: Eine Änderung dieser Konfiguration während des laufenden
Betriebs führt zu unterschiedlichen Grundlagen der Sortierung. Über das <<kommandozeilen-anwendung, Kommandozeilenwerkzeug XPlanCLI>> kann mit dem Kommando `admin sortdate-update` die Änderung für bereits importierte Daten nachgezogen werden.
