[[automatischer-workspace-reload]]
=== Automatischer Workspace-Reload

Der XPlanManager kann nach jedem Import, jeder Änderung oder jedem
Löschvorgang eines Planwerks automatisch einen Workspace-Reload des XPlanWMS/XPlanWerkWMS
auslösen. Dadurch werden Änderungen an Rasterplänen sofort im WMS sichtbar.

In der Datei _<XPLANBOX_CONFIG>/managerConfiguration.properties_ müssen folgende Felder gefüllt
werden:

.Konfigurationselemente in der managerConfiguration.properties Datei:
[source,properties]
----
workspaceReloadUrls=<XPLANWMS-URLS> <1>
workspaceReloadUser=<TOMCAT-NUTZERNAME> <2>
workspaceReloadPassword=<TOMCAT-PASSWORT> <3>
workspaceReloadAction=[ALL,RELOAD,PLANWERKWMS] <4>
----
<1> ein oder mehrere URLs (kommasepariert), wenn mehrere Instanzen des XPlanWMS/XPlanWerkWMS hinter einem Load-Balancer betrieben werden
<2> Nutzername für die Authentifizierung über BASIC-Authentication am Tomcat Webcontext
<3> Passwort für die Authentifizierung über BASIC-Authentication am Tomcat Webcontext
<4> definiert wie die Dienste aktualisiert werden, mit `ALL` (Vorgabewert) werden die Workspace-Konfigurationen aller Dienste neu geladen (`RELOAD`) und der XPlanWerkWMS aktualisiert (`PLANWERKWMS`), so dass einzelne XPlanWerkWMS Endpunkte entfernt werden können. Mit `RELOAD` und `PLANWERKWMS` können diese Aktualisierungen auch getrennt aufgerufen werden.

.Beispiel für mehrere URLs für das Element `workspaceReloadUrls`:
[source,properties]
----
workspaceReloadUrls=http://server1/xplan-wms/,http://server2:8081/xplan-wms/
----

CAUTION: *Wichtig*! Alle Dienste müssen über die gleiche Nutzername-Passwort-Kombination aufgerufen werden können.

