openapi: 3.0.1
info:
  title: XPlanValidatorAPI
  description: XPlanValidator REST API
  termsOfService: http://xplanbox.lat-lon.de/terms/
  contact:
    email: info@lat-lon.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.2
servers:
  - url: https://xplanbox.lat-lon.de/xvalidator/api/v1
  - url: http://xplanbox.lat-lon.de/xvalidator/api/v1
tags:
  - name: validate
    description: Validate XPlanGML documents
    externalDocs:
      description: xPlanBox
      url: http://xplanbox.lat-lon.de
paths:
  /validate:
    post:
      tags:
        - validate
      summary: Upload XPlanGML or XPlanArchive
      description: Uploads XPlanGML or XPlanArchive file
      operationId: upload
      parameters:
        - name: X-Filename
          in: header
          description: Name of the file to be uploaded
          example: File names such as xplan.gml, xplan.xml, xplan.zip
          schema:
            type: string
      requestBody:
        content:
          application/octet-stream:
            schema:
                  type: string
                  format: binary
              description: XPlanGML or XPlanArchive (application/zip) file to upload
          text/xml:
            schema:
              $ref: '#/components/schemas/XPlanGML'
          application/gml+xml:
            schema:
              $ref: '#/components/schemas/XPlanGML'
        required: true
      responses:
        200:
          description: successful upload confirmed by session ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadReport'
            application/xml:
              schema:
                $ref: '#/components/schemas/UploadReport'
            text/xml:
              schema:
                $ref: '#/components/schemas/UploadReport'
        406:
          description: Invalid input
          content: {}
        default:
          description: Unexpected error
          content: {}
  /validate/{sessionId}:
    get:
      tags:
        - validate
      summary: Validate uploaded XPlanGML or XPlanArchive
      description: Start validation using the given parameters
      operationId: validate
      parameters:
        - name: sessionId
          in: path
          description: Session ID of the validation
          example: '3fa85f64-5717-4562-b3fc-2c963f66afa6'
          required: true
          schema:
            type: string
        - name: name
          in: query
          description: Name of the validation
          example: 'xplan-1, Prüfbericht_Torstrasse_10, report#4223'
          schema:
            type: string
        - name: skipGeometrisch
          in: query
          description: Geometrische Validierung ueberspringen
          schema:
            type: boolean
            default: false
        - name: skipSemantisch
          in: query
          description: Semantische Validierung ueberspringen
          schema:
            type: boolean
            default: false
        - name: skipFlaechenschluss
          in: query
          description: Ueberpruefung des Flaechenschluss ueberspringen
          schema:
            type: boolean
            default: false
        - name: skipGeltungsbereich
          in: query
          description: Ueberpruefung des Geltungsbereich ueberspringen
          schema:
            type: boolean
            default: false
      responses:
        200:
          description: successful validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationReport'
            application/xml:
              schema:
                $ref: '#/components/schemas/ValidationReport'
            text/xml:
              schema:
                $ref: '#/components/schemas/ValidationReport'
            text/html:
              schema:
                $ref: '#/components/schemas/ValidationReport'
            application/pdf:
              schema:
                $ref: '#/components/schemas/ValidationReport'
            application/zip:
              schema:
                $ref: '#/components/schemas/ValidationReport'
        400:
          description: Invalid value for session ID
          content: {}
        404:
          description: Session ID is invalid, not found
          content: {}
        default:
          description: Unexpected error
          content: {}
components:
  schemas:
    XPlanGML:
      type: string
      format: binary
      description: 'XPlanGML to upload'
    UploadReport:
      type: object
      properties:
        sessionId:
          type: string
          format: uuid
        wmsUrl:
          type: string
          example: https://xplanbox.lat-lon.de/xplan-validator-wms/services/wms?PLANWERK_MANAGERID=13
    ValidationReport:
      type: object
