\i changelog_xplan2pre.sql
\i changelog_xplan2.sql
\i changelog_xplan3pre.sql
\i changelog_xplan3.sql
\i changelog_xplan40pre.sql
\i changelog_xplan40.sql
\i changelog_xplan41nsmpre.sql
\i changelog_xplan41nsm.sql
\i changelog_xplan41pre.sql
\i changelog_xplan41.sql
\i changelog_xplanmgr.sql
\i changelog_xplansynpre.sql
\i changelog_xplansyn.sql
\i create_xplan2archive.sql
\i create_xplan3archive.sql
\i create_xplan40archive.sql
\i create_xplan41archive.sql
\i create_xplan41nsmarchive.sql
\i create_xplansynarchive.sql