DROP INDEX xplansyn.spatial_idx_465;
DROP INDEX xplansyn.spatial_idx_466;
DROP INDEX xplansyn.spatial_idx_467;
DROP INDEX xplansyn.spatial_idx_468;
DROP INDEX xplansyn.spatial_idx_469;
DROP INDEX xplansyn.spatial_idx_470;
DROP INDEX xplansyn.spatial_idx_472;
DROP INDEX xplansyn.spatial_idx_473;
DROP INDEX xplansyn.spatial_idx_474;
DROP INDEX xplansyn.spatial_idx_475;
DROP INDEX xplansyn.spatial_idx_476;
DROP INDEX xplansyn.spatial_idx_477;
DROP INDEX xplansyn.spatial_idx_478;
DROP INDEX xplansyn.spatial_idx_479;
DROP INDEX xplansyn.spatial_idx_480;
DROP INDEX xplansyn.spatial_idx_482;
DROP INDEX xplansyn.spatial_idx_483;
DROP INDEX xplansyn.spatial_idx_484;
DROP INDEX xplansyn.spatial_idx_485;
DROP INDEX xplansyn.spatial_idx_486;
DROP INDEX xplansyn.spatial_idx_487;
DROP INDEX xplansyn.spatial_idx_488;
DROP INDEX xplansyn.spatial_idx_489;
DROP INDEX xplansyn.spatial_idx_490;
DROP INDEX xplansyn.spatial_idx_491;
DROP INDEX xplansyn.spatial_idx_492;

DROP INDEX xplansynarchive.spatial_idx_465;
DROP INDEX xplansynarchive.spatial_idx_466;
DROP INDEX xplansynarchive.spatial_idx_467;
DROP INDEX xplansynarchive.spatial_idx_468;
DROP INDEX xplansynarchive.spatial_idx_469;
DROP INDEX xplansynarchive.spatial_idx_470;
DROP INDEX xplansynarchive.spatial_idx_472;
DROP INDEX xplansynarchive.spatial_idx_473;
DROP INDEX xplansynarchive.spatial_idx_474;
DROP INDEX xplansynarchive.spatial_idx_475;
DROP INDEX xplansynarchive.spatial_idx_476;
DROP INDEX xplansynarchive.spatial_idx_477;
DROP INDEX xplansynarchive.spatial_idx_478;
DROP INDEX xplansynarchive.spatial_idx_479;
DROP INDEX xplansynarchive.spatial_idx_480;
DROP INDEX xplansynarchive.spatial_idx_482;
DROP INDEX xplansynarchive.spatial_idx_483;
DROP INDEX xplansynarchive.spatial_idx_484;
DROP INDEX xplansynarchive.spatial_idx_485;
DROP INDEX xplansynarchive.spatial_idx_486;
DROP INDEX xplansynarchive.spatial_idx_487;
DROP INDEX xplansynarchive.spatial_idx_488;
DROP INDEX xplansynarchive.spatial_idx_489;
DROP INDEX xplansynarchive.spatial_idx_490;
DROP INDEX xplansynarchive.spatial_idx_491;
DROP INDEX xplansynarchive.spatial_idx_492;

DROP INDEX xplansynpre.spatial_idx_465;
DROP INDEX xplansynpre.spatial_idx_466;
DROP INDEX xplansynpre.spatial_idx_467;
DROP INDEX xplansynpre.spatial_idx_468;
DROP INDEX xplansynpre.spatial_idx_469;
DROP INDEX xplansynpre.spatial_idx_470;
DROP INDEX xplansynpre.spatial_idx_472;
DROP INDEX xplansynpre.spatial_idx_473;
DROP INDEX xplansynpre.spatial_idx_474;
DROP INDEX xplansynpre.spatial_idx_475;
DROP INDEX xplansynpre.spatial_idx_476;
DROP INDEX xplansynpre.spatial_idx_477;
DROP INDEX xplansynpre.spatial_idx_478;
DROP INDEX xplansynpre.spatial_idx_479;
DROP INDEX xplansynpre.spatial_idx_480;
DROP INDEX xplansynpre.spatial_idx_482;
DROP INDEX xplansynpre.spatial_idx_483;
DROP INDEX xplansynpre.spatial_idx_484;
DROP INDEX xplansynpre.spatial_idx_485;
DROP INDEX xplansynpre.spatial_idx_486;
DROP INDEX xplansynpre.spatial_idx_487;
DROP INDEX xplansynpre.spatial_idx_488;
DROP INDEX xplansynpre.spatial_idx_489;
DROP INDEX xplansynpre.spatial_idx_490;
DROP INDEX xplansynpre.spatial_idx_491;
DROP INDEX xplansynpre.spatial_idx_492;

CREATE INDEX spatial_idx_465 ON xplansyn.xplan_rp_einzelhandel USING GIST (xplan_position);
CREATE INDEX spatial_idx_466 ON xplansyn.xplan_rp_erholung USING GIST (xplan_position);
CREATE INDEX spatial_idx_467 ON xplansyn.xplan_rp_erneuerbareenergie USING GIST (xplan_position);
CREATE INDEX spatial_idx_468 ON xplansyn.xplan_rp_freiraum USING GIST (xplan_position);
CREATE INDEX spatial_idx_469 ON xplansyn.xplan_rp_funktionszuweisung USING GIST (xplan_position);
CREATE INDEX spatial_idx_470 ON xplansyn.xplan_rp_industriegewerbe USING GIST (xplan_position);
CREATE INDEX spatial_idx_472 ON xplansyn.xplan_rp_kulturlandschaft USING GIST (xplan_position);
CREATE INDEX spatial_idx_473 ON xplansyn.xplan_rp_laermschutzbauschutz USING GIST (xplan_position);
CREATE INDEX spatial_idx_474 ON xplansyn.xplan_rp_luftverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_475 ON xplansyn.xplan_rp_planungsraum USING GIST (xplan_position);
CREATE INDEX spatial_idx_476 ON xplansyn.xplan_rp_radwegwanderweg USING GIST (xplan_position);
CREATE INDEX spatial_idx_477 ON xplansyn.xplan_rp_rohstoff USING GIST (xplan_position);
CREATE INDEX spatial_idx_478 ON xplansyn.xplan_rp_schienenverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_479 ON xplansyn.xplan_rp_sonstigerfreiraumschutz USING GIST (xplan_position);
CREATE INDEX spatial_idx_480 ON xplansyn.xplan_rp_sonstverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_482 ON xplansyn.xplan_rp_sportanlage USING GIST (xplan_position);
CREATE INDEX spatial_idx_483 ON xplansyn.xplan_rp_strassenverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_484 ON xplansyn.xplan_rp_wasserverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_485 ON xplansyn.xplan_rp_wohnensiedlung USING GIST (xplan_position);
CREATE INDEX spatial_idx_486 ON xplansyn.xplan_rp_sonstigersiedlungsbereich USING GIST (xplan_position);
CREATE INDEX spatial_idx_487 ON xplansyn.xplan_rp_siedlung USING GIST (xplan_position);
CREATE INDEX spatial_idx_488 ON xplansyn.xplan_rp_hochwasserschutz USING GIST (xplan_position);
CREATE INDEX spatial_idx_489 ON xplansyn.xplan_lp_schutzobjektlandesrecht USING GIST (xplan_position);
CREATE INDEX spatial_idx_490 ON xplansyn.xplan_bp_technischemassnahmenflaeche USING GIST (xplan_position);
CREATE INDEX spatial_idx_491 ON xplansyn.xplan_bp_nichtueberbaubaregrundstuecksflaeche USING GIST (xplan_position);
CREATE INDEX spatial_idx_492 ON xplansyn.xplan_fp_landwirtschaft USING GIST (xplan_position);

CREATE INDEX spatial_idx_465 ON xplansynarchive.xplan_rp_einzelhandel USING GIST (xplan_position);
CREATE INDEX spatial_idx_466 ON xplansynarchive.xplan_rp_erholung USING GIST (xplan_position);
CREATE INDEX spatial_idx_467 ON xplansynarchive.xplan_rp_erneuerbareenergie USING GIST (xplan_position);
CREATE INDEX spatial_idx_468 ON xplansynarchive.xplan_rp_freiraum USING GIST (xplan_position);
CREATE INDEX spatial_idx_469 ON xplansynarchive.xplan_rp_funktionszuweisung USING GIST (xplan_position);
CREATE INDEX spatial_idx_470 ON xplansynarchive.xplan_rp_industriegewerbe USING GIST (xplan_position);
CREATE INDEX spatial_idx_472 ON xplansynarchive.xplan_rp_kulturlandschaft USING GIST (xplan_position);
CREATE INDEX spatial_idx_473 ON xplansynarchive.xplan_rp_laermschutzbauschutz USING GIST (xplan_position);
CREATE INDEX spatial_idx_474 ON xplansynarchive.xplan_rp_luftverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_475 ON xplansynarchive.xplan_rp_planungsraum USING GIST (xplan_position);
CREATE INDEX spatial_idx_476 ON xplansynarchive.xplan_rp_radwegwanderweg USING GIST (xplan_position);
CREATE INDEX spatial_idx_477 ON xplansynarchive.xplan_rp_rohstoff USING GIST (xplan_position);
CREATE INDEX spatial_idx_478 ON xplansynarchive.xplan_rp_schienenverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_479 ON xplansynarchive.xplan_rp_sonstigerfreiraumschutz USING GIST (xplan_position);
CREATE INDEX spatial_idx_480 ON xplansynarchive.xplan_rp_sonstverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_482 ON xplansynarchive.xplan_rp_sportanlage USING GIST (xplan_position);
CREATE INDEX spatial_idx_483 ON xplansynarchive.xplan_rp_strassenverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_484 ON xplansynarchive.xplan_rp_wasserverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_485 ON xplansynarchive.xplan_rp_wohnensiedlung USING GIST (xplan_position);
CREATE INDEX spatial_idx_486 ON xplansynarchive.xplan_rp_sonstigersiedlungsbereich USING GIST (xplan_position);
CREATE INDEX spatial_idx_487 ON xplansynarchive.xplan_rp_siedlung USING GIST (xplan_position);
CREATE INDEX spatial_idx_488 ON xplansynarchive.xplan_rp_hochwasserschutz USING GIST (xplan_position);
CREATE INDEX spatial_idx_489 ON xplansynarchive.xplan_lp_schutzobjektlandesrecht USING GIST (xplan_position);
CREATE INDEX spatial_idx_490 ON xplansynarchive.xplan_bp_technischemassnahmenflaeche USING GIST (xplan_position);
CREATE INDEX spatial_idx_491 ON xplansynarchive.xplan_bp_nichtueberbaubaregrundstuecksflaeche USING GIST (xplan_position);
CREATE INDEX spatial_idx_492 ON xplansynarchive.xplan_fp_landwirtschaft USING GIST (xplan_position);

CREATE INDEX spatial_idx_465 ON xplansynpre.xplan_rp_einzelhandel USING GIST (xplan_position);
CREATE INDEX spatial_idx_466 ON xplansynpre.xplan_rp_erholung USING GIST (xplan_position);
CREATE INDEX spatial_idx_467 ON xplansynpre.xplan_rp_erneuerbareenergie USING GIST (xplan_position);
CREATE INDEX spatial_idx_468 ON xplansynpre.xplan_rp_freiraum USING GIST (xplan_position);
CREATE INDEX spatial_idx_469 ON xplansynpre.xplan_rp_funktionszuweisung USING GIST (xplan_position);
CREATE INDEX spatial_idx_470 ON xplansynpre.xplan_rp_industriegewerbe USING GIST (xplan_position);
CREATE INDEX spatial_idx_472 ON xplansynpre.xplan_rp_kulturlandschaft USING GIST (xplan_position);
CREATE INDEX spatial_idx_473 ON xplansynpre.xplan_rp_laermschutzbauschutz USING GIST (xplan_position);
CREATE INDEX spatial_idx_474 ON xplansynpre.xplan_rp_luftverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_475 ON xplansynpre.xplan_rp_planungsraum USING GIST (xplan_position);
CREATE INDEX spatial_idx_476 ON xplansynpre.xplan_rp_radwegwanderweg USING GIST (xplan_position);
CREATE INDEX spatial_idx_477 ON xplansynpre.xplan_rp_rohstoff USING GIST (xplan_position);
CREATE INDEX spatial_idx_478 ON xplansynpre.xplan_rp_schienenverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_479 ON xplansynpre.xplan_rp_sonstigerfreiraumschutz USING GIST (xplan_position);
CREATE INDEX spatial_idx_480 ON xplansynpre.xplan_rp_sonstverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_482 ON xplansynpre.xplan_rp_sportanlage USING GIST (xplan_position);
CREATE INDEX spatial_idx_483 ON xplansynpre.xplan_rp_strassenverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_484 ON xplansynpre.xplan_rp_wasserverkehr USING GIST (xplan_position);
CREATE INDEX spatial_idx_485 ON xplansynpre.xplan_rp_wohnensiedlung USING GIST (xplan_position);
CREATE INDEX spatial_idx_486 ON xplansynpre.xplan_rp_sonstigersiedlungsbereich USING GIST (xplan_position);
CREATE INDEX spatial_idx_487 ON xplansynpre.xplan_rp_siedlung USING GIST (xplan_position);
CREATE INDEX spatial_idx_488 ON xplansynpre.xplan_rp_hochwasserschutz USING GIST (xplan_position);
CREATE INDEX spatial_idx_489 ON xplansynpre.xplan_lp_schutzobjektlandesrecht USING GIST (xplan_position);
CREATE INDEX spatial_idx_490 ON xplansynpre.xplan_bp_technischemassnahmenflaeche USING GIST (xplan_position);
CREATE INDEX spatial_idx_491 ON xplansynpre.xplan_bp_nichtueberbaubaregrundstuecksflaeche USING GIST (xplan_position);
CREATE INDEX spatial_idx_492 ON xplansynpre.xplan_fp_landwirtschaft USING GIST (xplan_position);