###
# #%L
# xplan-mapproxy-config - Modul zur Gruppierung aller Webservices
# %%
# Copyright (C) 2008 - 2024 Freie und Hansestadt Hamburg, developed by lat/lon gesellschaft für raumbezogene Informationssysteme mbH
# %%
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# #L%
###
parts:
  wms_cfg: &wms_cfg
    type: wms
    wms_opts:
      featureinfo: true
      version: 1.3.0
    supported_srs: ['${XPLAN_SERVICES_DEFAULT_CRS_SRID}']
    coverage:
      bbox: [${XPLAN_SERVICES_BBOX_4326}]
      srs: 'EPSG:4326'
  cache_cfg_25832: &cache_cfg_25832
    format: image/png
    grids: [gdi_de_25832]
    meta_size: [3, 3]
    disable_storage: ${XPLAN_MAPPROXY_CACHE_DISABLE}
    cache:
      type: s3
      directory_layout: reverse_tms
  cache_cfg_3857: &cache_cfg_3857
    format: image/png
    grids: [GoogleMapsCompatible]
    meta_size: [3, 3]
    disable_storage: ${XPLAN_MAPPROXY_CACHE_DISABLE}
    cache:
      type: s3
      directory_layout: reverse_tms
  md_cfg: &md_cfg
    online_resource: '${XPLAN_SERVICES_PROVIDER_ONLINERESOURCE}'
    contact:
      person: '${XPLAN_SERVICES_PROVIDER_CONTACT_NAME}'
      position: '${XPLAN_SERVICES_PROVIDER_CONTACT_POSITIONNAME}'
      organization: '${XPLAN_SERVICES_PROVIDER_NAME}'
      address: '${XPLAN_SERVICES_PROVIDER_CONTACT_ADDRESS_DELIVERYPOINT}'
      city: '${XPLAN_SERVICES_PROVIDER_CONTACT_ADDRESS_CITY}'
      postcode: '${XPLAN_SERVICES_PROVIDER_CONTACT_ADDRESS_POSTALCODE}'
      state: '${XPLAN_SERVICES_PROVIDER_CONTACT_ADDRESS_ADMINAREA}'
      country: '${XPLAN_SERVICES_PROVIDER_CONTACT_ADDRESS_COUNTRY}'
      phone: '${XPLAN_SERVICES_PROVIDER_CONTACT_PHONE}'
      email: '${XPLAN_SERVICES_PROVIDER_CONTACT_MAIL}'
    access_constraints: '${XPLAN_SERVICES_ACCESSCONSTRAINTS}'
    fees: '${XPLAN_SERVICES_FEES}'
    keyword_list:
      - vocabulary: GEMET
        keywords:   [land use, land use plan]
      - keywords:   [Bodennutzung, XPlanung]
services:
  # für Probes?
  demo:
  wms:
    # TODO XPLAN_SERVICES_QUERY_CRS but with , as delimiter
    srs: ['EPSG:3857','EPSG:4326','EPSG:25832','EPSG:25833']
    bbox_srs: ["EPSG:4326"]
    on_source_errors: raise
    featureinfo_types: ["text", "html", "xml"]
    max_output_pixels: [${XPLAN_SERVICES_WMS_MAXWIDTH}, ${XPLAN_SERVICES_WMS_MAXHEIGHT}]
    md:
      title: WMS Cache XPlanung
      abstract: Gecachter WMS zur Visualisierung von XPlanungsdaten
      <<: *md_cfg
  wmts:
    restful: true
    restful_template: "/{Layer}/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.{Format}"
    kvp: true
    md:
      title: WMTS XPlanung
      abstract: WMTS zur Visualisierung von XPlanungsdaten
      <<: *md_cfg
layers:
  - name: bplan
    title: XPlanung Bebauungspläne
    layers:
      - name: bp_raster
        title: Rasterdarstellung der Bebauungspläne
        sources: [bplan_raster_cache_25832,bplan_raster_cache_3857]
        tile_sources: [bplan_raster_cache_25832,bplan_raster_cache_3857]
        min_res: 1.4
        max_res: 0.28
        md:
          metadata:
            - url: ${XPLAN_SERVICES_METADATA_URL}
              type: ISO19115:2003
              format: application/xml
      - name: bp_objekte
        title: Vektordarstellung der Bebauungspläne
        sources: [bplan_vektor_cache_25832,bplan_vektor_cache_3857]
        tile_sources: [bplan_vektor_cache_25832,bplan_vektor_cache_3857]
        min_res: 1.4
        max_res: 0.28
        md:
          metadata:
            - url: ${XPLAN_SERVICES_METADATA_URL}
              type: ISO19115:2003
              format: application/xml
  - name: fplan
    title: XPlanung Flächennutzungspläne
    layers:
      - name: fp_raster
        title: Rasterdarstellung der Flächennutzungspläne
        sources: [fplan_raster_cache_25832,fplan_raster_cache_3857]
        tile_sources: [fplan_raster_cache_25832,fplan_raster_cache_3857]
        min_res: 7.0
        max_res: 1.4
        md:
          metadata:
            - url: ${XPLAN_SERVICES_METADATA_URL}
              type: ISO19115:2003
              format: application/xml
      - name: fp_objekte
        title: Vektordarstellung der Flächennutzungspläne
        sources: [fplan_vektor_cache_25832,fplan_vektor_cache_3857]
        tile_sources: [fplan_vektor_cache_25832,fplan_vektor_cache_3857]
        min_res: 7.0
        max_res: 1.4
        md:
          metadata:
            - url: ${XPLAN_SERVICES_METADATA_URL}
              type: ISO19115:2003
              format: application/xml
  - name: lplan
    title: XPlanung Landschaftspläne
    layers:
      - name: lp_raster
        title: Rasterdarstellung der Landschaftspläne
        sources: [lplan_raster_cache_25832,lplan_raster_cache_3857]
        tile_sources: [lplan_raster_cache_25832,lplan_raster_cache_3857]
        min_res: 7.0
        max_res: 1.4
        md:
          metadata:
            - url: ${XPLAN_SERVICES_METADATA_URL}
              type: ISO19115:2003
              format: application/xml
      - name: lp_objekte
        title: Vektordarstellung der Landschaftspläne
        sources: [lplan_vektor_cache_25832,lplan_vektor_cache_3857]
        tile_sources: [lplan_vektor_cache_25832,lplan_vektor_cache_3857]
        min_res: 7.0
        max_res: 1.4
        md:
          metadata:
            - url: ${XPLAN_SERVICES_METADATA_URL}
              type: ISO19115:2003
              format: application/xml
  - name: rplan
    title: XPlanung Regionalpläne
    layers:
      - name: rp_raster
        title: Rasterdarstellung der Regionalpläne
        sources: [rplan_raster_cache_25832,rplan_raster_cache_3857]
        tile_sources: [rplan_raster_cache_25832,rplan_raster_cache_3857]
        min_res: 7.0
        max_res: 1.4
        md:
          metadata:
            - url: ${XPLAN_SERVICES_METADATA_URL}
              type: ISO19115:2003
              format: application/xml
      - name: rp_objekte
        title: Vektordarstellung der Regionalpläne
        sources: [rplan_vektor_cache_25832,rplan_vektor_cache_3857]
        tile_sources: [rplan_vektor_cache_25832,rplan_vektor_cache_3857]
        min_res: 7.0
        max_res: 1.4
        md:
          metadata:
            - url: ${XPLAN_SERVICES_METADATA_URL}
              type: ISO19115:2003
              format: application/xml
  - name: soplan
    title: XPlanung sonstige raumbezogene Pläne
    layers:
      - name: so_raster
        title: Rasterdarstellung der sonstigen raumbezogenen Pläne
        sources: [soplan_raster_cache_25832,soplan_raster_cache_3857]
        tile_sources: [soplan_raster_cache_25832,soplan_raster_cache_3857]
        min_res: 1.4
        max_res: 0.28
        md:
          metadata:
            - url: ${XPLAN_SERVICES_METADATA_URL}
              type: ISO19115:2003
              format: application/xml
      - name: so_objekte
        title: Vektordarstellung der sonstigen raumbezogenen Pläne
        sources: [soplan_vektor_cache_25832,soplan_vektor_cache_3857]
        tile_sources: [soplan_vektor_cache_25832,soplan_vektor_cache_3857]
        min_res: 1.4
        max_res: 0.28
        md:
          metadata:
            - url: ${XPLAN_SERVICES_METADATA_URL}
              type: ISO19115:2003
              format: application/xml
caches:
  bplan_raster_cache_25832:
    <<: *cache_cfg_25832
    cache:
      directory: /bplan_raster/25832/
      type: s3
    sources: ['xplan-mapserver:bp_raster']
  bplan_vektor_cache_25832:
    <<: *cache_cfg_25832
    cache:
      directory: /bplan_vektor/25832/
      type: s3
    sources: ['bplan-wms:bp_objekte']
  fplan_raster_cache_25832:
    <<: *cache_cfg_25832
    cache:
      directory: /fplan_raster/25832/
      type: s3
    sources: ['xplan-mapserver:fp_raster']
  fplan_vektor_cache_25832:
    <<: *cache_cfg_25832
    cache:
      directory: /fplan_vektor/25832/
      type: s3
    sources: ['fplan-wms:fp_objekte']
  lplan_raster_cache_25832:
    <<: *cache_cfg_25832
    cache:
      directory: /lplan_raster/25832/
      type: s3
    sources: ['xplan-mapserver:lp_raster']
  lplan_vektor_cache_25832:
    <<: *cache_cfg_25832
    cache:
      directory: /lplan_vektor/25832/
      type: s3
    sources: ['lplan-wms:lp_objekte']
  rplan_raster_cache_25832:
    <<: *cache_cfg_25832
    cache:
      directory: /rplan_raster/25832/
      type: s3
    sources: ['xplan-mapserver:rp_raster']
  rplan_vektor_cache_25832:
    <<: *cache_cfg_25832
    cache:
      directory: /rplan_vektor/25832/
      type: s3
    sources: ['rplan-wms:rp_objekte']
  soplan_raster_cache_25832:
    <<: *cache_cfg_25832
    cache:
      directory: /soplan_raster/25832/
      type: s3
    sources: ['xplan-mapserver:so_raster']
  soplan_vektor_cache_25832:
    <<: *cache_cfg_25832
    cache:
      directory: /soplan_vektor/25832/
      type: s3
    sources: ['soplan-wms:so_objekte']
  bplan_raster_cache_3857:
    <<: *cache_cfg_3857
    cache:
      directory: /bplan_raster/3857/
      type: s3
    sources: [ 'xplan-mapserver:bp_raster' ]
  bplan_vektor_cache_3857:
    <<: *cache_cfg_3857
    cache:
      directory: /bplan_vektor/3857/
      type: s3
    sources: [ 'bplan-wms:bp_objekte' ]
  fplan_raster_cache_3857:
    <<: *cache_cfg_3857
    cache:
      directory: /fplan_raster/3857/
      type: s3
    sources: [ 'xplan-mapserver:fp_raster' ]
  fplan_vektor_cache_3857:
    <<: *cache_cfg_3857
    cache:
      directory: /fplan_vektor/3857/
      type: s3
    sources: [ 'fplan-wms:fp_objekte' ]
  lplan_raster_cache_3857:
    <<: *cache_cfg_3857
    cache:
      directory: /lplan_raster/3857/
      type: s3
    sources: [ 'xplan-mapserver:lp_raster' ]
  lplan_vektor_cache_3857:
    <<: *cache_cfg_3857
    cache:
      directory: /lplan_vektor/3857/
      type: s3
    sources: [ 'lplan-wms:lp_objekte' ]
  rplan_raster_cache_3857:
    <<: *cache_cfg_3857
    cache:
      directory: /rplan_raster/3857/
      type: s3
    sources: [ 'xplan-mapserver:rp_raster' ]
  rplan_vektor_cache_3857:
    <<: *cache_cfg_3857
    cache:
      directory: /rplan_vektor/3857/
      type: s3
    sources: [ 'rplan-wms:rp_objekte' ]
  soplan_raster_cache_3857:
    <<: *cache_cfg_3857
    cache:
      directory: /soplan_raster/3857/
      type: s3
    sources: [ 'xplan-mapserver:so_raster' ]
  soplan_vektor_cache_3857:
    <<: *cache_cfg_3857
    cache:
      directory: /soplan_vektor/3857/
      type: s3
    sources: [ 'soplan-wms:so_objekte' ]
sources:
  xplan-mapserver:
    <<: *wms_cfg
    req:
      url: ${XPLAN_MAPSERVER_URL_INTERNAL}/mapserver?
      transparent: true
  bplan-wms:
    <<: *wms_cfg
    req:
      url: ${XPLAN_SERVICES_URL_INTERNAL}/xplan-wms/services/bpwms?PIXELSIZE=0.28001
      transparent: true
  fplan-wms:
    <<: *wms_cfg
    req:
      url: ${XPLAN_SERVICES_URL_INTERNAL}/xplan-wms/services/fpwms?PIXELSIZE=0.28001
      transparent: true
  lplan-wms:
    <<: *wms_cfg
    req:
      url: ${XPLAN_SERVICES_URL_INTERNAL}/xplan-wms/services/lpwms?PIXELSIZE=0.28001
      transparent: true
  rplan-wms:
    <<: *wms_cfg
    req:
      url: ${XPLAN_SERVICES_URL_INTERNAL}/xplan-wms/services/rpwms?PIXELSIZE=0.28001
      transparent: true
  soplan-wms:
    <<: *wms_cfg
    req:
      url: ${XPLAN_SERVICES_URL_INTERNAL}/xplan-wms/services/sowms?PIXELSIZE=0.28001
      transparent: true
grids:
  gdi_de_25832:
    srs: 'EPSG:25832'
    tile_size: [512, 512]
    res: [28.0,14.0,7.0,2.8,1.4,0.7,0.28]
    bbox: [${XPLAN_SERVICES_BBOX_4326}]
    bbox_srs: 'EPSG:4326'
    origin: 'ul'
  GoogleMapsCompatible:
      srs: 'EPSG:3857'
      tile_size: [512, 512]
      num_levels: 9
      min_res: 38.21851414258813
      max_res: 0.1492910708694849
      bbox: [${XPLAN_SERVICES_BBOX_4326}]
      bbox_srs: 'EPSG:4326'
      origin: 'ul'
globals:
  cache:
    lock_dir: "./cache_data/locks"
    tile_lock_dir: "./cache_data/tile_locks"
    s3:
      endpoint_url: https://${XPLAN_S3_ENDPOINT}
      bucket_name: ${XPLAN_S3_BUCKET_NAME_MAPPROXY_CACHE}
      region_name: ${XPLAN_S3_REGION}
  image:
    paletted: false
    resampling_method: bicubic
    formats:
      image/png:
        encoding_options:
          quantizer: fastoctree
  http:
    ssl_no_cert_checks: true
    client_timeout: 300
    method: GET
