[appendix]
[[Aenderungshistorie]]
== Änderungshistorie der xPlanBox

[[Aenderungshistorie-6.0.1]]
=== Version 6.0.1

==== Erweiterungen
- Aktualisierung der XPlanGML-Schemadateien auf Version 6.0.2

==== Fehlerbehebungen
- Aktualisierung der Validierungsregeln auf v1.1.2 für die XPlanGML-Version 6.0.2
- Korrektur der Reihenfolge der Textabschnitte im XPlanSynWMS und GFI des XPlanWMS, wenn kein Schlüssel angegeben ist
- Wiederherstellung der Bearbeitungsmöglichkeit des Gültigkeitszeitraums im Editiermodus des XPlanManagerWeb
- Verbesserung der geometrischen Validierung bzgl. inkorrekten Meldungen von Selbstüberschneidungen
- Hinzufügen fehlender Layer im XPlanWMS und FeatureTypes im XPlanSynWFS
- Warnung XPlanWMS "Error while trying to repair an expression" im Log behoben
- Fehlerkorrektur bei der parallelen Ausführung von Validierungen

[[Aenderungshistorie-6.0]]
=== Version 6.0

Mit der Version 6.0 der xPlanBox wird die Version XPlanGML 6.0 unterstützt. Neben der Aktualisierung auf deegree webservices Version 3.5 sind einige Erweiterungen und Verbesserungen an den Komponenten der xPlanBox vorgenommen worden. Ab Version 6.0 der xPlanBox ist mindestens PostgreSQL Version 12 mit der PostGIS-Erweiterung 3.1 erforderlich.

==== Erweiterungen
- Unterstützung für XPlanGML 6.0 in allen Komponenten der xPlanBox
- Unterstützung von Profilen mit zusätzlichen Validierungsregeln für den XPlanValidator
- Neuer Dienst XPlanArtWMS eingeführt, für jede spezifische Planklasse ein eigener WMS
- Verfahren kann nicht mehr über die Editierfunktion im XPlanManagerWeb für XPlanGML 6.0 geändert werden
- Im XPlanManagerWeb können über die Editierfunktion nun auch Flächennutzungspläne, Regionalpläne, Landschaftspläne und Sonstigen Pläne geändert werden
- Versionierung des Datenbankschemas mit Liquibase
- Aktualisierung der XPlanGML-Schemadateien auf Version 6.0.1
- Aktualisierung der Validierungsregeln auf v1.0 für XPlanGML Version 6.0.1
- VERSION.txt durch version.properties-Datei für Standard-Validierungsregeln ersetzt
- Validierung eines XPlan GML mit xsi:type ermöglicht
- Verbesserungen am XPlanSyn-Schema
- Langfassung für Übersetzung von Enumerationswerten im XPlanSynWFS und XPlanWMS
- Vereinheitlichen der Layernamen im XPlanWMS und XPlanWerkWMS
- Verbesserungen der Zeichenvorschriften für Layer aus dem Modellbereichen BP und FP im XPlanWMS
- Verbesserungen der Behandlung von Präsentationsobjekten mit einer Auswahl an Zeichenvorschriften
- Verbesserung der Fehlermeldung beim Import eines XPlanArchiv mit mehreren Instanzdokumenten mit uneindeutigen Bereichs-Nummern
- Verbesserung der Fehlermeldung beim Import eines XPlanArchiv mit mehreren Instanzdokumenten und Referenzierung über verbundenerPlan@xlink:href
- Verbessern der Fehlermeldung beim Editieren eines Plans ohne Bereich
- Unterstützung von XPlanGML 3.0 aus allen Komponenten entfernt
- Konfigurationsparameter defaultBboxIn4326 entfernt
- Hinzufügen einer Tabelle planslog in der XPlanDB
- Aktualisierung auf deegree 3.5
- Aktualisierung auf JTS 1.19.0

==== Fehlerbehebungen
- Fehler bei der Veröffentlichung von Bebauungsplänen als INSPIRE PLU behoben
- Fehler beim Editieren der Rasterbasis (XPlanGML 4.1) behoben
- Fehler in der XPlanWFS ListStoredQueries Antwort behoben
- Fehler beim wiederholten Import eines Plans mit mehreren Instanzen behoben
- Fehlerbehandlung für Anfrage von nicht vorhandenen Ressource über XPlanManagerAPI verbessert
- Fehlende Zeichenvorschriften ergänzt
- Fehler in der Flächenschlussprüfung für Änderungspläne und bei vollständiger Überlappung behoben

[[Aenderungshistorie-5.0.3]]
=== Version 5.0.3

==== Fehlerbehebungen
- Verbesserung der Geltungsbereichsprüfung im XPlanValidator
    - Ausgabe von Schnittpunkten verbessert
    - Prüfung von linien- oder punktförmigen Geometrien korrigiert
- Verbesserungen der Flächenschlussprüfung im XPlanValidator
    - Abweichungen von Stützpunkten unterhalb von 2mm im Bereich von Lücken werden erkannt
    - Verbesserte Ausgabe von potenziellen Lücken als Warnungen
- Fehlermeldung bei Abbruch der geometrischen Validierung im XPlanValidator verbessert
- Verbesserte Darstellung von geometrischen Warnungen im HTML-Format des Reports des XPlanValidator
- Korrekturen in der Benutzerdokumentation für den XPlanValidator vorgenommen

[[Aenderungshistorie-5.0.2]]
=== Version 5.0.2

==== Fehlerbehebungen
- Fehler in XPlanManagerWeb und XPlanManagerAPI bei Änderungen von Rasterdaten in Instanzdokumenten mit mehreren Bereichen behoben

[[Aenderungshistorie-5.0.1]]
=== Version 5.0.1

==== Fehlerbehebungen
- Fehler in OpenAPI-Dokument für XPlanManagerAPI und XPlanValidatorAPI behoben

[[Aenderungshistorie-5.0]]
=== Version 5.0

Mit der Version 5.0 der xPlanBox wird die Version XPlanGML 5.4 unterstützt. Neben der Aktualisierung auf deegree webservices Version 3.4.27 sind einige Erweiterungen und Verbesserungen an den Komponenten der xPlanBox vorgenommen worden. Ab Version 5.0 der xPlanBox ist Java 11 mit Tomcat 9.0 erforderlich. Ältere Java Versionen werden nicht mehr unterstützt.

==== Erweiterungen
- Umstellung von Java 8 auf Java 11 sowie Tomcat 8.5 auf Tomcat 9.0
- Unterstützung für XPlanGML 5.4 in allen Komponenten der xPlanBox
- Import von Instanzdokumenten mit mehreren XP_Plan-Objekten
- Editieren von BPlänen über XPlanManagerAPI
- Unterstützung von Links für externe Dokumente in XPlanManager und XPlanWMS GetFeatureInfo
- Sortierung von Textschlüsseln in XPlanManagerWeb und XPlanWMS GFI-Antwort
- Konfiguration des XPlanWMS verbessert
- Dokumenttyp in der GetFeatureInfo-Ausgabe des XPlanWMS ergänzt
- Editieren von externen Dokumenten über eine vollqualifizierte URL ermöglicht
- Umstellung der Referenz von Rasterbasis auf XP_Bereich.refScan in der Editierfunktion
- Unterstützung von externen Dokumenten über eine vollqualifizierte URL
- Klammern im Dateinamen erlaubt
- Ausgabe und Reihenfolge der Textschlüssel in der HTML GFI verbessert
- Verstöße gegen 2.2.2.1 (fehlerhafte Laufrichtung) als Fehler deklariert
- Option zum Ignorieren/Korrigieren von Verstößen gegen KB 2.2.2.1 (Laufrichtung) ergänzt
- Verbesserung der Darstellung des XPlanWMS und XPlanwerkWMS
- Optimierung der geometrischen Validierung: Geltungsbereich (2.2.3.1)
- Optimierung der geometrischen Validierung: Flächenschlussbedingung (2.2.1.1)
- Geometrischen Fehler "Die XLink-Integrität konnte nicht sichergestellt werden" als Warnung gekennzeichnet
- Berührungspunkte zwischen Polygon-Membern von Multiflächen erlaubt
- Berührungspunkt zwischen Außen- und Innenkontur erlaubt
- Gemeldete Fehler von Überschneidung zwischen äußeren und inneren Ring verbessert
- Ausgeben einer Warnung für Konformitätsregel 3.2.6.2
- Hinzufügen des Kommandozeilenwerkzeugs XPlanValidateDB
- Hinzufügen des Kommandozeilenwerkzeugs XPlanAuswerteschemaCLI
- Alternativen Betriebsmodus aus XPlanManagerCLI und Handbuch entfernt
- Entfernern der Erweiterung für ADE/NSM
- Log-Warnungen und Fehlermeldungen verbessert
- Aufrechterhaltung der HTTP Verbindung bei langlaufenden Validierungsprozessen
- Aktualisierung der Validierungsregeln auf v0.11.1
- Aktualisierung auf deegree 3.4.27
- Aktualisierung auf GDAL 3.0
- Aktualisieren der Apache Log4J Abhängigkeiten

==== Fehlerbehebungen
- Fehler in der Workspace Konfiguration des XPlanWMS behoben
- Fehler "org.deegree.geometry.standard.multi.DefaultMultiPoint cannot be cast to class org.deegree.geometry.primitive.Point" beim Import eines Plans behoben

Die vollständige Änderungshistorie ist auf der https://gitlab.opencode.de/diplanung/ozgxplanung/[OpenCoDE-Plattform] zu finden.