[appendix]
[[Aenderungshistorie]]
== Änderungshistorie der xPlanBox

[[Aenderungshistorie-7.0.1]]
=== Version 7.0.1

==== Erweiterungen
- Das Validierungsprofil Berlin ist in den Komponenten XPlanValidator und XPlanManager enthalten und kann aktiviert werden
- Verbesserung der Konfigurierbarkeit des MapServer-Container-Images
- OCI-Labels für alle Container-Images hinzugefügt
- Aktualisierung der Validierungsregeln auf v1.1.5

==== Fehlerbehebungen
- Fehler bei der Ausführung des XPlanValidator unter Windows behoben
- Fehler bei der Ausführung in Container-Images auf Basis von Bitnami/Tomcat behoben
- Korrekturen in den Zeichenvorschriften für den XPlanWMS vorgenommen
- Fehlermeldung im XPlanValidator bei der Validierung von XPlanArchiven (ZIP-Datei) verbessert
- Korrekturen im Betriebshandbuch für die Kommandozeilenprogramme (CLI) vorgenommen

[[Aenderungshistorie-7.0]]
=== Version 7.0
Neben der Aktualisierung auf die aktuelle deegree webservices Version 3.5.0 sind einige Erweiterungen und Verbesserungen an den Komponenten der xPlanBox vorgenommen worden. Ab Version 7.0 der xPlanBox kann der XPlanWMS als MapServer-Instanz konfiguriert und ein AWS S3-kompatibler Objektspeicher genutzt werden. Mit der Version 7.0 wurde die Ausgabe von Log-Meldungen in separate Log-Dateien je xPlanBox-Komponente aus den mitgelieferten Logging-Konfiguration entfernt. Bitte beachten Sie dazu die Hinweise im Betriebshandbuch, Kapitel Logging.

==== Erweiterungen
- Unterstützung für MapServer 8.0 zur Bereitstellung von Rasterdaten für XPlanWMS hergestellt
- Ablage von Rasterdaten in einem AWS S3-kompatiblen Objektspeicher wird unterstützt
- Ablage von Begleitdokumenten in einem AWS S3-kompatiblen Objektspeicher wird unterstützt
- Abruf von Dokumenten und Rasterdaten über die neue Schnittstelle XPlanDokumentenAPI hergestellt
- Verbesserter Abruf von Dokumenten und Rasterdaten in der GetFeatureInfo-Abfrage des XPlanWMS und GetFeature-Abfrage des XPlanSynWFS und XPlanWFS
- Verbesserung der Geltungsbereichsprüfung im XPlanValidator
- Prüfung der externen Referenzen bei Validierung eines Plans und Ausgabe des Ergebnisses im Validierungsbericht
- Der Import von XPlanGML-Dateien über den XPlanManagerWeb und XPlanManagerAPI wird unterstützt; eine ZIP-Datei ist nicht mehr erforderlich
- Der XPlanValidator kann Daten für den XPlanValidatorWMS temporär in der XPlanDB speichern
- Konfiguration der XPlanDB mit der Angabe des `srid` für alle Geometriespalten hinzugefügt
- Unterstützung einer neuer StoredQuery mit Filter auf planName und eingegrenzten FeatureType im XPlanSynWFS
- Unterstützung der StoredQuery mit Filter auf planName im XPlanSynWFS für alle Datenhaltungen
- Absicherung der deegree REST-API über ApiKeys
- Unterstützung des vereinfachten Downloads eines XPlanArchiv über die XPlanManagerAPI
- Erweiterung der Sortierung von Textabschnitten
- Entfernen des XML-Namespace Präfixes aus dem FeatureType-Namen in den Capabilities des XPlanWFS
- Verbesserung der Transaktionalität bei Auftreten unerwarteter Fehler beim Import im XPlanManager
- Neuer Vorgabewert für Verzeichnisse mit Konfigurationsdateien der xPlanBox

==== Sicherheitsupdates
- Schwachstelle im XML-Prozessor von XPlanValidator und XPlanManager behoben, sodass nur lokale statische DTD verwendet werden können; jede externe und jede deklarierte DTD wird nicht mehr zugelassen
- Schwachstelle im XPlanValidator und XPlanManager gegen persistentes Cross-Site-Scripting (XSS) behoben
- Schwachstelle im XPlanValidator und XPlanManager beim Upload schadhafter Dateien behoben
- Aktualisierung von Bibliotheken mit bekannten Sicherheitsmängeln

==== Fehlerbehebungen
- Fehler in XPlanManagerAPI bei Aufruf von HTTP DELETE für einen Plan behoben
- Fehler in XPlanValidatorAPI bei der Validierung syntaktisch invalider Pläne behoben
- Fehler in XPlanWMS bei Aufruf mit GetMap-Anfrage mit WMS 1.1.1 und EPSG:4326 behoben
- Fehler in XPlanWFS bei Aufruf mit Get-Feature-Anfrage mit WFS 1.1.0 behoben
- Fehler im Encoding der Attributtabelle von Shapefiles aus dem Validierungsreport des XPlanValidators behoben
- Fehler im XPlanWMS bei Aufruf mit GetMap-Anfrage mit WMS 1.1.1 und EPSG:4326 behoben
- Fehlende Ausgabe der detaillierten Zweckbestimmung in komplexen Attributen im XPlanSynWFS ergänzt

==== Veraltete Funktionen

Die folgenden Funktionen sind veraltet und werden in einer zukünftigen Version der xPlanBox entfernt:
- LDAP-Schnittstelle ist veraltet (deprecated)
- Schnittstelle zur Verfahrensdatenbank ist veraltet (deprecated)
- Filterkategorien im XPlanManagerWeb sind veraltet (deprecated)

[[Aenderungshistorie-6.0.3]]
=== Version 6.0.3

==== Fehlerbehebungen
- Aktualisierung der Validierungsregeln auf v1.1.4 mit Korrektur der Regel 5.3.1.2 für Flächennutzungspläne in der Version XPlanGML 5.1
- Externe Codes werden beim Import über den XPlanManagerWeb nicht übersetzt

[[Aenderungshistorie-6.0.2]]
=== Version 6.0.2

==== Fehlerbehebungen
- Aktualisierung der Validierungsregeln auf v1.1.3 mit Korrekturen der Regeln 4.5.1.3 und 5.3.1.2
- Fehlerkorrektur in der Geltungsbereichsprüfung

[[Aenderungshistorie-6.0.1]]
=== Version 6.0.1

==== Erweiterungen
- Aktualisierung der XPlanGML-Schemadateien auf Version 6.0.2

==== Fehlerbehebungen
- Aktualisierung der Validierungsregeln auf v1.1.2 für die XPlanGML-Version 6.0.2
- Korrektur der Reihenfolge der Textabschnitte im XPlanSynWMS und GFI des XPlanWMS, wenn kein Schlüssel angegeben ist
- Wiederherstellung der Bearbeitungsmöglichkeit des Gültigkeitszeitraums im Editiermodus des XPlanManagerWeb
- Verbesserung der geometrischen Validierung bzgl. inkorrekten Meldungen von Selbstüberschneidungen
- Hinzufügen fehlender Layer im XPlanWMS und FeatureTypes im XPlanSynWFS
- Warnung XPlanWMS "Error while trying to repair an expression" im Log behoben
- Fehlerkorrektur bei der parallelen Ausführung von Validierungen

[[Aenderungshistorie-6.0]]
=== Version 6.0

Mit der Version 6.0 der xPlanBox wird die Version XPlanGML 6.0 unterstützt. Neben der Aktualisierung auf deegree webservices Version 3.5 sind einige Erweiterungen und Verbesserungen an den Komponenten der xPlanBox vorgenommen worden. Ab Version 6.0 der xPlanBox ist mindestens PostgreSQL Version 12 mit der PostGIS-Erweiterung 3.1 erforderlich.

==== Erweiterungen
- Unterstützung für XPlanGML 6.0 in allen Komponenten der xPlanBox
- Unterstützung von Profilen mit zusätzlichen Validierungsregeln für den XPlanValidator
- Neuer Dienst XPlanArtWMS eingeführt, für jede spezifische Planklasse ein eigener WMS
- Verfahren kann nicht mehr über die Editierfunktion im XPlanManagerWeb für XPlanGML 6.0 geändert werden
- Im XPlanManagerWeb können über die Editierfunktion nun auch Flächennutzungspläne, Regionalpläne, Landschaftspläne und Sonstigen Pläne geändert werden
- Versionierung des Datenbankschemas mit Liquibase
- Aktualisierung der XPlanGML-Schemadateien auf Version 6.0.1
- Aktualisierung der Validierungsregeln auf v1.0 für XPlanGML Version 6.0.1
- VERSION.txt durch version.properties-Datei für Standard-Validierungsregeln ersetzt
- Validierung eines XPlanGML mit `xsi:type` ermöglicht
- Verbesserungen am XPlanSyn-Schema
- Langfassung für Übersetzung von Enumerationswerten im XPlanSynWFS und XPlanWMS
- Vereinheitlichen der Layernamen im XPlanWMS und XPlanWerkWMS
- Verbesserungen der Zeichenvorschriften für Layer aus dem Modellbereichen BP und FP im XPlanWMS
- Verbesserungen der Behandlung von Präsentationsobjekten mit einer Auswahl an Zeichenvorschriften
- Verbesserung der Fehlermeldung beim Import eines XPlanArchiv mit mehreren Instanzdokumenten mit uneindeutigen Bereichs-Nummern
- Verbesserung der Fehlermeldung beim Import eines XPlanArchiv mit mehreren Instanzdokumenten und Referenzierung über verbundenerPlan@xlink:href
- Verbessern der Fehlermeldung beim Editieren eines Plans ohne Bereich
- Unterstützung von XPlanGML 3.0 aus allen Komponenten entfernt
- Konfigurationsparameter defaultBboxIn4326 entfernt
- Hinzufügen einer Tabelle planslog in der XPlanDB
- Aktualisierung auf deegree 3.5
- Aktualisierung auf JTS 1.19.0

==== Fehlerbehebungen
- Fehler bei der Veröffentlichung von Bebauungsplänen als INSPIRE PLU behoben
- Fehler beim Editieren der Rasterbasis (XPlanGML 4.1) behoben
- Fehler in der XPlanWFS ListStoredQueries Antwort behoben
- Fehler beim wiederholten Import eines Plans mit mehreren Instanzen behoben
- Fehlerbehandlung für Anfrage von nicht vorhandenen Ressource über XPlanManagerAPI verbessert
- Fehlende Zeichenvorschriften ergänzt
- Fehler in der Flächenschlussprüfung für Änderungspläne und bei vollständiger Überlappung behoben

Die vollständige Änderungshistorie ist auf der https://gitlab.opencode.de/diplanung/ozgxplanung/[OpenCoDE-Plattform] zu finden.