== Ausblick
=== Empfehlungen für die Bereitstellung von XPlanungsdaten

Die Leitstelle XPlanung/XBau hat einen https://www.xleitstelle.de/leitfaden[Leitfaden XPlanung] herausgegeben, der sich an die Träger von Planverfahren, Planer in der öffentlichen Verwaltung als auch in Planungs- und Ingenieurbüros wendet, die mit der konkreten technischen Umsetzung von XPlanung bzw. der Erstellung von Planwerken gemäß dem Standard XPlanung beauftragt sind. Der Leitfaden bietet Unterstützung in der effektiven Umsetzung von XPlanung und der standardkonformen Erstellung und Bereitstellung von XPlanungsdaten von hoher Qualität.

=== Einbindung in andere Software

Zur Betrachtung der über den XPlanManager importierten Planwerke bietet sich die Einbindung des <<xplanwms,XPlanWMS oder XPlanWerkWMS>> in einen geeigneten Client an. Da es sich bei beiden Diensten jeweils um einen standardkonformen WMS handelt, kann jeder Client verwendet werden, der diese Schnittstelle in den Versionen 1.1.1 und 1.3.0 unterstützt.
Der Zugriff auf die XPlanGML-Daten ist über den XPlanSynWFS oder die versionsspezifischen <<xplanwfs,XPlanWFS-Dienste>> möglich.

TIP: Als Desktop-Client wird https://qgis.org/[QGIS] empfohlen. Als WebGIS-Client wird das https://www.masterportal.org[Masterportal] empfohlen. Detaillierte Informationen zur Installation, Konfiguration und Benutzung finden sich in der Dokumentation der jeweiligen Software.
