:doctype: book
:encoding: utf-8
:docinfo: shared,private-head
:toc-title: Inhaltsverzeichnis


= Benutzerhandbuch für den XPlanValidator


== Einleitung
include::XPlanValidator-Einleitung.adoc[]

include::XPlanValidator_Web.adoc[leveloffset=-2]


[[lizenz-des-dokuments]]
== Lizenz des Dokuments

Es wird die Erlaubnis gewährt, dieses Dokument zu kopieren, zu verteilen
und/oder zu modifizieren, unter den Bestimmungen der GNU Free
Documentation License, Version 1.3 oder jeder späteren Version,
veröffentlicht von der Free Software Foundation; ohne unveränderliche
Abschnitte, ohne vordere Umschlagtexte und ohne hintere Umschlagtexte.
Die Lizenz wird unter http://www.gnu.org/licenses/fdl-1.3
bereitgestellt.

[[autoren]]
== Autoren

Danilo Bretschneider, Jens Fitzke, Torsten Friebe, Sebastian Goerke, Lyn Elisa Goltz,
Lena Rippolz, Sabine Schmitz, Dirk Stenger, Carmen Tawalika, Jeronimo Wanhoff.

Copyright (C) 2010 - 2020, lat/lon GmbH

== Kontakt

Mehr Informationen zur xPlanBox erhalten Sie bei http://www.lat-lon.de[lat/lon GmbH, Bonn], E-mail
info@lat-lon.de.

== Lizenzen und Anerkennung der Rechte Dritter

Zum Lieferumfang der xPlanBox gehören Bibliotheken und andere Softwareprogrammen von Drittanbietern. Dabei handelt es sich um Open-Source Software, die im Rahmen der Bestimmungen der

- Apache Software License, Version 2.0
- Bouncy Castle Licence
- BSD License
- Eclipse Public License, Version 1.0
- GNU Library/Lesser General Public License (LGPL), Version 2.1
- Google Web Toolkit Terms
- H2 License, Version 1.0
- MIT License
- Mozilla Public License, Version 1.1
- Mozilla Public License, Version 2.0

lizenziert wird.
