[[ueberblick]]
== Überblick


Die xPlanBox dient der Abbildung der Bauleit- und der
Landschaftsplanung. Die xPlanBox basiert auf den Standards des
http://www.opengeospatial.org[Open Geospatial Consortium], der
http://inspire.ec.europa.eu[INSPIRE Richtlinie] und insbesondere dem
Standard http://www.xplanung.de[XPlanung] zur Abbildung des deutschen
Planungsrechts durch ein GML-Anwendungsschema.

Zur Implementierung der Komponenten der xPlanBox wurde die Open Source
Software http://www.deegree.org[deegree] eingesetzt, das ein
Projekt der OSGeo Foundation ist. Die xPlanBox besteht aus den
folgenden Komponenten:

 * <<xplanvalidator,XPlanValidator>>: Komponente zur Validierung von Daten des Standards XPlanung
 * <<xplanmanager,XPlanManager>>: Komponente zur Verwaltung von Daten des Standards XPlanung
 * <<xplanwms,XPlanWMS>>: Standard-Kartendienst (WMS) für die Auskunft
 * <<xplanwfs,XPlanWFS>>: Standard-Datendienst (WFS) für die Auskunft (XPlanGML-konforme Datenstruktur)
 * <<xplansynwfs,XPlanSynWFS>>: Standard-Datendienst (WFS) für die Auskunft (vereinfachte Datenstruktur)
 * <<xplandokumente-api,XPlanDokumenteAPI>>: Optionale Komponente für den Zugriff auf Dokumente aus einem <<xplanarchiv, XPlanArchiv>>
 * <<xplaninspirepluwms,XPlanInspirePluWMS>>: Optionale Komponente mit INSPIRE View Service für die Auskunft im INSPIRE Datenthema Planned Land Use (PLU)
 * <<xplaninspirepluwfs,XPlanInspirePluWFS>>: Optionale Komponente mit INSPIRE Download Service für die Auskunft im INSPIRE Datenthema Planned Land Use (PLU)

Aktuell werden für Bebauungspläne, Flächennutzungspläne, Landschaftspläne und Raumordnungspläne die XPlanGML-Versionen 4.0, 4.1, 5.0, 5.1, 5.2, 5.3, 5.4 und 6.0 durch die xPlanBox unterstützt.
Für sonstige raumbezogene Planwerke werden die XPlanGML-Versionen 5.0, 5.1, 5.2, 5.3, 5.4 und 6.0 unterstützt.

Die Komponenten der xPlanBox werden in diesem Benutzerhandbuch im
Einzelnen erläutert.
