[[xplanwms]]
== XPlanWMS, XPlanArtWMS und XPlanWerkWMS

Der XPlanWMS, XPlanArtWMS und XPlanWerkWMS basieren auf der Open Source Software http://www.deegree.org[deegree] und sind zu dem Standard Web Map Service (Version 1.1.1 und 1.3.0) des Open Geospatial Consortium (OGC) konforme Kartendienste. Diese bieten die Möglichkeit Visualisierungen von Plandaten sowie Sachinformationsabfragen zu einzelnen Planinhalten abzufragen.

[[xplanwms-inhalte-des-kartendienstes]]
=== Inhalte des Kartendienstes

Der XPlanWMS dient der Darstellung aller importierten XPlanArchive, während der XPlanWerkWMS einzelne Planwerke visualisiert. Die Datenquelle beider Dienste basiert auf den über den XPlanManager importierten Planwerken. Für jede Objektart aus den unterstützten XPlanGML-Applikationsschema, das Geometrie-Attribute enthält, existiert eine entsprechende Ebene im XPlanWMS und XPlanWerkWMS. Zusätzlich zu den aus dem XPlanGML abgeleiteten Ebenen stellen beide Dienste Ebenen zur Darstellung von gescannten Rasterplan-Dateien bereit.

Während der XPlanWMS die Inhalte planübergreifend dargestellt, visualisiert der XPlanWerkWMS genau ein einzelnes Planwerk. Der XPlanWMS stellt genau einen Endpunkt mit allen Planwerken bereit, der XPlanWerkWMS je einen Endpunkt pro importiertem Plan. Der XPlanArtWMS stellt je einen Endpunkt für jede Planart wie z. B. BPlan oder FPlan zur Verfügung.

[[xplanwms-benutzung-des-xplanwms]]
=== Benutzung des XPlanWMS und XPlanWerkWMS

Mit dem XPlanWMS und XPlanWerkWMS ist ein Benutzer in der Lage, WMS-Ebenen (Layer) mit einem Browser oder einem GIS anzufragen.
Die folgende Tabelle gibt einen Überblick über die zur Verfügung stehenden Operationen des WMS, die in den weiteren Kapiteln näher erläutert werden.

[width="95%",cols="29%,71%",options="header",]
|===============================================================
|WMS Operation |Inhalt
|GetCapabilities |Abfrage der Fähigkeiten des Dienstes
|GetMap |Abfrage von Kartenbildern zu WMS Ebenen
|GetFeatureInfo |Abfrage von Sachinformationen einzelner Objekte
|GetLegendGraphic |Abfrage von Legendengrafiken einzelner Ebenen
|GetAttachment |Abfrage von Anhängen aus dem XPlanArchiv
|===============================================================

[[xplanwms-adresse-des-dienstes]]
==== Adresse des XPlanWMS

----
http://<host>:<port>/xplan-services-wms/services/wms?
----

[[xplanwms-adresse-xplanwerkwms]]
==== Adresse des XPlanWerkWMS

Die Adresse des XPlanWerkWMS ist abhängig von dem Planwerk das angefragt werden soll. Der Name des Plans wird im XPlanManager (s. <<xplanmanager-web>>) in der Auflistung der Pläne angezeigt und in der URL für den Platzhalter <PLANNAME> angegeben. Der Planname wird aus dem XPlanGML-Element `xplan:name` abgeleitet. Dabei werden Sonderzeichen wie `/` entfernt und der Planname für die Erstellung der URL des XPlanWerkWMS kodiert (weitere Informationen zu URL Syntax und Zeichenkodierung in https://datatracker.ietf.org/doc/html/rfc3986[RFC 3986 – Uniform Resource Identifier (URI)]).

Die vollständige XPlanWerkWMS URL kann über die Kartenvorschau im XPlanManagerWeb abgerufen werden.

IMPORTANT: Vermeiden Sie Sonderzeichen im Plannamen wie z. B. `:`, `&`, `#` , `/`, `\`, `?`, `@`, `'`, `"` oder Zeilenumbrüche.

----
http://<host>:<port>/xplan-services-wms/services/planwerkwms/planname/<PLANNAME>
----

TIP: Alternativ kann die URL auch ohne Sonderzeichen verwendet werden. Dafür müssen alle anderen Zeichen als `a-zA-Z0-9-_` aus <PLANNAME> entfernt werden. Die so erstellte URL liefert eine identische Response wie die dazugehörige, kodierte URL.

[[xplanwms-adresse-xplanartwms]]
==== Adresse des XPlanArtWMS

Die Adresse des XPlanWerkWMS ist abhängig von der Planart die angefragt werden soll.
Neben der Planart ist auch der Planstatus bei der Nutzung des XPlanArtWMS entscheidend, so setzt sich der Name nach folgendem Schema zusammen _XPlanArtWMS<PLANART><PLANSTATUS>_, z.B. _XPlanArtWMSBPlanArchive_. Die URL des WMS ist wie folgt aufgebaut:

----
http://<host>:<port>/xplan-services-wms/services/<PLANART>wms<PLANSTATUS>?
----

Die folgende Tabelle listet die Endpunkte des XPlanArtWMS auf:

[width="100%",cols="30%,10%,10%,50%",options="header"]
|===
|XPlanArtWMS
|Planart
|Planstatus
|URL
|XPlanArtWMSBPlan
|BPlan
|Festgestellt
|http://<host>:<port>/xplan-services-wms/services/bpwms?
|XPlanArtWMSBPlanPre
|BPlan
|In Aufstellung
|http://<host>:<port>/xplan-services-wms/services/bpwmspre?
|XPlanArtWMSBPlanArchive
|BPlan
|Archiviert
|http://<host>:<port>/xplan-services-wms/services/bpwmsarchive?
|XPlanArtWMSFPlan
|FPlan
|Festgestellt
|http://<host>:<port>/xplan-services-wms/services/fpwms?
|XPlanArtWMSFPlanPre
|FPlan
|In Aufstellung
|http://<host>:<port>/xplan-services-wms/services/fpwmspre?
|XPlanArtWMSFPlanArchive
|FPlan
|Archiviert
|http://<host>:<port>/xplan-services-wms/services/fpwmsarchive?
|XPlanArtWMSLPlan
|LPlan
|Festgestellt
|http://<host>:<port>/xplan-services-wms/services/lpwms?
|XPlanArtWMSLPlanPre
|LPlan
|In Aufstellung
|http://<host>:<port>/xplan-services-wms/services/lpwmspre?
|XPlanArtWMSLPlanArchive
|LPlan
|Archiviert
|http://<host>:<port>/xplan-services-wms/services/lpwmsarchive?
|XPlanArtWMSRPlan
|RPlan
|Festgestellt
|http://<host>:<port>/xplan-services-wms/services/rpwms?
|XPlanArtWMSRPlanPre
|RPlan
|In Aufstellung
|http://<host>:<port>/xplan-services-wms/services/rlpwmspre?
|XPlanArtWMSRPlanArchive
|RPlan
|Archiviert
|http://<host>:<port>/xplan-services-wms/services/rpwmsarchive?
|XPlanArtWMSSOPlan
|SOPlan
|Festgestellt
|http://<host>:<port>/xplan-services-wms/services/sowms?
|XPlanArtWMSSOPlanPre
|SOPlan
|In Aufstellung
|http://<host>:<port>/xplan-services-wms/services/sowmspre?
|XPlanArtWMSSOPlanArchive
|SOPlan
|Archiviert
|http://<host>:<port>/xplan-services-wms/services/sowmsarchive?
|===


[[xplanwms-operationen]]
=== Operationen

Das folgende Kapitel beschreibt die Operationen, die mit dem XPlanWMS und XPlanWerkWMS durchführbar sind.

[[xplanwms-getcapabilities]]
==== GetCapabilities

Die GetCapabilities Abfrage dient der Auskunft über die Fähigkeiten des
WMS Dienstes. Dabei handelt es sich beispielsweise um Informationen zum
Dienstbetreiber, zu den unterstützten Operationen sowie zu den durch den
WMS angebotenen WMS Ebenen.

*XPlanWMS*
----
http://<host>:<port>/xplan-services-wms/services/wms?request=GetCapabilities&service=WMS&version=1.1.1
http://<host>:<port>/xplan-services-wms/services/wms?request=GetCapabilities&service=WMS&version=1.3.0
----

*XPlanWerkWMS*
----
http://<host>:<port>/xplan-services-wms/services/planwerkwms/planname/<PLANNAME>?request=GetCapabilities&service=WMS&version=1.1.1
http://<host>:<port>/xplan-services-wms/services/planwerkwms/planname/<PLANNAME>?request=GetCapabilities&service=WMS&version=1.3.0
----

*XPlanArtWMS*
----
http://<host>:<port>/xplan-services-wms/services/<PLANART>wms<PLANSTATUS>?request=GetCapabilities&service=WMS&version=1.1.1
http://<host>:<port>/xplan-services-wms/services/<PLANART>wms<PLANSTATUS>?request=GetCapabilities&service=WMS&version=1.3.0
----

[[xplanwms-getmap]]
==== GetMap

Die Operation GetMap stellt die Kernfunktionalität des XPlanWMS dar. Die
Operation ermöglicht es, die angebotenen Ebene zu den Planinhalten mit
GIS Clients zu nutzen, die die Schnittstellen WMS 1.1.1 bzw. WMS 1.3.0
unterstützen.

*XPlanWMS*
----
http://<host>:<port>/xplan-services-wms/services/wms?request=GetMap&Service=WMS&Version=1.1.1&Layers=bp_plan&Format=image/png&Transparent=true&Styles=&Srs=EPSG%3A25833&Bbox=377814.52931834,5697447.998419,381059.6791237,5698548.3070248&Width=1280&Height=434
http://<host>:<port>/xplan-services-wms/services/wms?request=GetMap&Service=WMS&Version=1.3.0&Layers=bp_plan&Format=image/png&Transparent=true&Styles=&Crs=EPSG%3A25833&Bbox=377814.52931834,5697447.998419,381059.6791237,5698548.3070248&Width=1280&Height=434
----

*XPlanWerkWMS*
----
http://<host>:<port>/xplan-services-wms/services/planwerkwms/planname/<PLANNAME>?request=GetMap&Service=WMS&Version=1.1.1&Layers=bp_plan&Format=image/png&Transparent=true&Styles=&Srs=EPSG%3A25833&Bbox=377814.52931834,5697447.998419,381059.6791237,5698548.3070248&Width=1280&Height=434
http://<host>:<port>/xplan-services-wms/services/planwerkwms/planname/<PLANNAME>?request=GetMap&Service=WMS&Version=1.3.0&Layers=bp_plan&Format=image/png&Transparent=true&Styles=&Crs=EPSG%3A25833&Bbox=377814.52931834,5697447.998419,381059.6791237,5698548.3070248&Width=1280&Height=434
----

[[xplanwms-styles]]
===== Styles

Bei der GetMap-Operation gibt es die Möglichkeit zwischen zwei
verschieden Styles zu wechseln, die die Darstellung der Inhalte des
Kartendienstes beeinflussen. Dabei liegen alle Zeichenvorschriften
(Styles) für alle Ebenen des XPlanWMS in transparenter und in
vollflächiger Form vor. Bei GetMap-Operationen kann mittels des
Style-Parameters zwischen beiden Darstellungen gewechselt werden. Im
XPlanWMS ist als Default-Style die vollflächige Darstellung
eingestellt, im XPlanWMSInAufstellung und im XPlanWMSArchiviert hingegen die
transparente. Wenn der transparente Style ausgewählt wird, sind
lediglich die Planumringe sichtbar.

[width="100%",cols="25%,25%,20%,25%,5%",options="header"]
|===
|Endpoint
|Planstatus
|Default-Style
|Dargestellte Planzeichen
|GFI
|XPlanWMSInAufstellung
|In Aufstellung
|`transparent`
|nur Planumring
|GFI
|XPlanWMSFestgestellt
|Festgestellt
|`vollflaechig`
|alle Planzeichen
|GFI
|XPlanWMSArchiviert
|Archiviert
|`transparent`
|nur Planumring
|GFI
|===

[[xplanwms-gueltigkeitszeitraum]]
===== Gültigkeitszeitraum

Der Gültigkeitszeitraum bestimmt die Sichtbarkeit der Inhalte eines Plans bei Aufruf des XPlanWMSInAufstellung über die GetMap-Operation. Der Gültigkeitszeitraum eines Plans kann beim Import über den XPlanManagerWeb als Zeitspanne angegeben werden.
Wird der XPlanWMSInAufstellung innerhalb des gewählten Zeitraums angefragt, so werden die Plandaten, sowohl Vektor- als auch Rasterdaten, angezeigt. Liegt der Zeitpunkt der GetMap-Anfrage an den XPlanWMSInAufstellung ausserhalb des Zeitraums, so werden keine Plandaten angezeigt.

NOTE: Ausnahme: Die Sichtbarkeit der Layer, die den Geltungsbereich darstellen, werden nicht über den Gültigkeitszeitraum verändert und werden immer angezeigt.

IMPORTANT: Die Möglichkeit einen Gültigkeitszeitraum anzugeben ist veraltet und wird in zukünftigen Versionen der xPlanBox entfernt.

[[xplanwms-getfeatureinfo]]
==== GetFeatureInfo

Die Operation GetFeatureInfo ermöglicht die Ausgabe von
Sachinformationen zu Planobjekten. In der HTML-Ausgabe dieser
Sachinformationen besteht neben der Ausgabe der entsprechenden
Eigenschaften der Planobjekte auch die Möglichkeit, referenzierte
Dokumente und Grafiken über die Operation <<xplanwms-getattachement>> abzurufen.

*XPlanWMS*
----
http://<host>:<port>/xplan-services-wms/services/wms?request=GetFeatureInfo&Service=WMS&Version=1.3.0&Width=460&Height=348&Layers=fp_bebausfl&Transparent=TRUE&Format=image%2Fpng&BBox=381754.08781343646,5716831.670553746,382351.0673120646,5717283.298522273&Crs=EPSG:25833&Styles=&Query_layers=fp_bebausfl&I=217&J=94&Feature_count=10&Info_format=text/html
http://<host>:<port>/xplan-services-wms/services/wms?request=GetFeatureInfo&Service=WMS&Version=1.3.0&Width=460&Height=348&Layers=fp_bebausfl&Transparent=TRUE&Format=image%2Fpng&BBox=381754.08781343646,5716831.670553746,382351.0673120646,5717283.298522273&Crs=EPSG:25833&Styles=&Query_layers=fp_bebausfl&I=217&J=94&Feature_count=10&info_format=application/vnd.ogc.gml
----

*XPlanWerkWMS*
----
http://<host>:<port>/xplan-services-wms/services/planwerkwms/planname/<PLANNAME>?request=GetFeatureInfo&Service=WMS&Version=1.3.0&Width=460&Height=348&Layers=fp_bebausfl&Transparent=TRUE&Format=image%2Fpng&BBox=381754.08781343646,5716831.670553746,382351.0673120646,5717283.298522273&Crs=EPSG:25833&Styles=&Query_layers=fp_bebausfl&I=217&J=94&Feature_count=10&Info_format=text/html
http://<host>:<port>/xplan-services-wms/services/planwerkwms/planname/<PLANNAME>?request=GetFeatureInfo&Service=WMS&Version=1.3.0&Width=460&Height=348&Layers=fp_bebausfl&Transparent=TRUE&Format=image%2Fpng&BBox=381754.08781343646,5716831.670553746,382351.0673120646,5717283.298522273&Crs=EPSG:25833&Styles=&Query_layers=fp_bebausfl&I=217&J=94&Feature_count=10&info_format=application/vnd.ogc.gml
----

[[xplanwms-getlegendgraphic]]
==== GetLegendGraphic

Mit der GetLegendGraphic Operation können Legendengrafiken zu allen
Ebenen des XPlanWMS abgefragt werden. Dies ermöglicht das gezielte
Abfragen von Legendengrafiken der Ebenen.

*XPlanWMS*
----
http://<host>:<port>/xplan-services-wms/services/wms?request=GetLegendGraphic&Service=WMS&Version=1.1.1&layer=bp_gruenfl&format=image/png
http://<host>:<port>/xplan-services-wms/services/wms?request=GetLegendGraphic&Service=WMS&Version=1.3.0&layer=bp_gruenfl&format=image/png
----

*XPlanWerkWMS*
----
http://<host>:<port>/xplan-services-wms/services/planwerkwms/planname/<PLANNAME>?request=GetLegendGraphic&Service=WMS&Version=1.1.1&layer=bp_gruenfl&format=image/png
http://<host>:<port>/xplan-services-wms/services/planwerkwms/planname/<PLANNAME>?request=GetLegendGraphic&Service=WMS&Version=1.3.0&layer=bp_gruenfl&format=image/png
----

[[xplanwms-getattachement]]
==== GetAttachment

Die beiden WMS-Dienste der xPlanBox unterstützen zusätzlich die Operation GetAttachment. Diese spezielle Erweiterung
der Schnittstelle erlaubt den Zugriff auf die im XPlanGML referenzierten Anhänge.

Die Operation unterstützt folgende Parameter:

* featureID: Die GML-ID eines Features im XPlanWMS (u.a. abrufbar über GetFeatureInfo), z.B. XPLAN_XP_RASTERPLANBASIS_7b36b0ee-5139-4a55-afc0-01fec18e9f0a
* filename: Der Dateiname der referenzierten Datei, z.B. Stellingen64.png

*XPlanWMS*
----
http://<host>:<port>/xplan-services-wms/getAttachment?featureID=XPLAN_XP_RASTERPLANBASIS_7b36b0ee-5139-4a55-afc0-01fec18e9f0a&filename=Stellingen64.png
----

[[xplanwms-koordinatenreferenzsysteme]]
=== Koordinatenreferenzsysteme

Der XPlanWMS und XPlanWerkWMS unterstützt die folgenden Koordinatenreferenzsysteme für Vektordaten:

* EPSG:25832
* EPSG:25833
* EPSG:325833
* EPSG:31466
* EPSG:31467
* EPSG:31468
* EPSG:31469
* EPSG:4258
* EPSG:4326
* EPSG:4839
* CRS:84

Für Rasterdaten wird dagegen nur eines dieser Koordinatenreferenzsysteme unterstützt. Der Vorgabewert ist EPSG:25832 und kann über die Konfiguration der xPlanBox geändert werden. Die Konfiguration ist im Betriebshandbuch der xPlanBox beschrieben. Weitere Informationen zu den Anforderungen an die Rasterdaten stehen im Kapitel <<voraussetzungen-fuer-die-rasterdaten>>.
