[[xplanmanager-web]]
=== XPlanManagerWeb

Die Komponente XPlanManagerWeb ist eine Web-Oberfläche, die dem
Fachadministrator der xPlanBox ermöglicht, die Datenhaltung zu
kontrollieren und zu verwalten. Mit dem XPlanManagerWeb kann der Benutzer ein XPlanGML
Instanzdokumente in die Datenhaltung laden, editieren, löschen sowie
bereits importiere XPlanArchive in einer Liste anzeigen.

[[xplanmanager-web-benutzungsanleitung]]
==== Benutzungsanleitung

Die Webanwendung XPlanManagerWeb dient der Verwaltung von XPlanGML
konformen Plänen und ist unter:

----
http://<host>:<port>/xplan-manager/
----

verfügbar und kann mit einem gängigen Web-Browser aufgerufen werden.

[[xplanmanager-web-hilfe]]
===== Hilfe

Die Hilfe mit den Angaben zu den möglichen Funktionen lässt sich durch
Betätigen des Buttons _Hilfe_ ausgeben.

[[xplanmanager-web-hinzufuegen]]
===== Hinzufügen

Vor dem Importieren eines XPlanGML Instanzdokumentes in die Datenbasis,
muss dieser über die Web-Oberfläche hochgeladen werden. Hierfür kann der Plan
über den Button _Durchsuchen_ ausgewählt und durch einen Klick auf
_Import_ hochgeladen werden. Der Benutzer wird
über das erfolgreiche bzw. fehlerhafte Hinzufügen des Plans in Form
eines PopUps informiert.

Nachdem der Plan hochgeladen wurde, kann dieser
validiert bzw. entfernt werden. Erst nachdem der Plan erfolgreich
validiert wurde, kann der Plan in die Datenbasis importiert werden.
Andernfalls ist der Button _Import_ deaktiviert.

[[xplanmanager-web-import]]
===== Import

Nachdem der Plan erfolgreich validiert wurde, kann der Plan durch einen
Klick auf den Button _Import_ in die Datenbasis importiert werden. Der
Benutzer wird über den erfolgreichen bzw. fehlerhaften Import des Plans
in Form eines PopUps informiert.

[[xplanmanager-web-auflistung]]
===== Auflistung

Standardmäßig werden alle importierten Pläne in einer Liste angezeigt.
Diese Liste kann nach dem __Namen__, der __ID__, dem __Plantyp__, der
__sonstige Planart__, dem __Rechtsstand__, dem
__Veröffentlichungsdatum__, dem _Importdatum_ oder nach dem _Planstatus_
auf- oder absteigend sortiert werden.

[[xplanmanager-web-kartenvorschau]]
===== Kartenvorschau

Durch den Klick auf den Button _Kartenvorschau_ öffnet sich ein neues
Fenster, indem der XPlan visualisiert wird. Im Hintergrund befindet sich
eine Hintergrundkarte. Durch den Klick auf _Schließen_ wird die
Kartenvorschau wieder geschlossen.

[[xplanmanager-web-herunterladen]]
===== Herunterladen

Die importierten Pläne können vom Benutzer durch den Klick auf den
Button _Herunterladen_ wieder als XPlanArchiv heruntergeladen werden.

[[loeschen]]
===== Löschen

Je nach Benutzerrechten können die importierten Pläne durch den Klick
auf den Button _Löschen_ aus der Datenbasis gelöscht werden. Hat ein
Benutzer keine Rechte, so wird der Button grau dargestellt.

[[xplanmanager-web-editieren]]
===== Editieren

Abhängig von den Benutzerrechten können Pläne editiert werden. Fehlen dem Benutzer
die entsprechenden Rechte ist die Funktion deaktiviert und der Button __Editieren__ wird grau dargestellt. 
Die Editieransicht öffnet sich durch den Klick auf den Button __Editieren__. Die Ansicht ist in verschiedene Bereiche
aufgeteilt, die insgesamt die Bearbeitung folgender Elemente zulässt:

*Basisdaten*

* name
* beschreibung
* technHerstellDatum
* untergangsDatum
* planArt
* sonstPlanArt
* verfahren
* rechtsstand
* rechtsverordnungsDatum

Das Editieren des Rechtsstands kann dazu führen, dass eine
Zustandsänderung des Plans eintritt. Damit verbunden ist das Verschieben
der Vektor- und Rasterdaten in die entsprechende Datenhaltung. Übergänge
sind beliebig zwischen den drei Zuständen 'Festgestellt', 'In
Aufstellung' und 'Archiviert' möglich. Eine Zustandsänderung von
'Festgestellt' nach 'In Aufstellung' tritt beispielsweise beim Ändern
des Rechtsstands von 'InkraftGetreten' nach 'Untergegangen' ein.

NOTE: __Achtung__: Beim Import kann der Nutzer den Zustand eines Planes über eine
Auswahlliste mit den Optionen 'Festgestellt', 'In Aufstellung' und
'Archiviert' ändern. Abhängig von dem im Plan gesetzten Rechtsstand wird
eine Vorauswahl getroffen, die der Nutzer aber überschreiben kann. Beim
Öffnen der Editieransicht wird der Rechtsstand aus dem Plan
berücksichtigt, der vom Nutzer ausgewählte Zustand bleibt dagegen
unberücksichtigt. Somit entspricht die Auswahl des Rechtsstands nicht
dem Zustand des Plans, falls dieser beim Import manipuliert wurde. Beim
Abspeichern eines Editiervorgangs ist hier somit Vorsicht geboten, da so
unbeabsichtigt eine Zustandsänderung vorgenommen werden kann!

*Gültigkeitszeitraum*

* Der Zeitraum in dem ein Plan gültig ist. Für dieses Feld gibt es keine
Entsprechung im XPlanGML. Die Einschränkung, wie sie beim Import
erfolgt ist, wird überschrieben.

*Änderungen*

* aendert
* wurdeGeaendertVon

*Texte*

* texte

*Referenzen*

* refBegruendung
* refRechtsplan
* refGruenordnungsplan

*Rasterbasis*

* rasterbasis

*Änderungen von Rasterplänen*

* rasterAenderung

Werden Referenzen entfernt oder verändert, so werden die nicht mehr
referenzierten Dateien aus der Datenhaltung entfernt. In den Bereichen
'Rasterbasis' und 'Änderungen von Rasterplänen' kann lediglich ein
Austausch bereits referenzierter Dateien erfolgen. Änderungen führen zu
einer Aktualisierung der XPlanWMS-Konfiguration. Klickt der Nutzer auf
__Speichern__, wird zunächst eine Validierung der Rasterdaten
vorgenommen. Bei invaliden Dateien bekommt der Nutzer eine
Entscheidungsoption wie mit diesen Daten umgegangen werden soll.
Anschließend erfolgt die Aktualisierung der Daten.


NOTE: Die Editierfunktion steht nur für BPläne in den XPlanGML Versionen
3.0, 4.1, 5.0 und 5.1 zur Verfügung.


[[xplanmanager-web-inspireplu]]
===== Bereitstellung als INSPIRE PLU Datensatz

Abhängig von den Benutzerrechten können Pläne im Datenthema INSPIRE Planned Land Use veröffentlicht werden. Fehlen dem Benutzer die entsprechenden Rechte ist die Funktion deaktiviert und der Button __Bereitstellung als INSPIRE Datensatz__ wird nicht dargestellt.

Durch Klick auf den Button __Bereitstellung als INSPIRE Datensatz__ wird der Plan in das INSPIRE PLU Datenschema überführt und in den INSPIRE konformen Download Service importiert. Anschließend kann der transformierte Plan über den INSPIRE Download Service (XPlanInspirePluWFS) und INSPIRE View Service (XPlanInspirePluWMS) abgerufen werden.

NOTE: Die Bereitstellung als INSPIRE PLU Datensatz steht nur für BPläne in den XPlanGML Versionen 4.1, 5.0 und 5.1 zur Verfügung.