[[xplanvalidator-cli]]
=== XPlanValidatorCLI

Analog zum XPlanManagerWeb können XPlanGML-Dokumente mit der Komponente XPlanValidatorCLI über ein Kommandozeilenwerkzeug validiert werden.

[[xplanvalidator-cli-benutzungsanleitung]]
==== Benutzungsanleitung

Beim XPlanValidatorCLI handelt es sich um ein Kommandozeilentool, das
parametrisiert aufgerufen wird. Da diese Anwendung bei der Installation
in die PATH Variable aufgenommen wird, ist diese von einem beliebigen
Ort aufrufbar.

[[xplanvalidator-cli-konfiguration-ueber-datei]]
===== Konfiguration über Datei

In dem Verzeichnis _<validator-cli-directory>/etc/_ befindet sich die
Konfigurationsdatei __validatorConfiguration.properties__, welche
genutzt werden kann, um generelle Konfigurationen an dem
Kommandozeilentool durchzuführen.

Über _validationReportDirectory=<directory>_ kann konfiguriert werden,
wo die Reports mit dem Validierungsergebnis, die während der Ausführung
des Tools generiert werden, abgespeichert werden sollen.

Mit der Option _validationRulesDirectory=<directory>_ kann konfiguriert
werden, in welchem Verzeichnis die semantischen Validierungsregeln liegen,
die für die Validierung verwendet werden sollen. Erfolgt keine Angabe
werden die unter  _<validator-cli-directory>/etc/rules_ liegenden
semantischen Validierungsregeln verwendet.

[[xplanvalidator-cli-hilfe]]
===== Hilfe

Die Hilfe mit den Angaben zu den möglichen Eingabeparametern lässt sich
mit dem Parameter `help` ausgeben.

Aufruf:

----
XPlanValidator -help
----

Ausgabe:

----
usage: XPlanValidator [-name <arg>] -validate <arg> [-vo <arg>] [-vtype
       <arg>] [-xq <arg>]

   -name <arg>         name of the validation
   -validate <arg>     zip file path
   -vo <arg>           validation options
   -vtype <arg>        values: syntax, geometric, semantic. multiple types must
                       be comma separated
----

[[xplanvalidator-cli-auswahl-planarchiv]]
===== Auswahl XPlanArchiv

Über den Parameter `validate <planarchiv>` kann der Pfad zum XPlanArchiv
 auswählt werden, welcher validiert werden soll. Die Angabe
des Parameters ist obligatorisch.

Aufruf:

----
XPlanValidator -validate Plan.zip
----

[[xplanvalidator-cli-bezeichnung-der-validierung]]
===== Bezeichnung für den Report

Über den Parameter `name <bezeichnung>` kann eine Bezeichnung für den generierten
Report vergeben werden. Die Angabe des Parameters `-name` ist optional.
Fehlt dieser Parameter, wird der Name des XPlanArchivs verwendet.

Aufruf:

----
XPlanValidator -validate Plan.zip -name Validierung
----

[[xplanvalidator-cli-validierungsart]]
===== Validierungsart

Die Kommandozeilenschnittstelle des XPlanValidator kann zur Auswahl der
Validierungsart parametrisiert aufgerufen werden. Die Angabe des
Parameters `-vtype` ist optional.

Aufruf:

----
XPlanValidator -validate Plan.zip -vtype [syntax|geometric|semantic]
----

Zuordnung der Werte:

* syntax = Syntaktisch
* geometric = Geometrisch
* semantic = Semantisch

Wird kein `vtype` Parameter gewählt, werden alle Validierungsarten durchgeführt.

Ausgabe:

----
[16:13:34]  INFO: [CRSManager] --------------------------------------------------------------------------------
[16:13:34]  INFO: [CRSManager] No 'crs' directory -- use default configuration.
[16:13:34]  INFO: [CRSManager] --------------------------------------------------------------------------------
[16:13:34]  INFO: [CRSManager] Setting up crs store 'default' from file 'file:/home/xplanbox/install-packages/1.0-RC2/workspace/cli/xplan-validator-cli-1.0-RC2/repo/deegree-core-cs-3.2.5.jar!/org/deegree/cs/persistence/default.xml'...
[16:13:36]  INFO: [CRSManager] Registering global crs store with id 'default', type: 'org.deegree.cs.persistence.deegree.d3.DeegreeCRSStore'
- Einlesen der Features (+ Geometrievalidierung)...Fehler.

Geometrie-Warnungen: 6
 - Polygon (Zeile 30, Spalte 7): Äußerer Ring verwendet falsche Laufrichtung (CW).
 - Polygon (Zeile 55, Spalte 7): Äußerer Ring verwendet falsche Laufrichtung (CW).
 - Polygon (Zeile 1031, Spalte 5): Äußerer Ring verwendet falsche Laufrichtung (CW).
 - Polygon (Zeile 1054, Spalte 5): Äußerer Ring verwendet falsche Laufrichtung (CW).
 - Polygon (Zeile 1077, Spalte 5): Äußerer Ring verwendet falsche Laufrichtung (CW).
 - Polygon (Zeile 1100, Spalte 5): Äußerer Ring verwendet falsche Laufrichtung (CW).

Geometrie-Fehler: 5
 - Polygon (Zeile 55, Spalte 7): Äußerer Ring schneidet den inneren Ring mit Index 0.
 - Polygon (Zeile 55, Spalte 7): Innerer Ring mit Index 0 befindet sich nicht innerhalb des äußeren Rings.
 - Polygon (Zeile 55, Spalte 7): Äußerer Ring schneidet den inneren Ring mit Index 1.
 - Polygon (Zeile 55, Spalte 7): Innerer Ring mit Index 1 befindet sich nicht innerhalb des äußeren Rings.
 - Polygon (Zeile 55, Spalte 7): Der innere Ring 0 schneidet den inneren Ring mit Index 1.
Fortsetzung trotz Geometrie-Fehlern (--force).
- Überprüfung der XLink-Integrität...OK [1 ms]
----

[[xplanvalidator-cli-validierungsoption]]
===== Validierungsoption

Die Kommandozeilenschnittstelle des XPlanValidator kann zur Auswahl von
zusätzlichen Validierungsoptionen parametrisiert aufgerufen werden. Die
Angabe des Parameters `-vo` ist optional.

Aufruf:

----
XPlanValidator -validate Plan.zip -vo skip-flaechenschluss -vo skip-geltungsbereich
----

Zuordnung der Werte:

  * skip-flaechenschluss -> Geometrische Überprüfung der Flächenschlussbedingung (2.2.1.1) überspringen [ja]
  * skip-geltungsbereich -> Geometrische Überprüfung des Geltungsbereich (2.2.3.1) überspringen [ja]

[[xplanvalidator-cli-validierungsergebnis]]
===== Validierungsergebnis

Am Ende des Validierungsdurchlaufs wird dem Benutzer der Pfad zu dem
Validierungsergebnis ausgegeben. Das Validierungsergebnis wird als HTML,
XML sowie PDF in einem Archiv gespeichert. Das Archiv ist nach dem
Validierungsdurchlaufs benannt und kann somit leicht identifiziert
werden.
