[[xplaninspirepluwfs]]
== XPlanInspirePluWFS

Der XPlanInspirePluWFS ist ein INSPIRE Download Service zur Abfrage von Vektordaten im Datenformat des INSPIRE Datenthema Planned Land Use (PLU).

[[xplaninspirepluwfs-benutzung-des-xplaninspirepluwfs]]
=== Benutzung des XPlanInspirePluWFS

Der XPlanInspirePluWFS ist ein INSPIRE Download Service (WFS 2.0) basierend auf der Open Source Software https://www.deegree.org[deegree]. Die folgende Tabelle gibt einen Überblick über die zur Verfügung stehenden Operationen des XPlanInspirePluWFS, die in den weiteren Kapiteln noch näher erläutert werden.

[width="97%",cols="30%,70%",options="header",]
|=========================================================
|WFS Operation |Inhalt
|GetCapabilities |Abfrage der Fähigkeiten des Dienstes
|GetFeature |Abfrage von Planobjekten
|DescribeFeatureType |Abfrage der Struktur von Objektarten
|=========================================================

[[xplaninspirepluwfs-adresse-des-dienstes]]
==== Adresse des Dienstes

----
http://<host>:<port>/xplan-webservices-inspireplu/services/downloadservice?
----

[[xplaninspirepluwfs-beispielanfragen]]
==== Beispielanfragen


[[xplaninspirepluwfs-getcapabilities]]
===== GetCapabilities

----
http://<host>:<port>/xplan-webservices-inspireplu/services/downloadservice?request=GetCapabilities&Service=WFS&Version=2.0.0
----

[[xplaninspirepluwfs-getfeature]]
===== GetFeature

----
http://<host>:<port>/xplan-webservices-inspireplu/services/downloadservice?request=GetFeature&Service=WFS&Version=2.0.0&typename=plu:SpatialPlan
----

[[xplaninspirepluwfs-describefeaturetype]]
===== DescribeFeatureType

----
http://<host>:<port>/xplan-webservices-inspireplu/services/downloadservice?request=DescribeFeatureType&Service=WFS&Version=2.0.0
----

[[xplaninspirepluwfs-operationen]]
=== Operationen

Das folgende Kapitel beschreibt die Operationen, die mit dem XPlanInspirePluWFS durchführbar sind.

[[xplaninspirepluwfs-getcapabilities-1]]
==== GetCapabilities

Die GetCapabilities Abfrage dient der Auskunft über die Fähigkeiten des WFS Dienstes. Dabei handelt es sich beispielsweise um Informationen zum Dienstbetreiber, zu den unterstützten Operationen sowie zu den durch den WFS angebotenen WFS Objektarten.

[[xplaninspirepluwfs-getfeature-1]]
==== GetFeature

Die Operation GetFeature stellt die Kernfunktionalität des XPlanInspirePluWFS dar. Die Operation ermöglicht es, die angebotenen Vektordaten anzufragen.

[[xplaninspirepluwfs-describefeaturetype-1]]
==== DescribeFeatureType

Die Operation DescribeFeatureType gibt Informationen zur Struktur der einzelnen Feature Types wieder.

=== Response Paging

Der XPlanInspirePluWFs ist so konfiguriert, dass maximal 100 Instanzen des angefragten FeatureTypes zurückgegeben werden. Um alle Instanzen abzufragen muss daher das vom WFS unterstützte Response Paging verwendet werden: die Parameter COUNT und STARTINDEX ermöglichen das "Blättern" im Gesamtdatenbestand. Mit COUNT wird die Anzahl der maximal zurückgegeben Instanzen vorgegeben, mit STARTINDEX der Index der ersten Instanz (beginnend bei 1) die zurückgegeben werden soll. Beispiele (Beschreibung von <GET_FEATURE_REQUEST> s. oben):

"Seite 1":

----
<GET_FEATURE_REQUEST>&COUNT=10
----

"Seite 2":
----
<GET_FEATURE_REQUEST>&COUNT=10&STARTINDEX=11
----

Über die Attribute @next und @previous im GetFeatureResponse werden die URLs der nächsten bzw. vorherigen "Seite" bereits ausgegeben.