[[xplanmanager-web]]
=== XPlanManagerWeb

Die Komponente XPlanManagerWeb ist eine Web-Oberfläche, die dem
Fachadministrator der xPlanBox ermöglicht, die Datenhaltung zu
kontrollieren und zu verwalten. Mit dem XPlanManagerWeb kann der Benutzer XPlanArchive in die Datenhaltung laden, diese editieren, löschen sowie bereits importiere XPlanArchive wieder exportieren und in einer Liste anzeigen.

[[xplanmanager-web-benutzungsanleitung]]
==== Einstiegsseite

Die Webanwendung XPlanManagerWeb dient der Verwaltung von <<xplanarchiv, XPlanArchiven>> und ist unter:

----
http://<host>:<port>/xplan-manager/
----

verfügbar und kann mit einem Web-Browser aufgerufen werden.

==== Funktionen des XPlanManagerWeb

[[xplanmanager-web-hilfe]]
===== Hilfe

Die Hilfe mit den Angaben zu den möglichen Funktionen lässt sich durch
Betätigen des Buttons _Hilfe_ ausgeben.

[[xplanmanager-web-hinzufuegen]]
===== Hinzufügen

Vor dem Importieren eines XPlanGML-Dokuments in die Datenbasis,
muss dieser über die Web-Oberfläche hochgeladen werden. Hierfür kann der Plan
über den Button _Durchsuchen_ ausgewählt und durch einen Klick auf
_Import_ hochgeladen werden. Der Benutzer wird
über das erfolgreiche bzw. fehlerhafte Hinzufügen des Plans in Form
eines PopUp-Fensters informiert.

Nachdem der Plan hochgeladen wurde, kann dieser
validiert bzw. entfernt werden. Erst nachdem der Plan erfolgreich
validiert wurde, kann der Plan in die Datenbasis importiert werden.
Andernfalls ist der Button _Import_ deaktiviert.

IMPORTANT: Bei der Validierung werden immer die syntaktische und Basis-Geometrische Prüfung (s. Abschnitt <<xplanvalidator-web-geometrisch, geometrische Validierung>>) ausgeführt. Diese stellen sicher, dass ein Plan keine schwerwiegenden Fehler hat, die einen Import verhindern würden. Um die automatische Korrektur der Laufrichtung von Polygonen beim Import zu erzwingen, muss die Option "Prüfung der Laufrichtung (2.2.2.1) überspringen" aktiviert sein.

[[xplanmanager-web-import]]
===== Import

Nachdem der Plan erfolgreich validiert wurde, kann der Plan durch einen
Klick auf den Button _Import_ in die Datenbasis importiert werden. Der
Benutzer wird über den erfolgreichen bzw. fehlerhaften Import des Plans
in Form eines PopUps informiert.

[[xplanmanager-web-auflistung]]
===== Auflistung

Standardmäßig werden alle importierten Pläne in einer Liste angezeigt.
Diese Liste kann nach den angezeigen Spaltennamen
auf- oder absteigend sortiert werden.

[[xplanmanager-filter]]
===== Filter

Diese Liste kann auch nach verschiedenen Kriterien gefiltert werden. Neben dem Filter nach "Gemeinde" und "Planstatus" kann
über den freien Filer die Anzeige der Pläne im XPlanManager reduziert werden. Mit dem Button "Alle Pläne anzeigen" können alle Filter aufgehoben werden und alle
Pläne werden wieder angezeigt.

[[xplanmanager-web-kartenvorschau]]
===== Kartenvorschau

Durch den Klick auf den Button _Kartenvorschau_ öffnet sich ein neues
Fenster, indem der XPlan visualisiert wird. Im Hintergrund befindet sich
eine Hintergrundkarte. Durch den Klick auf _Schließen_ wird die
Kartenvorschau wieder geschlossen.

TIP: Die Kartenvorschau verwendet den Browser-Cache. Falls in der Kartenvorschau nicht der aktuelle Status des Plans angezeigt wird, muss der Cache des genutzten Web-Browsers gelöscht werden.

[[xplanmanager-web-herunterladen]]
===== Herunterladen

Die importierten Pläne können vom Benutzer durch den Klick auf den
Button _Herunterladen_ wieder als XPlanArchiv heruntergeladen werden.

[[loeschen]]
===== Löschen

Je nach Benutzerrechten können die importierten Pläne durch den Klick
auf den Button _Löschen_ aus der Datenbasis gelöscht werden. Hat ein
Benutzer keine Rechte, so wird der Button grau dargestellt.

[[xplanmanager-web-editieren]]
===== Editieren

Abhängig von den Benutzerrechten können Pläne editiert werden. Fehlen dem Benutzer
die entsprechenden Rechte ist die Funktion deaktiviert und der Button __Editieren__ wird grau dargestellt. 
Die Editieransicht öffnet sich durch den Klick auf den Button __Editieren__. Die Ansicht ist in verschiedene Bereiche
aufgeteilt, die insgesamt die Bearbeitung folgender Elemente zulässt:

*Basisdaten*

 * name
 * beschreibung
 * technHerstellDatum
 * untergangsDatum
 * planArt
 * sonstPlanArt
 * verfahren
 * rechtsstand
 * rechtsverordnungsDatum

Das Editieren des Rechtsstands kann dazu führen, dass eine
Zustandsänderung des Plans eintritt. Damit verbunden ist das Verschieben
der Vektor- und Rasterdaten in die entsprechende Datenhaltung. Übergänge
sind beliebig zwischen den drei Zuständen 'Festgestellt', 'In
Aufstellung' und 'Archiviert' möglich. Eine Zustandsänderung von
'Festgestellt' nach 'In Aufstellung' tritt beispielsweise beim Ändern
des Rechtsstands von 'InkraftGetreten' nach 'Untergegangen' ein.

IMPORTANT: **Achtung**: Beim Import kann der Nutzer den Zustand eines Planes über eine
Auswahlliste mit den Optionen 'Festgestellt', 'In Aufstellung' und
'Archiviert' ändern. Abhängig von dem im Plan gesetzten Rechtsstand wird
eine Vorauswahl getroffen, die der Nutzer aber überschreiben kann. Beim
Öffnen der Editieransicht wird der Rechtsstand aus dem Plan
berücksichtigt, der vom Nutzer ausgewählte Zustand bleibt dagegen
unberücksichtigt. Somit entspricht die Auswahl des Rechtsstands nicht
dem Zustand des Plans, falls dieser beim Import manipuliert wurde. Beim
Abspeichern eines Editiervorgangs ist hier somit Vorsicht geboten, da so
unbeabsichtigt eine Zustandsänderung vorgenommen werden kann!

*Gültigkeitszeitraum*

 * Der Zeitraum in dem ein Plan gültig ist. Für dieses Feld gibt es keine
Entsprechung im XPlanGML. Die Angabe des Zeitraums, wie sie beim Import
erfolgt ist, wird beim Ändern des Zeitraums überschrieben.

*Änderungen*

 * aendert
 * wurdeGeaendertVon

*Texte*

 * texte

*Dokumente*

Abhängig von der XPlanGML Version können folgende Dokumente editiert werden:

XPlanGML 3.0:

 * refBegruendung

XPlanGML 4.1:

 * refBegruendung
 * refRechtsplan
 * refGruenordnungsplan

XPlanGML 5.x:

 * alle verfügbaren Typen aus `XP_ExterneReferenzTyp` (Enumeration)

Dabei kann der Benutzer wählen, ob er eine Datei über einen vollqualifizierten Link (URL) referenziert oder zum XPlanArchiv hinzugefügt und dann relativ verlinkt.

*Rasterbasis*

 * rasterbasis

Die Rasterbasis kann nur editiert werden, wenn ein Plan ein Objekt vom Typ BP_Bereich besitzt. Ist dies nicht der Fall, wird ein entsprechender Hinweis in der Oberfläche angegeben. Die Angabe einer Rasterbasis kann in diesem Fall nicht erfolgen.

Werden Referenzen entfernt oder verändert, so werden die nicht mehr
referenzierten Dateien aus der Datenhaltung entfernt. Änderungen führen zu
einer Aktualisierung der XPlanWMS-Konfiguration. Klickt der Nutzer auf
__Speichern__, wird zunächst eine Validierung der Rasterdaten
vorgenommen. Bei invaliden Dateien bekommt der Nutzer eine
Entscheidungsoption wie mit diesen Daten umgegangen werden soll.
Anschließend erfolgt die Aktualisierung der Daten.

Wie im Abschnitt <<referenzierung-von-rasterdaten-im-xplangml>> beschrieben, sind in den Versionen 5.1, 5.2, 5.3 und 5.4 zwei Varianten zur Referenzierung von Rasterdaten möglich. Die Anzeige im XPlanManager unterstützt die alte und die neue Variante. Wird über den XPlanManager eine Referenz geändert, dann erfolgt die Referenzierung immer über das Element `<refScan/>` unabhängig von der im Plan ursprünglich verwendeten Referenzierung.

Die ebenfalls in diesem Abschnitt editierbaren Referenzen auf Texte (refText) und Legenden (refLegende) müssen in den Versionen 5.1, 5.2, 5.3 und 5.4 über die Abschnitte `Texte` und `Dokumente` editiert werden.

NOTE: Die Editierfunktion steht nur für BPläne in den XPlanGML Versionen
3.0, 4.1, 5.0, 5.1, 5.2, 5.3 und 5.4 zur Verfügung.


[[xplanmanager-web-inspireplu]]
===== Bereitstellung als INSPIRE PLU Datensatz

Abhängig von den Benutzerrechten können Pläne im Datenthema INSPIRE Planned Land Use veröffentlicht werden. Fehlen dem Benutzer die entsprechenden Rechte ist die Funktion deaktiviert und der Button __Bereitstellung als INSPIRE Datensatz__ wird nicht dargestellt.

Durch Klick auf den Button __Bereitstellung als INSPIRE Datensatz__ wird der Plan in das INSPIRE PLU Datenschema überführt und in den INSPIRE konformen Download Service importiert. Anschließend kann der transformierte Plan über den INSPIRE Download Service (XPlanInspirePluWFS) und INSPIRE View Service (XPlanInspirePluWMS) abgerufen werden.

NOTE: Die Bereitstellung als INSPIRE PLU Datensatz steht nur für BPläne in den XPlanGML Versionen 4.1, 5.0, 5.1, 5.2, 5.3 und 5.4 zur Verfügung.