[[xplanvalidator-cli]]
=== XPlanCLI - Das validate Kommando

Mit den XPlanCLI `validate` Kommando können XPlanGML-Dateien und XPlanArchive validiert werden.

[[xplanvalidator-cli-benutzungsanleitung]]
==== Benutzungsanleitung

Das Kommando wird mit `xpb validate [SUBCOMMAND]` aufgerufen.

[[xplanvalidator-cli-konfiguration-ueber-datei]]
===== Konfiguration über Datei

In dem Verzeichnis _<validator-cli-directory>/etc/_ befindet sich die
Konfigurationsdatei __validatorConfiguration.properties__, welche
genutzt werden kann, um generelle Konfigurationen an dem
Kommandozeilenwerkzeug durchzuführen.

Über _validationReportDirectory=<directory>_ kann konfiguriert werden,
wo die Reports mit dem Validierungsergebnis, die während der Ausführung
des Tools generiert werden, abgespeichert werden sollen.

Mit der Option _validationRulesDirectory=<directory>_ kann konfiguriert
werden, in welchem Verzeichnis die semantischen Validierungsregeln liegen,
die für die Validierung verwendet werden sollen. Erfolgt keine Angabe
werden die unter  _<validator-cli-directory>/etc/rules_ liegenden
semantischen Validierungsregeln verwendet.

[[xplanvalidator-cli-hilfe]]
===== Hilfe

Die Hilfe mit den Angaben zu den möglichen Eingabeparametern lässt sich
mit dem Parameter `help` ausgeben.

Aufruf:

----
xpb validate help
----

Ausgabe:

----
Usage: xpb validate [COMMAND]
Validate a plan or all plans in a database
Commands:
  help  Display help information about the specified command.
  file  Validate a XPlanArchive or XPlanGML file.
  db    Validate XPlanGML in xPlanBox database.
----

[[xplanvalidator-cli-auswahl-planarchiv]]
===== Auswahl XPlanArchiv

Über das Kommando `validate` und Angabe des Pfads zum XPlanArchiv
 kann ausgewählt werden, welches Planwerk validiert werden soll. Die Angabe
des Parameters ist obligatorisch.

Aufruf:

----
xpb validate --file=planwerk.zip
----

[[xplanvalidator-cli-bezeichnung-der-validierung]]
===== Bezeichnung für den Report

Über den Parameter `name <bezeichnung>` kann eine Bezeichnung für den generierten
Report vergeben werden. Die Angabe des Parameters `-name` ist optional.
Fehlt dieser Parameter, wird der Name des XPlanArchivs verwendet.

Aufruf:

----
xpb validate --file=planwerk.zip --name=Report_Planwerk_1
----

[[xplanvalidator-cli-validierungsart]]
===== Validierungsart

Die Kommandozeilenschnittstelle des XPlanValidator kann zur Auswahl der
Validierungsart parametrisiert aufgerufen werden. Die Angabe des
Parameters `-vtype` ist optional.

Aufruf:

----
xpb validate --file=planwerk.zip --type=[syntax|geometric|semantic]
----

Zuordnung der Werte:

* syntax = Syntaktisch
* geometric = Geometrisch
* semantic = Semantisch

Wird kein `type` Parameter gewählt, werden alle Validierungsarten durchgeführt.

Beispiel für eine Ausgabe:

----
Configuration directory is /xplan-cli-tools/etc
Configuration is read from file /xplan-cli-tools/etc/validatorConfiguration.properties
-------------------------------------------
[main] Configuration of the XPlanValidator:
-------------------------------------------
	validation report directory
	- /tmp/validationReport17446416227420229747
	validation rules directory
	- internal rules are used
	XPlanValidatorWMS Endpoint
	- null
-------------------------------------------
Ergebnisse der syntaktischen Validierung: 0
Einlesen der Features (+ Geometrievalidierung)...
Features with invalid flaechenschluss:
- 2.2.1.1: Das Flaechenschlussobjekt mit der gml id Gml_068D3EBD-3701-42FC-9CED-C9DB9947B5CE erfuellt die Flaechenschlussbedingung an folgender Stelle nicht: (571672.134,5940838.1235)
No features outside geltungsbereich
- Ueberpruefung der XLink-Integritaet...
Geometrie-Fehler: 1
- 2.2.1.1: Das Flaechenschlussobjekt mit der gml id Gml_068D3EBD-3701-42FC-9CED-C9DB9947B5CE erfuellt die Flaechenschlussbedingung an folgender Stelle nicht: (571672.134,5940838.1235)
Fortsetzung trotz Geometrie-Fehlern (--force).
Ergebnisse der geometrischen Validierung:
	Warnungen: 0
	Fehler: 1
- 2.2.1.1: Das Flaechenschlussobjekt mit der gml id Gml_068D3EBD-3701-42FC-9CED-C9DB9947B5CE erfuellt die Flaechenschlussbedingung an folgender Stelle nicht: (571672.134,5940838.1235)
...
Geometrische Validierung hat ergeben: Dokument ist nicht valide
Semantische Validierung hat ergeben: Dokument ist valide
Syntaktische Validierung hat ergeben: Dokument ist valide
Archiv mit Validierungsergebnissen wird erstellt.
Archiv mit Validierungsergebnissen wurde unter /tmp/validationReport17446416227420229747 abgelegt.
----

[[xplanvalidator-cli-validierungsoption]]
===== Validierungsoption

Die Kommandozeilenschnittstelle des XPlanValidator kann zur Auswahl von
zusätzlichen Validierungsoptionen parametrisiert aufgerufen werden. Die
Angabe des Parameters `--option` ist optional.

Aufruf:

----
xpb validate --file=planwerk.zip -option=skip-flaechenschluss,skip-geltungsbereich,skip-laufrichtung=true
----

Zuordnung der Werte:

  * `skip-flaechenschluss`: Geometrische Überprüfung der Flächenschlussbedingung (2.2.1.1) überspringen [ja]
  * `skip-geltungsbereich`: Geometrische Überprüfung des Geltungsbereich (2.2.3.1) überspringen [ja]
  * `skip-laufrichtung`: Geometrische Überprüfung Laufrichtung (2.2.2.1) überspringen

[[xplanvalidator-cli-validierungsergebnis]]
===== Validierungsergebnis

Am Ende des Validierungsdurchlaufs wird dem Benutzer der Pfad zu dem
Validierungsergebnis ausgegeben. Das Validierungsergebnis wird als HTML,
XML sowie PDF in einem Archiv gespeichert. Das Archiv ist nach dem
Validierungsdurchlaufs benannt und kann somit leicht identifiziert
werden.
