[[xplanvalidator]]
== XPlanValidator

Der XPlanValidator ist ein Prüftool, das ein XPlanArchiv und die darin enthaltene XPlanGML-Datei validieren kann. Dabei bietet
der XPlanValidator verschiedene Prüfmethoden zur Validierung an.

=== Syntaktische Validierung

Der XPlanValidator kann XPlanGML-Dateien in allen unterstützen Versionen prüfen, ob diese die im zugehörigen XML-Schema festgelegten Syntaxregeln
erfüllen. Die Minimalvoraussetzung wird damit sichergestellt: die XPlanGML-Datei ist wohlgeformt und valide gegenüber den jeweiligen XML-Schema.

=== Geometrische Validierung

Zusätzlich kann der XPlanValidator die in dem XPlanGML-Dokument enthaltenen Geometrien auf Korrektheit hin prüfen.
Dabei werden folgende Prüfungen in Abhängigkeit vom Geometrietyp durchgeführt:

 * Punkte/Punktelisten: Prüfung auf 2D-Koordinaten
 * Kurven: Segment-Kontinuität
 * Generische Kurve/LineString: falls geschlossen, Laufrichtung CCW
 * Ring: Geschlossenheit
 * Ring: Keine Selbstüberschneidung
 * Polygon/PolygonPatch: Äußerer Ring, Orientierung CCW
 * Polygon/PolygonPatch: Innere Ringe, Orientierung CW
 * Polygon/PolygonPatch: Keine Berührung äußerer Ring / innere Ringe
 * Polygon/PolygonPatch: Kein Schnitt äußerer Ring / innere Ringe
 * Polygon/PolygonPatch: Innere Ringe liegen innerhalb der vom äußeren Ring umschlossenen Fläche
 * Polygon/PolygonPatch: Keine Berührung innere Ringe / innere Ringe (Fehler)
 * Polygon/PolygonPatch: Schnittmenge der von zwei inneren Ringen gebildeten Flächen ist leer (Fehler)

Weiterhin werden die folgenden Regeln aus den Konformitätsbedingungen geprüft:

 * 2.2.1.1: Flächenschlussbedingung (Die Prüfung von "Bei allen Objekten mit flächenhaftem Raumbezug muss das Attribut
flaechenschluss belegt sein." ist Bestandteil der semantischen Validierung)
 * 2.2.3.1 Raumbezogene Objekte im Innern des Geltungsbereichs

=== Semantische Validierung

Darüber hinaus kann der XPlanValidator eine XPlanGML-Datei auf folgende Konformitätsbedingungen prüfen:

 * http://www.xplanungwiki.de/images/7/77/Konformit%C3%A4tsbedingungen_XPlanGML_4_0_2.pdf[Konformitätsbedingungen für XPlanGML 4.0]
 * http://www.xplanungwiki.de/images/e/ee/Konformit%C3%A4tsbedingungen-XPlanGML_4_1V2.pdf[Konformitätsbedingungen für XPlanGML 4.1]
 * http://www.xplanungwiki.de/upload/XPlanGML/5.0/Konformit%c3%a4tsbedingungen.pdf[Konformitätsbedingungen für XPlanGML 5.0]
 * http://www.xplanungwiki.de/upload/XPlanGML/5.1/Konformit%C3%A4tsbedingungen-XPlanGML_%205_1_1.pdf[Konformitätsbedingungen für XPlanGML 5.1]

Eine XPlanGML-Datei ist dann zu der jeweiligen XPlanGML Version konform, wenn das XML-Dokument gegen das jeweilige XPlanGML Schema validiert und
alle in den Konformitätsbedingungen spezifizierten Regeln erfüllt werden.

Der Validator kann über ein Kommandozeilentool (XPlanValidatorCLI) und eine Web-Oberfläche (XPlanValidatorWeb) aufgerufen werden.

include::XPlanValidator_CLI.adoc[]

include::XPlanValidator_Web.adoc[]
