[[xplaninspirepluwms]]
== XPlanInspirePluWMS

Der XPlanInspirePluWMS ist ein INSPIRE View Service zur Abfrage der Daten im INSPIRE Datenthema Planned Land Use (PLU). Der
Dienst ermöglicht die Visualisierungen von Plandaten sowie Sachinformationsabfragen zu einzelnen Planinhalten.

[[xplaninspirepluwms-benutzung-des-xplaninspirepluwms]]
=== Benutzung des XPlanInspirePluWMS

Der XPlanInspirePluWMS ist ein INSPIRE View Service basierend auf der Open Source Software http://www.deegree.org[deegree]. Die folgende Tabelle gibt einen Überblick über die zur Verfügung stehenden Operationen des XPlanInspirePluWMS, die in den weiteren Kapiteln noch näher erläutert werden.

[width="95%",cols="29%,71%",options="header",]
|===============================================================
|WMS Operation |Inhalt
|GetCapabilities |Abfrage der Fähigkeiten des Dienstes
|GetMap |Abfrage von Kartenbildern zu WMS Ebenen
|===============================================================

[[xplaninspirepluwms-adresse-des-dienstes]]
==== Adresse des Dienstes

----
http://<host>:<port>/xplan-webservices-inspireplu/services/viewservice?
----

[[xplaninspirepluwms-beispielanfragen]]
==== Beispielanfragen


[[xplaninspirepluwms-getcapabilities]]
===== GetCapabilities

----
http://<host>:<port>/xplan-webservices-inspireplu/services/viewservice?request=GetCapabilities&service=WMS&version=1.3.0
----

[[xplaninspirepluwms-getmap]]
===== GetMap

----
http://<host>:<port>//xplan-webservices-inspireplu/services/viewservice?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=49.0,9.0,50.0,9.5&CRS=EPSG:4326&WIDTH=1000&HEIGHT=1000&LAYERS=LU.SpatialPlan&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE
----

[[xplaninspirepluwms-operationen]]
=== Operationen

Das folgende Kapitel beschreibt die Operationen, die mit dem XPlanInspirePluWMS durchführbar sind.

[[xplaninspirepluwms-getcapabilities-1]]
==== GetCapabilities

Die GetCapabilities Abfrage dient der Auskunft über die Fähigkeiten des WMS Dienstes. Dabei handelt es sich beispielsweise um Informationen zum Dienstbetreiber, zu den unterstützten Operationen sowie zu den durch den WMS angebotenen WMS Ebenen.

[[xplaninspirepluwms-getmap-1]]
==== GetMap

Die Operation GetMap stellt die Kernfunktionalität des XPlanInspirePluWMS dar. Die Operation ermöglicht es, die angebotenen Ebene zu den Planinhalten mit GIS Clients zu nutzen, die die Schnittstellen WMS 1.3.0 unterstützen.