[[xplanmanager-grundlagen]]
=== XPlanManager Grundlagen

Der XPlanManager dient zur Verwaltung von Planwerken innerhalb der xPlanBox. Mit
dem XPlanManager können XPlanGML-Dateien und XPlanArchive importiert, editiert oder gelöscht werden.
Nachdem ein Planwerk erfolgreich über den XPlanManager importiert wurde, können die Daten über die Dienste <<xplanwfs,XPlanWFS>>, <<xplansynwfs,XPlanSynWFS>> und <<xplanwms,XPlanWMS>> abgerufen werden. In den folgenden Abschnitten werden die Anforderungen an ein XPlanGML-Dokument und XPlanArchiv beschrieben.

[[xplangmlfile]]
==== Das XPlanGML-Dokument

Das XPlanGML-Dokument muss folgende Eigenschaften aufweisen:

 * Das XPlanGML-Dokument ist wohlgeformt und hat die Dateiendung `.gml` oder `.xml` (Dateiformat `application/xml`).
 * Das Wurzelelement ist ein `xplan:XPlanAuszug` (aus dem Namensraum der jeweiligen XPlanGML-Version) oder eine `wfs:FeatureCollection` (aus dem Namensraum `http://www.opengis.net/wfs/2.0` aus dem OGC-Standard WFS 2.0)
 * Das XPlanGML-Dokument beinhaltet nur ein oder mehrere Elemente vom Typ `xplan:XP_Plan`. Beinhaltet eine Datei mehrere dieser Elemente, so dürfen keine nicht-referenzierten Features im XPlanGML-Dokument vorkommen, wie z. B. ein freies Präsentationsobjekt ohne Bezug zum Fachobjekt.
 * Wenn das XPlanGML-Dokument mehrere `BP_Bereich`-Elemente beinhaltet, muss das Element `xplan:nummer` für jeden `xplan:BP_Bereich` eindeutig sein.
 * Das XPlanGML-Dokument beinhaltet keine internen Referenzen auf andere Planobjekte über eines der folgenden Elemente `aendert/XP_VerbundenerPlan/verbundenerPlan` oder `wurdeGeaendertVon/XP_VerbundenerPlan/verbundenerPlan` bzw. in XPlanGML 6.0 über
`aendertPlan/XP_VerbundenerPlan/verbundenerPlan`,
`wurdeGeaendertVonPlan/XP_VerbundenerPlan/verbundenerPlan`,
`aendertPlanBereich/XP_VerbundenerPlanBereich/verbundenerPlanBereich` oder
`wurdeGeaendertVonPlanBereich/XP_VerbundenerPlanBereich/verbundenerPlanBereich`. Wird eines der Elemente in einem XPlanGML-Dokument verwendet, dann kann der Plan nicht importiert werden!

[[xplanarchiv]]
==== Das XPlanArchiv

Das XPlanArchiv ist eine ZIP-Datei (Dateiformat `application/zip`) mit folgendem Aufbau:

* Im Basisverzeichnis muss die XPlanGML-Datei mit dem Dateinamen __xplan.gml__ vorhanden sein. Die Datei muss die Eigenschaften eines <<xplangmlfile,XPlanGML-Dokuments>> erfüllen.
* Alle in der XPlanGML-Datei referenzierten Anhänge wie Rasterdaten und Begleitdokumente müssen entweder im Basisverzeichnis der ZIP-Datei liegen oder werden über einen Link auf eine externe Datei (URL) referenziert.
* Referenzen auf Rasterdaten müssen entsprechend der XPlanGML-Version korrekt gesetzt sein, siehe Kapitel <<referenzierung-von-rasterdaten-im-xplangml>>.
* Das XPlanArchiv kann Dateien in folgenden Dateiformaten enthalten:
  ** `application/xml`
  ** `image/tiff`
  ** `image/png`
  ** `text/plain`
  ** `application/pdf`

IMPORTANT: Dateinamen dürfen keine Sonderzeichen wie z. B. `&`, `#` , `/`, `\`, `"`, `'` (doppeltes oder einfaches Anführungszeichen),
Leerzeichen oder auch Umlaute beinhalten. Groß- und Kleinschreibung in den Dateinamen (auch der Dateiendung) werden berücksichtigt
und müssen vollständig mit den Referenzen im Dokument übereinstimmen!

[[referenzierung-von-rasterdaten-im-xplangml]]
===== Referenzierung von Rasterdaten im XPlanGML

Die Rasterdaten müssen mit in dem XPlanArchiv enthalten sein und im Basisverzeichnis neben der Datei __xplan.gml__ liegen.

Innerhalb des XPlanGML müssen die Rasterdateien wie folgt referenziert
sein:

*XPlanGML 4.x:*

Rasterdateien werden im Feature Type XP_RasterplanBasis,
XP_RasterplanAenderung, BP_RasterplanAenderung, FP_RasterplanAenderung,
LP_RasterplanAenderung oder RP_RasterplanAenderung referenziert:

----
gml:featureMember
  xplan:XP_RasterplanBasis
  (oder) xplan:XP_RasterplanAenderung
  (oder) xplan:BP_RasterplanAenderung
  (oder) xplan:FP_RasterplanAenderung
  (oder) xplan:LP_RasterplanAenderung
  (oder) xplan:RP_RasterplanAenderung
    xplan:refScan (kann auch mehrfach vorkommen)
      xplan:XP_ExterneReferenz
        xplan:georefURL
        xplan:art
        xplan:referenzName
        xplan:referenzURL
----

Das Element `<refScan/>` kann beliebig häufig vorkommen. Das Element
`<referenzURL/>` beinhaltet die relative Referenz auf die Rasterdatei.

.Beispiel mit externer Referenz für XPlanGML 4.0 (veraltet):
[source,xml]
----
<gml:featureMember>
    <xplan:XP_RasterplanBasis gml:id="FEATURE_1234567890">
        <xplan:refScan>
            <xplan:XP_ExterneReferenz>
                <xplan:georefURL>rasterdatei.tfw</xplan:georefURL>
                <xplan:art>PlanMitGeoreferenz</xplan:art>
                <xplan:referenzName>rasterdatei</xplan:referenzName>
                <xplan:referenzURL>rasterdatei.tif</xplan:referenzURL>
            </xplan:XP_ExterneReferenz>
        </xplan:refScan>
    </xplan:XP_RasterplanBasis>
</gml:featureMember>
----

*XPlanGML 5.x:*

Rasterdateien werden im Feature Type XP_Rasterdarstellung referenziert:

----
gml:featureMember
  xplan:XP_Rasterdarstellung
    xplan:refScan (kann auch mehrfach vorkommen)
      xplan:XP_ExterneReferenz
        xplan:georefURL
        xplan:art
        xplan:referenzName
        xplan:referenzURL
----

Das Element `<refScan/>` kann beliebig häufig vorkommen. Das Element
`<referenzURL/>` beinhaltet die relative Referenz auf die Rasterdatei.

.Beispiel mit externer Referenz für XPlanGML 5.x (veraltet):
[source,xml]
----
<gml:featureMember>
    <xplan:XP_Rasterdarstellung gml:id="FEATURE_1234567890">
        <xplan:refScan>
            <xplan:XP_ExterneReferenz>
                <xplan:georefURL>rasterdatei.tfw</xplan:georefURL>
                <xplan:art>PlanMitGeoreferenz</xplan:art>
                <xplan:referenzName>rasterdatei</xplan:referenzName>
                <xplan:referenzURL>rasterdatei.tif</xplan:referenzURL>
            </xplan:XP_ExterneReferenz>
        </xplan:refScan>
    </xplan:XP_Rasterdarstellung>
</gml:featureMember>
----

Ab XPlanGML 5.1 ist diese Referenzierung als veraltet notiert. Mit Version XPlanGML 6.0 wird diese auch nicht mehr unterstützt. Stattdessen werden Rasterdateien über die von XP_Bereich abgeleiteten Feature Types und dort über das Element `<refScan/>` referenziert (im folgendem Beispiel BP_Bereich):

----
gml:featureMember
  xplan:BP_Bereich
    xplan:refScan (kann auch mehrfach vorkommen)
      xplan:XP_ExterneReferenz
        xplan:georefURL
        xplan:art
        xplan:referenzName
        xplan:referenzURL
----

Das Element `<refScan/>` kann beliebig häufig vorkommen. Das Element
`<referenzURL/>` beinhaltet die relative Referenz auf die Rasterdatei.

.Beispiel mit externer Referenz für XPlanGML 6.0:
[source,xml]
----
<gml:featureMember>
    <xplan:BP_Bereich gml:id="FEATURE_1234567890">
        ...
        <xplan:refScan>
            <xplan:XP_ExterneReferenz>
                <xplan:georefURL>rasterdatei.tfw</xplan:georefURL>
                <xplan:art>PlanMitGeoreferenz</xplan:art>
                <xplan:referenzName>rasterdatei</xplan:referenzName>
                <xplan:referenzURL>rasterdatei.tif</xplan:referenzURL>
            </xplan:XP_ExterneReferenz>
        </xplan:refScan>
        ...
    </xplan:BP_Bereich>
</gml:featureMember>
----

Ab Version 6.0 wird nur noch die Variante über das Element `<refScan/>` unterstützt.

NOTE: Über die Editor-Funktion des XPlanManager können Rasterdaten über XP_RasterplanBasis oder über das Element `<refScan/>` innerhalb eines von XP_Bereich abgeleiteten Feature Type angezeigt werden. Weitere Informationen dazu auch im Kapitel <<xplanmanager-web-editieren>>.

[[voraussetzungen-fuer-die-rasterdaten]]
===== Voraussetzungen für die Rasterdaten

Um Rasterdaten importieren und diese über die XPlanWMS-Ebene zur Verfügung
stellen zu können, müssen die Daten folgende Anforderungen erfüllen.

Die Unterstützung verschiedener Rasterdatenformate ist vom gesetzten
Raster-Konfigurationstyp abhängig.

IMPORTANT: Dies kann nur zentral für die xPlanBox konfiguriert und nicht durch den Nutzer geändert werden. Hinweise zur Konfiguration sind im Betriebshandbuch zu finden.

Unterschieden wird dabei zwischen Rasterdatenformaten mit oder ohne World-File.

Folgende Voraussetzung werden an die einzelnen Formate gestellt:

*GeoTIFF*:

  * Rasterdaten liegen im Format https://www.ogc.org/standards/geotiff[GeoTIFF] vor.
  * GeoTIFF-Dateien liegen als gekachelte GeoTiff-Dateien vor.
  * GeoTIFF-Dateien liegen in dem Koordinatenreferenzsystem vor, welches für den XPlanManager konfiguriert ist.
  * GeoTIFF-Dateien enthalten ihre räumliche Ausdehnung als Metatags innerhalb der Datei.
  * Zur Optimierung der Antwortzeit beim Zugriff auf die GeoTIFF-Dateien
  wird empfohlen, in den GeoTIFF-Dateien Overlays mit niedriger
  Auflösung hinzuzufügen.

*TIFF*:

  * TIFF-Dateien enthalten ihre räumliche Ausdehnung in dem ausgelagerten World-File (tfw-Datei).
  * TIFF-Dateien liegen in dem Koordinatenreferenzsystem vor, welches für den XPlanManager konfiguriert ist.

*PNG*:

  * Farbmodell (RGB) mit ein, drei oder vier Bändern.
  * Farbtiefe ist 8bit, 16bit oder 256 indizierten Farben im Farbpalettenmodus.
  * Transparenz ist als Alphakanal je Band (RGBA) oder als "NoData Value" angegeben.
  * PNG-Dateien liegen in dem Koordinatenreferenzsystem vor, welches für
  den XPlanManager konfiguriert ist.
  * PNG-Dateien enthalten ihre räumliche Ausdehnung in dem
  ausgelagerten World-File (pgw-Datei).
  * Wenn das Kommandozeilentool __XPlanManagerCLI__ verwendet wird, muss in
  der Datei _aux.xml_ das Koordinatenreferenzsystem der PNG-Datei definiert
  sein. Für den XPlanManagerWeb ist dies keine Voraussetzung, da der
  Fachadministrator beim Import der Daten das Koordinatenreferenzsystem der
  PNG-Datei über einen Dialog bestätigen kann.

[[sortierung-textabschnitte]]
===== Sortierung von Textabschnitten

Textabschnitte können über das Element `XP_TextAbschnitt` je Planart im XPlanGML hinterlegt werden. Da eine Sortierung auf Basis der Reihenfolge im XPlanGML-Dokument bei der Ausgabe technisch nicht gewährleistet werden kann, werden Textabschnitte in der xPlanBox über den Textschlüssel im Element `XP_TextAbschnitt/schluessel` sortiert ausgegeben. Die Sortierung erfolgt in der GetFeatureInfo-Ausgabe des <<xplanwms,XPlanWMS>> und bei der Anzeige von Textabschnitten in der <<xplanmanager-web-editieren,Editieroberfläche des XPlanManagerWeb>>.

Um die gewünschte Sortierung zu erreichen, müssen die Textschlüssel einem bestimmten Aufbau folgen. Für die Sortierung werden alle Ziffern und Buchstaben bis zum ersten Leerzeichen im Textschlüssel berücksichtigt. Dabei unterstützt die xPlanBox folgende Sortierungen nach Ordnungszahlen und -buchstaben:

* Sortierung nach Ziffern
----
1.1 text
1.2 text
2.1 text
2.2 text
----

* Sortierung nach Kleinbuchstaben
----
a) text
b) text
c) text
----

* Sortierung nach Ziffern mit Kleinbuchstaben
----
1.a) text
1.b) text
2.a) text
2.b) text
----

* Sortierung mit einer Mischform aus Ziffern und Kleinbuchstaben mit Priorität auf Ziffern
----
1.1 text
1.2 text
2.1 text
a) text
b) text
----

* Sortierung mit einer Mischform aus Großbuchstaben mit Ziffern
----
A text
A.1.1 text
A.1.2 text
B text
B.1.1 text
B.1.2 text
----

* Abweichend sortiert werden Textschlüssel, die mit einem Paragrafenzeichen (`§`) beginnen. Hier werden nur die Zahlen bei der Sortierung berücksichtigt:
----
§1 Nr.1
§1 Nr.2
§2 Nr.1.1
§2 Nr.1.2
----