[[xplanwms]]
== XPlanWMS und XPlanWerkWMS

Der XPlanWMS ist ein auf dem Standard Web Map Service
(Version 1.1.1 und 1.3.0) des Open Geospatial Consortium (OGC)
basierender Kartendienst. Dieser bietet die Möglichkeit Visualisierungen
von Plandaten sowie Sachinformationsabfragen zu einzelnen Planinhalten
abzufragen.

Während der XPlanWMS die Inhalte planübergreifend dargestellt, visualisiert der XPlanWerkWMS genau ein einzelnes Planwerk.

Der XPlanWMS stellt somit genau einen Endpunkt bereit, der XPlanWerkWMS einen Endpunkt pro importiertem Plan. Jeder dieser Endpunkte verhält sich konform zum Web Map Service (Version 1.1.1 und 1.3.0) des Open Geospatial Consortium (OGC). Dies gilt auch für die Abfrage von Sachinformationen von einzelnen Planwerken.

[[xplanwms-benutzung-des-xplanwms]]
=== Benutzung des XPlanWMS und XPlanWerkWMS

Mit dem XPlanWMS und XPlanWerkWMS ist ein Benutzer in der Lage, WMS-Ebenen (Layer) mit einem Browser oder einem GIS anzufragen.
Der XPlanWMS und XPlanWerkWMS basieren auf der
Open Source Software http://www.deegree.org[deegree] und sind konform zu
den OGC Standards WMS 1.1.1 und WMS 1.3.0. Die folgende Tabelle
gibt einen Überblick über die zur Verfügung stehenden Operationen des
WMS, die in den weiteren Kapiteln noch näher erläutert werden.

[width="95%",cols="29%,71%",options="header",]
|===============================================================
|WMS Operation |Inhalt
|GetCapabilities |Abfrage der Fähigkeiten des Dienstes
|GetMap |Abfrage von Kartenbildern zu WMS Ebenen
|GetFeatureInfo |Abfrage von Sachinformationen einzelner Objekte
|GetLegendGraphic |Abfrage von Legendengrafiken einzelner Ebenen
|===============================================================

[[xplanwms-adresse-des-dienstes]]
==== Adresse des Dienstes

----
http://<host>:<port>/xplan-wms/services/wms?
----

[[xplanwms-beispielanfragen]]
==== Beispielanfragen

Die Adresse des XPlanWerkWMS ist abhängig von dem Planwerk das angefragt werden soll. Der Name des Plans wird im XPlanManager (s. <<xplanmanager-web>>) in der Ausflistung der Pläne angezeigt und wird in der URL für den Platzhalter <PLANNAME> angegeben. Der Platzhalter <PLANNAME> darf jedoch nur bestimmte Zeichen beinhalten: a-z, A-Z, 0-9, _ , - Nicht erlaubte Zeichen sind somit u.a.: &,( ).:; <LEERZEICHEN>, <CR> uvm. Der Planname wie er in der Ausflistung angegeben ist, muss um die nicht erlaubten Zeichen bereinigt werden. So wird aus dem Plannamen 'BPlan "Muster" (8)' der Platzhalter 'BPlanMuster8'.

[[xplanwms-getcapabilities]]
===== GetCapabilities

*XPlanWMS*
----
http://<host>:<port>/xplan-wms/services/wms?request=GetCapabilities&service=WMS&version=1.1.1
http://<host>:<port>/xplan-wms/services/wms?request=GetCapabilities&service=WMS&version=1.3.0
----

*XPlanWerkWMS*

----
http://<host>:<port>/xplan-wms/services/planwerkwms/planname/<PLANNAME>?request=GetCapabilities&service=WMS&version=1.1.1
http://<host>:<port>/xplan-wms/services/planwerkwms/planname/<PLANNAME>?request=GetCapabilities&service=WMS&version=1.3.0
----

[[xplanwms-getmap]]
===== GetMap

*XPlanWMS*
----
http://<host>:<port>/xplan-wms/services/wms?request=GetMap&Service=WMS&Version=1.1.1&Layers=bp_plan&Format=image/png&Transparent=true&Styles=&Srs=EPSG%3A25833&Bbox=377814.52931834,5697447.998419,381059.6791237,5698548.3070248&Width=1280&Height=434
http://<host>:<port>/xplan-wms/services/wms?request=GetMap&Service=WMS&Version=1.3.0&Layers=bp_plan&Format=image/png&Transparent=true&Styles=&Crs=EPSG%3A25833&Bbox=377814.52931834,5697447.998419,381059.6791237,5698548.3070248&Width=1280&Height=434
----

*XPlanWerkWMS*

----
http://<host>:<port>/xplan-wms/services/planwerkwms/planname/<PLANNAME>?request=GetMap&Service=WMS&Version=1.1.1&Layers=bp_plan&Format=image/png&Transparent=true&Styles=&Srs=EPSG%3A25833&Bbox=377814.52931834,5697447.998419,381059.6791237,5698548.3070248&Width=1280&Height=434
http://<host>:<port>/xplan-wms/services/planwerkwms/planname/<PLANNAME>?request=GetMap&Service=WMS&Version=1.3.0&Layers=bp_plan&Format=image/png&Transparent=true&Styles=&Crs=EPSG%3A25833&Bbox=377814.52931834,5697447.998419,381059.6791237,5698548.3070248&Width=1280&Height=434
----

[[xplanwms-getfeatureinfo]]
===== GetFeatureInfo

*XPlanWMS*
----
http://<host>:<port>/xplan-wms/services/wms?request=GetFeatureInfo&Service=WMS&Version=1.3.0&Width=460&Height=348&Layers=fp_bebausfl&Transparent=TRUE&Format=image%2Fpng&BBox=381754.08781343646,5716831.670553746,382351.0673120646,5717283.298522273&Crs=EPSG:25833&Styles=&Query_layers=fp_bebausfl&I=217&J=94&Feature_count=10&Info_format=text/html
http://<host>:<port>/xplan-wms/services/wms?request=GetFeatureInfo&Service=WMS&Version=1.3.0&Width=460&Height=348&Layers=fp_bebausfl&Transparent=TRUE&Format=image%2Fpng&BBox=381754.08781343646,5716831.670553746,382351.0673120646,5717283.298522273&Crs=EPSG:25833&Styles=&Query_layers=fp_bebausfl&I=217&J=94&Feature_count=10&info_format=application/vnd.ogc.gml
----

*XPlanWerkWMS*

----
http://<host>:<port>/xplan-wms/services/planwerkwms/planname/<PLANNAME>?request=GetFeatureInfo&Service=WMS&Version=1.3.0&Width=460&Height=348&Layers=fp_bebausfl&Transparent=TRUE&Format=image%2Fpng&BBox=381754.08781343646,5716831.670553746,382351.0673120646,5717283.298522273&Crs=EPSG:25833&Styles=&Query_layers=fp_bebausfl&I=217&J=94&Feature_count=10&Info_format=text/html
http://<host>:<port>/xplan-wms/services/planwerkwms/planname/<PLANNAME>?request=GetFeatureInfo&Service=WMS&Version=1.3.0&Width=460&Height=348&Layers=fp_bebausfl&Transparent=TRUE&Format=image%2Fpng&BBox=381754.08781343646,5716831.670553746,382351.0673120646,5717283.298522273&Crs=EPSG:25833&Styles=&Query_layers=fp_bebausfl&I=217&J=94&Feature_count=10&info_format=application/vnd.ogc.gml
----


[[xplanwms-getlegendgraphic]]
===== GetLegendGraphic

*XPlanWMS*
----
http://<host>:<port>/xplan-wms/services/wms?request=GetLegendGraphic&Service=WMS&Version=1.1.1&layer=bp_gruenfl&format=image/png
http://<host>:<port>/xplan-wms/services/wms?request=GetLegendGraphic&Service=WMS&Version=1.3.0&layer=bp_gruenfl&format=image/png
----

*XPlanWerkWMS*

----
http://<host>:<port>/xplan-wms/services/planwerkwms/planname/<PLANNAME>?request=GetLegendGraphic&Service=WMS&Version=1.1.1&layer=bp_gruenfl&format=image/png
http://<host>:<port>/xplan-wms/services/planwerkwms/planname/<PLANNAME>?request=GetLegendGraphic&Service=WMS&Version=1.3.0&layer=bp_gruenfl&format=image/png
----

[[xplanwms-inhalte-des-kartendienstes]]
=== Inhalte des Kartendienstes

Der XPlanWMS dient der Darstellung aller importierten XPlanArchive, während der XPlanWerkWMS einzelne Planwerke visualisiert. Die Datenbasis beider Dienste basiert auf den über den XPlanManager importierten XPlanArchiven. Für jede Objektart aus den unterstützten XPlanGML-Applikationsschema, das Geometrie-Attribute enthält, existiert eine entsprechende Ebene im XPlanWMS und XPlanWerkWMS. Zusätzlich zu den aus dem XPlanGML abgeleiteten Ebenen stellen beide Dienste Ebenen zur Darstellung von gescanten Rasterplan-Dateien bereit.

[[xplanwms-operationen]]
=== Operationen

Das folgende Kapitel beschreibt die Operationen, die mit dem XPlanWMS und XPlanWerkWMS durchführbar sind.

[[xplanwms-getcapabilities-1]]
==== GetCapabilities

Die GetCapabilities Abfrage dient der Auskunft über die Fähigkeiten des
WMS Dienstes. Dabei handelt es sich beispielsweise um Informationen zum
Dienstbetreiber, zu den unterstützten Operationen sowie zu den durch den
WMS angebotenen WMS Ebenen.

[[xplanwms-getmap-1]]
==== GetMap

Die Operation GetMap stellt die Kernfunktionalität des XPlanWMS dar. Die
Operation ermöglicht es, die angebotenen Ebene zu den Planinhalten mit
GIS Clients zu nutzen, die die Schnittstellen WMS 1.1.1 bzw. WMS 1.3.0
unterstützen.

[[xplanwms-styles]]
===== Styles

Bei der GetMap Operation gibt es die Möglichkeit zwischen zwei
verschieden Styles zu wechseln, die die Darstellung der Inhalte des
Kartendienstes beeinflussen. Dabei liegen alle Zeichenvorschriften
(Styles) für alle Ebenen des XPlanWMS in transparenter und in
vollflaechiger Form vor. Bei GetMap Operationen kann mittels des
Style-Parameter zwischen beiden Darstellungen gewechselt werden. Im
WMS-Endpoint ist als default Style die vollflaechige Darstellung
eingestellt, im WMSpre-Endpoint und im WMSarchive-Endpoint hingegen die
transparente. Wenn der transparente Style ausgewählt wird, sind
lediglich die Planumringe sichtbar.

[[xplanwms-gueltigkeitszeitraum]]
===== Gültigkeitszeitraum

Der Gültigkeitszeitraum bestimmt die Sichtbarkeit der Inhalte des
Kartendienstes bei der GetMap Operation. Der Gültigkeitszeitraum eines
Plans wird beim Import in Form einer Zeitspanne angegeben. Handelt es
sich dabei um eine aktuelle Zeitspanne, so werden die Plandaten bei der
GetMap Operation angezeigt. Handelt es sich wiederum um einen
abgelaufenen bzw. noch nicht begonnenen Gültigkeitszeitraums, so werden
die Plandaten bei einer GetMap Operation nicht dargestellt.

Ausnahme: Die Layer, die den Geltungsbereich darstellen, werden nicht
über den Gültigkeitszeitraum definiert und sind immer verfügbar.

[[xplanwms-getfeatureinfo-1]]
==== GetFeatureInfo

Die Operation GetFeatureInfo ermöglicht die Ausgabe von
Sachinformationen zu Planobjekten. In der HTML Ausgabe dieser
Sachinformationen besteht neben der Ausgabe der entsprechenden
Eigenschaften der Planobjekte auch die Möglichkeit, referenzierte
Dokumente und Grafiken über die Operation <<xplanwms-getattachement>> abzurufen.

[[xplanwms-getlegendgraphic-1]]
==== GetLegendGraphic

Mit der GetLegendGraphic Operation können Legendengrafiken zu allen
Ebenen des XPlanWMS abgefragt werden. Dies ermöglicht das gezielte
Abfragen von Legendengrafiken der Ebenen.

[[xplanwms-getattachement]]
==== GetAttachment

Die beiden WMS-Dienste der xPlanBox unterstützen zusätzlich die Operation GetAttachment. Diese spezielle Erweiterung
der Schnittstelle erlaubt den Zugriff auf die im XPlanGML referenzierten Anhänge.

Die Operation unterstützt folgende Parameter:

* featureID: Die GML-ID eines Features, z.B. XPLAN_XP_RASTERPLANBASIS_7b36b0ee-5139-4a55-afc0-01fec18e9f0a
* filename: Der Dateiname der referenzierten Datei, z.B. Stellingen64.png

----
http://<host>:<port>/xplan-wms/getAttachment?featureID=XPLAN_XP_RASTERPLANBASIS_7b36b0ee-5139-4a55-afc0-01fec18e9f0a&filename=Stellingen64.png
----

[[xplanwms-koordinatenreferenzsysteme]]
=== Koordinatenreferenzsysteme

Der XPlanWMS und XPlanWerkWMS unterstützt die folgenden Koordinatenreferenzsysteme für Vektordaten:

* EPSG:25833,
* EPSG:25832,
* EPSG:325833,
* EPSG:31466,
* EPSG:31467,
* EPSG:31468,
* EPSG:31469,
* EPSG:4258,
* EPSG:4326,
* EPSG:4839,
* CRS:84.

Für Rasterdaten wird dagegen nur eines dieser Koordinatenreferenzsysteme unterstützt.
