[[xplanmanager-grundlagen]]
=== XPlanManager Grundlagen

Der XPlanManager dient zur Verwaltung von Planwerken innerhalb der xPlanBox. Mit
dem XPlanManager können XPlanGML-Dateien und XPlanArchive importiert, editiert oder gelöscht werden.
Nachdem ein Planwerk erfolgreich über den XPlanManager importiert wurde, können die Daten über die Dienste XPlanWFS und XPlanWMS abgerufen werden. In den folgendenen Abschnitten werden die Anforderungen an ein XPlanGML-Dokument und XPlanArchiv beschrieben.

[[xplangmlfile]]
==== Das XPlanGML-Dokument

Das XPlanGML-Dokument muss folgende Eigenschaften aufweisen:

 * Das XPlanGML-Dokument ist wohlgeformt und hat die Dateiendung `.gml` oder `.xml` (Dateiformat `application/xml`).
 * Das Wurzelelement ist `xplan:XPlanAuszug` (im Namespace des XPlanGMLs) oder `wfs:FeatureCollection` (im Namespace http://www.opengis.net/wfs/2.0 aus WFS 2.0)
 * Das XPlanGML-Dokument beinhaltet nur ein oder mehrere Elemente vom Typ `xplan:XP_PLAN`. Beinhaltet eine Datei mehrere dieser Elemente, so dürfen keine nicht referenzierte Features im XPlanGML-Dokument vorkommen, wie z. B. ein freies Präsentationsobjekt ohne Bezug zum Bereich.
 * Wenn das XPlanGML-Dokument mehrere `BP_Bereich`-Elemente beinhaltet, muss das Element `xplan:nummer` für jeden `xplan:BP_Bereich` eindeutig sein.
 * Das XPlanGML-Dokument beinhaltet keine interne Referenzen auf andere Planobjekte über eines der folgenden Elemente `aendert/XP_VerbundenerPlan/verbundenerPlan` oder `wurdeGeaendertVon/XP_VerbundenerPlan/verbundenerPlan` bzw. in XPlanGML 6.0 über
`aendertPlan/XP_VerbundenerPlan/verbundenerPlan`,
`wurdeGeaendertVonPLan/XP_VerbundenerPlan/verbundenerPlan`,
`aendertPlanBereich/XP_VerbundenerPlanBereich/verbundenerPlanBereich` oder
`wurdeGeaendertVonPLanBereich/XP_VerbundenerPlanBereich/verbundenerPlanBereich`. Wird eines der Elemente in einem XPlanGML-Dokument verwendet, dann kann der Plan nicht importiert werden.

[[xplanarchiv]]
==== Das XPlanArchiv

Das XPlanArchiv ist eine ZIP-Datei (Dateiformat `application/zip`) mit folgendem Aufbau:

* Im Basisverzeichnis muss die XPlanGML-Datei mit dem Dateinamen __xplan.gml__ vorhanden sein. Die Datei muss die Eigenschaften eines <<xplangmlfile,XPlanGML-Dokuments>> erfüllen.
* Rasterdaten, die in der XPlanGML-Datei referenziert sind, müssen ebenfalls im Basisverzeichnis der ZIP-Datei liegen, siehe dazu auch <<referenzierung-von-rasterdaten-im-xplangml>>.
* Alle anderen in der XPlanGML-Datei referenzierten Anhänge müssen entweder im Basisverzeichnis der ZIP-Datei liegen oder werden über einen Link auf eine externe Datei (URL) referenziert.
* Das XPlanArchiv kann Dateien mit folgenden Dateiformaten enthalten:
  ** `application/xml`
  ** `image/png`
  ** `image/tiff`
  ** `application/pdf`
  ** `text/plain`

IMPORTANT: Dateinamen dürfen keine Sonderzeichen wie z. B. `&`, `#` , `/`, `\`, `"`, `'` (doppeltes oder einfaches Anführungszeichen),
Leerzeichen oder auch Umlaute beinhalten. Gross- und Kleinschreibung in den Dateinamen (auch der Dateiendung) werden berücksichtigt
und müssen vollständig mit den Referenzen im Dokument übereinstimmen!

[[referenzierung-von-rasterdaten-im-xplangml]]
===== Referenzierung von Rasterdaten im XPlanGML

Die Rasterdaten müssen mit in dem XPlanArchiv enthalten sein und neben der Datei __xplan.gml__ liegen.

Innerhalb des XPlanGML müssen die Rasterdateien wie folgt referenziert
sein:

*XPlanGML 4.x:*

Rasterdateien werden im Feature Type XP_RasterplanBasis,
XP_RasterplanAenderung, BP_RasterplanAenderung, FP_RasterplanAenderung,
LP_RasterplanAenderung oder RP_RasterplanAenderung referenziert:

----
gml:featureMember
  xplan:XP_RasterplanBasis
  (oder) xplan:XP_RasterplanAenderung
  (oder) xplan:BP_RasterplanAenderung
  (oder) xplan:FP_RasterplanAenderung
  (oder) xplan:LP_RasterplanAenderung
  (oder) xplan:RP_RasterplanAenderung
    xplan:refScan (kann auch mehrfach vorkommen)
      xplan:XP_ExterneReferenz
        xplan:georefURL
        xplan:art
        xplan:referenzName
        xplan:referenzURL
----

Das Element `<refScan/>` kann beliebig häufig vorkommen. Das Element
`<referenzURL/>` beinhaltet die relative Referenz auf die Rasterdatei.
Beispiel:

[source,xml]
----
<gml:featureMember>
    <xplan:XP_RasterplanBasis gml:id="FEATURE_1234567890">
        <xplan:refScan>
            <xplan:XP_ExterneReferenz>
                <xplan:georefURL>rasterdatei.tfw</xplan:georefURL>
                <xplan:art>PlanMitGeoreferenz</xplan:art>
                <xplan:referenzName>rasterdatei</xplan:referenzName>
                <xplan:referenzURL>rasterdatei.tif</xplan:referenzURL>
            </xplan:XP_ExterneReferenz>
        </xplan:refScan>
    </xplan:XP_RasterplanBasis>
</gml:featureMember>
----

*XPlanGML 5.x:*

Rasterdateien werden im Feature Type XP_Rasterdarstellung referenziert:

----
gml:featureMember
  xplan:XP_Rasterdarstellung
    xplan:refScan (kann auch mehrfach vorkommen)
      xplan:XP_ExterneReferenz
        xplan:georefURL
        xplan:art
        xplan:referenzName
        xplan:referenzURL
----

Das Element `<refScan/>` kann beliebig häufig vorkommen. Das Element
`<referenzURL/>` beinhaltet die relative Referenz auf die Rasterdatei.
Beispiel:

[source,xml]
----
<gml:featureMember>
    <xplan:XP_Rasterdarstellung gml:id="FEATURE_1234567890">
        <xplan:refScan>
            <xplan:XP_ExterneReferenz>
                <xplan:georefURL>rasterdatei.tfw</xplan:georefURL>
                <xplan:art>PlanMitGeoreferenz</xplan:art>
                <xplan:referenzName>rasterdatei</xplan:referenzName>
                <xplan:referenzURL>rasterdatei.tif</xplan:referenzURL>
            </xplan:XP_ExterneReferenz>
        </xplan:refScan>
    </xplan:XP_Rasterdarstellung>
</gml:featureMember>
----

Ab XPlanGML 5.1 ist diese Referenzierung als veraltet notiert. Mit Version XPlanGML 6.0 wird diese auch nicht mehr unterstützt. Stattdessen werden Rasterdateien über die von XP_Bereich abgeleiteten Feature Types und dort über das Element `<refScan/>` referenziert (im folgendem Beispiel BP_Bereich):

----
gml:featureMember
  xplan:BP_Bereich
    xplan:refScan (kann auch mehrfach vorkommen)
      xplan:XP_ExterneReferenz
        xplan:georefURL
        xplan:art
        xplan:referenzName
        xplan:referenzURL
----

Das Element `<refScan/>` kann beliebig häufig vorkommen. Das Element
`<referenzURL/>` beinhaltet die relative Referenz auf die Rasterdatei.
Beispiel:

[source,xml]
----
<gml:featureMember>
    <xplan:BP_Bereich gml:id="FEATURE_1234567890">
        ...
        <xplan:refScan>
            <xplan:XP_ExterneReferenz>
                <xplan:georefURL>rasterdatei.tfw</xplan:georefURL>
                <xplan:art>PlanMitGeoreferenz</xplan:art>
                <xplan:referenzName>rasterdatei</xplan:referenzName>
                <xplan:referenzURL>rasterdatei.tif</xplan:referenzURL>
            </xplan:XP_ExterneReferenz>
        </xplan:refScan>
        ...
    </xplan:BP_Bereich>
</gml:featureMember>
----

Ab Version 6.0 wird nur noch die zweite Variante über das Element `<refScan/>` unterstützt.

NOTE: Über die Editor-Funktion des XPlanManager können Rasterdaten über XP_RasterplanBasis oder über das Element `<refScan/>` innerhalb eines von XP_Bereich abgeleiteten Feature Type angezeigt werden. Weitere Informationen dazu auch im Kapitel <<xplanmanager-web-editieren>>.

[[voraussetzungen-fuer-die-rasterdaten]]
===== Voraussetzungen für die Rasterdaten

Um Rasterdaten importieren und diese über den XPlanWMS-Ebene zur Verfügung
stellen zu können, müssen die Daten folgende Anforderungen erfüllen.

Die Unterstützung verschiedener Rasterdatenformate ist vom gesetzten
Raster-Konfigurationstyp abhängig.

IMPORTANT: Dies kann nur zentral für die xPlanBox konfiguriert und nicht durch den Nutzer geändert werden. Hinweise zur Konfiguration sind im Betriebshandbuch zu finden.

Unterschieden wird dabei zwischen den Konfigurationstypen _GeoTiff_ und
__GDAL__:


*GeoTiff* - Konfigurationstyp:

  * Es werden ausschließlich Rasterdaten im https://www.ogc.org/standards/geotiff[GeoTiff] Format unterstützt.

*GDAL* - Konfigurationstyp:

  * Grundsätzlich können alle durch https://gdal.org/drivers/raster/index.html[GDAL] unterstützten Rasterdatenformate auch durch deegree und somit dem XPlanManager
  verarbeitet werden.
  * Getestet wurden bisher nur die Formate GeoTiff und PNG.

Folgende Voraussetzung werden an die einzelnen Formate gestellt:

*GeoTiff*:

  * GeoTiff-Dateien liegen als gekachelte GeoTiff-Dateien vor.
  * GeoTiff-Dateien liegen in dem Koordinatenreferenzsystem vor, welches
  für den XPlanManager konfiguriert ist.
  * GeoTiff-Dateien enthalten ihre räumliche Ausdehnung als Metatags innerhalb der Datei.
  * Zur Optimierung der Antwortzeit beim Zugriff auf die GeoTiff-Dateien
  wird empfohlen, in den GeoTiff-Dateien Overlays mit niedriger
  Auflösung hinzuzufügen.

*PNG*:

  * Farbmodell (RGB) mit ein, drei oder vier Bändern.
  * Farbtiefe ist 8bit, 16bit oder 256 indizierten Farben im Farbpalettenmodus.
  * Transparenz ist als Alphakanal je Band (RGBA) oder als "NoData Value" angegeben.
  * PNG-Dateien liegen in dem Koordinatenreferenzsystem vor, welches für
  den XPlanManager konfiguriert ist.
  * PNG-Dateien enthalten ihre räumliche Ausdehnung in einer
  ausgelagerten PGW-Datei (PNG World File).
  * Wenn das Kommandozeilentool __XPlanManagerCLI__ verwendet wird, muss in
  der Datei _aux.xml_ das Koordinatenreferenzsystem der PNG-Datei definiert
  sein. Für den XPlanManagerWeb ist dies keine Voraussetzung, da der
  Fachadministrator beim Import der Daten das Koordinatenreferenzsystem der
  PNG-Datei über einen Dialog bestätigen kann.

[[anlegen-von-deegree-konfigurationsstrukturen-fuer-rasterdaten]]
==== Anlegen von deegree Konfigurationsstrukturen für Rasterdaten

Beim Import von XPlanArchiven mit Rasterdaten werden Konfigurationsdateien für den XPlanWMS automatisch angelegt, die eine Darstellung im XPlanWMS ermöglichen.

Für jede importierte Rasterdatei werden folgende Konfigurationen
angelegt:

* eine Konfigurationsdatei für einen GeoTiffTileStore oder
GDALTileStore,
* eine Konfigurationsdatei für einen TileLayer und
* in der Ebenenbaum-Konfiguration wird ein neuer Layer in die
Kategorieebene eingefügt, die die Rasterpläne nach Datum sortiert
beinhaltet.
