[[xplansynwfs]]
== XPlanSynWFS

Der XPlanSynWFS dient der Abbildung des synthetisierten
XPlanGML Anwendungsschemas (XPlanSynGML). Dieses stellt eine
vereinfachte und zusammenfassende Form der verschiedenen XPlanGML
Versionen dar.

[[xplansynwfs-benutzung-des-xplansynwfs]]
=== Benutzung des XPlanSynWFS

Die folgende Tabelle fasst die vom XPlanSynWFS unterstützten Operationen
zusammen. Der XPlanSynWFS unterstützt den Zugriff über die OGC WFS
Protokollversionen 1.1.0 und 2.0.0. Dabei ist es möglich, Anfragen per
HTTP GET und POST über einen beliebigen Webbrowser an den Dienst zu
senden. Ebenfalls ist die Einbindung in WFS Client Anwendungen möglich,
die die o.g. Versionen für OGC WFS Dienste unterstützen.

[width="97%",cols="30%,70%",options="header",]
|=========================================================
|WFS Operation |Inhalt
|GetCapabilities |Abfrage der Fähigkeiten des Dienstes
|GetFeature |Abfrage von Planobjekten
|DescribeFeatureType |Abfrage der Struktur von Objektarten
|=========================================================

[[xplansynwfs-adresse-des-dienstes]]
==== Adresse des Dienstes

----
http://<host>:<port>/xplansyn-wfs/services/xplansynwfs?
----

[[xplansynwfs-beispielanfragen]]
==== Beispielanfragen


[[xplansynwfs-getcapabilities]]
===== GetCapabilities

----
http://<host>:<port>/xplansyn-wfs/services/xplansynwfs?request=GetCapabilities&Service=WFS&Version=1.1.0
----

[[xplansynwfs-getfeature]]
===== GetFeature

----
http://<host>:<port>/xplansyn-wfs/services/xplansynwfs?request=GetFeature&Service=WFS&Version=1.1.0&typename=xplan:BP_Bereich
----

[[xplansynwfs-describefeaturetype]]
===== DescribeFeatureType

----
http://<host>:<port>/xplansyn-wfs/services/xplansynwfs?request=DescribeFeatureType&Service=WFS&Version=1.1.0
----

[[xplansynwfs-liststoredqueries]]
===== ListStoredQueries

----
http://<host>:<port>/xplansyn-wfs/services/xplansynwfs?request=ListStoredQueries&Service=WFS&Version=2.0.0
----

[[xplansynwfs-inhalte-des-datendienstes]]
=== Inhalte des Datendienstes

[[xplansynwfs-operationen]]
=== Operationen

Das folgende Kapitel beschreibt die Operationen, die mit dem XPlanSynWFS
durchführbar sind.

[[xplansynwfs-getcapabilities-1]]
==== GetCapabilities

Die GetCapabilities Abfrage dient der Auskunft über die Fähigkeiten des
WFS Dienstes. Dabei handelt es sich beispielsweise um Informationen zum
Dienstbetreiber, zu den unterstützten Operationen sowie den durch den
WFS angebotenen Objektarten.

[[xplansynwfs-getfeature-1]]
==== GetFeature

Die Operation GetFeature stellt die Kernfunktionalität des XPlanSynWFS
dar. Die Operation ermöglicht es, die angebotenen Ebene zu den
Planinhalten mit GIS Clients zu nutzen, die die Schnittstellen WFS 1.1.0
bzw. WFS 2.0.0 unterstützen.

[[xplansynwfs-describefeaturetype-1]]
==== DescribeFeatureType

Die Operation DescribeFeatureType gibt Informationen zur Struktur der
einzelnen Feature Types wieder.

[[xplansynwfs-liststoredqueries-1]]
==== ListStoredQueries

Die Operation ListStoredQueries gibt Informationen über die verfügbaren
StoredQueries zurück. Diese Operation steht nur in der Protokollversion
2.0.0 zur Verfügung.

=== StoredQueries

Neben den üblichen StoredQueries urn:ogc:def:query:OGC-WFS::GetFeatureById
und urn:ogc:def:query:OGC-WFS::GetFeatureByType bietet der Endpoint __xplansynwfs__
drei weitere StoredQueries an:

 * urn:ogc:def:query:OGC-WFS::InternalId
 * urn:ogc:def:query:OGC-WFS::PlanId
 * urn:ogc:def:query:OGC-WFS::PlanName

Darüber lassen sich die Vektordaten eines einzelnen Plans über die vom
XPlanManager vergebene interne Id, die im XPlanGML vergebene Nummer bzw.
den im XPlanGML angegebenen Namen abrufen.

Aufgrund der Eigenschaften des XPlanSynWFS lassen sich aktuell nur für die StoredQuery
_PlanName_ zu einem Plan gehörigen Vektordaten abrufen.
Die StoredQueries _InternalId_ und _PlanId_
geben nur die Vektordaten des feature types BP_Plan (bzw. FP_Plan, LP_Plan, RP_Plan und SO_Plan) zurück,
nicht ggf. referenzierte Vektordaten.

Um die Eindeutigkeit der StoredQueries _PlanId_ und _PlanName_ zu gewährleisten,
muss sichergestellt werden, dass bei den importierten Plänen die Nummer und der Name
des Plans eindeutig sind.

Die Nutzung der StoredQueries erfolgt über GetFeature-Anfragen. Beispielanfrage für
den Plan mit dem Namen _Musterdorf_:

----
http://<host>:<port>/xplansyn-wfs/services/xplansynwfs?request=GetFeature&service=WFS&version=2.0.0&resolvedepth=*&StoredQuery_ID=urn:ogc:def:query:OGC-WFS::PlanName&planName=Musterdorf
----

[[xplansynwfs-koordinatenreferenzsysteme]]
=== Koordinatenreferenzsysteme

Der XPlanSynWFS unterstützt die folgenden
Koordinatenreferenzsysteme:

* EPSG:25833
* EPSG:25832
* EPSG:325833
* EPSG:31466
* EPSG:31467
* EPSG:31468
* EPSG:31469
* EPSG:4258
* EPSG:4326
* EPSG:4839
* CRS:84
