[[xplanmanager-cli]]
===  XPlanCLI - Das manage Kommando

Mit den XPlanCLI `manage` Kommando können XPlanGML-Dateien und XPlanArchive in die XPlanDB verwaltet werden, sowie Service-Metadaten für den XPlanWerkWMS zu erzeugt werden.

[[xplanmanager-cli-benutzungsanleitung]]
==== Benutzungsanleitung

Das Kommando wird mit `xpb manage [SUBCOMMAND]` aufgerufen.

[[xplanmanager-cli-konfiguration-ueber-datei]]
===== Konfiguration über Datei

In dem Verzeichnis _<manager-cli-directory>/etc/_ befindet sich die
Konfigurationsdatei __managerConfiguration.properties__, welche genutzt
werden kann, um generelle Konfigurationen an dem Kommandozeilentool
durchzuführen.

Wird der Parameter `managerconfiguration` nicht angegeben, nutzt das Tool die unter
_etc/_ abgelegte Datei. Wenn der Parameter mitgegeben wird, muss sich die
Konfigurationsdatei in dem referenzierten Verzeichnis befinden.

[[xplanmanager-cli-hilfe]]
===== Hilfe

Die Hilfe mit den Angaben zu den möglichen Eingabeparametern lässt sich
mit dem Kommando `help` ausgeben.

Aufruf:

----
xpb manage help
----

Ausgabe:

----
Usage: xpb manage [COMMAND]
Manage plans
Commands:
  help             Display help information about the specified command.
  list             List all plans that are available in the data storage.
  import           Import a single or multiple XPlanArchive(s) or XPlanGML file
                     (s).
  export           Export a single or multiple plan(s).
  delete           Delete a single or multiple plan(s).
  create-metadata  Create service metadata records.
----

[[xplanmanager-cli-auflistung]]
===== Auflistung

Das Kommando `list` gibt die Liste der Pläne aus, die im XPlanManager importiert sind.

Aufruf:

----
xpb manage list
----

Beispiel Ausgabe:

----
Anzahl Plaene: 24
- Id: 1, Version: XPLAN_40, Typ: BP_Plan, Name: Alsterdorf2_SoapUI-XPlanManagerAPI, Nummer: -, GKZ: 02000000, Raster: nein, Veroeffentlichungsdatum: null, Importiert: 2023-09-12 16:27:13.563
- Id: 2, Version: XPLAN_41, Typ: BP_Plan, Name: Eidelstedt4_SoapUI-XPlanManagerAPI, Nummer: -, GKZ: 02000000, Raster: nein, Veroeffentlichungsdatum: 1973-10-16 00:00:00.0, Importiert: 2023-09-12 16:27:17.844
- Id: 3, Version: XPLAN_41, Typ: BP_Plan, Name: Eidelstedt4_SoapUI-XPlanManagerAPI, Nummer: -, GKZ: 02000000, Raster: nein, Veroeffentlichungsdatum: 1973-10-16 00:00:00.0, Importiert: 2023-09-12 16:27:19.601
- Id: 4, Version: XPLAN_50, Typ: BP_Plan, Name: Alsterdorf24_SoapUI-XPlanManagerAPI, Nummer: -, GKZ: 02000000, Raster: ja, Veroeffentlichungsdatum: null, Importiert: 2023-09-12 16:27:20.639
- Id: 5, Version: XPLAN_50, Typ: BP_Plan, Name: DemoPlanAenderung_1_SoapUI-XPlanManagerAPI, Nummer: -, GKZ: 1234567, Raster: nein, Veroeffentlichungsdatum: 2007-04-01 00:00:00.0, Importiert: 2023-09-12 16:27:22.903
- Id: 6, Version: XPLAN_50, Typ: BP_Plan, Name: BPlan Demo-Gemeinde_SoapUI-XPlanManagerAPI, Nummer: -, GKZ: 1234567, Raster: nein, Veroeffentlichungsdatum: 2006-09-01 00:00:00.0, Importiert: 2023-09-12 16:27:22.924
- Id: 7, Version: XPLAN_52, Typ: BP_Plan, Name: Bahrenfeld74_SoapUI-XPlanManagerAPI, Nummer: -, GKZ: 02000000, Raster: nein, Veroeffentlichungsdatum: 2022-03-02 00:00:00.0, Importiert: 2023-09-12 16:27:27.488
- Id: 8, Version: XPLAN_52, Typ: BP_Plan, Name: xplan52-Laufrichtungsfehler_SoapUI-XPlanManagerAPI, Nummer: -, GKZ: 02000000, Raster: nein, Veroeffentlichungsdatum: null, Importiert: 2023-09-12 16:27:29.51
...
----

[[xplanmanager-cli-import]]
===== Import

Ein Import kann durch das Kommando `import`, gefolgt vom Pfad
zum XPlanArchiv, angestoßen werden. Bei dem Import können
XPlanGML-Vektordaten und XPlanGML-Rasterdaten ohne zusätzlichen
Parameter in die Datenhaltung geladen werden. Mehrere Pläne können durch Leerzeichen getrennt angegeben werden.

Beispiel Aufruf:

----
xpb manage import planwerk.zip
----

Während des Imports finden zahlreiche Konsistenz- und
Korrektheitsüberprüfungen statt. Dies betrifft u.a. Schemavalidität,
Geometrievalidität, Korrektheit von Links, Angabe von
Koordinatenreferenzsystemen, u.v.m.

Folgende Parameter können mit angegeben werden, um z. B. fehlende
Informationen anzugeben.

----
--force
--crs=EPSG:25832
----

_--force_

Enthält das XPlanGML-Dokument Geometriefehler o.ä., ist es
dringend angeraten, diese vor einem Import zu bereinigen. Der Import eines Planes kann mit dem Parameter `force` erzwungen werden.

CAUTION: Bitte beachten Sie, dass dabei vorliegenden Geometriefehler o.ä. übernommen werden und der importierte Plan dadurch fehlerhaft ist. Die
Auswirkungen können von einer fehlerhaften Darstellung des Plans bis hin zu unerwarteten Verhalten der xPlanBox reichen.

----
xpb import --force --files=planwerk.zip
----

_-–crs_

Fehlt die Angabe des Koordinatenreferenzsystems in den Daten, so kann
dieses mit dem Parameter `crs` übergeben werden.

Beispiel Aufruf:

----
xpb manage import --files=planwerk.zip --crs=EPSG:25832
----

Beispiel Ausgabe für erfolgreichen Import

----
Import des Plans /BPlan002_5-2.zip
...
- Analyse des XPlanArchivs ('/BPlan002_5-2.zip')... OK. [XPLAN_52, BP_Plan, EPSG:25832]
- Importiere Plan [XPLAN_52, BP_Plan, EPSG:25832]
- Ueberpruefung des raeumlichen Bezugssystems... OK, EPSG:25832
- Schema-Validierung (Hauptdokument)... OK [88 ms].
- Ueberpruefung der externen Referenzen... OK [0 ms]
- Insert XPlan
- Insert XPlan in XPlanDB
- Erzeugen der XPlan-Syn Features...
- Read rules from internal directory: /rules/xplan52.syn
- Read additional/overwriting rules from directory: /xplanbox/xplan-manager-config/synthesizer/xplan52.syn
- Configured codelist: codeList xplan_BP_SonstPlanArt.xml from directory /xplanbox/xplan-manager-config/synthesizer.
OK [2417 ms]
- Insert XPlan in XplanWFS/XPlanWMS
- Einfuegen von 3 Feature(s) in den FeatureStore (XPLAN_52)...
- Aktualisierung des Plans mit ID '25'
- Aktualisierung der XPlan-Features von Plan mit ID '25'
- Insert XPlan in XPlanSynWF
- Einfuegen von 3 Feature(s) in den FeatureStore (XPLAN_SYN)...
- Insert XPlan in XPlanDB
OK [2934 ms].
XPlanArchiv wurde erfolgreich importiert. Zugewiesene Id: 25
----

[[xplanmanager-cli-rasterdatenanalyse]]
===== Rasterdatenanalyse

Die Rasterdaten werden beim Import auf Nutzbarkeit überprüft werden,
damit sichergestellt ist, dass diese korrekt in den XPlanWMS
eingebettet werden können.
Die Prüfung beinhaltet das CRS des Rasterplans, sowie das Format.

Beispiel Aufruf:

----
xpb import --files=planwerk.zip
----

Beispiel Ausgabe:

----
Import des Plans /BPlan002_5-2.zip
...
- Rasterdatei mit Namen BP_4_020_Bleiche_Hirzberg_u_Schwarzwaldstrasse.tif gefunden.
- Koordinatensystem des Rasters: PROJCS[...["EPSG","25832"]]
- Evaluationsergebnis der referenzierten Rasterdaten:
  - Name: BP_4_020_Bleiche_Hirzberg_u_Schwarzwaldstrasse.tif Unterstuetztes CRS: Ja Unterstuetztes Bildformat: Ja
Die Rasterdaten des Plans sind valide
...
- XPlanArchiv wurde erfolgreich importiert. Zugewiesene Id: 25
...
- Erzeugen/Einsortieren der Rasterkonfigurationen (nach Datum: unbekannt )... OK [0 ms]
Rasterscans:
- BP_4_020_Bleiche_Hirzberg_u_Schwarzwaldstrasse.tif
----

Passt das CRS der Rasterdaten nicht mit dem CRS der Rasterdatenhaltung überein, so
erhält der Nutzer die Option, den Plan ohne Erzeugung der
Rasterkonfiguration zu importieren:

----
Evaluationsergebniss von referenzierten Rasterdaten:
  - Name: Abrundungssatzung_Gruhno_ergb.tif Unterstuetztes CRS: Kein Unterstuetztes Bildformat: Ja
Aufgrund invalider Rasterdaten wird der Import abgebrochen. Sie können den Import ohne die Erzeugung von Rasterkonfigurationen erzwingen, indem Sie die Option --force angeben.
----

[[xplanmanager-cli-export]]
===== Export

Der Export eines Planes erfolgt mit dem Kommando `export`,
gefolgt von der PlanID (diese kann zuvor mit dem Parameter `list` herausgefunden werden)
und dem Ausgabeverzeichnis. Mehrere PlanIDs können durch Leerzeichen getrennt angegeben werden.

Beispiel Aufruf:

----
xpb manage export --id=9 --target=../ausgabeverzeichnis
----

Beispiel Ausgabe für erfolgreichen Export:

----
- Schreibe Artefakt 'xplan.gml'...OK.
Plan 9 wurde nach 'xplan-exported-9.zip' exportiert.
----

[[xplanmanager-cli-loeschen]]
===== Löschen

Beim Löschen wird dem Kommando `delete` die PlanID (diese kann zuvor mit
`list` herausgefunden werden) übergeben. Mehrere PlanIDs können durch Leerzeichen getrennt angegeben werden.

Beispiel Aufruf:

----
xpb manage delete --id=21
----

Beispiel Ausgabe:

----
Delete XPlan 21
- Entferne XPlan 21 aus dem FeatureStore (XPLAN_SYN)... OK
- Entferne XPlan 21 aus dem FeatureStore (XPLAN_60)... OK
- Workspace reloader configuration is valid.
- Attempting to delete XPlanWerkWMS configuration with URL http://xplan-services:8080//xplan-wms/planwerkwmsapi/21
- Delete completed successfully.
XPlanArchiv mit Id 21 wurde gelöscht.
----

[[xplanmanager-metadaten-erzeugen]]
===== Erzeugen von Service-Metadatensätzen

Mit dieser Option können Metadatensätze für den XPlanWerkWMS erstellt werden. Bei der Erstellung der Informationen für die Capabilities des XPlanWerkWMS werden dabei bereits vorhandene Informationen überschrieben. Generierte Service-Metadatensätze werden nicht überschrieben, sondern können anhand des Zeitstempels im Dateinamen dem Zeitpunkt der Erstellung zugeordnet werden. Es wird jedoch ein neuer FileIdentifier generiert.
Für einzelne Pläne können Metadatensätze durch Angabe der PlanID (diese kann zuvor mit `list` herausgefunden werden) erzeugt werden. Mehrere PlanIDs können durch Leerzeichen getrennt angegeben werden. Wird keine PlanID angegeben, werden die Metadatensätze für alle Pläne erzeugt.

Beispiel Aufruf:

----
xpb manage create-metadata --ids=1
----

[[xplanmanager-cli-troubleshooting]]
===== Troubleshooting

Beim Import sehr großer Archive, kann es zu einem _OutOfMemoryError_
Laufzeitfehler kommen, da die Java Virtual Machine keinen weiteren
freien Speicher allokieren kann. Wenn der Server noch über freien
Arbeitsspeicher verfügt, dann kann dieser über die Umgebungsvariable
`JAVA_OPTS` unter Linux wie folgt erhöht werden:

----
export JAVA_OPTS='-Xmx4096m'
----

Weitere Informationen zur Konfiguration des Servers im Kapitel
<<bekannte-probleme,Bekannte Probleme - Kapazitätsbezogene Einschränkungen>> und
im Betriebshandbuch.
