[[xplanvalidator-web]]
=== XPlanValidatorWeb

Die Komponente XPlanValidatorWeb ist eine Web-Oberfläche, welche dem
Fachadministrator der xPlanBox ermöglicht, XPlanGML Instanzdokumente zu
validieren.

[[xplanvalidator-web-benutzungsanleitung]]
==== Benutzungsanleitung

Die Web-Anwendung XPlanValidatorWeb dient der Validierung von XPlanGML und
ist unter:

----
http://<host>:<port>/xplan-validator/
----

verfügbar kann mit einem gängigen Web-Browser aufgerufen werden.

[[xplanvalidator-web-hinzufuegen]]
===== XPlanArchiv Hinzufügen

Ein im lokalen Dateisystem vorliegendes XPlanArchiv kann über den Button _Durchsuchen_ ausgewählt und über
die Auswahl _Hochladen und Validierungsoption einstellen_ auf den Server
hochgeladen werden.

Nachdem die Datei erfolgreich übertragen wurde, erhält der Benutzer einen Hinweis, dass das XPlanArchiv in die Web-Anwendung
geladen wurde.

[[xplanvalidator-web--bezeichnung-der-validierung]]
===== Bezeichnung der Validierung

Für jede Validierung kann eine Bezeichnung vergeben werden, sodass der
Durchlauf zu einem späterem Zeitpunkt eindeutig zugeordnet werden kann.

[[xplanvalidator-web-validierungsart]]
===== Validierungstyp

Eine der folgenden Validierungstypen muss ausgewählt werden:

  * Einfache Validierung: Beinhaltet nur die syntaktische Validierung
  * Geometrische Validierung: Beinhaltet die syntaktische und geometrische Validierung
  * Vollständige Validierung: Beinhaltet die syntaktische, geometrische und semantische Validierung

[[xplanvalidator-web-validierungsoption]]
===== Validierungsoptionen

Die folgenden Validierungsoptionen für die geometrische Validierung können ausgewählt werden:

  * Selbstüberschneidungen ignorieren
  * falsche Laufrichtung von Polygonen ignorieren
  * Mindestabstand von Stützpunkten in Metern
  * Geometrische Prüfung der Flächenschlussbedingung (2.2.1.1) überspringen
  * Geometrische Prüfung des Geltungsbereichs (2.2.3.1) überspringen

[[xplanvalidator-web-validierung]]
===== Validierung

Die Validierung kann über den Button _Validierung starten_ gestartet werden.

[[xplanvalidator-web-validierungsergebnis]]
==== Validierungsergebnis

Das Ergebnis der Validierung kann im Anschluss als HTML, PDF und XML
Report herunter geladen werden. Je nachdem ob ein Geometriefehler
enthalten ist, können Geometriefehler zusätzlich auch als Shapefile und als Grafik
gespeichert werden.

Alle Ergebnisdateien werden in einem ZIP-Archiv gespeichert. Der
Dateiname enthält die Bezeichnung des Validierungsdurchlaufs.

[[xplanvalidator-web-kartenvorschau]]
==== Kartenvorschau

Über den Button _Kartenvorschau_ kann in die Kartenansicht des Plans gewechselt werden. Hier kann eine visuelle Überprüfung des Plans vorgenommen werden. Der Plan steht in der Kartenansicht nur für eine begrenzte Zeitspanne zur Verfügung, anschließend ist nur noch die Hintergrundkarte zu sehen.

[NOTE]
====

Die Kartenvorschau visualisiert ausschließlich die XPlanGML-Datei. Angehängte Rasterpläne werden beispielsweise nicht dargestellt.

====
