[[xplanmanager-web]]
=== XPlanManagerWeb

Die Komponente XPlanManagerWeb ist eine Web-Oberfläche, die dem
Fachadministrator der xPlanBox ermöglicht, die Datenhaltung zu
kontrollieren und zu verwalten.

[[xplanmanager-web-benutzungsanleitung]]
==== Einstiegsseite

Die Webanwendung XPlanManagerWeb kann mit einem Browser aufgerufen werden. Die Adresse der Webanwendung lautet:

----
http://<host>:<port>/xplan-manager-web/
----

==== Funktionen des XPlanManagerWeb

Mit dem XPlanManagerWeb kann der Benutzer <<xplanarchiv, XPlanArchive>> und <<xplangmlfile, XPlanGML-Dateien>> in die Datenhaltung laden, diese editieren und löschen sowie bereits importiere Planwerke wieder exportieren.

[[xplanmanager-web-hinzufuegen]]
===== Hinzufügen

Vor dem Importieren eines XPlanArchives oder XPlanGML-Dokuments in die Datenhaltung,
muss die Datei über die Web-Oberfläche hochgeladen und validiert werden.
Dazu muss die Datei ausgewählt und über den Browser hochgeladen werden. Hierfür kann die Datei über den Button _Durchsuchen_ ausgewählt und durch einen Klick auf
_Hinzufügen_ hochgeladen werden. Der Benutzer wird über den Abschluss des Vorgangs über einen Hinweis in einem PopUp-Fenster informiert.

[[xplanmanager-web-validieren]]
===== Validieren

Nachdem die Datei hochgeladen wurde, kann diese
validiert werden. Hier stehen die Auswahlmöglichkeiten des <<xplanvalidator-web-validieren, XPlanValidatorWeb>> zur Verfügung.

IMPORTANT: Bei der Validierung werden die syntaktische und basisgeometrische Prüfung (s. Abschnitt <<xplanvalidator-web-geometrisch, geometrische Validierung>>) immer mit ausgeführt. Diese Prüfungen stellen sicher, dass ein Plan keine schwerwiegenden Fehler enthält, die einen Import verhindern. Um die automatische Korrektur der Laufrichtung von Polygonen beim Import zu erzwingen, muss die Option "Prüfung der Laufrichtung (2.2.2.1) überspringen" aktiviert sein.

[[xplanmanager-web-import]]
===== Import

Wenn die Datei erfolgreich validiert wurde, kann der Plan in die Datenhaltung durch Klick auf den Button _Import_ in die Datenhaltung übernommen werden. Ist der Plan nicht valide, dann ist der Button _Import_ deaktiviert. Der Benutzer wird über den erfolgreichen bzw. fehlerhaften Import des Plans in Form eines PopUp-Fensters informiert.

Ist ein Import nicht möglich und soll ein anderer Plan importiert werden, dann kann der Plan über den Button _Entfernen_ aus der laufenden Sitzung entfernt werden.

[[xplanmanager-web-auflistung]]
===== Auflistung

Standardmäßig werden alle importierten Pläne in einer Liste angezeigt.
Die Liste kann nach den angezeigten Spaltennamen auf- oder absteigend sortiert werden. Sind mehr als 15 Pläne in der Auswahl, so wird unterhalb der Liste eine Navigation angezeigt, die ein seitenweises Vor- und Zurückblättern innerhalb der Ergebnismenge erlaubt.

[[xplanmanager-filter]]
===== Filter

Die Liste kann auch nach verschiedenen Kriterien gefiltert werden. Neben den beiden Filtern "Gemeindeauswahl" und "Planstatus" kann der Benutzer auch einen freien Filer auswählen und mit Klick auf den Button _Suche_ die Anzeige der Pläne reduzieren. Mit dem Button "Alle Pläne anzeigen" können alle Filter aufgehoben werden und es werden wieder alle Pläne angezeigt.

[[xplanmanager-web-kartenvorschau]]
===== Kartenvorschau

Durch den Klick auf den Button _Kartenvorschau_ öffnet sich ein neues
Fenster, indem der XPlan visualisiert wird. Im Hintergrund befindet sich
eine Hintergrundkarte. Durch den Klick auf _Schließen_ wird die
Kartenvorschau wieder geschlossen.

TIP: Der Browser verwendet bei der Kartenvorschau die Dateien aus dem Cache des Browsers. Wenn in der Kartenvorschau nicht der aktuelle Stand des Plans angezeigt wird, muss der Cache des Browsers gelöscht werden.

[[xplanmanager-web-herunterladen]]
===== Herunterladen

Die importierten Pläne können vom Benutzer durch den Klick auf den
Button _Herunterladen_ als XPlanArchiv heruntergeladen werden.

[[loeschen]]
===== Löschen

Je nach Benutzerrechten können importierten Pläne durch den Klick
auf den Button _Löschen_ aus der Datenhaltung gelöscht werden. Hat ein
Benutzer keine entsprechende Rechte, so wird der Button grau dargestellt.

[[xplanmanager-web-editieren]]
===== Editieren

Abhängig von den Benutzerrechten können Pläne editiert werden. Fehlen dem Benutzer die entsprechenden Rechte ist die Funktion deaktiviert und der Button __Editieren__ wird grau dargestellt.
Die Editieransicht öffnet sich durch Klick auf den Button __Editieren__. Die Ansicht ist in verschiedene Bereiche aufgeteilt, die die Bearbeitung einzelner Elemente im XPlanGML über die Oberfläche zulässt. Je nach Planart kann die Liste der änderbaren Elemente variieren. Unterstützt werden Bebauungspläne ab der Version 4.1, Flächennutzungspläne, Regionalpläne und Sonstige Pläne ab der Version 5.0 sowie Landschaftspläne ab der Version 6.0.

*Basisdaten*

Folgende Basisdaten eines Plans können geändert werden:

 * _name_
 * _beschreibung_
 * _technHerstellDatum_
 * _untergangsDatum_
 * _planArt_
 * _sonstPlanArt_
 * _rechtsstand_
 * _rechtsverordnungsDatum_

Alle Texteingaben werden von der Anwendung sowohl client- als auch serverseitig geprüft. Dabei sind die zugelassenen Zeichen (und Zeichenketten) limitiert und dienen dem Schutz vor Angriffen wie z. B. Cross Site Scripting (XSS) und SQL-Injection.

IMPORTANT: Das Editieren des Rechtsstands kann dazu führen, dass eine
Zustandsänderung des Plans eintritt. Damit verbunden ist das Verschieben
der Vektor- und Rasterdaten in die entsprechende Datenhaltung. Übergänge
zwischen den drei Zuständen 'Festgestellt', 'In
Aufstellung' und 'Archiviert' sind möglich. Eine Zustandsänderung von
'Festgestellt' nach 'In Aufstellung' tritt beispielsweise beim Ändern
des Rechtsstands von 'InkraftGetreten' nach 'Untergegangen' ein.

WARNING: Beim Import kann der Nutzer den Zustand eines Planes über eine
Auswahlliste mit den Optionen 'Festgestellt', 'In Aufstellung' und
'Archiviert' ändern. Abhängig von dem im Plan gesetzten Rechtsstand wird
eine Vorauswahl getroffen, die der Nutzer aber ändern kann. Beim
Öffnen der Editieransicht wird der Rechtsstand aus dem Plan
angezeigt und nicht der vom Nutzer zum Zeitpunkt des Imports ausgewählte Rechtsstand. Somit entspricht die Anzeige des Rechtsstands im Editor nicht
dem Zustand des Plans, falls dieser beim Import geändert wurde. Beim
Abspeichern von Änderungen ist somit Vorsicht geboten, da es so
unbeabsichtigt zu einer Zustandsänderung des Plans kommen kann!

*Gültigkeitszeitraum*

 * Der Zeitraum in dem ein Plan im XPlanWMSInAufstellung angezeigt wird. Für dieses Feld gibt es keine
Entsprechung im XPlanGML. Die Angabe des Zeitraums, wie sie beim Import
erfolgt ist, wird beim Ändern des Zeitraums überschrieben.

*Änderungen*

bis XPlanGML 5.4:

 * aendert
 * wurdeGeaendertVon

ab XPlanGML 6.0:

* aendertPlan
* wurdeGeaendertVonPlan

*Texte*

 * texte

*Dokumente*

Abhängig von der XPlanGML-Version können folgende Elemente editiert werden:

XPlanGML 4.1:

 * refBegruendung
 * refRechtsplan
 * refGruenordnungsplan

ab XPlanGML 5.0:

 * externeReferenz

Dabei kann der Benutzer wählen, ob er eine Datei über einen vollqualifizierten Link (URL) referenziert oder zum XPlanArchiv hinzugefügt und dann relativ verlinkt.

*Rasterbasis*

 * rasterBasis

Die Rasterbasis kann nur editiert werden, wenn ein Plan ein Objekt vom Typ BP|FP|LP|RP|SO_Bereich besitzt. Ist dies nicht der Fall, wird ein entsprechender Hinweis in der Oberfläche angegeben. Die Angabe einer Rasterbasis kann in diesem Fall nicht erfolgen.

Wie im Abschnitt <<referenzierung-von-rasterdaten-im-xplangml>> beschrieben, sind in den Versionen 5.1, 5.2, 5.3 und 5.4 zwei Varianten zur Referenzierung von Rasterdaten möglich. Die Anzeige im XPlanManager unterstützt die alte und die neue Variante. Wird über den XPlanManager eine Referenz geändert, dann erfolgt die Referenzierung immer über das Element `<refScan/>` unabhängig von der im Plan ursprünglich verwendeten Referenzierung.

NOTE: Werden Referenzen auf Rasterbasisdateien entfernt oder verändert, so werden die nicht mehr referenzierten Dateien aus der Datenhaltung entfernt. Änderungen führen zu einer Aktualisierung der XPlanWMS-Konfiguration. Klickt der Nutzer auf __Speichern__, wird zunächst eine Validierung der Rasterdaten
vorgenommen. Bei invaliden Dateien bekommt der Nutzer eine
Entscheidungsoption wie mit diesen Daten umgegangen werden soll. Stimmt das CRS der Rasterdaten nicht mit dem CRS der Rasterdatenhaltung überein, so
erhält der Nutzer die Option, den Plan ohne Erzeugung der
Rasterkonfiguration zu importieren.
Anschließend erfolgt die Aktualisierung der Daten.

Wie im Abschnitt <<referenzierung-von-rasterdaten-im-xplangml>> beschrieben, sind in den Versionen 5.1, 5.2, 5.3 und 5.4 noch zwei Varianten zur Referenzierung von Rasterdaten möglich. Die Anzeige im XPlanManager unterstützt die alte und die neue Variante. Wird über den XPlanManager eine Referenz geändert, dann erfolgt die Referenzierung immer über das Element `<refScan/>` unabhängig von der im Plan ursprünglich verwendeten Referenzierung.

Die ebenfalls in diesem Abschnitt editierbaren Referenzen auf Texte (refText) und Legenden (refLegende) müssen in den Versionen 5.1, 5.2, 5.3 und 5.4 über die Abschnitte `Texte` und `Dokumente` editiert werden.


[[xplanmanager-web-inspireplu]]
===== Bereitstellung als INSPIRE PLU Datensatz

Abhängig von den Benutzerrechten können Pläne im Datenthema INSPIRE Planned Land Use veröffentlicht werden. Fehlen dem Benutzer die entsprechenden Rechte ist die Funktion deaktiviert und der Button __Bereitstellung als INSPIRE Datensatz__ wird nicht dargestellt.

Durch Klick auf den Button __Bereitstellung als INSPIRE Datensatz__ wird der Plan in das INSPIRE PLU Datenschema transformiert. Anschließend kann der Plan über den INSPIRE Download Service (<<xplaninspirepluwfs,XPlanInspirePluWFS>>) und INSPIRE View Service (<<xplaninspirepluwms, XPlanInspirePluWMS>>) abgerufen werden.

NOTE: Die Bereitstellung als INSPIRE PLU Datensatz steht nur für BPläne in den XPlanGML-Versionen 4.1, 5.0, 5.1, 5.2, 5.3, 5.4 und 6.0 zur Verfügung.

[[xplanmanager-web-hilfe]]
===== Hilfe

Eine Hilfeseite mit einer Kurzbeschreibung der Funktionen des XPlanManagerWeb lässt sich durch Betätigen des Buttons _Hilfe_ anzeigen.