[[xplanmanager-cli]]
=== XPlanManager REST-API

Die REST-API des XPlanManager ermöglicht es, die Funktionen des XPlanManager über eine Web-API aufzurufen.
Die REST-API des XPlanManager stellt folgende Ressourcen bereit:

[width="100%",cols="25%,15%,60%",options="header",]
|===
|Ressource |HTTP Methode |Beschreibung
|`/` |`GET` |Beschreibung der Schnittstelle als OpenAPI 3.0 Dokument
|`/plan` |`POST` |Importieren eines XPlanGML-Dokuments oder XPlanArchivs
|`/plan/{planId}` |`GET` |Abfrage der Daten zu einem XPlanArchiv über PlanID
|`/plan/{planId}` |`DELETE` |Löschen eines XPlanArchivs
|`/plan/name/{planName}` |`GET` |Abfrage der Daten zu einem XPlanArchiv über den Plannamen
|`/plans/` |`GET` |Suche nach XPlanArchiven über den Plannamen
|`/info` |`GET` |Informationen zur Software und Konfiguration
|===

Eine vollständige Beschreibung der HTTP Status-Codes und der unterstützten Formate (Encodings) für die jeweiligen Ressourcen sind in der Schnittstellenbeschreibung enthalten.

NOTE: Die URL für die REST-API des XPlanManager setzt sich wie folgt zusammen: http://<host>:<port>/xplan-api-manager/api/v1/. Die URL für die xPlanBox-Demo lautet https://xplanbox.lat-lon.de/xmanager/api/v1/.

NOTE: Die alte REST-API mit den Ressourcen `/xplanmgrweb/rest/manager/plans` und `/xplanmgrweb/rest/manager/plan/{planId}` wird durch die neue
API komplett ersetzt und in einer zukünftigen Version der xPlanBox entfernt!