[[xplanmanager-grundlagen]]
=== XPlanManager Grundlagen

Der XPlanManager dient zur Verwaltung von XPlanArchiven innerhalb der xPlanBox. Mit
dem XPlanManager können XPlanArchive importiert, editiert oder gelöscht werden.
Nachdem ein XPlanArchiv erfolgreich über den XPlanManager importiert wurde, können die Daten über die Dienste
XPlanWFS und XPlanWMS abgerufen werden. Im folgenden Abschnitt werden die Anforderungen an ein XPlanArchiv beschrieben.

[[xplanarchiv]]
==== Das XPlanArchiv

Das XPlanArchiv ist eine ZIP-Datei mit folgendem Aufbau:

 * Im Basisverzeichnis muss das XPlanGML-Instanzdokument mit dem Dateinamen __xplan.gml__ vorhanden sein.
 * Rasterdaten sowie alle anderen im __xplan.gml__ referenzierten Anhänge müssen ebenfalls im Basisverzeichnis der ZIP-Datei liegen.

NOTE: *Wichtig*: Dateinamen dürfen keine Sonderzeichen wie z. B. `&`, `#` , `/`, `\`, `"`, `'` (doppeltes oder einfaches Anführungszeichen),
Leerzeichen oder auch Umlaute beinhalten. Gross- und Kleinschreibung in den Dateinamen (auch der Dateiendung) werden berücksichtigt
und müssen vollständig mit den Referenzen im Dokument übereinstimmen!

==== Das XPlanGML-Instanzdokument

Das XPlanGML-Instanzdokument muss folgende Eigenschaften aufweisen:

 * Das XPlanGML-Instanzdokument ist wohlgeformt und hat den Dateinamen __xplan.gml__.
 * Das XPlanGML-Instanzdokument beinhaltet nur ein Element vom Typ `<xplan:XP_PLAN/>`. Beinhaltet eine Datei mehrere Elemente, ist ein Import über den XPlanManager nicht möglich.

[[anlegen-von-deegree-konfigurationsstrukturen-fuer-rasterdaten]]
==== Anlegen von deegree Konfigurationsstrukturen für Rasterdaten

Beim Import von XPlanGML-Rasterdaten werden in der Datenbasis
Konfigurationen angelegt, welche die Visualisierung der Rasterdaten im
XPlanWMS ermöglichen.

Für jede importierte Rasterdatei werden folgende Konfigurationen
angelegt:

  * eine Konfigurationsdatei für einen GeoTiffTileStore oder
  GDALTileStore,
  * eine Konfigurationsdatei für einen TileLayer und
  * in der Ebenenbaum-Konfiguration wird ein neuer Layer in die
  Kategorieebene eingefügt, die die Rasterpläne nach Datum sortiert
  beinhaltet.

[[referenzierung-von-rasterdaten-im-xplangml]]
===== Referenzierung von Rasterdaten im XPlanGML

Die Rasterdaten müssen mit in dem Zip-Archiv verpackt sein und neben der
Datei __xplan.gml__ liegen.

Innerhalb des XPlanGML müssen die Rasterdateien wie folgt referenziert
sein:

*XPlanGML 3:*

Rasterdateien werden im Feature Type XP_RasterplanBasis,
XP_RasterplanAenderung, BP_RasterplanAenderung oder
FP_RasterplanAenderung über einen xlink referenziert:

----
gml:featureMember
  xplan:XP_RasterplanBasis
  (oder) xplan:XP_RasterplanAenderung
  (oder) xplan:BP_RasterplanAenderung
  (oder) xplan:FP_RasterplanAenderung
    xplan:refScan (mit xlink Attribut)
----

xlink zeigt auf den Feature Type XP_ExterneReferenz oder
XP_ExterneReferenzPlan:

----
gml:featureMember
  xplan:XP_ExterneReferenz
  (oder) xplan:XP_ExterneReferenzPlan (nur XPlanGML 3) (jeweils mit id Attribut)
    xplan:referenzName
    xplan:referenzURL
    xplan:referenzMimeType
    xplan:georefURL (falls Feature Type XP_ExterneReferenzPlan, nur XPlanGML 3)
    xplan:georefMimeType (falls Feature Type XP_ExterneReferenzPlan, nur XPlanGML 3)
----

Das Element referenzURL beinhaltet die relative Referenz auf die
Rasterdatei. Beispiel:

[source,xml]
----
<gml:featureMember>
    <xplan:XP_ExterneReferenzPlan gml:id="GML_1234567890">
        <xplan:referenzName>rasterdatei</xplan:referenzName>
        <xplan:referenzURL>rasterdatei.tif</xplan:referenzURL>
        <xplan:georefURL>rasterdatei.tfw</xplan:georefURL>
    </xplan:XP_ExterneReferenzPlan>
</gml:featureMember>
----

*XPlanGML 4.x:*

Rasterdateien werden im Feature Type XP_RasterplanBasis,
XP_RasterplanAenderung, BP_RasterplanAenderung, FP_RasterplanAenderung,
LP_RasterplanAenderung oder RP_RasterplanAenderung referenziert:

----
gml:featureMember
  xplan:XP_RasterplanBasis
  (oder) xplan:XP_RasterplanAenderung
  (oder) xplan:BP_RasterplanAenderung
  (oder) xplan:FP_RasterplanAenderung
  (oder) xplan:LP_RasterplanAenderung
  (oder) xplan:RP_RasterplanAenderung
    xplan:refScan (kann auch mehrfach vorkommen)
      xplan:XP_ExterneReferenz (jeweils mit id Attribut)
        xplan:georefURL
        xplan:art
        xplan:referenzName
        xplan:referenzURL
----

Das Element refScan kann beliebig häufig vorkommen. Das Element
referenzURL beinhaltet die relative Referenz auf die Rasterdatei.
Beispiel:

[source,xml]
----
<gml:featureMember>
    <xplan:XP_RasterplanBasis gml:id="FEATURE_1234567890">
        <xplan:refScan>
            <xplan:XP_ExterneReferenz>
                <xplan:georefURL>rasterdatei.tfw</xplan:georefURL>
                <xplan:art>PlanMitGeoreferenz</xplan:art>
                <xplan:referenzName>rasterdatei</xplan:referenzName>
                <xplan:referenzURL>rasterdatei.tif</xplan:referenzURL>
            </xplan:XP_ExterneReferenz>
        </xplan:refScan>
    </xplan:XP_RasterplanBasis>
</gml:featureMember>
----

*XPlanGML 5.x:*

Rasterdateien werden im Feature Type XP_Rasterdarstellung referenziert:

----
gml:featureMember
  xplan:XP_Rasterdarstellung
    xplan:refScan (kann auch mehrfach vorkommen)
      xplan:XP_ExterneReferenz (jeweils mit id Attribut)
        xplan:georefURL
        xplan:art
        xplan:referenzName
        xplan:referenzURL
----

Das Element refScan kann beliebig häufig vorkommen. Das Element
referenzURL beinhaltet die relative Referenz auf die Rasterdatei.
Beispiel:

[source,xml]
----
<gml:featureMember>
    <xplan:XP_Rasterdarstellung gml:id="FEATURE_1234567890">
        <xplan:refScan>
            <xplan:XP_ExterneReferenz>
                <xplan:georefURL>rasterdatei.tfw</xplan:georefURL>
                <xplan:art>PlanMitGeoreferenz</xplan:art>
                <xplan:referenzName>rasterdatei</xplan:referenzName>
                <xplan:referenzURL>rasterdatei.tif</xplan:referenzURL>
            </xplan:XP_ExterneReferenz>
        </xplan:refScan>
    </xplan:XP_RasterplanBasis>
</gml:featureMember>
----

In XPlanGML 5.1 und 5.2 ist diese Referenzierung als veraltet notiert. Stattdessen werden Rasterdateien über die von XP_Bereich abgeleiteten Feature Types referenziert (im folgendem Beispiel BP_Bereich):

----
gml:featureMember
  xplan:BP_Bereich
    xplan:refScan (kann auch mehrfach vorkommen)
      xplan:XP_ExterneReferenz (jeweils mit id Attribut)
        xplan:georefURL
        xplan:art
        xplan:referenzName
        xplan:referenzURL
----

Das Element refScan kann beliebig häufig vorkommen. Das Element
referenzURL beinhaltet die relative Referenz auf die Rasterdatei.
Beispiel:

[source,xml]
----
<gml:featureMember>
    <xplan:BP_Bereich gml:id="FEATURE_1234567890">
        ...
        <xplan:refScan>
            <xplan:XP_ExterneReferenz>
                <xplan:georefURL>rasterdatei.tfw</xplan:georefURL>
                <xplan:art>PlanMitGeoreferenz</xplan:art>
                <xplan:referenzName>rasterdatei</xplan:referenzName>
                <xplan:referenzURL>rasterdatei.tif</xplan:referenzURL>
            </xplan:XP_ExterneReferenz>
        </xplan:refScan>
        ...
    </xplan:XP_RasterplanBasis>
</gml:featureMember>
----

Ab Version 6.0 wird nur noch die zweite Variante unterstützt.

[[voraussetzungen-fuer-die-rasterdaten]]
===== Voraussetzungen für die Rasterdaten


Um Rasterdaten importieren und diese über den XPlanWMS-Ebene zur Verfügung
stellen zu können, müssen die Daten folgende Anforderungen erfüllen.

Die Unterstützung verschiedener Rasterdatentypen ist vom gesetzten
Raster-Konfigurationstyp abhängig.

NOTE: *Wichtig*: Dies kann nur zentral für die xPlanBox konfiguriert und nicht durch den Nutzer geändert werden.
Hinweise zur Konfiguration sind im Betriebshandbuch zu finden.**

Unterschieden wird dabei zwischen den Konfigurationstypen _GeoTiff_ und
__GDAL__:


*GeoTiff* - Konfigurationstyp:

  * Es werden ausschließlich Rasterdaten im GeoTiff Format unterstützt.

*GDAL* - Konfigurationstyp:

  * Grundsätzlich können alle durch GDAL unterstützten
  Rasterdatenformate auch durch deegree und somit dem XPlanManager
  verarbeitet werden.
  * Getestet wurden bisher nur die Formate GeoTiff und PNG.

Folgende Voraussetzung werden an die einzelnen Formate gestellt:


*GeoTiff*:

  * GeoTiff-Dateien liegen als gekachelte BIGTIFF GeoTiff-Dateien vor.
  * GeoTiff-Dateien liegen in dem Koordinatenreferenzsystem vor, welches
  für den XPlanManager konfiguriert ist.
  * GeoTiff-Dateien enthalten ihre räumliche Ausdehnung als Metatags innerhalb der Datei.
  * Zur Optimierung der Antwortzeit beim Zugriff auf die GeoTiff-Dateien
  wird empfohlen, in den GeoTiff-Dateien Overlays mit niedriger
  Auflösung hinzuzufügen.


*PNG*:

  * Farbmodell (RGB) mit ein, drei oder vier Bändern.
  * Farbtiefe ist 8bit, 16bit oder 256 indizierten Farben im Farbpalettenmodus.
  * Transparenz ist als Alphakanal je Band (RGBA) oder als "NoData Value" angegeben.
  * PNG-Dateien liegen in dem Koordinatenreferenzsystem vor, welches für
  den XPlanManager konfiguriert ist.
  * PNG-Dateien enthalten ihre räumliche Ausdehnung in einer
  ausgelagerten pgw-Datei (PNG World File).
  * Wenn das Kommandozeilentool XPlanManagerCLI verwendet wird, muss in
  einer aux.xml-Datei das Koordinatenreferenzsystem der PNGs definiert
  sein. Für den XPlanManagerWeb ist dies keine Voraussetzung, der
  Nutzer kann beim Import der Daten das Koordinatenreferenzsystem der
  PNG-Datei bestätigen.
