[[konfiguration-xplanwms-gfi]]
=== HTML-Template für XPlanWMS GFI
Nach der Installation ist in der Datei _html.gfi_ im Verzeichnis _<DEEGREE_WORKSPACE_ROOT>/xplan-services-wms-workspace/services_ die Anpassung der URL des XPlanWMS vorzunehmen.

Damit Links auf Dokumente in der WMS GetFeatureInfo (GFI) Ausgabe
auch bei externen Aufrufen funktionsfähig sind, muss eine Anpassung der URL in der Datei _html.gfi_
erfolgen. Die URL der Variable `WMS_URL` muss auf die öffentliche URL des XPlanWMS geändert werden, über die die Anhänge aus dem XPlanArchiv über die Operation GetAttachment des XPlanWMS bereitgestellt werden.

Vorgabewert in der Datei _html.gfi_:
----
var WMS_URL = "http://localhost:8080/xplan-services-wms";
----

Eine Übersicht der weiteren Konfigurationsdateien des XPlanWMS ist im Anhang <<appendix_xplanwms-workspace>> zu finden.

TIP: Wenn die relativen Referenzen bereits beim Import durch absolute URLs ersetzt werden, wie im Kapitel <<konfiguration-externe-refrenzen>> beschrieben, ist keine Konfiguration in der Datei _html.gfi_ erforderlich und der Vorgabewert kann beibehalten werden.