# template
.kaniko:build:
  stage: build:docker
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
  - /kaniko/executor --context=tar://${CI_PROJECT_DIR}/$tarGzFile --destination=$destination:$xplanboxVersion
    --build-arg="BUILD_DATE='$(date --utc +'%Y-%m-%d %H:%M:%SZ')'"
    --build-arg="DOCKER_IMAGE_NAME=$dockerImageName"
    --build-arg="GIT_REVISION=${CI_COMMIT_SHA}"
    --build-arg="XPLANBOX_IMAGE_NAME_PREFIX=${CI_REGISTRY_IMAGE}/xplanbox"
    --build-arg="XPLANBOX_VERSION=${xplanboxVersion}"
  rules:
  - if: $CI_PIPELINE_SOURCE == 'schedule'
    when: never 
  - if: $CI_COMMIT_TAG != null
    when: on_success
  - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    when: never 
  - when: on_success 
  variables:
    GIT_STRATEGY: none
    destination: ${CI_REGISTRY_IMAGE}/xplanbox/${dockerImageName}

## job per image to produce

kaniko:xplan-cli-docker:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-cli-docker
    tarGzFile: xplan-cli/xplan-cli-docker/target/docker/xplanbox/xplan-cli/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-cli
    - kaniko:xplan-docker-volume-init

kaniko:xplan-db-updater:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-db-updater
    tarGzFile: xplan-resources/xplan-database-scripts/target/docker/xplanbox/xplan-db-updater/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-others

kaniko:xplan-docker-tomcat-gdal:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-docker-tomcat-gdal
    tarGzFile: xplan-docker/xplan-docker-tomcat-gdal/target/docker/xplanbox/xplan-docker-tomcat-gdal/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-others
    - kaniko:xplan-docker-tomcat

kaniko:xplan-docker-tomcat:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-docker-tomcat
    tarGzFile: xplan-docker/xplan-docker-tomcat/target/docker/xplanbox/xplan-docker-tomcat/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-others

kaniko:xplan-docker-volume-init:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-docker-volume-init
    tarGzFile: xplan-docker/xplan-docker-volume-init/target/docker/xplanbox/xplan-docker-volume-init/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-others

kaniko:xplan-dokumente-api:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-dokumente-api
    tarGzFile: xplan-api/xplan-api-dokumente/target/docker/xplanbox/xplan-dokumente-api/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-apis-and-inspire-plu
    - kaniko:xplan-docker-tomcat

kaniko:xplan-inspireplu:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-inspireplu
    tarGzFile: xplan-webservices/xplan-inspireplu/target/docker/xplanbox/xplan-inspireplu/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-apis-and-inspire-plu

kaniko:xplan-manager-api:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-manager-api
    tarGzFile: xplan-api/xplan-api-manager/target/docker/xplanbox/xplan-manager-api/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-apis-and-inspire-plu
    - kaniko:xplan-docker-tomcat-gdal

kaniko:xplan-mapproxy:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-mapproxy
    tarGzFile: xplan-docker/xplan-docker-mapproxy/target/docker/xplanbox/xplan-mapproxy/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-others

kaniko:xplan-mapserver:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-mapserver
    tarGzFile: xplan-docker/xplan-docker-mapserver/target/docker/xplanbox/xplan-mapserver/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-others

kaniko:xplan-manager-web:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-manager-web
    tarGzFile: xplan-webapps/xplan-manager-web/target/docker/xplanbox/xplan-manager-web/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-web-apps
    - kaniko:xplan-docker-tomcat-gdal

kaniko:xplan-root:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-root
    tarGzFile: xplan-webapps/xplan-root/target/docker/xplanbox/xplan-root/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-web-apps
    
kaniko:xplan-services:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-services
    tarGzFile: xplan-webservices/xplan-services-docker/target/docker/xplanbox/xplan-services/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-others
    - kaniko:xplan-docker-tomcat-gdal

kaniko:xplan-tests-soapui:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-tests-soapui
    tarGzFile: xplan-tests/xplan-tests-soapui/target/docker/xplanbox/xplan-tests-soapui/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-others

kaniko:xplan-validator-api:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-validator-api
    tarGzFile: xplan-api/xplan-api-validator/target/docker/xplanbox/xplan-validator-api/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-apis-and-inspire-plu
    - kaniko:xplan-docker-tomcat
 

kaniko:xplan-validator-web:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-validator-web
    tarGzFile: xplan-webapps/xplan-validator-web/target/docker/xplanbox/xplan-validator-web/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-web-apps
    - kaniko:xplan-docker-tomcat

kaniko:xplan-validator-wms:
  extends: .kaniko:build
  variables:
    dockerImageName: xplan-validator-wms
    tarGzFile: xplan-webservices/xplan-validator-wms/target/docker/xplanbox/xplan-validator-wms/tmp/docker-build.tar.gz
  needs:
    - maven-prepare-docker-contexts-others
    - kaniko:xplan-docker-tomcat
