swagger: "2.0"
info:
  title: "XPlanManagerAPI"
  description: "XPlanManager REST API"
  version: "0.0.1"
  termsOfService: "http://xplanbox.lat-lon.de/terms/"
  contact:
    email: "info@lat-lon.de"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "xplanbox.lat-lon.de"
basePath: "/api/v1"
tags:
  - name: "validate"
    description: "Validate XPlanGML documents"
    externalDocs:
      description: "xPlanBox"
      url: "http://xplanbox.lat-lon.de"
  - name: "manage"
    description: "Manage XPlanGML documents"
    externalDocs:
      description: "xPlanBox"
      url: "http://xplanbox.lat-lon.de"
schemes:
  - "https"
  - "http"
paths:
  /validate:
    post:
      tags:
        - "validate"
      summary: "Upload XPlanGML or XPlanArchive"
      description: "Uploads XPlanGML or XPlanArchive file"
      operationId: "upload"
      consumes:
        - "multipart/form-data"
        - "application/xml"
        - "text/xml"
        - "application/zip"
        - "application/gml+xml"
      produces:
        - "application/json"
      parameters:
        - in: "formData"
          name: "body"
          description: "XPlanGML or XPlanArchive file to upload"
          required: true
          #TODO should use multipart upload with content type
          type: file
          #schema:
          #  $ref: "#/definitions/XPlanGML"
        - in: "header"
          name: "X-Filename"
          description: "Name of the file to be uploaded"
          type: string
          required: false
      responses:
        "200":
          description: "successful upload confirmed by session ID"
          schema:
            $ref: "#/definitions/UploadReport"
        "406":
          description: "Invalid input"
        default:
          description: "Unexpected error"
  /validate/{sessionId}:
    get:
      tags:
        - "validate"
      summary: "Validate uploaded XPlanGML or XPlanArchive"
      description: "Start validation using the given parameters"
      operationId: "validate"
      produces:
        - "application/json"
      parameters:
        - name: "sessionId"
          in: "path"
          description: "Session ID of the validation"
          required: true
          type: "string"
        - name: "name"
          in: "query"
          description: "Name of the validation"
          required: false
          type: "string"
        - name: "skipGeometrisch"
          in: "query"
          description: "Geometrische Validierung ueberspringen"
          required: false
          type: "boolean"
          default: "false"
        - name: "skipSemantisch"
          in: "query"
          description: "Semantische Validierung ueberspringen"
          required: false
          type: "boolean"
          default: "false"
        - name: "skipFlaechenschluss"
          in: "query"
          description: "Ueberpruefung des Flaechenschluss ueberspringen"
          required: false
          type: "boolean"
          default: "false"
        - name: "skipGeltungsbereich"
          in: "query"
          description: "Ueberpruefung des Geltungsbereich ueberspringen"
          required: false
          type: "boolean"
          default: "false"
      responses:
        "200":
          description: "successful validation"
          schema:
            $ref: "#/definitions/ValidationReport"
        "400":
          description: "Invalid value for session ID"
        "404":
          description: "Session ID is invalid, not found"
        default:
          description: "Unexpected error"
  /import/{sessionId}:
    put:
      tags:
        - "manage"
      summary: "Import the plan for the given session ID"
      description: "Imports the plan for the given session ID"
      operationId: "import"
      produces:
        - "application/json"
      parameters:
        - name: "sessionId"
          in: "path"
          description: "Session ID of the validation"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ValidationReport"
        "400":
          description: "Invalid value for session ID"
        "404":
          description: "Session ID is invalid, not found"
        default:
          description: "Unexpected error"
  /plan/{planId}:
    get:
      tags:
        - "manage"
      summary: "Get plan identified by the given plan ID"
      description: "Returns an existing plan identified by the given plan ID"
      operationId: "get"
      consumes:
        - "application/json"
        - "application/xml"
        - "text/xml"
      produces:
        - "application/json"
        - "application/xml"
        - "application/zip"
      parameters:
        - name: "planId"
          in: "path"
          description: "ID of the plan to be returned"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Status"
        "400":
          description: "Invalid tag value"
        "404":
          description: "Invalid plan ID, not found"
    post:
      tags:
        - "manage"
      summary: "Update plan identified by the given plan ID"
      description: "Updates an existing plan identified by the given plan ID"
      operationId: "update"
      consumes:
        - "application/json"
        - "application/xml"
        - "text/xml"
      produces:
        - "application/json"
      parameters:
        - name: "planId"
          in: "path"
          description: "ID of the plan to be updated"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Status"
        "400":
          description: "Invalid tag value"
        "404":
          description: "Invalid plan ID, not found"
    delete:
      tags:
        - "manage"
      summary: "Delete plan identified by the given plan ID"
      description: "Deletes an existing plan identified by the given plan ID"
      operationId: "delete"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "planId"
          in: "path"
          description: "ID of the plan to be removed"
          required: true
          type: "string"
      responses:
        "204":
          description: "successful operation"
        "400":
          description: "Invalid tag value"
        "404":
          description: "Invalid plan ID, not found"
  /plan/name/{planName}:
    get:
      summary: "Get plan identified by the given planName"
      description: "Returns an existing plan identified by the given planName"
      parameters:
        - name: "planName"
          in: "path"
          description: "planName of the plan to be return"
          required: true
          type: "string"
      responses:
        "200":
          description: OK
        "404":
          description: "Invalid plan name, not found"
  /plans:
    get:
      summary: "Search for plan by name"
      description: "Returns a list of plans which match the search query"
      parameters:
        - name: "planName"
          in: "query"
          type: "string"
          description: "The name of the plan to search for"
      responses:
        200:
          description: OK
  /plan/{planId}/inspireplu:
    post:
      tags:
        - "manage"
      summary: "Publish plan identified by the given plan id"
      description: "Publishs plan identified by the given plan id"
      operationId: "publish"
      parameters:
        - name: "planId"
          in: "path"
          description: "ID of the plan to be removed"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ValidationReport"
        "400":
          description: "Invalid value for session ID"
        "404":
          description: "Session ID is invalid, not found"
        default:
          description: "Unexpected error"
  /config:
    get:
      summary: "Show system and application configuration"
      description: "Returns the system and application configuration"
      operationId: "config"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SystemConfig"
definitions:
  XPlanGML:
    type: "object"
  UploadReport:
    type: "object"
    properties:
      sessionId:
        type: string
        format: uuid
        example: A4AFBBC4770232049A45C6F315D66236
      wmsUrl:
        type: string
        example: https://xplanbox.lat-lon.de/xplan-validator-wms/services/wms?PLANWERK_MANAGERID=13
  ValidationReport:
    type: "object"
  Status:
    type: boolean
  SystemConfig:
    type: "object"
    properties:
      crs:
        type: string
        example: "epsg:2835"
      raster:
        type: string
        example: "gdal or tiff"
      version:
        type: string
        example: "v3.3.0"





