openapi: 3.0.1
info:
  title: XPlanManagerAPI
  description: XPlanManager REST API
  termsOfService: http://xplanbox.lat-lon.de/terms/
  contact:
    email: info@lat-lon.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.4
servers:
  - url: https://xplanbox.lat-lon.de/xmanager/api/v1
  - url: http://xplanbox.lat-lon.de/xmanager/api/v1
tags:
  - name: manage
    description: Manage XPlanGML documents
    externalDocs:
      description: xPlanBox
      url: http://xplanbox.lat-lon.de
  - name: search
    description: Search for XPlanGML documents
    externalDocs:
      description: xPlanBox
      url: http://xplanbox.lat-lon.de
paths:
  /:
    get:
      summary: OpenAPI document
      description: API documentation
      operationId: openApi
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
  /plan:
    post:
      tags:
        - manage
      summary: Import the plan
      description: Imports the plan
      operationId: import
      parameters:
        - name: X-Filename
          in: header
          description: Name of the file to be uploaded
          example: File names such as xplan.gml, xplan.xml, xplan.zip
          schema:
            type: string
        - name: skipSemantisch
          in: query
          description: Semantische Validierung ueberspringen
          schema:
            type: boolean
            default: false
        - name: skipGeometrisch
          in: query
          description: Geometrische Validierung ueberspringen
          schema:
            type: boolean
            default: false
        - name: skipFlaechenschluss
          in: query
          description: Ueberpruefung des Flaechenschluss ueberspringen
          schema:
            type: boolean
            default: false
        - name: skipGeltungsbereich
          in: query
          description: Ueberpruefung des Geltungsbereich ueberspringen
          schema:
            type: boolean
            default: false
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
              description: XPlanArchive (application/zip) file to upload
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        400:
          description: Invalid input
        405:
          description: Invalid method
        406:
          description: Invalid content only ZIP with XPlanGML is accepted
        415:
          description: Unsupported Media Type, only ZIP is accepted
        default:
          description: Unexpected error
          content: {}
  /plan/{planId}:
    get:
      tags:
        - manage
        - search
      summary: Get plan identified by the given plan ID
      description: Returns an existing plan identified by the given plan ID
      operationId: getById
      parameters:
        - name: planId
          in: path
          description: ID of the plan to be returned
          example: '123'
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanInfo'
            application/xml:
              schema:
                $ref: '#/components/schemas/PlanInfo'
            application/zip:
              schema:
                type: string
                format: binary
        400:
          description: Invalid tag value
          content: {}
        404:
          description: Invalid plan ID, not found
          content: {}
    delete:
      tags:
        - manage
      summary: Delete plan identified by the given plan ID
      description: Deletes an existing plan identified by the given plan ID
      operationId: delete
      parameters:
        - name: planId
          in: path
          description: ID of the plan to be removed
          example: '123'
          required: true
          schema:
            type: string
      responses:
        204:
          description: successful operation
          content: {}
        400:
          description: Invalid tag value
          content: {}
        404:
          description: Invalid plan ID, not found
          content: {}
  /plan/name/{planName}:
    get:
      tags:
        - search
      summary: Get plan identified by the given planName
      description: Returns an existing plan identified by the given planName
      operationId: getByName
      parameters:
        - name: planName
          in: path
          description: planName of the plan to be return
          example: 'bplan_123, fplan-123, rplan20200803'
          required: true
          schema:
            type: string
            pattern: '^[A-Za-z0-9_-]*$'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanInfo'
            application/xml:
              schema:
                $ref: '#/components/schemas/PlanInfo'
            application/zip:
              schema:
                type: string
                format: binary
        404:
          description: Invalid plan name, not found
          content: {}
  /plans:
    get:
      tags:
        - search
      summary: Search for plan by name
      description: Returns a list of plans which match the search query
      operationId: findByName
      parameters:
        - name: planName
          in: query
          description: The name of the plan to search for
          example: 'bplan_123, fplan-123, rplan20200803'
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlanInfo'
  /info:
    get:
      summary: Show system and application configuration
      description: Returns the system and application configuration
      operationId: showConfig
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManagerSystemConfig'
components:
  schemas:
    PlanInfo:
      type: object
      properties:
        id:
          type: integer
          example: 123
        name:
          type: string
          example: "Othmarschen3"
        description:
          type: string
          example: "Beschreibung des BPlan"
        type:
          type: string
          example: "BP_Plan"
        additionalType:
          type: string
        version:
          type: string
          example: "XPLAN_51"
        number:
          type: string
          example: "-"
        internalId:
          type: string
          example: "12341"
        gkz:
          type: string
          example: "02000000"
        gemeinde:
          type: string
          example: "Gemeinde"
        raster:
          type: boolean
          example: true
        legislationStatus:
          type: string
          example: "Satzung"
        releaseDate:
          type: string
          format: date-time
        importDate:
          type: string
          format: date-time
        valid:
          type: boolean
          example: true
        inspirePublished:
          type: boolean
          example: false
        bbox:
          type: object
          properties:
            minX:
              type: integer
              example: 9.880772
            minY:
              type: integer
              example: 53.544973
            maxX:
              type: integer
              example: 9.890302
            maxY:
              type: integer
              example: 53.546704
            crs:
              type: string
              example: epsg:4326
        xplanMetadata:
          type: object
          properties:
            planStatus:
              type: string
              example: "FESTGESTELLT"
            startDateTime:
              type: string
              format: date-time
            endDateTime:
              type: string
              format: date-time
        links:
          type: array
          description: Links related to the resource such as XPlanWerkWMS or self link
          items:
            $ref: '#/components/schemas/Link'
          example:
            href: https://xplanbox.lat-lon.de/xplan-wms/services/planwerkwms/planname/<PLANNAME>?
            rel: planwerkwms
            type: image/png
            hreflang: de
            title: Othmarschen 3
    Status:
      description: Status
      type: object
      properties:
        planId:
          type: integer
          example: '123'
        link:
          type: string
          format: uri
          example: https://xplanbox.lat-lon.de/xmanager/api/v1/plan/123
        validationReport:
          $ref: '#/components/schemas/ValidationReport'
    Link:
      type: object
      description: Link to a resource related to the resource such as XPlanWerkWMS or the resource itself
      required:
        - href
      properties:
        href:
          type: string
          format: uri
          example: https://xplanbox.lat-lon.de/xmanager/api/v1/plan/123
        rel:
          type: string
          enum: [self,alternate,planwerkwms]
          example: self
        type:
          type: string
          example: application/json
        hreflang:
          type: string
          example: en
        title:
          type: string
          example: Othmarschen 3, Hamburg
        length:
          type: integer
    ValidationReport:
      type: object
      properties:
        filename:
          type: string
          example: xplan52-test.gml
        name:
          type: string
          example: xplan52-test
        date:
          type: string
          format: date-time
          example: '2020-08-24T15:06:36.662Z'
        valid:
          type: boolean
          example: false
        externalReferences:
          type: array
          items:
            type: string
            example: 'stelling.png'
        wmsUrl:
          type: string
          format: uri
          example: https://xplanbox.lat-lon.de/xplan-validator-wms/services/wms?PLANWERK_MANAGERID=13
        rulesMetadata:
          $ref: '#/components/schemas/RulesMetadata'
        validationResult:
          type: object
          properties:
            semantisch:
              type: object
              properties:
                valid:
                  type: boolean
                  example: false
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      isValid:
                        type: boolean
                      message:
                        type: string
                      invalidFeatures:
                        type: array
                        items:
                          type: string
                          description: GML-ID
                          example: GML_b4e47d29-d21c-42ab-85b7-b12ea57e89f2
            geometrisch:
              type: object
              properties:
                valid:
                  type: boolean
                  example: false
                errors:
                  type: array
                  items:
                    type: string
                warnings:
                  type: array
                  items:
                    type: string
            syntaktisch:
              type: object
              properties:
                valid:
                  type: boolean
                  example: false
                messages:
                  type: array
                  items:
                    type: string
    RulesMetadata:
      type: object
      properties:
        version:
          type: string
          example: 0.9.14
        source:
          type: string
          example: 'https://bitbucket.org/geowerkstatt-hamburg/xplanung/get/v0.9.14.zip'
    SystemConfig:
      type: object
      properties:
        version:
          description: Version der xPlanBox
          type: string
          example: 'v3.4.0'
        rulesMetadata:
          $ref: '#/components/schemas/RulesMetadata'
    ManagerSystemConfig:
      allOf:
        - $ref: '#/components/schemas/SystemConfig'
        - type: object
          properties:
            rasterCrs:
              description: 'Konfiguriertes CRS für die Rasterdatenhaltung'
              type: string
              example: 'epsg:28352'
            rasterType:
              description: 'Typ der Rasterdatenhaltung: gdal oder tiff'
              type: string
              example: 'gdal'
            skipSemantisch:
              description: 'Semantische Validierung bei Import ueberspringen'
              type: boolean
              default: false
            skipGeometrisch:
              description: 'Geometrische Validierung bei Import ueberspringen'
              type: boolean
              default: false
            skipFlaechenschluss:
              description: 'Ueberpruefung des Flaechenschluss bei Import ueberspringen'
              type: boolean
              default: false
            skipGeltungsbereich:
              description: 'Ueberpruefung des Geltungsbereich bei Import ueberspringen'
              type: boolean
              default: false