CREATE TABLE FEATURE_TYPES (id smallint PRIMARY KEY, qname text NOT NULL);
COMMENT ON TABLE FEATURE_TYPES IS 'Ids and bboxes of concrete feature types';
SELECT ADDGEOMETRYCOLUMN('public', 'feature_types','bbox','0','GEOMETRY',2);
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (0,'{http://inspire.ec.europa.eu/schemas/ad/4.0}Address');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (1,'{http://inspire.ec.europa.eu/schemas/ad/4.0}AddressAreaName');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (2,'{http://inspire.ec.europa.eu/schemas/ad/4.0}AdminUnitName');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (3,'{http://inspire.ec.europa.eu/schemas/ad/4.0}PostalDescriptor');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (4,'{http://inspire.ec.europa.eu/schemas/ad/4.0}ThoroughfareName');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (5,'{http://inspire.ec.europa.eu/schemas/au/4.0}AdministrativeBoundary');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (6,'{http://inspire.ec.europa.eu/schemas/au/4.0}AdministrativeUnit');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (7,'{http://inspire.ec.europa.eu/schemas/au/4.0}Condominium');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (8,'{http://inspire.ec.europa.eu/schemas/cp/4.0}BasicPropertyUnit');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (9,'{http://inspire.ec.europa.eu/schemas/cp/4.0}CadastralBoundary');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (10,'{http://inspire.ec.europa.eu/schemas/cp/4.0}CadastralParcel');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (11,'{http://inspire.ec.europa.eu/schemas/cp/4.0}CadastralZoning');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (12,'{http://inspire.ec.europa.eu/schemas/gn/4.0}NamedPlace');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (13,'{http://inspire.ec.europa.eu/schemas/net/4.0}CrossReference');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (14,'{http://inspire.ec.europa.eu/schemas/net/4.0}GradeSeparatedCrossing');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (15,'{http://inspire.ec.europa.eu/schemas/net/4.0}Network');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (16,'{http://inspire.ec.europa.eu/schemas/net/4.0}NetworkConnection');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (17,'{http://inspire.ec.europa.eu/schemas/plu/4.0}OfficialDocumentation');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (18,'{http://inspire.ec.europa.eu/schemas/plu/4.0}SpatialPlan');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (19,'{http://inspire.ec.europa.eu/schemas/plu/4.0}SupplementaryRegulation');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (20,'{http://inspire.ec.europa.eu/schemas/plu/4.0}ZoningElement');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (21,'{http://inspire.ec.europa.eu/schemas/tn/4.0}AccessRestriction');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (22,'{http://inspire.ec.europa.eu/schemas/tn/4.0}ConditionOfFacility');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (23,'{http://inspire.ec.europa.eu/schemas/tn/4.0}MaintenanceAuthority');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (24,'{http://inspire.ec.europa.eu/schemas/tn/4.0}MarkerPost');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (25,'{http://inspire.ec.europa.eu/schemas/tn/4.0}OwnerAuthority');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (26,'{http://inspire.ec.europa.eu/schemas/tn/4.0}RestrictionForVehicles');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (27,'{http://inspire.ec.europa.eu/schemas/tn/4.0}TrafficFlowDirection');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (28,'{http://inspire.ec.europa.eu/schemas/tn/4.0}TransportNetwork');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (29,'{http://inspire.ec.europa.eu/schemas/tn/4.0}VerticalPosition');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (30,'{http://www.opengis.net/gmlcov/1.0}GridCoverage');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (31,'{http://www.opengis.net/gmlcov/1.0}MultiCurveCoverage');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (32,'{http://www.opengis.net/gmlcov/1.0}MultiPointCoverage');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (33,'{http://www.opengis.net/gmlcov/1.0}MultiSolidCoverage');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (34,'{http://www.opengis.net/gmlcov/1.0}MultiSurfaceCoverage');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (35,'{http://www.opengis.net/gmlcov/1.0}RectifiedGridCoverage');
INSERT INTO FEATURE_TYPES  (id,qname) VALUES (36,'{http://www.opengis.net/gmlcov/1.0}ReferenceableGridCoverage');
CREATE TABLE GML_OBJECTS (id serial PRIMARY KEY, gml_id text UNIQUE NOT NULL, ft_type smallint REFERENCES FEATURE_TYPES , binary_object bytea);
COMMENT ON TABLE GML_OBJECTS IS 'All objects (features and geometries)';
SELECT ADDGEOMETRYCOLUMN('public', 'gml_objects','gml_bounded_by','0','GEOMETRY',2);
ALTER TABLE GML_OBJECTS ADD CONSTRAINT gml_objects_geochk CHECK (ST_IsValid(gml_bounded_by));
CREATE INDEX gml_objects_sidx ON GML_OBJECTS  USING GIST (gml_bounded_by);
