Configuration:
  name: XPlanManagerCli
  status: warn
  Properties:
    Property:
      - name: log.file
        value: xplan-manager-cli.log
      - name: log.path
        value: ${sys:catalina.base:-.}/logs
  Appenders:
    Console:
      name: STDOUT
      target: SYSTEM_OUT
      PatternLayout:
        Pattern: "%d %p %C{1.} [%t] %m%n"
    RollingFile:
      name: RollingFile_Appender
      fileName: ${log.path}/${log.file}
      filePattern: ${log.path}/${log.file}.%d{yyyy-MM-dd-hh-mm}
      PatternLayout:
        pattern: "%d %p %C{1.} [%t] %m%n"
      Policies:
        SizeBasedTriggeringPolicy:
          size: 100 MB
      DefaultRollOverStrategy:
        max: 2
  Loggers:
    Root:
      AppenderRef:
        - ref: STDOUT
          level: error
        - ref: RollingFile_Appender
          level: info
    Logger:
      - name: org.deegree
        level: info
      - name: de.latlon.xplan
        level: info
      - name: org.springframework
        level: warn
      - name: org.reflections
        level: fatal
      - name: org.deegree.geometry.standard.AbstractDefaultGeometry
        level: info
      - name: de.latlon.xplan.validator.geometric.XPlanGeometryInspector
        level: info