pipeline {
   agent any
   tools {
      maven 'maven-3.8'
      jdk 'openjdk11'
   }
   stages {
      stage('Test XPlanManagerAPI') {
         steps {
            withCredentials([
               usernamePassword(credentialsId:'xplanbox.lat-lon.de', passwordVariable: 'Password', usernameVariable: 'Username')
            ]) {
               sh 'mvn test -pl :xplan-tests-soapui -Pintegration-tests -DtestFileName=xplan-api-manager-soapui-project.xml -Dendpoint=https://xplanbox.lat-lon.de/xmanager/api/v1 -Dusername=$Username -Dpassword=$Password'
            }
         }
      }

      stage('Test XPlanValidatorAPI') {
         steps {
            withCredentials([
               usernamePassword(credentialsId:'xplanbox.lat-lon.de', passwordVariable: 'Password', usernameVariable: 'Username')
            ]) {
               sh 'mvn test -pl :xplan-tests-soapui -Pintegration-tests -DtestFileName=xplan-api-validator-soapui-project.xml -Dendpoint=https://xplanbox.lat-lon.de/xvalidator/api/v1 -Dusername=$Username -Dpassword=$Password'
            }
         }
      }

      stage('Test XPlanManagerWeb') {
         steps {
            withCredentials([
               usernamePassword(credentialsId:'xplanbox.lat-lon.de', passwordVariable: 'Password', usernameVariable: 'Username')
            ]) {
               sh 'mvn test -pl :xplan-tests-soapui -Pintegration-tests -DtestFileName=xplan-manager-web-soapui-project.xml -Dendpoint=https://xplanbox.lat-lon.de/xplan-manager-web -Dusername=$Username -Dpassword=$Password'
            }
         }
      }

      stage('Test XPlanDienste') {
         steps {
            withCredentials([
               usernamePassword(credentialsId:'xplanbox.lat-lon.de', passwordVariable: 'Password', usernameVariable: 'Username')
            ]) {
               sh 'mvn test -pl :xplan-tests-soapui  -Pintegration-tests -DtestFileName=xplan-webservices-soapui-project.xml -DbaseUrl=https://xplanbox.lat-lon.de -DbaseUrlInspirePlu=https://xplanbox.lat-lon.de -DbaseUrlManagerApi=https://xplanbox.lat-lon.de -Dusername=$Username -Dpassword=$Password'
            }
         }
      }

      stage('Results') {
         steps{
            junit '**/**/target/soapui/TEST-*.xml'
         }
      }
   }
}
