/* --- BEGIN schema setup --- */
CREATE SCHEMA xplan2;
SET search_path TO xplan2,public;
/* --- END schema setup --- */

/* --- BEGIN global section --- */
CREATE TABLE feature_types (id smallint PRIMARY KEY, qname text NOT NULL);
COMMENT ON TABLE feature_types IS 'Ids and bboxes of concrete feature types';
SELECT ADDGEOMETRYCOLUMN('xplan2', 'feature_types','bbox','-1','GEOMETRY',2);
INSERT INTO feature_types  (id,qname) VALUES (0,'{http://www.opengis.net/gml}MultiPointCoverage');
INSERT INTO feature_types  (id,qname) VALUES (1,'{http://www.opengis.net/gml}RectifiedGridCoverage');
INSERT INTO feature_types  (id,qname) VALUES (2,'{http://www.xplanung.de/xplangml}BP_AbgrabungsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (3,'{http://www.xplanung.de/xplangml}BP_AbstandsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (4,'{http://www.xplanung.de/xplangml}BP_AnpflanzungBindungErhaltung');
INSERT INTO feature_types  (id,qname) VALUES (5,'{http://www.xplanung.de/xplangml}BP_AufschuettungsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (6,'{http://www.xplanung.de/xplangml}BP_Ausgleich');
INSERT INTO feature_types  (id,qname) VALUES (7,'{http://www.xplanung.de/xplangml}BP_BahnVerkehr');
INSERT INTO feature_types  (id,qname) VALUES (8,'{http://www.xplanung.de/xplangml}BP_BauGrenze');
INSERT INTO feature_types  (id,qname) VALUES (9,'{http://www.xplanung.de/xplangml}BP_BauLinie');
INSERT INTO feature_types  (id,qname) VALUES (10,'{http://www.xplanung.de/xplangml}BP_Baugebiet');
INSERT INTO feature_types  (id,qname) VALUES (11,'{http://www.xplanung.de/xplangml}BP_BaugebietsTeilFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (12,'{http://www.xplanung.de/xplangml}BP_Bereich');
INSERT INTO feature_types  (id,qname) VALUES (13,'{http://www.xplanung.de/xplangml}BP_BereichOhneEinAusfahrtLinie');
INSERT INTO feature_types  (id,qname) VALUES (14,'{http://www.xplanung.de/xplangml}BP_BesondererNutzungszweckFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (15,'{http://www.xplanung.de/xplangml}BP_BodenschaetzeFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (16,'{http://www.xplanung.de/xplangml}BP_DenkmalschutzEinzelanlagePunkt');
INSERT INTO feature_types  (id,qname) VALUES (17,'{http://www.xplanung.de/xplangml}BP_DenkmalschutzEnsembleFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (18,'{http://www.xplanung.de/xplangml}BP_EinfahrtPunkt');
INSERT INTO feature_types  (id,qname) VALUES (19,'{http://www.xplanung.de/xplangml}BP_EinfahrtsbereichLinie');
INSERT INTO feature_types  (id,qname) VALUES (20,'{http://www.xplanung.de/xplangml}BP_ErhaltungsBereichFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (21,'{http://www.xplanung.de/xplangml}BP_Fachgesetz');
INSERT INTO feature_types  (id,qname) VALUES (22,'{http://www.xplanung.de/xplangml}BP_FestsetzungenBaugebiet');
INSERT INTO feature_types  (id,qname) VALUES (23,'{http://www.xplanung.de/xplangml}BP_FirstRichtungsLinie');
INSERT INTO feature_types  (id,qname) VALUES (24,'{http://www.xplanung.de/xplangml}BP_FoerderungsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (25,'{http://www.xplanung.de/xplangml}BP_FreiFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (26,'{http://www.xplanung.de/xplangml}BP_GebaeudeFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (27,'{http://www.xplanung.de/xplangml}BP_GemeinbedarfsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (28,'{http://www.xplanung.de/xplangml}BP_GemeinschaftsanlagenFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (29,'{http://www.xplanung.de/xplangml}BP_GenerischesObjekt');
INSERT INTO feature_types  (id,qname) VALUES (30,'{http://www.xplanung.de/xplangml}BP_GestaltungBaugebiet');
INSERT INTO feature_types  (id,qname) VALUES (31,'{http://www.xplanung.de/xplangml}BP_GewaesserFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (32,'{http://www.xplanung.de/xplangml}BP_GruenFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (33,'{http://www.xplanung.de/xplangml}BP_HoehenPunkt');
INSERT INTO feature_types  (id,qname) VALUES (34,'{http://www.xplanung.de/xplangml}BP_Immissionsschutz');
INSERT INTO feature_types  (id,qname) VALUES (35,'{http://www.xplanung.de/xplangml}BP_KennzeichnungsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (36,'{http://www.xplanung.de/xplangml}BP_LandwirtschaftsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (37,'{http://www.xplanung.de/xplangml}BP_LuftreinhalteFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (38,'{http://www.xplanung.de/xplangml}BP_LuftverkehrFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (39,'{http://www.xplanung.de/xplangml}BP_NebenanlagenFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (40,'{http://www.xplanung.de/xplangml}BP_NutzungsartenGrenze');
INSERT INTO feature_types  (id,qname) VALUES (41,'{http://www.xplanung.de/xplangml}BP_PersGruppenBestimmteFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (42,'{http://www.xplanung.de/xplangml}BP_Plan');
INSERT INTO feature_types  (id,qname) VALUES (43,'{http://www.xplanung.de/xplangml}BP_RasterplanAenderung');
INSERT INTO feature_types  (id,qname) VALUES (44,'{http://www.xplanung.de/xplangml}BP_SchutzPflegeEntwicklungsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (45,'{http://www.xplanung.de/xplangml}BP_Schutzgebiet');
INSERT INTO feature_types  (id,qname) VALUES (46,'{http://www.xplanung.de/xplangml}BP_SpielSportanlagenFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (47,'{http://www.xplanung.de/xplangml}BP_StrassenVerkehrsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (48,'{http://www.xplanung.de/xplangml}BP_StrassenbegrenzungsLinie');
INSERT INTO feature_types  (id,qname) VALUES (49,'{http://www.xplanung.de/xplangml}BP_Strassenkoerper');
INSERT INTO feature_types  (id,qname) VALUES (50,'{http://www.xplanung.de/xplangml}BP_TechnikBestimmteFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (51,'{http://www.xplanung.de/xplangml}BP_UeberbaubareGrundstuecksFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (52,'{http://www.xplanung.de/xplangml}BP_VerEntsorgungsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (53,'{http://www.xplanung.de/xplangml}BP_VerEntsorgungsleitungLinie');
INSERT INTO feature_types  (id,qname) VALUES (54,'{http://www.xplanung.de/xplangml}BP_VerkehrsflaecheBesondererZweckbestimmung');
INSERT INTO feature_types  (id,qname) VALUES (55,'{http://www.xplanung.de/xplangml}BP_VorbHochwSchutzFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (56,'{http://www.xplanung.de/xplangml}BP_WaldFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (57,'{http://www.xplanung.de/xplangml}BP_WasserrechtlicheFestsetzungsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (58,'{http://www.xplanung.de/xplangml}BP_WasserwirtschaftsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (59,'{http://www.xplanung.de/xplangml}BP_Wegerecht');
INSERT INTO feature_types  (id,qname) VALUES (60,'{http://www.xplanung.de/xplangml}FP_AbgrabungsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (61,'{http://www.xplanung.de/xplangml}FP_AufschuettungsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (62,'{http://www.xplanung.de/xplangml}FP_AusgleichsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (63,'{http://www.xplanung.de/xplangml}FP_Bahnverkehr');
INSERT INTO feature_types  (id,qname) VALUES (64,'{http://www.xplanung.de/xplangml}FP_BebauungsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (65,'{http://www.xplanung.de/xplangml}FP_Bereich');
INSERT INTO feature_types  (id,qname) VALUES (66,'{http://www.xplanung.de/xplangml}FP_BodenschaetzeFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (67,'{http://www.xplanung.de/xplangml}FP_DenkmalschutzEnsemble');
INSERT INTO feature_types  (id,qname) VALUES (68,'{http://www.xplanung.de/xplangml}FP_Erhaltungssatzung');
INSERT INTO feature_types  (id,qname) VALUES (69,'{http://www.xplanung.de/xplangml}FP_Fachgesetz');
INSERT INTO feature_types  (id,qname) VALUES (70,'{http://www.xplanung.de/xplangml}FP_Gemeinbedarf');
INSERT INTO feature_types  (id,qname) VALUES (71,'{http://www.xplanung.de/xplangml}FP_GenerischesObjekt');
INSERT INTO feature_types  (id,qname) VALUES (72,'{http://www.xplanung.de/xplangml}FP_Gewaesser');
INSERT INTO feature_types  (id,qname) VALUES (73,'{http://www.xplanung.de/xplangml}FP_Gruen');
INSERT INTO feature_types  (id,qname) VALUES (74,'{http://www.xplanung.de/xplangml}FP_KeineZentrAbwasserBeseitigungFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (75,'{http://www.xplanung.de/xplangml}FP_Kennzeichnung');
INSERT INTO feature_types  (id,qname) VALUES (76,'{http://www.xplanung.de/xplangml}FP_LandwirtschaftsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (77,'{http://www.xplanung.de/xplangml}FP_Luftverkehr');
INSERT INTO feature_types  (id,qname) VALUES (78,'{http://www.xplanung.de/xplangml}FP_NutzungsbeschraenkungsFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (79,'{http://www.xplanung.de/xplangml}FP_Plan');
INSERT INTO feature_types  (id,qname) VALUES (80,'{http://www.xplanung.de/xplangml}FP_PriviligiertesVorhaben');
INSERT INTO feature_types  (id,qname) VALUES (81,'{http://www.xplanung.de/xplangml}FP_RasterplanAenderung');
INSERT INTO feature_types  (id,qname) VALUES (82,'{http://www.xplanung.de/xplangml}FP_SchutzPflegeEntwicklung');
INSERT INTO feature_types  (id,qname) VALUES (83,'{http://www.xplanung.de/xplangml}FP_Schutzgebiet');
INSERT INTO feature_types  (id,qname) VALUES (84,'{http://www.xplanung.de/xplangml}FP_SpielSportanlage');
INSERT INTO feature_types  (id,qname) VALUES (85,'{http://www.xplanung.de/xplangml}FP_Strassenverkehr');
INSERT INTO feature_types  (id,qname) VALUES (86,'{http://www.xplanung.de/xplangml}FP_VerEntsorgung');
INSERT INTO feature_types  (id,qname) VALUES (87,'{http://www.xplanung.de/xplangml}FP_VorbHochwSchutz');
INSERT INTO feature_types  (id,qname) VALUES (88,'{http://www.xplanung.de/xplangml}FP_VorbehalteFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (89,'{http://www.xplanung.de/xplangml}FP_WaldFlaeche');
INSERT INTO feature_types  (id,qname) VALUES (90,'{http://www.xplanung.de/xplangml}FP_Wasserrecht');
INSERT INTO feature_types  (id,qname) VALUES (91,'{http://www.xplanung.de/xplangml}FP_Wasserwirtschaft');
INSERT INTO feature_types  (id,qname) VALUES (92,'{http://www.xplanung.de/xplangml}RP_Bereich');
INSERT INTO feature_types  (id,qname) VALUES (93,'{http://www.xplanung.de/xplangml}RP_Entwicklungsschwerpunkte');
INSERT INTO feature_types  (id,qname) VALUES (94,'{http://www.xplanung.de/xplangml}RP_Plan');
INSERT INTO feature_types  (id,qname) VALUES (95,'{http://www.xplanung.de/xplangml}RP_Windenergie');
INSERT INTO feature_types  (id,qname) VALUES (96,'{http://www.xplanung.de/xplangml}XP_BegruendungAbschnitt');
INSERT INTO feature_types  (id,qname) VALUES (97,'{http://www.xplanung.de/xplangml}XP_DatumAttribut');
INSERT INTO feature_types  (id,qname) VALUES (98,'{http://www.xplanung.de/xplangml}XP_DoubleAttribut');
INSERT INTO feature_types  (id,qname) VALUES (99,'{http://www.xplanung.de/xplangml}XP_ExterneReferenz');
INSERT INTO feature_types  (id,qname) VALUES (100,'{http://www.xplanung.de/xplangml}XP_FPO');
INSERT INTO feature_types  (id,qname) VALUES (101,'{http://www.xplanung.de/xplangml}XP_IntegerAttribut');
INSERT INTO feature_types  (id,qname) VALUES (102,'{http://www.xplanung.de/xplangml}XP_LPO');
INSERT INTO feature_types  (id,qname) VALUES (103,'{http://www.xplanung.de/xplangml}XP_LTO');
INSERT INTO feature_types  (id,qname) VALUES (104,'{http://www.xplanung.de/xplangml}XP_PPO');
INSERT INTO feature_types  (id,qname) VALUES (105,'{http://www.xplanung.de/xplangml}XP_PTO');
INSERT INTO feature_types  (id,qname) VALUES (106,'{http://www.xplanung.de/xplangml}XP_Praesentationsobjekt');
INSERT INTO feature_types  (id,qname) VALUES (107,'{http://www.xplanung.de/xplangml}XP_RasterplanBasis');
INSERT INTO feature_types  (id,qname) VALUES (108,'{http://www.xplanung.de/xplangml}XP_StringAttribut');
INSERT INTO feature_types  (id,qname) VALUES (109,'{http://www.xplanung.de/xplangml}XP_TextAbschnitt');
INSERT INTO feature_types  (id,qname) VALUES (110,'{http://www.xplanung.de/xplangml}XP_URLAttribut');
INSERT INTO feature_types  (id,qname) VALUES (111,'{http://www.xplanung.de/xplangml}XP_VerfahrensMerkmal');

CREATE TABLE gml_objects (id serial PRIMARY KEY, gml_id text UNIQUE NOT NULL, ft_type smallint REFERENCES feature_types , binary_object bytea, plan_id text, plan_name text, internal_id text, rechtsstand text);
COMMENT ON TABLE gml_objects IS 'All objects (features and geometries)';
SELECT ADDGEOMETRYCOLUMN('xplan2', 'gml_objects','gml_bounded_by','-1','GEOMETRY',2);
ALTER TABLE gml_objects ADD CONSTRAINT gml_objects_geochk CHECK (ST_isValid(gml_bounded_by));
CREATE INDEX gml_objects_sidx ON gml_objects  USING GIST (gml_bounded_by);
/* --- END global section --- */
